### ISSUE TITLE
Uninstall Biblioteq

### ISSUE THREAD

**Issue by avapanity** [textbrowser/biblioteq#10]
I have probably installed wrongly the program and now i can't remove it from my pc. I can't find it in my applications. Any idea how to do it?

**Comment by textbrowser** [comment]
Windows? Which version of BiblioteQ? As of 2016.03.15, BQ is portable. So, just remove the BiblioteQ folder.

**Comment by avapanity** [comment]
thank you very much [😊]

________________________________
Από: Guess Who <notifications@github.com>
Στάλθηκε: Κυριακή, 27 Νοεμβρίου 2016 11:12:13 μμ
Προς: textbrowser/biblioteq
Κοιν.: avapanity; Author
Θέμα: Re: [textbrowser/biblioteq] Uninstall Biblioteq (#10)


Windows? Which version of BiblioteQ? As of 2016.03.15, BQ is portable. So, just remove the BiblioteQ folder.

**Comment by textbrowser** [comment]
User is happy. Closing.
