### ISSUE TITLE
Copy Browser multiple save w/o close

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#103]
Please examine, if this is reproducible or just appearing for me:

Change the status of a copy in copy browser, save, then without closing copy browser change again and save.

"Unable to save the copy data." In error log: "...Database Error,Unable to create copy data.,ERROR: duplicate key value violates unique constraint "book_copy_info_pkey" DETAIL: Key (item_oid, copyid)=(...) already exists. (23505) QPSQL: Unable to create query,Source\biblioteq_copy_editor_book.cc,155..."

**Comment by textbrowser** [comment]
Yes, I see it too. Just committed a correction. Thank you!

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/b11d02b7c0ae643bbf2886a5672817b588228a8f

**Comment by textbrowser** [comment]
Release this week. Closing. Thanks. Bye. See you.
