### ISSUE TITLE
Virus warning with 2021.06.12 BiblioteQ.exe.

### ISSUE THREAD

**Issue by coldacid** [textbrowser/biblioteq#104]
MaxSecure flags the latest version of BiblioteQ as trojan malware, Trojan.Malware.300983.susgen. It's very likely to be a false positive, but figured it would be good to let you know.

https://www.virustotal.com/gui/file/ee403cfe7854148ffed2d6a76b820c389d887418971d32d8976377a23fc68f16/detection

**Comment by textbrowser** [comment]
Aha, you found us!

**Comment by textbrowser** [comment]
The best solution is for people to build it from source. On Mac, it's simple. I think it'll build with Homebrew's Qt.

**Comment by textbrowser** [comment]
Even on Windows it's simple: mingw32-make followed by mingw32-make install.

**Comment by coldacid** [comment]
I strongly disagree with building from source for Windows and Mac users, for several reasons:

* Most Windows and Mac users are not programmers nor do they have any development toolchain installed on their computers
* Qt now prevents downloading their Windows SDK unless you provide them with a bunch of personally identifiable identification to create an account for their download site. It's probably the same for the Mac SDK.

Even for Linux, the number of people who are just users and not also developers has been increasing. However for Windows and Mac users we've always been a small minority, and the vast majority of users want a package they can install and have the app "just work".

**Comment by textbrowser** [comment]
Qt requires an e-mail account.

**Comment by textbrowser** [comment]
On Mac, you don't need an account to install Homebrew's Qt. Once installed: brew install qt. So on. Although you may be correct with Xcode. Everyone wants packages. It's sad.

**Comment by textbrowser** [comment]
And thank you for reporting this. :)

**Comment by bulvara** [comment]
> Most Windows and Mac users are not programmers
> The vast majority of users want a package they can install and have the app "just work".

You don't have to use this software. The are many proprietary solutions tailored just for you.

**Comment by textbrowser** [comment]
Closing.

**Comment by textbrowser** [comment]
The latest BiblioteQ.exe file is also flagged by the site.
