### ISSUE TITLE
import/export (CSV file) attribute do not support Arabic letters

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#106]
Hello
import/export (CSV file) attribute do not support Arabic letters
Thank you

**Comment by textbrowser** [comment]
Can you please provide a sample test file?

**Comment by textbrowser** [comment]
And screenshots or a video recording. The more information the better.

**Comment by 2010fares** [comment]
[arabic-file.zip](https://github.com/textbrowser/biblioteq/files/7150529/arabic-file.zip)
![arabic-record](https://user-images.githubusercontent.com/7378389/133007159-db852593-d1c1-4c04-bc22-91046d834970.jpg)
[csv-export.csv](https://github.com/textbrowser/biblioteq/files/7150531/csv-export.csv)
![problem](https://user-images.githubusercontent.com/7378389/133007162-a69dd49f-e8b4-43bd-b122-3ea7c34f261a.jpg)

**Comment by textbrowser** [comment]
The top image is BQ and the bottom is MS Excel? BQ looks fine.

**Comment by 2010fares** [comment]
The problem appears when we export to CSV file
 or when we import CSV file to BQ
There are no problems when writing in the BQ system
[arabic-file.zip](https://github.com/textbrowser/biblioteq/files/7150565/arabic-file.zip)
[csv-export.csv](https://github.com/textbrowser/biblioteq/files/7150566/csv-export.csv)

**Comment by textbrowser** [comment]
Alright. I will focus on the export first. :)

**Comment by textbrowser** [comment]
Here's an image of my export of your database.

![Screenshot from 2021-09-12 22-10-39](https://user-images.githubusercontent.com/10701156/133013888-50f067ab-b7e3-40da-8a39-41c293a4eb9d.png)

**Comment by textbrowser** [comment]
Will attempt an export while I'm configured for Arabic. Perhaps the translation files should be embedded in the executable. Another discussion for another time.

**Comment by 2010fares** [comment]
Thanks for your help
It seems that things are perfect according to the picture sent by you
But I don't know the cause of the problem
Attached is a video about the problem
[video-for-excel-problem.zip](https://github.com/textbrowser/biblioteq/files/7157421/video-for-excel-problem.zip)

**Comment by textbrowser** [comment]
I have not reviewed the import.

**Comment by textbrowser** [comment]
Alright. I have tested the import successfully.

1. Open the database that you provided.
2. Select the Books category.
3. Export the database to a CSV file.
4. Close the database.
5. Create a new empty SQLite database.
6. Import the CSV file from #3.

Success!

**Comment by 2010fares** [comment]
Thank you so much

**Comment by textbrowser** [comment]
Is this still an issue?

**Comment by 2010fares** [comment]
There is still a problem with the appearance of Arabic letters
