### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#11]
If it possible to add the Arabic language in order to do the translation.
Greetings

**Comment by textbrowser** [comment]
You need to provide a translation file. Do you know how to use Qt's Linguist?

**Comment by 2010fares** [comment]
Thanks for your reply
I will later translate biblioteq_ar_JO.ts file for Arabic (Jordan) language support. 
Greetings

**Comment by 2010fares** [comment]
Can you provide me with an empty translation file that I should translated it using Qt's Linguist
Thank you for your patience.

**Comment by textbrowser** [comment]
I have not used Linguist.

Does http://doc.qt.io/qt-5/linguist-translators.html help?

**Comment by 2010fares** [comment]
Here are the initial translation attachment of the biblioteq_ar_JO.ts file in order to test the Arabic (Jordan) Language in a BiblioteQ system.


[biblioteq_ar_JO.zip](https://github.com/textbrowser/biblioteq/files/801046/biblioteq_ar_JO.zip)

**Comment by textbrowser** [comment]
Thank you! Will upload them today.

**Comment by textbrowser** [comment]
Files uploaded!
