### ISSUE TITLE
Can you provide sql/csv test data for the demonstration

### ISSUE THREAD

**Issue by sunyuyangg555** [textbrowser/biblioteq#110]
I think it would be better if I had test data imported directly into the database.

**Comment by textbrowser** [comment]
You can also prepare one yourself. Create an SQLite database, populate it with some items, and export the data to a CSV file. Then, create a new SQLite database and import the CSV file.

**Comment by sunyuyangg555** [comment]
I apologize for not being clear.
I mean whether you can share a demo database file,  so I can import directly into the local database to play with this greate program.

**Comment by textbrowser** [comment]
Closing. Thanks for the ticket!

**Comment by textbrowser** [comment]
Will add additional entries to the database. :)
