### ISSUE TITLE
Arabic characters are invisible (disappear) when we export the data to Excel

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#12]
When we export the data to Excel, the Arabic characters are invisible (disappear).
Greetings

**Comment by textbrowser** [comment]
You're exporting it to a CSV file? Will take a look.

**Comment by textbrowser** [comment]
Please post an image of the Excel spreadsheet.

**Comment by textbrowser** [comment]
I exported a sample item having Arabic text and the results appear fine.

**Comment by 2010fares** [comment]
This an image of the Excel spreadsheet.
![16-02-2017 11-26-05](https://cloud.githubusercontent.com/assets/7378389/23042440/99932600-f44d-11e6-92f9-7ac6fe6bb02e.png)
May be the problem with the Excel settings of program that I own.
Thank you for your cooperation

**Comment by textbrowser** [comment]
Via LibreOffice.

![bq](https://cloud.githubusercontent.com/assets/10701156/23044493/759bf8be-f46e-11e6-8e4e-c993ed5a1e4a.png)

**Comment by 2010fares** [comment]
It seems that the problem in my computer, I will try to solve it.
Thanks for your help
