### ISSUE TITLE
Member ID that begins with number not supported (anymore or with PSQL)?

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#128]
`2021/11/15 13:46:51,Database Error,An error occurred while attempting to create a database account for the new member.,ERROR: syntax error at or near "17" LINE 1: CREATE USER 17a30 ENCRYPTED PASSWORD 'tempPass' ^ (42601) QPSQL: Unable to create query,Source\biblioteq_c.cc,5373`

**Comment by textbrowser** [comment]
I prefer the prefix 'm' when defining a new member identifier. There is a basic regular expression (must be a word) set on the input field. PostgreSQL is ultimately responsible for validating the input and is therefore assigned that responsibility. :)

https://www.postgresql.org/docs/current/sql-createrole.html

**Comment by textbrowser** [comment]
Remember that you can create a user outside of BQ through PostgreSQL. PostgreSQL may change requirements and I do not wish to follow those changes in the software. The minimum requirement that the name must be a word is sufficient. The rest will be validated by PQ. :)
