### ISSUE TITLE
Custom Database Query

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#13]
If there was Query Statements as Samples to use it. 
In order to facilitate the process for librarians.
Thanks alot

**Comment by textbrowser** [comment]
Proper SQL knowledge is required. :o)

An example: "SELECT author, title, myoid FROM book". All legal syntax is supported.

**Comment by 2010fares** [comment]
Thanks alot
Did I send to you the translated biblioteq_ar_JO.ts file when I finish translation to arabic.
Or there are other things should I do

**Comment by textbrowser** [comment]
Yes, attach the file to a ticket.

**Comment by 2010fares** [comment]
Update translation of the biblioteq_ar_JO.ts‏
Here are the update translation attachment of the biblioteq_ar_JO.ts file
in order to add the Arabic (Jordan) Language in a Desktop BiblioteQ
software (client
We will test BiblioteQ software in our library, and if there are updates on
the translation I will send it to you
Thank you for your cooperation

2017-02-17 15:21 GMT+02:00 Guess Who <notifications@github.com>:

**Comment by textbrowser** [comment]
Hi. Did you attach the file?
