### ISSUE TITLE
Request to preserve the order of the columns in the main table.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#130]
After discussion, the feasibility of this option would be a real plus to improve the user experience.
Thank you in advance.

**Comment by textbrowser** [comment]
I briefly looked at this and the resolution is pretty annoying because the dynamic column menu. :)

**Comment by meteos77** [comment]
it's not a necessary request it was for comfort :-)

**Comment by meteos77** [comment]
![2021-12-29_Ecran-BiblioteQ](https://user-images.githubusercontent.com/56431039/147684489-e01551ac-23ec-4363-9b33-a190e75dcf70.png)

we have a good tool and a lot of information outside the table so it is enough

**Comment by textbrowser** [comment]
Yes, it's a fabulous concept for tables with many columns. I wish LibreOffice offered it.

**Comment by textbrowser** [comment]
> ![2021-12-29_Ecran-BiblioteQ](https://user-images.githubusercontent.com/56431039/147684489-e01551ac-23ec-4363-9b33-a190e75dcf70.png)
> 
> we have a good tool and a lot of information outside the table so it is enough

You can collapse the left-hand summary panel by using the splitter.

https://user-images.githubusercontent.com/10701156/147698836-a7ddb411-c8e0-4de9-8afa-3cc90f545450.mp4

**Comment by meteos77** [comment]
after reflexions on this request : I reformulate the request by hoping to simplify it

the real big concern is "accession_number" (the reference of the books of the library for the loans / returns) which is found in the last column, we can manage the library only with this field (backup if the shower is broken).

this means that each user will have to move the last column to the first one at each time.

Request : can we modify the basic configuration without the option save on demand. 

for just this field?
instead of having Read Status ; Title ; Authors ...
have Accession_number , title; authors ... (the read status field has no sense in a library).

at worst I can even try to compile the sources with the modification to have a personal version with this column order.

**Comment by meteos77** [comment]
if I understood correctly Biblioteq works :
the Select is always the same and the "Select Viewable columns" does not affect the SQL query
BiblioteQ retrieves all the fields and then makes a filter on the display of the columns that the user has chosen to see.
BiblioteQ makes the tools tip only during the query (if the option is deactivated, no tools tip is made without redoing the query, even if you activate the option in the preferences).

**Comment by meteos77** [comment]
Suggestion
BiblioteQ should make the personal query according to the "Select Viewable columns" configuration

I start with the simple case: 
for example if the user has chosen to see only these 5 columns accession_number, title,author,isbn13,read_status then BiblioteQ makes SELECT accession_number, title,author,isbn13,read_status to display the table

shortens the queries so improves the speed (in theory)

**Comment by meteos77** [comment]
on the other hand it could solve the problem of saving the position of the columns

the option "Select Viewable Columns" becomes "Select Viewable Columns AND Emplacement
the fields are clickable : visible/invisible as now but the user can move them in the order he wants

then BiblioteQ retrieves the Locations and builds its query with the well placed fields
the user defines position1=accession_number position2=title position3=isbn13 position4=author
BiblioteQ makes the query SELECT position1, position2 position3 position4 FROM book ...

the order of the columns is defined by the user at the beginning and no need to save the moving columns of the table

**Comment by meteos77** [comment]
I come back to this request with another idea

could we have a custom SQL query 
- associated with a shortcut key (for example F4) 
- associated with a "View" menu entry for example : "SQL User Query Preference".

this will allow me to make my personal query
"SELECT accession_number, callnumber, deweynumber, title, author, target_audience, myoid, type FROM book 
and in one keystroke to have my table with the fields in the right order with only the information that interests me.

**Comment by textbrowser** [comment]
TO-DO.

> I come back to this request with another idea
> 
> could we have a custom SQL query
> 
>     * associated with a shortcut key (for example F4)
> 
>     * associated with a "View" menu entry for example : "SQL User Query Preference".
> 
> 
> this will allow me to make my personal query "SELECT accession_number, callnumber, deweynumber, title, author, target_audience, myoid, type FROM book and in one keystroke to have my table with the fields in the right order with only the information that interests me.

This is not related to the column order. It's another request: custom queries and favorites and favorites are included in TO-DO.
