### ISSUE TITLE
sql result : first field is always invisible (uncheck) in the presentation

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#137]
to select several documents in the database with specific fields:
pour sélectionner plusieurs documents dans la base avec les champs spécifiques :

custom query:
SELECT callnumber, title, author, isbn13 FROM book WHERE accession_number IN ('7056','7057','7058')

the result is ok but in the table the first field is always invisible (uncheck) in the presentation is it voluntary ?

_Originally posted by @meteos77 in https://github.com/textbrowser/biblioteq/discussions/136#discussioncomment-1777997_

**Comment by textbrowser** [comment]
I cannot reproduce this problem. Are you sure you're not hiding columns?

**Comment by textbrowser** [comment]
OK, please pull the latest source and recompile.

![Screenshot_20211209_102231](https://user-images.githubusercontent.com/10701156/145424363-1bea0b98-d5eb-4d9c-92bb-25b1b66cd8ca.png)

**Comment by meteos77** [comment]
always the same at each SQL query, it unchecks the first field to display
if I activate it afterwards, it is still there but I find it strange


![pb-sql](https://user-images.githubusercontent.com/56431039/145426259-dcfd42dd-811d-4229-97b4-73948e63dd5d.png)

**Comment by meteos77** [comment]
if the 1st column is hidden at each query

**Comment by textbrowser** [comment]
Make it visible. :P

**Comment by textbrowser** [comment]
Let me see if it's persistent.

**Comment by textbrowser** [comment]
I see the cause.

**Comment by meteos77** [comment]
you are the magician who tried to make the results disappear :-)

**Comment by textbrowser** [comment]
It's quite annoying. :)

**Comment by textbrowser** [comment]
OK, I think it's correct now. Including the column-configuration menu. Let me know!

**Comment by meteos77** [comment]
for me it’s okay thanks for the work

**Comment by textbrowser** [comment]
Most excellent. :)
