### ISSUE TITLE
RTL for arabic 

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#141]
good greeting
Arabic should be from right to left (RTL)
This feature is not available in the latest version
Thank you

**Comment by textbrowser** [comment]
Please post an image. Did it work before?

**Comment by 2010fares** [comment]
https://user-images.githubusercontent.com/7378389/145629073-9b30ab65-328c-4ae5-8d4b-1aa73be48c77.mp4

**Comment by textbrowser** [comment]
Are you using Windows?

**Comment by 2010fares** [comment]
Yes I use Windows

**Comment by textbrowser** [comment]
I embedded the translation files into the application in version 2021.10.30. Is that the version you're using?

**Comment by 2010fares** [comment]
this is Version 2021.09.10  and RTL  works good.

But Version 2021.10.30 RTL not works.

**Comment by textbrowser** [comment]
The video is of 2021.09.10?

**Comment by 2010fares** [comment]
Yes The video is of 2021.09.10

**Comment by textbrowser** [comment]
OK, you need to specify that because it is RTL and not LTR. :)

**Comment by textbrowser** [comment]
Are the other applications on your system correct?

**Comment by 2010fares** [comment]
it looks fine

**Comment by textbrowser** [comment]
Perhaps I need to embed the Qt translation files also. Don't know.

**Comment by textbrowser** [comment]
Difficult to test. :P

**Comment by 2010fares** [comment]
Ok, thank you, I hope the next version will be fixed
Thank you very much for your good efforts

**Comment by textbrowser** [comment]
![Screenshot_20211210_163646](https://user-images.githubusercontent.com/10701156/145644417-b2d7383d-4b78-43d2-af62-111eb97355ae.png)

:)

**Comment by 2010fares** [comment]
Thank you very much

**Comment by textbrowser** [comment]
I accidentally omitted Qt translation files. The next release includes these files.

**Comment by 2010fares** [comment]
Thank you
