### ISSUE TITLE
added cancel button in the Z39.50

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#144]
in case of no answer, the timeout of the request is quite high, can you add a cancel button in the Z39.50 request as for the SRU request

thank you

**Comment by textbrowser** [comment]
There is an asynchronous mode for the ZOOM connection. This implies that operations are non-blocking. I don't know if an ongoing request can be removed, however. That is, an interrupt followed by the destruction of a live ZOOM connection may terminate BQ.

How about a timeout option instead?

https://software.indexdata.com/yaz/doc/zoom.html

**Comment by textbrowser** [comment]
The default timeout is 30 seconds.

**Comment by textbrowser** [comment]
Completed.

https://github.com/textbrowser/biblioteq/commit/77adf6c31976fc0aac3d5338153978fdaba7e0e0

**Comment by textbrowser** [comment]
https://github.com/indexdata/yaz/issues/62

**Comment by meteos77** [comment]
30 seconds was probably too long 
reduced to 10 seconds is cool

**Comment by textbrowser** [comment]
Happy? There's also a question for the YAZ group.

**Comment by meteos77** [comment]
the library that you ask for the analysis is really the project that should propose it if it is not already done

**Comment by textbrowser** [comment]
https://doc.qt.io/qt-5/qloggingcategory.html

export QT_LOGGING_RULES='*.debug=false;qt.qpa.*=false'

**Comment by textbrowser** [comment]
This be closed now. I will consider adding a means to interrupt the process if YAZ has the possibility. The timeout is also a pleasant solution. :)
