### ISSUE TITLE
Update translation of the biblioteq_ar_JO.ts

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#15]
Here are the update translation attachment of the biblioteq_ar_JO.ts file in order to add the Arabic (Jordan) Language in a Desktop BiblioteQ software (client).
We will test BiblioteQ software in our library, and if there are updates on the translation I will send it to you.
Thank you for your cooperation.
[14-3-2017biblioteq_ar_JO.zip](https://github.com/textbrowser/biblioteq/files/841873/14-3-2017biblioteq_ar_JO.zip)

**Comment by textbrowser** [comment]
Uploaded. Thanks again!
