### ISSUE TITLE
Import /Export csv file and Templates

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#157]
suggestion for csv import

have 2 templates in the import of books
template 1 - with minimum fields (not null values in the database)
template 2 - with all available fields

**Comment by textbrowser** [comment]
Started. Perhaps finished by tomorrow.

https://github.com/textbrowser/biblioteq/commit/e1245e8d1f414d8316a4a8e0261e660cad714a09

**Comment by meteos77** [comment]
Suggestion for improvement
instead of putting the column number in the import table (part 3), put in CSV Column Number the 1st analyzed line of the file in CSV Preview.

in the case of my example import file
01_title will be on the same line as title
02_author will be on the same line as author
...

we would gain in readability rather than going to the top of the screen to see the name of the field and at the bottom of the screen to see if it corresponds well

Translated with www.DeepL.com/Translator (free version)

**Comment by textbrowser** [comment]
Column number and the associated text, sure. For added columns, the associated text will be empty.

**Comment by textbrowser** [comment]
The order of the columns in the new template is the order of the fields in the database which is an alphabetic order.

**Comment by meteos77** [comment]
I need to review my script fix to put them in the right order

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/147787495-c94f9744-3a9a-4897-a930-8d7f92b115b4.mp4

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/147787706-09c75508-0e57-43bb-8b7c-6e91841a1a24.mp4

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/147787995-286677d2-7982-4411-bfd0-012f0c1039c2.mp4

**Comment by textbrowser** [comment]
Completed and closing!
