### ISSUE TITLE
import problem in Abstract / Description fields

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#158]
url -> ok
keyword -> ok
marc_tags -> ok
description -> KO

I have no problem with the other fields but this one doesn't want to know anything :-) 

can you look at this problem

thanks in advance

**Comment by textbrowser** [comment]
This should be corrected with the latest commit.

https://github.com/textbrowser/biblioteq/commit/9082dcd1956bcdca1208d44a643880561d8acb53

I imported the file BQ-110000-fix0.1.9, manually defining the keyword, marc_tags, and url. The description is now mandatory.

**Comment by meteos77** [comment]
great it works

**Comment by textbrowser** [comment]
Will be available in the next release. :)
