### ISSUE TITLE
add fields in the database for Physical Description

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#159]
can you set up a new field dedicated to the material description of the document
Field 215 of the unimarc: Physical description

to inform the size of the book, the number of pages, the illustrated cover, if the document is in several volumes ...

thank you in advance

**Comment by textbrowser** [comment]
The abstract / description field is already present in the book table. It is a place where a librarian can add miscellaneous information. Similar to notes. It is mandatory but it does not have a rigid definition.

**Comment by meteos77** [comment]
I tried to put several items in this box but  the "\n" does not cause a line break Do you have an idea ?

**Comment by textbrowser** [comment]
Press the Enter key instead.

**Comment by meteos77** [comment]
out of the 500 records :-)

**Comment by textbrowser** [comment]
Try SQL.

**Comment by textbrowser** [comment]
I'm closing this ticket because the field already exists. Thanks.
