### ISSUE TITLE
Problem with the latest update (20.01.2017)

### ISSUE THREAD

**Issue by nikoscrete** [textbrowser/biblioteq#16]
the latest update is not working to my pc.
when i search a book title i have a message "Unable to retrieve the data required for populating the main views". What can i do?
or how can i download the previous from the latest version?

**Comment by textbrowser** [comment]
Please copy and paste the contents of the Error Log. The log is available via Tools -> View Error Log.
Are you using SQLite? Which version of BQ did you use previously?

Also under the Tools menu, you'll find an Upgrade SQLite Schema tool.

**Comment by nikoscrete** [comment]
Now I use the version 2015.07.04 Qt version 5.4.2 
In the last version i have this error message
![2](https://cloud.githubusercontent.com/assets/20591427/24990854/98e02796-201f-11e7-930a-a382e766da2f.JPG)

![1](https://cloud.githubusercontent.com/assets/20591427/24990784/03d42f8a-201f-11e7-8d0d-66489d1bc5ae.JPG)

Now i think that everything is ok. Thank you!!!

**Comment by textbrowser** [comment]
So you're now able to use the 2017.01.20 (latest) version?

**Comment by nikoscrete** [comment]
yes, thank you so much!!!

**Comment by textbrowser** [comment]
Great. Have fun!
