### ISSUE TITLE
ISBN-10 and ISBN-13 Other Options options. Example ISBN-10 X-ABCD-EFGH-Y.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#160]
with the automatic conversion, we lost the dashes

can you keep the BiblioteQ treatment without the hyphens but have the presentation to the user with the form (the hyphens become 2 spaces)

9 782702 182819
X XXXXX XXXXX (on the 20 books that I have just looked at it is like this) allows to facilitate the reading

**Comment by textbrowser** [comment]
The dashes are removed. Are they mandatory?

**Comment by textbrowser** [comment]
What's the standard presentation format for ISBNs?

**Comment by textbrowser** [comment]
There isn't one.

"Use hyphens if they are included, as they divide the number into meaningful parts; the placement of hyphens varies between books."

https://en.wikipedia.org/wiki/Wikipedia:ISBN

**Comment by textbrowser** [comment]
Which of course requires a new Other Options option.

**Comment by textbrowser** [comment]
For 13, one format could be 978(9)-X-ABCD-EFGH-Y.

**Comment by meteos77** [comment]
I don't know about you, but look at the isbn of the books next to you...
for the option or not option part I don't know
on the other hand facilitating the reading of a number of 13 digits seems to me essential

each book in my possession has no dashes it is printed with spaces (easier to read than dashes no doubt)

**Comment by textbrowser** [comment]
I'm an excellent reader. I can read a 1024-digit number without a single separator. Try me.

**Comment by textbrowser** [comment]
This creates an interesting problem. How should the ISBN values be stored? Some of the logic requires that the values contain only 10 or only 13 digits. There are dialogs in place. Perhaps the values should be displayed and stored however they are and the logic should remove the hyphens as required without interfering with the appearances.

Library software is too complex. I give up.

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/Template:ISBNT is nice.

There is also the problem with converting ISBNs from 10 to 13 or 13 to 10. An ISBN-10 must have 10 digits. The conversion process does not tolerate hyphens so they cannot be present. After the conversion, the process should re-insert the hyphens but that would require it record their locations. That is quite silly.

I'll modify the conversion processes to remove the hyphens, perform the conversion, and insert the hyphens according to that template. Yes. That will be perfect. No one will ever complain.

**Comment by meteos77** [comment]
in my import file I removed all dashes (with script fix) because your conversion buttons did not want dashes :-)

**Comment by textbrowser** [comment]
No, the import already removes them. I am undoing that but I have to modify the ISBN-10 to ISBN-13 (and the other) conversions.
Regardless. I am not interested in the manner in which the values are stored. Hyphens or without hyphens. I am interested in their presentation and in their interactions with other APIs (Amazon, SRU, etc.). Some of those systems have their own requirements.

**Comment by textbrowser** [comment]
I prefer hyphen-less as there is absolute clarify from a parsing view. Presentation is another matter. Also, it is easier on the query-minded person: SELECT FROM ... WHERE id LIKE ('978%-2'). If there are hyphens, the query-minded person has to be aware of this whereas the agnostic (proper use?) does not. You can also remove the hyphens from the WHERE clause but that requires additional thinking.

**Comment by textbrowser** [comment]
So, the import remains as it currently sits. The importance is in the presentation.

**Comment by meteos77** [comment]
pour la présentation , je ne m'interesse pas trop au norme 
je regarde les 6 derniers et si cela correspond , il y a de grande chance que c'est le bon doc ( 1024 ou 6 :-)
pour ce qui est des requêtes sql ou le stockage fait au mieux pour votre gestion complexité/changement ...

**Comment by textbrowser** [comment]
A-B-C-D-E-F-G-H-I-J is a valid ISBN.

**Comment by textbrowser** [comment]
19 characters.

**Comment by textbrowser** [comment]
12 + 13 = 25 for ISBN-13. The fields in the database may contain at most 32 characters. I'm glad I considered this 20 years ago. :)

**Comment by textbrowser** [comment]
The new options should allow you to specify the format. ABCD-EFGH-IJ, for example, or ABCD-EFGHIJ.

**Comment by meteos77** [comment]
super and bravo for your reflexion of 20 years ago :-)
you who is visionary what is the future in 20 years :-) ?

**Comment by textbrowser** [comment]
It was all an accident.

**Comment by meteos77** [comment]
I really liked the movie Back to the Future

**Comment by textbrowser** [comment]
Excellent movies.

**Comment by textbrowser** [comment]
One part completed.

https://github.com/textbrowser/biblioteq/commit/efdf69eb58ef9b58599ba22877b059b0438f9f52

**Comment by textbrowser** [comment]
![Screenshot_20220101_120656](https://user-images.githubusercontent.com/10701156/147855968-9fc2e24b-66a5-4adb-b7fa-a17f282f8b57.png)

Two new options. I will also add your ISBN-13 format A-BCDEFG-HIJKLM.

**Comment by textbrowser** [comment]
The table is almost complete. Tool tips and book details remain.

**Comment by textbrowser** [comment]
Committed. Now for the tool tips.

**Comment by textbrowser** [comment]
This is now completed. :) Closing. If you'd like more formats, please specify.

**Comment by meteos77** [comment]
super lisible merci

test : pb with the converter button isbn-10 <-> isbn13 and it causes a pb with the download of the cover images because isbn-10 is not in the right format for amazon or openlibrary

**Comment by textbrowser** [comment]
OK, so the hyphens have to be removed.

**Comment by textbrowser** [comment]
Corrected and committed!

**Comment by meteos77** [comment]
works perfectly bravo!
