### ISSUE TITLE
csv import in text fields and line breaks - magic character ?

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#163]
when importing by Z3950 fields display data on several lines
when importing csv, the character \n has no effect

I have tried several  \\n '\n' '\\n' ('\n') or serie with \r but they remain unsuccessful

what is this magic character that makes a line break :-)

**Comment by textbrowser** [comment]
See HTML and rich text in Qt. A newline in HTML is <br>.

**Comment by meteos77** [comment]
I hadn't thought about html
it works great

but the <br> appears in clear in the table area :-(

**Comment by textbrowser** [comment]
I tried it (inserted a `<br>` in a keyword field) and I don't see the `<br>` in BQ. I see a empty line.

**Comment by meteos77** [comment]
in general table view the fields with <br> show it

in my version the keyword field is not in the table view ?

**Comment by textbrowser** [comment]
Ah, you want it in the table? I think that may not work. Do you see the new line in the item's view?

**Comment by textbrowser** [comment]
The main table in BQ is not a spreadsheet table.

**Comment by textbrowser** [comment]
If it works in the main table it is because Qt interprets it correctly. I am viewing an item's detail and I see new lines.

**Comment by meteos77** [comment]
the formatting is perfect in the table view  ; but it should be transparent 
not taken into account AND not displayed

**Comment by textbrowser** [comment]
> the formatting is perfect in the table view ; but it should be transparent not taken into account AND not displayed

What do you mean? Tables are generally for single-line items. Details are for paragraphs.

**Comment by textbrowser** [comment]
Hence uniform row heights.

**Comment by textbrowser** [comment]
I added the tool tips for that reason as well. Many columns and lengthy content.

**Comment by meteos77** [comment]
for example for the category field where it is OK
there are several lines
the first one : Firemen
the second one : Assistance to person in danger

\<br> is too much and should be a ;
in the table view: Firemen \<br> Assistance to person in danger = KO
in the table view: Firemen ; Assistance to person in danger = OK

**Comment by meteos77** [comment]
the Z3950 import does not have the same behavior
it manages to put these data on several lines without the \<br> in the middle of the table

**Comment by textbrowser** [comment]
The text in the main table and the tool tips will be simplified. Try it!

https://github.com/textbrowser/biblioteq/commit/9a302104ee5517b1c5df9678e74c806f6e124a60

**Comment by meteos77** [comment]
your modifications are superb for the ToolTips a line by category makes it more readable. what is cool the Tooltips!

but my problem <br> was not solved :-( so as you answer sometimes it's open so "do it yourself" :-) i tried ...

in French grammar: The semicolon is used to separate the different parts of an enumeration when these parts have some extent. 
I don't know if in other languages it's the same ?

I managed to replace the <br> of the table by ; and the <br> are well on the detailed view which allow a return to the line

well helped by your modifications; it gave me the lines to change :-) (3843 and 850)
thank you otherwise I would not have found in all the code of BiblioteQ

I give you my 2 lines of diffs to : either integrate them ; or improve them :-)

[my-modifications.zip](https://github.com/textbrowser/biblioteq/files/7800975/my-modifications.zip)

**Comment by textbrowser** [comment]
It does not replace HTML newlines. What if one creates HTML tables? Or adds font tags? There is a limit to the madness. :P

**Comment by meteos77** [comment]
I have only replaced <br>
- html tables in the table view ? and font tags is <font>
-
[100_Fichier-TEST-Imports-difficultés.csv.zip](https://github.com/textbrowser/biblioteq/files/7801680/100_Fichier-TEST-Imports-difficultes.csv.zip)

**Comment by textbrowser** [comment]
The point is: when to stop? :)

**Comment by meteos77** [comment]
for the moment it suits me well  :-) I have to go later good day

**Comment by textbrowser** [comment]
Done, again. If one modifies a live item's details and saves the information, the main table will temporarily include special characters. A refresh will present simplified content.

**Comment by meteos77** [comment]
it's perfect

**Comment by textbrowser** [comment]
I have added the other peculiarity as a reminder because it requires a review of all items which support embedded hyperlinks and HTML.

**Comment by meteos77** [comment]
thank you for the addition, the only hyperlink that should go on the web is the field url that goes to the record provided by the BnF but I do not know how to present the field to have the link active
I just put http://catalogue.bnf.fr/ark:/12148/cb42065660q for the moment.

anyway my library doesn't have internet :-) but if I have the info I will modify the catmandu script to have the import with less lost details

**Comment by textbrowser** [comment]
No, other hyperlinks. See the Categories. If you click on one of those links, BQ performs a self-query and locates other items having that link's content. So, a search is performed for discovering similar items.

![Screenshot_20220103_095613](https://user-images.githubusercontent.com/10701156/147945380-a0242f4b-e398-4270-b0f4-d9071213927f.png)

**Comment by textbrowser** [comment]
Similarly for Authors, Publisher, Place of Publication, etc.

**Comment by textbrowser** [comment]
Non-Web software which listens on clicked links.

**Comment by meteos77** [comment]
great surprise nice feature!
the doc talks about it but on the visualization side
how do you implement this in the case of csv import?

**Comment by textbrowser** [comment]
You have to emulate <a href> content.

**Comment by textbrowser** [comment]
`<ahref>Link</a>` = <ahref>Link</a>

**Comment by meteos77** [comment]
I am in the fog? 
I didn't understand the way to do it?
finally if on 2 documents I put <a href>history ...</a>history
the words are in blue but no link between them?

[test-link.sqlite.zip](https://github.com/textbrowser/biblioteq/files/7803195/test-link.sqlite.zip)

**Comment by textbrowser** [comment]
It is something to discover later. Not important.

**Comment by textbrowser** [comment]
```<a href='book_search?category?Number theory.'>book_search?category?Number theory.</a>```

**Comment by textbrowser** [comment]
That is one of the examples. It could be performed in the import and will require testing. :)

**Comment by meteos77** [comment]
I still haven't succeeded even after copying your line?
something must be wrong with this feature?

in theory, the text becomes blue and when you click it, it should select all the documents that have the same blue text in their description?


another question about the import : is it more strict than before ?
it doesn't accept fake isbn13 anymore ?
9790000000001
9790000000002
9790000000003
...

**Comment by textbrowser** [comment]
Are you trying this in the import?

**Comment by textbrowser** [comment]
What do you mean about the fake ISBN-13s?

**Comment by textbrowser** [comment]
Well, you wanted it to convert ISBN-10 to ISBN-13 (is ISBN-13 is not present) and ISBN-13 to ISBN-10 (if ISBN-10 is not present). It is not?

**Comment by meteos77** [comment]
I didn't try to import with the hyperlink feature because I can't set it up manually.

for isbn 10 and 13 i have a file of 7112 documents and the major from not 'isbn 10 and not isbn13 so i created one per document by doing 979391500000x and x+1 9793915000001 ...
the import indicates me an error because if I calculate the checksum that passes

**Comment by textbrowser** [comment]
I need to see the error.

**Comment by meteos77** [comment]
summary of my import tests

I think that the filtering 978 and 979 is not the same ?

if isbn13 has a 978 + valid control code OK
if isbn13 has 979 + valid control code OK
if isbn13 has 12 digits but in 978 OK
if isbn13 has 12 digits but in 979 KO (N° 7 and N° 8)


N° 5 if isbn13 has 978 + 13 digits it seems to keep only the 1st ?
N° 6 different treatment from N° 5 ?

N° 9 & 10 (979) = idem N° 5 & 6 (978) but KO


N° 11 (977) Ko 13 digits

after the import goes well
979xxxx (7 digits ok)
from 15 it is the method that I will choose if possible

It remains to see the automatic transfomration in isbn10 if it does not involve other problems ?
what would you advise me ?

suggestion: provide a mechanism to import documents that do not have isbn10 AND isbn13
i have old books without isbn so i have to make one
I wanted to give them a code that commands with 977xxx but it doesn't work (filtering 978 and 979)

in 979 short (7 digits no problem from line 15 to 24 ...) it is OK

[file-import-test.csv.zip](https://github.com/textbrowser/biblioteq/files/7816312/file-import-test.csv.zip)

**Comment by textbrowser** [comment]
I have to revert the description field from the import. It breaks the import. The description field is not included in the Books category and therefore cannot be exported. The original (and now kind of broken) import was working because it was the inverse of the export. We have to keep previous functionality working.

**Comment by textbrowser** [comment]
New functionality has to not break existing functionality. I am not doing to modify the original import. It needs to work.

**Comment by textbrowser** [comment]
I cannot test the export / import functions because the description field is now mandatory. It was not because it was not included in the original and safe export. This is a sign that we need to slow down.

**Comment by meteos77** [comment]
to have an export equal to the import is coherent!

in the export it misses description ; keyword ; marctags ; url
on the other hand read status in addition in the export which is not present in the import.

in the import tool you put a Substitute value box I thought that it was used for this very case

**Comment by textbrowser** [comment]
Right. The original two were inverses of each other and they worked. Someone requested the Read Status and I complied by adding it by making an existing column check-enabled. They were unhappy so I added a new column which also broke the export / import. Ugh. I need to slow down.

Yes, the export misses every column that you do not see in the Books category. A description can be quite elaborate and seeing it in a table may create havoc. The table is for a general view. When you go online for a book or in a library, you don't get to see the entire synopsis of an item unless you see its details. That is the purpose of the table. Details? Look in the details.

**Comment by textbrowser** [comment]
If the table included everything, the detailed viewed becomes redundant.

Simple view to get a big picture -> detailed view to see the bigger picture of a thing.

**Comment by textbrowser** [comment]
I mean even books have summaries on the backs or inside the cover flags in nice columns. The book is in the book.

**Comment by meteos77** [comment]
the first quality of biblioteQ is its stability so do the things you need to do for that: if you have to remove the last additions and if it allows to have the coherence it is the main one on the long term.

When I look at the table, I uncheck a lot of useless information to my eyes in the table view.

if one day i have to export all the info from the books i guess SQL will do that much better than the csv export?

**Comment by textbrowser** [comment]
The greatest menace to any good software is the general user. :) Not that you're a menace. But generally, that's a fact.

**Comment by meteos77** [comment]
thank you for this compliment :-)

I see in the usefulness of the table the fact of classifying the column that one wishes to locate the inconsistencies (that's why I put in unlimited by pages in the table view)
I list all the editors for example and where they are misspelled allows to pass in the edition view to correct the field (if you have another method I am taker; because with 7000 documents, that starts to slow down)

for the import, which will not be automated, I do not see filling the fields by hand to delete the documents 6 months or 1 year later. for us the books rotate between the Departmental Library and our local library.

in the unimarc the field 330$a gives a small summary like on the back cover of a physical book; the search function of BiblioteQ allows to search words in it (it's a great feature)

if the functionality is there, so much the better, if it's not there, we'll do without it :-)

**Comment by meteos77** [comment]
53599 lines of code in Source ... I say a **very big BRAVO !**

**Comment by textbrowser** [comment]
It is not the responsibility of an import to correct, guess, or modify the data that it's provided. It is not am import then. It's a translator.
