### ISSUE TITLE
not urgent : multi volume import problem with identical isbn-13

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#167]
continuation of the subject :  2 books + 1 isbn + 2 access numbers = 1 problem csv import #153 

**please look at this small detail when you have time : it's not urgent ; todo list :-)** 

solve the problem of non-import because same isbn-13 for 2 volumes books.
1 - the accession number is different for each volume
2 - the unimarc field 461 $v indicates the position

20_Source_PB_Import_File-doublons-without-column-volume_number

I can create a "volume" field in the catmandu -> csv script to help the import
20_Source_PB_Import_File-doublons-with-column-volume_number

on the other hand I can't know if there will be a conflict because catmandu treats line by line and doesn't know the duplicates.

it's necessarily at the BiblioteQ level that we should create a pseudo isbn-13 to authorize the import

Unimarc : the field 461 and subfield $v indicates the Part / volume number of the catalogued document

461  1 $t Au revoir là-haut $v 1
461  1 $t Au revoir là-haut $v 2
461  1 $t L'aile des vierges $v 1
461  1 $t L'aile des vierges $v 2
...
...
the import file with just the 10 books concerned

[multi-volume_import_problem_with_identical_isbn-13.zip](https://github.com/textbrowser/biblioteq/files/7799137/multi-volume_import_problem_with_identical_isbn-13.zip)

**Comment by textbrowser** [comment]
We can relax the ISBN rules or add a volume field.

**Comment by meteos77** [comment]
for me there are not enough fields in the database

- volume : 1 2 3 
- total volume (when the collection is finished)
- name of the collection : an author can take a long time to release a collection of x volumes for example and having the name of the collection allows to have a common field to link the x volumes
or for example for comic collections

a field with the target audience is also important for me, especially for statistics

**Comment by meteos77** [comment]
I will make a point with the volume numbers + unimarc because apparently there are several places where the volume information is given
in 5 minutes I have already seen 3 of them: 
200 $h
225 $v
410 $v

**Comment by textbrowser** [comment]
I'll finish group returns and if I have enough time before 2022.01.30, we can add new fields.

**Comment by meteos77** [comment]
There are already a lot of novelties in the current version. You have to digest all this :-)

in the release notes "Print Icons View" did not appear; I'd rather finish this part for this version. before starting the new fields part.

**Comment by textbrowser** [comment]
The printing works with the basic rendering functions that are given by Qt. There are other solutions which are not as simple:
- export the view to an HTML document to be printed by other programs
- paginate the view according to the specifications of the output device; not simple and not universal
- create a collage

**Comment by meteos77** [comment]
qt is not perfect :-)

**Comment by meteos77** [comment]
if it is not in pdf but in image format it is easier?   export in png format for example

the most annoying is the layout with 50% lost

**Comment by textbrowser** [comment]
I have not tried an export of the entire scene. Without implementing it, I don't know the results.

**Comment by textbrowser** [comment]
I do know that Qt has a limit on images.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/dooble/issues/106

**Comment by meteos77** [comment]
see [subject](https://github.com/textbrowser/biblioteq/discussions/175

**Comment by textbrowser** [comment]
https://www.loc.gov/marc/bibliographic/bd020.html

**Comment by textbrowser** [comment]
ISBN may also be considered to be application invalid if it is not directly applicable to the bibliographic item represented by a particular record. Application invalidity is usually related to the cataloging treatment employed by a particular agency in terms of the number of records involved. **For example, if there is a record for a multivolume set as well as separate records for each of the volumes in the set, the ISBN for the set is considered application invalid on the records for the volumes.** Only the ISBN applicable to the entity represented by a particular record is considered valid on that record.

**Comment by textbrowser** [comment]
If you have a multi-volume set and there is one ISBN assigned to the set, one ISBN is presented.

If you have a multi-volume set and there are ISBNs per each item, the set is considered several items.

A new non-essential field may be necessary to create relaxed relationships between individual records. For single multi-volume sets this is not necessary as the description suffices. For example, the description can contain information about each volume in a set.

For multiple multi-volume sets (each volume has a unique ISBN), BQ does not strictly require a change. However, a new non-essential field) may allow for establishing relationships between database records.

**Comment by meteos77** [comment]
in this ticket there are 2 problems

1 - importing multi-volume documents with only 1 isbn for all volumes.

2 - the management of documents forming a multi-volume collection

I join you a test base for the point 2
[multi_volume_with_different_isbn.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/7980731/multi_volume_with_different_isbn.sqlite.tar.gz)
:

**Comment by meteos77** [comment]
in the cycle "THE ROMANS" of Max Gallo, there are 5 documents with 5 different isbn
the fields 225 $a or 461 $t indicate the name of the collection
the fields 225 $v or 461 $v indicates the volume number

**Comment by meteos77** [comment]
in marc21( documents in English version + search on Z39 Library of Congress
the field 490 1 $a The stone of light indicates the name of the collection
the field 490 1 $a The stone of light $v v. 1 indicates the volume in the collection

**Comment by meteos77** [comment]
concerning the import of multi-volume with only 1 ISBN; in my 1st message I had put some test files

**Comment by meteos77** [comment]
I discover the history of the 3 suns - trisolarians :-)
[notices_navette_2022_02_02.pan_unimarc.tar.gz](https://github.com/textbrowser/biblioteq/files/8017525/notices_navette_2022_02_02.pan_unimarc.tar.gz)

**Comment by textbrowser** [comment]
Would you like a new database field for sets which have individual books having unique ISBNs? How about "multivolume_set_isbn"?

**Comment by textbrowser** [comment]
I'm looking for a yes or a no answer. :P

**Comment by textbrowser** [comment]
The ticket's heading?

**Comment by meteos77** [comment]
ok for multivolume_set_isbn

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/discussions/191

**Comment by meteos77** [comment]
if you create games of tracks all the clues are in the release notes :-)

**Comment by textbrowser** [comment]
Import remains? Do you have a plain summary of the import change(s)?

**Comment by textbrowser** [comment]
OK. That's very descriptive.

**Comment by meteos77** [comment]
I did not understand your question

**Comment by meteos77** [comment]
Does the import remain?
for me the import tool does its job normally,
line 2 has an isbn A
line 3 has an isbn A so it rejects it
line 4 has an isbn B
line 5 has an isbn B so it rejects it

**Comment by meteos77** [comment]
in my first message I had suggested to rely on the unimarc field 461 $v which indicates the volume number

if isbn A has as value in 461 $v equal to 2 it means that we have a book in several volumes but which can have an identical isbn

**Comment by textbrowser** [comment]
The new multi-volume field now exists. How should the import behave?

**Comment by meteos77** [comment]
how to manage the copies when importing csv ?

**Comment by meteos77** [comment]
BiblioteQ analyzes the number of copies field and creates 2 documents and assigns 2 barcodes X-1 and X-2
this looks like the problem
the only thing that is different with multi-volume books 
1 - the field 461 $v
2 - the barcode of the library (accession_number)

**Comment by meteos77** [comment]
I hope to be understandable

if BiblioteQ has a column Z in the import (field 461$v ) with the number 1 -> normal import

if the Z column has a number different from 1
then biblioteQ understands that it must create 1 copy for the number 2
create 2 copies for number 3 ...

it places as barcode of the copy the field accession_number column A and in the isbn of the document it activates Multi-volume-Set ISBN

**Comment by textbrowser** [comment]
> [20_Source_PB_Import_File-doublons-without-column-volume_number.csv](https://github.com/textbrowser/biblioteq/files/8444946/20_Source_PB_Import_File-doublons-without-column-volume_number.csv)
> 
> ![Rapport-import-multivolume](https://user-images.githubusercontent.com/56431039/162253281-17344770-d938-40f6-ba8b-340d6dbb5c4d.png)

The CSV contains items having non-unique ISBNs. The import does not look ahead to determine if something is a copy. Copies are indicated by the quantity field.

You're asking the import to look ahead, make a guess, and assume that the second (or third or forth or nth) item (having the non-unique ISBN) is in fact a copy. That's silly. That's a broken CSV.

**Comment by textbrowser** [comment]
Copies in a library have the same ISBN. Copy 1's ISBN is not -1 and copy 2's ISBN is not -2. An ISBN is assigned to an item. Two copies of said item have the same ISBN. Copies have other criteria to differentiate them. Not ISBNs. Broken CSV.

**Comment by meteos77** [comment]
no because I propose to add the Z column with the report of the 461$v field

**Comment by textbrowser** [comment]
And the CSV is broken because it requires BQ to look ahead and compute your intentions. Is this a copy? Why is it a copy? What if it isn't a copy and the CSV is actually mistaken?

**Comment by textbrowser** [comment]
No one knows what 461$v means. That's also silly.

**Comment by textbrowser** [comment]
The export and the import are inverse functions of one another. If the import is something else, than it's another thing. Export(Import(CSV)) = CSV. You don't have this with this file.

**Comment by textbrowser** [comment]
When you export a view, the export does not include copy information. It isn't an export of a database.

**Comment by textbrowser** [comment]
Whereas the import (in your example) is like a database in the form of a CSV.

**Comment by textbrowser** [comment]
Typically, people pay a lot of money to take their databases (in whatever form they are) and be migrated to other databases. Importing is hard work. Now, if you had INSERT statements it would work. You're asking the import tool to be extra smart for specific use-cases.

**Comment by textbrowser** [comment]
Actually, you're asking the import tool to treat the CSV like a database.

**Comment by meteos77** [comment]
I don't agree with you.

I ask the import tool to process 2 documents:
- which exists in reality
- which is an exception, I agree
- which have the same ISBN for several volumes

-which have almost everything identical except
- the field 461 $a in the unimarc records with numbers 1 , 2 ...
- the different barcode label put by
- which is printed on the cover of Volume 1 and Volume 2.

If this is stupid and boring for you, close the ticket and enjoy other things.

**Comment by textbrowser** [comment]
The solution: if an ISBN is already encountered, create a copy and assign the person-provided field as the copy's barcode.

**Comment by meteos77** [comment]
assign the person-provided field as the copy's barcode ?

**Comment by textbrowser** [comment]
Access # or Call # for your example CSV.

**Comment by textbrowser** [comment]
Along with the already-too complex import will be included a new menu for specifying what to do when a non-unique ISBN is encountered. It will read the field and create a copy using the said field value.

**Comment by meteos77** [comment]
> Along with the already-too complex import will be included a new menu for specifying what to do when a non-unique ISBN is encountered. It will read the field and create a copy using the said field value.

perfect

**Comment by textbrowser** [comment]
People should give me solutions beyond 461$v.

**Comment by textbrowser** [comment]
My next project is going to be named 461$v.

**Comment by meteos77** [comment]
I don't know if it will attract crowds but it is intriguing

**Comment by meteos77** [comment]
we count on your experience to find a good solution.

For me, the problem comes from the fact that BiblioteQ wants a UNIQUE ISBN-10 or ISBN-13.

In reality (even if it concerns only 0,000001 ‰ of the books), cases exist where 2 books have the same ISBN.

In our library, the books concerned are re-edited books in large print and therefore 2 volumes instead of 1.
We have elderly readers, it improves the comfort of reading :-)

**However, these are still exceptions, hence my non-urgent request.**

If this is too complicated to manage, I will create fake isbn-13 and copy the info manually.

**Comment by textbrowser** [comment]
There are standards regarding ISBN. Standards which publishers, countries, people adopt and adhere to. Yes? If a publisher decides to do something else, you're asking another exception of BQ. And when this exception is valid and bypassed, you'll ask that BQ protect the integrity of the standard. I say the few standards which BQ enforces are legitimate and that the data is flawed.

**Comment by textbrowser** [comment]
If we agree that ISBNs must be unique, yet another exception is not required in the import. If do not agree, than the import is not the problem.

**Comment by textbrowser** [comment]
Let's say ISBNs are not unique. Then, I can edit a book and set the ISBN to an existing ISBN. Should the standard be followed there? When happens if I delete a book using the ISBN? If there are multiple items having that ISBN, I need to remember this and delete the right one. This is both a database problem and a BQ problem.

**Comment by textbrowser** [comment]
If 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001% of something violates a standard, it isn't a standard. Uniqueness is pretty significant with respect to ISBNs. Perhaps the most significant attribute is uniqueness.

**Comment by textbrowser** [comment]
I'm not being annoying. These are questions you should be asking. :) It's your data and people will delete using ISBNs. When you see 5 or 6 or 20 rows deleted via "WHERE ISBN = '1234567890', that will be scary.

**Comment by textbrowser** [comment]
And if you have such a small percentage of broken ISBNs, I suggest manual entries. BQ does not require ISBNs. However, it requires unique ISBNs. So, for items where this problem occurs, I would manually enter them. If there are thousands, yikes, contact the publisher.

**Comment by meteos77** [comment]
source : https://www.isbn-international.org/content/isbn-users-manual/29

[ISBN International Users Manual - 7th edition_absolutely_final.docx.tar.gz](https://github.com/textbrowser/biblioteq/files/8452112/ISBN.International.Users.Manual.-.7th.edition_absolutely_final.docx.tar.gz)

page 13 
item 6.5 Multi-volume publications
item 6.6 Multi-item packs

extract :
Publications may comprise more than one volume, and in these cases an ISBN must be assigned to cover the entire set.
...
Even if the multiple volume publication will only be available as a complete set, the assignment of a separate ISBN to each individual volume is still recommended. Doing so will facilitate various stages of transaction processing.

the standard says everything and its opposite :-)

**Comment by textbrowser** [comment]
If a set has just one ISBN and each book in the set is not assigned an ISBN, then I would create the one entry and describe the contents of the set. The regulating body recommends individual copies. Since the single-ISBN is an exception, BQ will still work.

If multiple ISBNs are provided for each book in the set, the multi-set ISBN works along with the uniqueness of each book.

So, it works. BQ provides a meaningful way of cataloging your items. If it gets cumbersome in practice, then something else can address it. I don't find this a problem, at all.

**Comment by textbrowser** [comment]
Here's why.

- I can find the books because of the ISBN.
- Copies have barcodes and those barcodes are site specific.
- The description describes the contents of the set.
- BQ allows you to checkout a particular copy. If you have two copies of book #2, you'll know that.

The quality of your data is derived from the quality of your cataloging system. BQ doesn't restrict it. ISBNs are unique, that's the requirement. If they're not, BQ cannot protect your data. If you don't want some guarantee, don't use BQ. :)

**Comment by meteos77** [comment]
Rapport on Multi-Volume Set ISBN
[2022-04-16_Catmandu-avec-prets-permanents.zip](https://github.com/textbrowser/biblioteq/files/8501428/2022-04-16_Catmandu-avec-prets-permanents.zip)

it seems to accept that isbn-10
if 2 isbn-10 => both OK (exemple 1)
if 2 isbn-13 => both KO (exemple 2)
if 1 isbn-10 and 1 isbn-13 only isbn-10 is taken into account whatever the order isbn-10 before (exemple 3) or after isbn-13 (exemple 4)

the error message is about book.edition is not about multi_volume_set_isbn as expected?
Database error (NOT NULL constraint failed: book.edition Unable to fetch row) at row 3.

**Comment by meteos77** [comment]
I did not understand how the field works multi-volume-set-isbn field works?

I did not manage to create 2 books with identical isbn-13 even in
1 - copying the isbn13 in Multi-Volume Set ISBN
2 - putting the volume number 1 . 2 .. ( the famous 461$v) in Multi-Volume Set ISBN

can you explain how this feature works ?

**Comment by meteos77** [comment]
the departmental library manages the 2 volumes separately
however - both have the same isbn-13
- accession_number is different
- the field 461$v is different

with these 2 informations, they manage to do it 
how do they do it mystery?
![Haut-revoir-la-haut](https://user-images.githubusercontent.com/56431039/163717894-a41d1e97-4164-4c22-bda6-97bb1160b597.png)

**Comment by meteos77** [comment]
unimarc format
[Au_revoir_là-haut-format-UNIMARC.zip](https://github.com/textbrowser/biblioteq/files/8501780/Au_revoir_la-haut-format-UNIMARC.zip)

texte format
[Haut-Revoir-La-Haut-volume1.txt](https://github.com/textbrowser/biblioteq/files/8501781/Haut-Revoir-La-Haut-volume1.txt)
[Haut-Revoir-La-Haut-volume2.txt](https://github.com/textbrowser/biblioteq/files/8501782/Haut-Revoir-La-Haut-volume2.txt)

differences file
[differences_file.txt](https://github.com/textbrowser/biblioteq/files/8501789/differences_file.txt)

**Comment by meteos77** [comment]
their secret : 
unimarc filed : 

001 Record Identifier
Definition
This field contains the control number of the record assigned by the institution that creates, uses or distributes the record

thus effectively 
001 frOr0212502394 -> volume 1
001 frOr1300703440 -> volume 2

**Comment by textbrowser** [comment]
Is the system closed?

It isn't a mystery. BQ requires unique ISBNs or NULL ISBNs. These are facts. How some other systems work isn't mysterious. They can manage the uniqueness through the interface or they can manage it through people or they can totally ignore it. It's a separate system.

**Comment by meteos77** [comment]
**abandon this multi-volume import feature**

suggestion 
As BQ manages with ISBN unique constraint, it is not possible so **we abandon this functionality.**
I will manage them differently (with pseudo isbn-13)

let's convert the multi volume set id field to host the volume number
a new field will host the title of the set.

on the same line TITLE OF THE SERIES | VOLUME
exemple HARYY-POTTER | v2

**Comment by textbrowser** [comment]
This is getting silly now. MVI are not mandatory. They exist in the world.

**Comment by textbrowser** [comment]
Time for life now!

**Comment by textbrowser** [comment]
And again, BQ is a volunteering effort. I cannot spend all my free time on importing and multi-volume ISBN confusion.

Have a nice Sunday!

**Comment by meteos77** [comment]
Also have a good weekend
thanks again for everything
