### ISSUE TITLE
CLOSE : not urgent : request management of membership fees

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#168]
at the beginning of this year, the library is collecting the fees from each member.

Biblioteq has a field : Overdue Fees
Biblioteq has a field : Expiration Date
Biblioteq gives an alert if Expiration Date is exceeded

Request : Can we have a similar mechanism to manage the annual fee

1 - some libraries choose to charge the fee on the anniversary date of the registration.
2 - some libraries choose to charge the fee on January 1st of the year.
knowing that the expiry date in this case is the 31/12 of each year

mechanism to foresee at the 1st of January -> to put at the beginning of the year to all the members a debt of the amount of the contribution.
to have an alert when selecting the member if he has a debt (like his expiration date)
button to validate the payment of the fee and reset the amount due

have a management table of who paid and when
amount in the fund ...

**Comment by textbrowser** [comment]
Of course I will look. :)

**Comment by meteos77** [comment]
I'm asking for a lot of new features but I'm trying to transcribe the real time needs of the library to be able to manage it better with BiblioteQ in the future :-)
- permanence of wednesday 5th january = subscription 

the next membership fees will be in January 2023 so there is time to see the functionality but I put it in a ticket to not forget it

**Comment by textbrowser** [comment]
BQ does not provide alerts for expiration dates and fees. Would you like it to?

**Comment by meteos77** [comment]
About: BiblioteQ is a professional archiving, cataloging and library management suite. 

even if for me it is not a priority, in the library management part
the management of members : subscriptions / memberships, alert if return is late (mail or mail(pdf) to the member to ask for the return of the documents), fines should be part of BiblioteQ.

**Comment by textbrowser** [comment]
Added Overdue Fees column to the Members Browser last night.

**Comment by textbrowser** [comment]
I do not know of a universal mailing solution. How about a notification in highlights? Or generating a report?

**Comment by meteos77** [comment]
mailing is only an option, anyway my library has no internet connection :-)
<a href="**mailto**:name@provider_mail"/Sending mail list document overdue </a>   is not universal?

How about a notification in _**highlights**_? => translation problem, I don't understand

having a generated report can be not bad so volunteers can contact by phone or email.

**Comment by textbrowser** [comment]
Similar to Availability highlight colors.

**Comment by textbrowser** [comment]
As a reminder, sure. If the membership has expired, items cannot be reserved. This is the current behavior and the policy placed by the software.

For fees, it can be a reminder and the library places the policy without the software.

**Comment by meteos77** [comment]
you mean membership fees or late fees ?

**Comment by textbrowser** [comment]
Late fees. Membership fees are not present.

**Comment by textbrowser** [comment]
Overdue Fees in BQ.

**Comment by meteos77** [comment]
we do not apply late fees

my request was about the management of membership fees. (see my title :-)

**Comment by meteos77** [comment]
we do not apply late fees

my request was about the management of membership fees. (see my title :-)

in the management of the members we have a list of the delays by members but one information is missing: the email address
a small button to send a mail with a predefined form

in the other project I'm monitoring (ubpm - blood pressure monitoring, the author has set up an email to the doctor with a report on the data)
it runs on Windows/Linux/macOS

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/152691040-57504f07-5527-4a1f-a378-9a0eb4ab87a5.mp4

**Comment by textbrowser** [comment]
A new icon is necessary. The request will be then completed.

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/152691197-05c9f5ef-c2d0-4c20-a101-8d85f69109c0.mp4

**Comment by meteos77** [comment]
thank you for your development but it remains in my opinion incomplete

two requests got mixed up in our discussion

1 - the first one was the management of contributions

1a : at the 1st of January of year N : the librarian has a button to apply the amount of the contribution to all the members (for example 10€) (foresee in options/preferences the "amount of contribution to apply" and a button "to apply contribution for year xxxx" (a control which blocks if the action was already made not to apply twice the action in one year :-)

1b : when a member comes to the library, the librarian gets a message from BiblioteQ to tell him that the member owes his fee.

the librarian receives the money from the member and has a button "fee paid" (to be created) that updates the fields
Expiration Date : "N+1/01/01" and Membership Fees : "0,00".

**Comment by meteos77** [comment]
the 2nd point was about books that are not returned before the due date but I will make another ticket for this new feature

**Comment by textbrowser** [comment]
I think the request is turning BQ into a notification service. Membership Fees are now present. The fees can be managed per member.

1a. As BQ is unfamiliar with time, it cannot automatically apply fees unless it becomes familiar with time. 1a is a process specific to your needs.

1b. If a new member is created, the default should require a new Other Options setting. The default is 0.00.

**Comment by textbrowser** [comment]
1b is also similar to a collection agency. "Payment Received"

**Comment by textbrowser** [comment]
These processes. I'm not enjoying them.

**Comment by meteos77** [comment]
unfortunately the management of contribution is mandatory in the status of our association even if the contribution is 7€ per year and per family (about 50-60) 
we have to have an annual meeting, validate the accounts, have a manager... a whole administrative work to be able to have the books of the Departmental Library our main goal

**Comment by textbrowser** [comment]
:P

**Comment by meteos77** [comment]
your argument is a bit short :-)
I make my mea culpa : I should have made a suggestion in the discussion format instead of making a ticket
that would have surely allowed to better determine the functionality.

BibliteQ does the bare minimum with the new contribution field
I don't see the librarian reviewing each member's form to see if its validity date has expired to send him an email or a letter?

the membership field is relevant if it is reused somewhere else, otherwise the expiration date would be enough.

the mail feature is very interesting : 
I never received from a library that my subscription was over and asked me if I wanted to re-register (it's rather a physical contact).
This mail feature will be really interesting in the context of returning overdue documents.

**Comment by textbrowser** [comment]
I'm adding a Tools menu to Members Browser. There will be an action which will allow the library to set the membership fees of all patrons. A confirmation will exist. A librarian would set this manually on January 1st for example. This solution is not great because patrons who have already paid will be required to pay again. We only know who has paid if there is at least one additional field in the member table; a last-paid or something similar field. As you notice, I don't like this solution because it isn't BQ. It's transforming BiblioteQ into an accounting project even if the change is relatively small.

**Comment by meteos77** [comment]
as I had put this ticket not urgent I probably did not think enough about the problem.
if it's too complicated, leave this function alone

BiblioteQ is obviously not an accounting project but it is the one that holds the list of members and its management. To have all of them in the same software is still very practical for users like us
we could take an association management software and copy the members but it would be less practical
we could take a simple spreadsheet but the same problem of synchro of users
if you have an external solution to BiblioteQ, I'm interested

the solution you propose that a librarian sets the membership fee to zero on January 1 is good for a library that, like us, has subscriptions from January 1 to December 31
for those who manage from date to date this functionality will not be used but at the expiration warning message and therefore contribution

All the library softwares that I tested propose to manage a minimum of the subscription even if it is not their first goal it is part of the obligations of many libraries (in any case in France - rare are the entities not asking for a subscription even symbolic)

the one currently used, even manages the history of the contributions and statistics by years.

**Comment by textbrowser** [comment]
Histories are troublesome for libraries and privacy. Anonymous statistics are more beneficial. :)

**Comment by meteos77** [comment]
I quite agree with you that statistics should be anonymous
![Cotisation](https://user-images.githubusercontent.com/56431039/152832759-71effd88-d53f-49b1-b0f0-d074919d2784.png)


on the page of the current statistics on the contributions only the details are nominative.

in order by month, by year, by age, by city, by grades ? graphs and the number of memberships per month. and finally details by person.

I find relevant the statistics
by year to see the evolution of the number of members.
by city to see the area of influence of the library.
by age group to see what we have to supply as documents with the departmental library. (youth, adult)

**Comment by textbrowser** [comment]
> 

It's nice. Since the data exists in BQ, a more competent process which is designed for statistics is the best solution. If one is not available, SQL itself is a solution.

**Comment by meteos77** [comment]
great reset of the counters at the beginning of the year

**Comment by textbrowser** [comment]
You may close the ticket if you're happy with the solution.

**Comment by meteos77** [comment]
is it my turn to close? how to do it ?

**Comment by textbrowser** [comment]
Solutions without an additional last-set field.

1. A cron job which automatically sets the desired membership_fees field for all patrons.
2. The new Tools option.
3. Individually set the value through BQ.
4. Set the membership_fees for only the selected patrons.

Two solutions are already present.

**Comment by meteos77** [comment]
when it is closed it is always open :-)

2 and 3 are good and are enough for me to manage contributions

the 1 : cron to "remind the librarian" that he has an action to do to reset the counters and BiblioteQ does its internal cooking for the statistics before erasing.

the 4 : it seems to me vague : you select the members who are in delay of contribution and make an action ?

**Comment by textbrowser** [comment]
Highlighted Membership Fees would help the librarian select the appropriate members before using the new tool. This way, the fees are applied to a specific set.

**Comment by meteos77** [comment]
suggestion: Member Manager

- add the column "members' contribution" in the view
- be able to reduce the size of each column to a smaller size (to have more visible columns) (like in the document view)
- have the choice of visible columns (like in the document view)

**Comment by textbrowser** [comment]
Membership Fees added. Minimum column size removed. Visible columns? Maybe another time. :)

**Comment by meteos77** [comment]
_visible columns_ was a way to have the information that we want
DVD, CD, VIDEO GAMES ... useless but with the decrease in size of the columns, all is ok
and as usual, I make a suggestion, I never know too much work that it will ask you behind
thank you for the 2 improvements, they are perfect
