### ISSUE TITLE
1 need Chinese translation; 2 cloud backup of databases; 3 auto scan book barcode.

### ISSUE THREAD

**Issue by zhou0** [textbrowser/biblioteq#17]
I want to manager my books using this app. Can you add Chinese translation?

also it will also be neat if user can backup the database to cloud automatically because tragedy happens to personal computer almost all the time and it will be just too sad to have to input all the book data again. 

it would also be handy if we can use webcam to scan the barcode of a book so that user need not to manually input  data into the database.

**Comment by textbrowser** [comment]
A translator is needed for the first request. If you're interested, you'll need to learn Qt's Linguist.

I think the second request is beyond the normal duties of the application. A portion of BQ users prefer PostgreSQL. (https://www.postgresql.org/docs/9.1/static/backup.html) There are open source backup products for local files.

The third item has been requested and it would be great to have.

Let's leave this ticket open.

**Comment by textbrowser** [comment]
A new translation file is available (https://github.com/textbrowser/biblioteq/blob/master/Translations/biblioteq_zh_CN.ts). Please use Qt's Linguist and update the contents of the file.
