### ISSUE TITLE
not urgent : add search field (Ctrl+F ) Author

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#174]
the authors field would be a plus to know which books he wrote

thank you in advance

**Comment by textbrowser** [comment]
Or you could try a Book search instead.

**Comment by textbrowser** [comment]
General
-----------
Book
...
...

**Comment by meteos77** [comment]
I discover BiblioteQ :-)  you can close my request

**Comment by textbrowser** [comment]
First look and then ask. :P

**Comment by meteos77** [comment]
I don't understand the use of Ctrl+F, it's a double use ?

and I will always prefer the keyboard shortcut; it's my fault :-)

**Comment by textbrowser** [comment]
Find?

**Comment by textbrowser** [comment]
Ctrl + F = General Search (Find)

**Comment by meteos77** [comment]
each one makes different searches and there it is the super search multi documents (Books Dvds... at the same time)
I don't understand all the fields like id or quantity (do they have a different id and a search by quantity?)

author has probably all its place because we can want to know if we have the books and the movies from the same author?

**Comment by textbrowser** [comment]
In the General search, the ID covers a specific item's field which is believed to be its ID. For example, books have ISBNs and journals have ISSNs. None of the fields are required. A Copy of 0 indicates that the field should not be included in the search most likely because BQ does not store items which do not have representation.

**Comment by textbrowser** [comment]
I included the fields which are represented by all of the categories in the General search. Otherwise, a specific search is more adequate. It was intuitive, I suppose.

**Comment by meteos77** [comment]
yes it is logical : general search on general fields

it's true that I only test on books, so the other categories of documents are rather a mystery to me

if you have a small demo base to share to present BiblioteQ ; that would be great

**Comment by textbrowser** [comment]
Which categories are confusing?

Grey Literature represents electronic and physical items: documentation, legal documents, anything really.

**Comment by meteos77** [comment]
not confusing (translation problem probably)
I don't use them so I am not aware of the practices in these areas. 
for example the collections of photos I absolutely do not know how it is classified and organized to manage the collections
fields : copyright, reproduction, number, medium, format
are they included in the back of the photo? in a digital file, are they in the EXIF format field? all this information is a mystery to me. 

it's far from the management of a library that has other specific fields and other ways of practice.

**Comment by textbrowser** [comment]
The information is rational and photographs can exist digitally. I use it at home for family pictures. Most of the fields are not necessary. Imagine storing information in physical and digital formats about WWII. One could access the archives without damaging the originals. The meta-information is for both archivists and a patron. BQ is also an archiving project.

**Comment by textbrowser** [comment]
You can attach files to books. If you have PDFs or other formats, they can exist in the database. For PQ, patrons do not have to be at a library to access the material. They can look at it in BQ for PDF content or download it for other readers.

**Comment by textbrowser** [comment]
Since PQ has archiving things, BQ can hop along for the fun.
