### ISSUE TITLE
978 or 9-78 + convert isbn13 -> isbn10

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#177]
when importing a csv, the isbn-13 formatting is rendered perfectly 9-xxxxxx-yyyyy (if you choose the option) in the book detail window but when asking for a conversion to isbn-10, BiblioteQ asks for a 978 or 979 ; it doesn't like the first dash :-)
978 or 979 OK but not 9-78 or 9-79

can you enlarge the permission with the 2 dashes
thank you in advance

**Comment by textbrowser** [comment]
Try now.

**Comment by meteos77** [comment]
all working well thank you

**Comment by textbrowser** [comment]
Is The Dispossessed available in your collection?

**Comment by meteos77** [comment]
if it is the novel of Ursula K. Le Guin; no they do not have this title; there are many books of this author but not this one

internally we don't have any of them.

[recherche-ursula-k-le-guin.pdf](https://github.com/textbrowser/biblioteq/files/7884067/recherche-ursula-k-le-guin.pdf)

**Comment by textbrowser** [comment]
It should be present. She briefly states the lost relationship between maker and user. But the overall story ignites this framework and others. Maker and user; like faraway countries.

**Comment by textbrowser** [comment]
Completed until the next one.
