### ISSUE TITLE
not urgent : Z3950 : undesirable character

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#178]
the Z3950 server of the sudoc (France) has as a rule of classification not to take into account the articles in the title of the documents

result when Z3950 adds a book through them, the titles with article are found with the ascii code 0098 at the beginning and 009C after the article

example : \La \révolution des fourmis

can you remove the 2 ascii codes in the title field to have something clean

thank you in advance

**Comment by textbrowser** [comment]
Z39.50 should be removed instead. If I remove it for the blanket person, I will be asked about it. You'll have to await custom implementations. :)

**Comment by textbrowser** [comment]
And I am asking again to slow down. We have discussed much and there are pending items that require priority. I cannot respond to every request without proper consideration. :)

**Comment by meteos77** [comment]
ok no problem, but aren't the tickets there to store the requests ?
I want to put my requests in a file on my computer :-)

**Comment by textbrowser** [comment]
Sure and we have discussed this topic in conversations too. We cannot make progress in a disorganized manner.

**Comment by textbrowser** [comment]
This is what I see:

example : \�La \�révolution des fourmis

.

**Comment by textbrowser** [comment]
You should specify the precise codes. $a, $b, etc. and then provide examples.

**Comment by meteos77** [comment]
isbn13 : 978-2226-0863-65
Z3950 server : Sudoc (france)

my image was not integrated in my 1st message
![pb-ascii](https://user-images.githubusercontent.com/56431039/150495233-a25292d4-515f-4e27-89e4-58a2dc6cfe39.png)

it's in the 200$a zone
![PB_Sudoc-ascii](https://user-images.githubusercontent.com/56431039/150495363-3a20e2bf-c327-42fb-b3a1-ee5c04122795.png)

**Comment by textbrowser** [comment]
Wait a minute! There is nothing to remove. This is probably a locale problem.

**Comment by textbrowser** [comment]
Results of my query.

01591cam0 2200517   450 
001 003862410
003 http://www.sudoc.fr/003862410
005 20210112140926.000
010    $a 2-226-08636-6 $b br. $d 22 EUR
010    $a 978-2-226-08636-5
020    $a FR $b 09622360
021    $a FR $b DL 96-19098
033    $a http://catalogue.bnf.fr/ark:/12148/cb358187920
035    $a 094724520 $9 sudoc
035    $a (OCoLC)300913954
035    $a sib0753048
035    $a ocm36008888
035    $a frBN021465472
035    $a FRBNF358187920000004 $z FRBNF35818792
073  1 $a 9782226086365
100    $a 19960620d1996    m  y0frey50      ba
101 0  $a fre
102    $a FR
105    $a y   z   000ay
106    $a r
181    $6 z01 $c txt $2 rdacontent
181  1 $6 z01 $a i# $b xxxe##
182    $6 z01 $c n $2 rdamedia
182  1 $6 z01 $a n
183  1 $6 z01 $a nga $2 RDAfrCarrier
200 1  $a La révolution des fourmis $e roman $f Bernard Werber
210    $a Paris $c A. Michel $d DL 1996 $e 18-Saint-Amand-Montrond $g Impr. Bussière
215    $a 1 vol. (533 p.) $c couv. ill. en coul. $d 24 cm
305    $a Autre tirage : 1998, 2006
345    $b 9782226086365
606    $3 027233405 $a Fourmis $3 027342204 $x Roman $2 rameau
606    $3 027248267 $a Science-fiction $2 rameau
675    $a 823 $v Éd. 1967
676    $a 800
680    $a PQ2683.E65 $b R48 1996
700  1 $3 030637554 $a Werber $b Bernard $f 1961-.... $4 070
801  3 $a FR $b Abes $c 20210112 $g AFNOR $h 094724520
801  3 $a FR $b BN $c 19990130 $g AFNOR
801  3 $a FR $b SF $c 19990209
801  1 $a US $b OCLC $g AACR2
801  2 $a FR $b AUROC

**Comment by textbrowser** [comment]
database_name = abes-z39-public
format = "utf-8"
hostname = carmin.sudoc.abes.fr
name = Sudoc (France)
password =
port = 10646
proxy_host =
proxy_port =
record_syntax = unimarc
timeout = 10
username =

Is your definition different?

**Comment by meteos77** [comment]
same configuration for the server 
if you open my database, the characters are present ?
[test-les-fourmis.sqlite.zip](https://github.com/textbrowser/biblioteq/files/7914926/test-les-fourmis.sqlite.zip)


I think it's the characters for the sorting : [iso6630](https://www.itscj-ipsj.jp/ir/067.pdf)
Non-sorting characters: the NSB and NSE control characters are used in some examples to represent positions 08/08 and 08/09 of ISO 6630 4 respectively; they surround strings that are not used for sorting. used for classification.

**Comment by meteos77** [comment]
I tested with the 15/12 version ; I just compiled BiblioteQ
it's my configuration that causes the problem but what parameters can influence the reception of the Z3950 ?
on virtual machine with linuxmint 20.3 freshly installed + installation of the 15/12 version of BiblioteQ -> identical problem

tested on raspberry version 15/12 and there it's OK

**Comment by textbrowser** [comment]
Locale.

**Comment by textbrowser** [comment]
Your database is shown properly here.

**Comment by textbrowser** [comment]
QString::fromUtf8() converts the strings received from the Z39.50 server.

**Comment by meteos77** [comment]
I did not find a solution; my locales are in fr_FR_UTF-8
I have no problem with characters in the system 

I don't even know where to look in the different configuration files, if you have an idea ?

with yaz-client , it's OK
![UNIMARC](https://user-images.githubusercontent.com/56431039/150801651-795d730a-6cd7-4513-8512-e6281ddde4af.png)

**Comment by textbrowser** [comment]
If it's system-dependent, it's going to be difficult to explain.

**Comment by meteos77** [comment]
this is a brand new linux mint 20.3 installation from this weekend with default settings.

**Comment by textbrowser** [comment]
Did you configure the yaz-client identically to the configuration settings in BQ?

**Comment by meteos77** [comment]
yaz-client carmin.sudoc.abes.fr:10646/abes-z39-public
format unimarc
find @attr 1=7 "9782226086365"
show 1

**Comment by textbrowser** [comment]
How about the format?

render; charset=utf-8

**Comment by textbrowser** [comment]
I'll try it too.

**Comment by textbrowser** [comment]
The character set is something else in the client.

**Comment by meteos77** [comment]
lang parameter ?

**Comment by textbrowser** [comment]
Interesting.

displaycharset utf-8

And I do not see the special accented e in 200.

**Comment by meteos77** [comment]
I see it

**Comment by textbrowser** [comment]
I tried lang fr and the e is normal.

**Comment by meteos77** [comment]
marccharset is none ?

**Comment by textbrowser** [comment]
I set that to utf-8 too. e remains normal.

**Comment by textbrowser** [comment]
It could be BQ, Qt, your system, the YAZ library, or gremlins.

**Comment by meteos77** [comment]
can we specify more options in the biblioteQ.conf file for the yaz client?
page 132 of the doc https://software.indexdata.com/yaz/doc/yaz.pdf

**Comment by textbrowser** [comment]
Not unless there is an implementation behind it. The yaz-client and the YAZ library do not have 1-1 mappings. I wanted that when I discovered it. Like a generation option where one can place a myriad of settings which would be interpreted by YAZ without BQ mapping it. So, yes but no if it isn't mapped.

**Comment by textbrowser** [comment]
You're discovering the idea that open source is the general solution. It is plagued by nebulous things where options don't exist because developers are lazy. Or requiring 10,000 libraries to get a bit of information.

**Comment by meteos77** [comment]
I will test with the Z3950 server of the BnF

**Comment by textbrowser** [comment]
What will that show?

**Comment by meteos77** [comment]
nothing but they provide 3 bases
ISO5426
UTF8 : UNICODE UTF-8
LATIN1 : ISO8859
and I continue my research

**Comment by textbrowser** [comment]
List the new options you'd like.
Then find the mappings.

For example, you could define a general_option_1 = "key_a = ...", etc.

Then BQ can set that without having to map it using the YAZ API (key_a would be something in YAZ).

**Comment by textbrowser** [comment]
And we can have infinite general_option options. The person would be responsible for faulting and living or dying. :)

**Comment by textbrowser** [comment]
It could be simpler.

YAZ_name_of_option = value

BQ will remove YAZ_ and set the option name_of_option to the value value.

**Comment by textbrowser** [comment]
Yup, I do that and then I don't have to think.

**Comment by textbrowser** [comment]
The thinking will be on you. :) Find the options and experiment.

**Comment by textbrowser** [comment]
Another reason I don't use Z. It's busted.

**Comment by meteos77** [comment]
I'd like to too but the servers have a different base that the Bnf doesn't have; so no more records available

**Comment by meteos77** [comment]
the option to test would be related to the command 
charset negotiationcharset [displaycharset] [[marccharset]]

currently BiblioteQ interacts the server with the negotiationcharset with the special name - ?

**Comment by textbrowser** [comment]
No, not negotationcharset.

**Comment by meteos77** [comment]
![gremlins](https://user-images.githubusercontent.com/56431039/150825321-55c647c7-0d54-4660-9d07-0b69a06eec8e.jpeg)

**Comment by meteos77** [comment]
the yaz version is different between linux mint (5.28.0-1build2) and raspberry os (5.30.3-1)

**Comment by textbrowser** [comment]
Yes, the gremlins.

**Comment by textbrowser** [comment]
Perhaps it's Linux Mint.

**Comment by meteos77** [comment]
finally find it!
in biblioteq.conf : do not specify the line : record_syntax and everything is fine

**Comment by textbrowser** [comment]
Strange. Why?

**Comment by textbrowser** [comment]
So fixed? Excellent job. Closing!

**Comment by textbrowser** [comment]
Something new.

https://github.com/textbrowser/biblioteq/commit/d97cf910317eb8dabca4ced62058159468781fa6

**Comment by meteos77** [comment]
thank you for all the options but despite all the evolutions you have made, the only solution that really works is to delete the line record_syntax = unimarc or put usmarc.
all the yaz_xxxxx options don't change anything in the sudoc server response
this line of configuration overrides all other yaz_xxx

what I could observe in a network capture, it is if the server answers with usmarc request, it is ok in 245 13 a for the title.
if we specify in the biblioteq.conf the : record_syntax = unimarc , it answers well in unimarc with the zone 200 $a but the undesirable characters appear.

**Comment by meteos77** [comment]
yaz_format = unimarc
yaz_charset = utf-8 utf-8
yaz_query utf-8
yaz_marccharset utf-8
yaz_display utf8
yaz_lang fr
yaz_databaseName = abes-z39-public
record_syntax = usmarc

**Comment by textbrowser** [comment]
The record_syntax maps to preferredRecordSyntax. If record_syntax is empty, BQ sets it to MARC21.

**Comment by textbrowser** [comment]
This override can be canceled of course. :)

**Comment by meteos77** [comment]
the 3 types of configurations presented do not have a field : record_syntax specified in the configuration 
UNIMARC / MARC21 at choice with UTF8 on port 10646
[sudoc config](https://abes.fr/reseau-sudoc/reutiliser-les-donnees-sudoc/z39-50/)

after the communication with the server to specify that we want to be in UNIMARC is not too important for the moment because the server answers well in MARC21 and the BiblioteQ parser is OK in MARC21

with the yaz-client and the record_syntax command line is OK through BiblioteQ and the yaz library, there is still a little problem which depends on the server so ... can we close this subject ? 
if in the future other people have problems of this nature, we'll have to look at this question again :-)

**Comment by textbrowser** [comment]
People are not interested in such intricacies. It's like a raging climate. Too difficult, tune it out.

**Comment by textbrowser** [comment]
I will comment the assumption which BQ applies.

**Comment by textbrowser** [comment]
Done.

**Comment by meteos77** [comment]
for the configuration of the Z3950 Sudoc server (France)
the biblioteq.conf file contains the line record_syntax = UNIMARC
and the characters
0098 NON-SORT BEGIN / START OF STRING
009C NON-SORT END / STRING TERMINATOR
appear in the titles with articles with the server [Z39.50-7] (Sudoc France)

2 solutions work
replace the line
record_syntax = UNIMARC to record_syntax = MARC21
or delete this record_syntax line

exemple : 978-2226-0863-65

**Comment by textbrowser** [comment]
Done. Timeout also added.
