### ISSUE TITLE
Arabic (Jordan) language option is not in the list of languages

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#18]
Thank you very much for your efforts and My great thanks for this wonderful work
But There are some notes:
1- The Arabic (Jordan) language option is not in the list of languages
FROM options languages.

2. It is important to add YYYY only option in publication date
FROM other options

3. I have modified some of the translated terms as shown in the attached file 1-5-2017biblioteq_ar_JO

4. When I change the database password, the database remains without a password even though the system is shut down and restarted

I will test BiblioteQ software in our library, and if there are updates on the translation OR any Other notes I will send it to you.

Thank you for your cooperation.

[1-5-2017biblioteq_ar_JO.zip](https://github.com/textbrowser/biblioteq/files/967672/1-5-2017biblioteq_ar_JO.zip)

**Comment by textbrowser** [comment]
You're right! Just uploaded a correction for the first point.

**Comment by textbrowser** [comment]
Second item, yyyy in Other, is complete.

**Comment by textbrowser** [comment]
Uploaded your new TS file.

**Comment by textbrowser** [comment]
I need more information about the password problem. Are you expecting to see asterisks in the UI after a change? They will not be displayed.

**Comment by 2010fares** [comment]
If the password problem is repeated I will send you. I am afraid that the problem is caused by the operating system in my computer.
Thanks again for your help and cooperation.
