### ISSUE TITLE
Z39.50 Mokka (Hungary)

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#181]
Please update for next version:

[Z39.50-3]

**database_name = mokka**
format = marc8s,utf8
hostname = z3950.mokka.hu
name = Mokka (Hungary)
password =
**port = 2210**
proxy_host =
proxy_port =
record_syntax = MARC21
timeout = 10
username =

**Comment by textbrowser** [comment]
Completed.

**Comment by textbrowser** [comment]
Completed again.
