### ISSUE TITLE
not urgent: management of delays in the return of borrowed documents

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#182]
if the person has given his email address to be able to send him an email

if the person has given his cell phone number, I can send him a text message

if the person has given his postal address send him a letter

**Comment by textbrowser** [comment]
So what's the request? :P

**Comment by textbrowser** [comment]
1. BQ is not transforming into an e-mail system.
2. Integrate SMS?
3. BQ will craft automatic letters for the post office?

There are aspirations, but it's fine to have tools specific for tasks.

**Comment by meteos77** [comment]
NO URGENT .NO URGENT I should have put it in the discussion area

I don't ask BiblioteQ to do the work of mail, sms and mailing but biblioteq can be connected to the outside world by calls to other specialized programs.
mailto opens the mail manager defined on the host system and puts an attachment 
the recipient's address and a message with the overdue books (for example I use thunderbird)
the librarian presses a button and the mail is sent (thanks BiblioteQ)

people use their phone more so sms has a future

when the letter, if BiblioteQ formates a nice PDF that the librarian prints and sends by mail it will be perfect (we have people who do not have a smartphone, nor internet to contact)

**Comment by meteos77** [comment]
I would rather have BiblioteQ format a nice mail/message than having to copy/paste the information from the overdue documents, the contact information ...and copy them into a Libreoffice document or a Thunderbird message

the software has all the information you need, you just have to format them and provide them to other programs

**Comment by textbrowser** [comment]
OK.

**Comment by textbrowser** [comment]
Place the database in an encrypted drive on a FreeBSD or Linux machine. Also duplication. Upgrading the server software is my only complaint. :)

**Comment by textbrowser** [comment]
I recently upgraded an instance on FreeBSD.

1. I have a weekly cron which performs an export of two schemas in the late evening / early morning.
2. Upgraded the FreeBSD PQ server. This is easy.
3. Recreated the schemas. Easy.
4. Imported the large files. Easy but untimely.
5. Brief data verification. Removed the old PQ data files.

That's the extent of an upgrade of the PostgreSQL server software between major versions.

**Comment by meteos77** [comment]
FreeBSD : nobody knows
PostgreSQL : nobody knows
only 1 machine under windows10
no computer network
no telephone network
very few electrical outlets 2 from memory

I want to have fun at home with all this little world for the fun of it, but don't count on other people from the library to maintain it all.

BiblioteQ + Sqlite is PERFECT for that 
copy the .sqlite file on a usb key for backup and when I pass, I copy everything on my ssd.
if the machine crashes : redo windows10 + install BiblioteQ + last backup

we are not a structure with a computer service but an association of volunteers whose goal is to provide books on loan :-)

**Comment by meteos77** [comment]
and if the machine is out of order BiblioteQ is so small that it runs with a raspberry

**Comment by meteos77** [comment]
I try the FreeBSD adventure at home

**Comment by textbrowser** [comment]
> FreeBSD : nobody knows PostgreSQL : nobody knows only 1 machine under windows10 no computer network no telephone network very few electrical outlets 2 from memory
> 
> I want to have fun at home with all this little world for the fun of it, but don't count on other people from the library to maintain it all.
> 
> BiblioteQ + Sqlite is PERFECT for that copy the .sqlite file on a usb key for backup and when I pass, I copy everything on my ssd. if the machine crashes : redo windows10 + install BiblioteQ + last backup
> 
> we are not a structure with a computer service but an association of volunteers whose goal is to provide books on loan :-)

A few hundred years ago people knew that Earth was the center of everything. Then someone introduced them to new information. So, introduce them.

**Comment by textbrowser** [comment]
> FreeBSD : nobody knows PostgreSQL : nobody knows only 1 machine under windows10 no computer network no telephone network very few electrical outlets 2 from memory
> 
> I want to have fun at home with all this little world for the fun of it, but don't count on other people from the library to maintain it all.
> 
> BiblioteQ + Sqlite is PERFECT for that copy the .sqlite file on a usb key for backup and when I pass, I copy everything on my ssd. if the machine crashes : redo windows10 + install BiblioteQ + last backup
> 
> we are not a structure with a computer service but an association of volunteers whose goal is to provide books on loan :-)

If you can flow electrons to a device, it can run PostgreSQL. PQ can live on a separate drive.

https://pimylifeup.com/raspberry-pi-postgresql/

A network is not required. If you can survive with SQLite, you can survive with a legacy card catalog. You see? You would say that BQ and SQLite simplify many other duties. And I would say that the next thing to simplify the unknowns and the known would be a database worthy of data.

**Comment by meteos77** [comment]
the mail generation works perfectly
%1 : name
%2 : first name
%3 : member fee due

Additional request: can we have a new variable %4 with the list of overdue loans for the member.

**Comment by textbrowser** [comment]
String arguments are intended for brief values, not lists.

**Comment by meteos77** [comment]
I think the subject is closed

if BiblioteQ can only send the name and the first name to the person, 
and his membership fee; I don't see much point in developing this feature further

**Comment by textbrowser** [comment]
It would require the retrieval of all borrowed items, bundling them into a list, and placing that content into the clipboard buffer.

**Comment by textbrowser** [comment]
The correct answer:

A cron job which queries the SQLite database and determines which loaned items are expired. Once these items are known, it creates an e-mail and sends it to the designated administrator. The administrator then contacts the patron with additional information / actions. A desktop application is not suitable for automating such concepts because (a) it isn't suited for daemon-like behavior and (b) embedding site-specific duties into the application is a poor solution.

This is yet another reason for PQ. Some NAS systems have this automation for other duties.

**Comment by meteos77** [comment]
our computer is only running during the 2 hour shifts.
I'll do a notice when I'm up to speed on the overdue books.

I just saw List all overdue items in the member view.

listing all overdue items in the general view; we will note the names 
then in the member view -> list of overdue items of the member.

the practical option for this request and others would be to be able to refilter a search result (a header)
![entonnoire-Personne](https://user-images.githubusercontent.com/56431039/162583002-475639e5-63a8-4f86-bb56-c39ba5dfa313.png)

**Comment by textbrowser** [comment]
Members Browser has a feature for exporting overdue items for the selected member. Export As CSV. Then you can attach this to the e-mail.

**Comment by textbrowser** [comment]
And by it has, I mean it should. :D

**Comment by meteos77** [comment]
the attachment csv  is good

**Comment by textbrowser** [comment]
Yes, but someone has to yet make another export thing.

**Comment by textbrowser** [comment]
Real libraries automate this stuff and do not create dependencies on desktop applications.

**Comment by textbrowser** [comment]
Connect a Pi to computer, read the SQLite database, determine the expired items, and send emails. Easy. Learning opportunity. Not inflating BQ with things that most people will not use (also must be kept current if database changes occur and the export only retrieves specific fields). That's the future. Solving solutions on your own. :) That's what I do. I mean, whenever I encounter a thing that Linux doesn't do, I create my own solution.

**Comment by meteos77** [comment]
export already exists?
if in member we ask for the delays of member 1
then export the view in CSV
save the CSV and attach to the contact mail

**Comment by textbrowser** [comment]
For my databases, I have a simple cron job which creates copies of them at night (off-hours) and then I manually remove older copies. The results are compressed and if I error, I return to archived copies. This is site-specific activity and it's fun.

**Comment by textbrowser** [comment]
> export already exists? if in member we ask for the delays of member 1 then export the view in CSV save the CSV and attach to the contact mail

No, it needs to be implemented. I categorize this as a site-specific task and not something desktop applications are meant for. BQ is not a mailing system.

**Comment by meteos77** [comment]
I agree with BQ, for the large site and their millions of documents; but for my 70 members and 10 volunteers it will be enough. If we have 50-100 reminders in a year to manage :-)

**Comment by meteos77** [comment]
I have spent far too many hours in front of my screen over the past 40 years
I still spend way too much time in front of my screen today.
I hope to find some turnkey solutions :-)

my motivation for computer science is decreasing year after year
I don't explain it, I'm interested in other things, that's it

5 years ago I would have looked with interest ... not anymore

**Comment by meteos77** [comment]
I am currently doing my documentation for my library and I am in the search function

currently there is 
1 - the general search at the top of the main page (case sensitive)
the function you just modified with the wildcard : %.

2 - the general search : By the menu "Tools/Database search" or "Ctrl+F
the % is included in the queries

3 - the specific search by type of documents
the % is included in the queries

question : you are not going to modify queries 2 and 3 to make them more strict
obligation to use the % ? 

I find the current situation (1 strict and 2 & 3 relaxed) very good

**Comment by textbrowser** [comment]
Right, I am leaving them alone.

**Comment by textbrowser** [comment]
> I have spent far too many hours in front of my screen over the past 40 years I still spend way too much time in front of my screen today. I hope to find some turnkey solutions :-)
> 
> my motivation for computer science is decreasing year after year I don't explain it, I'm interested in other things, that's it
> 
> 5 years ago I would have looked with interest ... not anymore

If the original data resided in relational database, it would be possible using select and insert statements.

Short of artificial intelligence, two solutions exist: import and manual.

**Comment by meteos77** [comment]
in bibliography there is a standard exchange format MARC
if everyone respected the standard with  
1 - MARC export
2 - MARC import
 ... the good times are ours :-)
