### ISSUE TITLE
Multiple pages sort

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#183]
If the (eg keyword) search results in more items that the "entries/page" option, not all of the results gets sorted and splitted to pages, but the other way around.

**Comment by textbrowser** [comment]
Which search are you using?

Manner in which search results are sorted is based on their types. For example, say we have two tables A and B. BQ sorts A and B, not the union of A and B.

**Comment by tamascz** [comment]
- Eg search by keyword "8." (class number for textbooks for me)
- Main window sort (only) by title.
- Entries per page: 10. 

1st page: (first) 10 hits, titles beginning from B... to N...
2nd page: E... - T...
3rd page: A... - T...

**Comment by textbrowser** [comment]
Those results are not sorted by the database. I'll add a tool tip stating this.

**Comment by textbrowser** [comment]
I looked a bit. BQ sorts the results of the unions. Or, SORT (A U B U C U ... U Z) and not SORT(A) U SORT(B).

**Comment by textbrowser** [comment]
Completed. :)

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/10d1bfb7babf2d929fa69a2d722c9f35a7ddb8a4

Thanks for the ticket.
