### ISSUE TITLE
"2022.02.30"

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#184]
#define BIBLIOTEQ_VERSION "2022.02.**30**"
February 29 occurs every four years, but February 30 will be a precedent... 😉

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/List_of_non-standard_dates#February_30

BQ is smart.

**Comment by textbrowser** [comment]
Happy that you noticed it. Perhaps it was intentional. Perhaps it was not.
