### ISSUE TITLE
new version of BiblioteQ 2022.02.30

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#185]
thanks for the new version of BiblioteQ which will landmark  :-)

when the 38 errors during the update of the schema ?
should I worry ?
[Log-mise-a-jour-base.txt](https://github.com/textbrowser/biblioteq/files/8168496/Log-mise-a-jour-base.txt)

improvement suggestion
during this update, it is necessary to update the schema of the sqlite database
can you help the user by suggesting him to update the schema when opening the database if it is obsolete
because Please upgrade database schemas. in the Release Notes is a bit hidden :-)

**Comment by textbrowser** [comment]
There is an "Upgrading an SQLite Database Schema" section in the documentation.

**Comment by textbrowser** [comment]
The errors are self-explanatory.  :) SQLite attempts to modify the schema. If something already exists and it cannot modify it, the attempt fails.

The statements must be curtailed in the future, but some person will become demented because their 8-year old version does not work today.

**Comment by meteos77** [comment]
I had never used Tool/Update SQL Schema because I was importing my database from csv at each new version. It is with surprise that I receive these errors but they are not errors :-)

not everyone is an expert in sql and reading the 38 errors does not indicate if it is problematic or not

how to know if the error for example n°37 is "normal"?

70. CREATE TRIGGER grey_literature_purge_trigger AFTER DELETE ON grey_literature FOR EACH row BEGIN DELETE FROM item_borrower WHERE item_oid = old.myoid; DELETE FROM member_history WHERE item_oid = old.myoid AND type = old.type; END ;

Error 37 : the grey_literature_purge_trigger already exists, impossible to execute the instruction. Statement : CREATE TRIGGER grey_literature_purge_trigger AFTER DELETE ON grey_literature FOR EACH row BEGIN DELETE FROM item_borrower WHERE item_oid = old.myoid ; DELETE FROM member_history WHERE item_oid = old.myoid AND type = old.type ; END ;.

**Comment by meteos77** [comment]
everyone has these 38 mistakes or is it just my base?

**Comment by textbrowser** [comment]
As written before, there is specific baggage that is carried over from several (many) revisions. My preference was including only statements which alter the previous schema of a database with respect to the current release. Some people have complained. I will not create statements to inspect the intent of each statement before executing it.

Customers are expected to have some oversight of their data. With PQ, it is far easier to upgrade the schema than it is with SQLite.

In a future, near, release, I'll remove most of the statements.

How do you know? You have to have some sense of intuition with regards to SQLite. :)

**Comment by textbrowser** [comment]
There is the upgrade process or the manual process. :P If you have alternatives which do not involve a new Moon, I will help.

**Comment by meteos77** [comment]
I don't know if it's a new moon, but when opening the database BiblioteQ checks that it can have write access to it, so at the same time BiblioteQ could also check if the schema is the right one, otherwise it would display a little message saying "Be careful to update the schema so that everything works properly".

**Comment by meteos77** [comment]
for errors with ALTER ... once you know and it doesn't matter it's not a problem anymore.

maybe specify it in the documentation
if you encounter 
"Error xx: duplicate column name: yyyyyy to execute statement. Statement: ALTER TABLE " 
this is part of the normal process

**Comment by textbrowser** [comment]
Include the software version in the SQLite database? I suppose that's fine. It would make development annoying if someone plays around with versions or if the version has to change for a few days later. But what if the upgrade fails on some statements while the version statement succeeds? You'd have a correct version but an incorrect schema. :P Then there are reminders for people using the database as read-only (not file permissions). So there would have to be a do-not-remind-me option. I know, many unlikely situations. But it'll happen. :)

**Comment by textbrowser** [comment]
The ALTER statements may succeed in Qt but fail in SQLite. I'm seeing it now. Reviewing it. Could be a problem or could not be. I don't know if SQLite has a 'IF NOT EXISTS' for fields. It does for tables, triggers, and some other things. I'll add your suggestion first. That's easy.

**Comment by meteos77** [comment]
my suggestion is just an information to the user that his version is obsolete (I had the case this morning with the change to be made) BiblioteQ opened my database but at the time of the loan
message : Impossible to extract the data concerning the member to fill the table.

even if managing the version of the database implies side effects, warning the user beforehand of the real cause is more relevant than leaving the database in v1 with the application in v2 until the error message which does not inform of the cause

**Comment by meteos77** [comment]
You'd have a correct version but an incorrect schema
this is way beyond my skills :-)
idea : if you analyze the output of the requests and you have only normal errors" you can apply the tag of the new version, if not we stay at the old version

**Comment by meteos77** [comment]
the update tool should not check the version tag, so if the user wants to reapply the update, he can
and if the database is in a bad state, the user realizes it

**Comment by textbrowser** [comment]
"Did you read the release notes?"

**Comment by meteos77** [comment]
after the problem :-)

**Comment by textbrowser** [comment]
"They are not that long."

**Comment by textbrowser** [comment]
Google release notes: improved stability of device.

**Comment by meteos77** [comment]
at least google is clearer :-)

**Comment by meteos77** [comment]
I tested the version of the day (git), great
thanks again for the less experienced users :-)
no more errors in updating the schema

[2021-10-30_log_vers_2022-03-30.txt](https://github.com/textbrowser/biblioteq/files/8178839/2021-10-30_log_vers_2022-03-30.txt)
