### ISSUE TITLE
Can not use database after upgrade

### ISSUE THREAD

**Issue by RyanMcCoskrie** [textbrowser/biblioteq#186]
After upgrading to the latest version from one from about six months to a year ago I can no longer properly view or modify my library's database.

The SQLite DB loads without error and and selecting the "Books" category works as it did before but when I go to view a book's details or enter a new book I get a message reading "Unable to retrieve the selected book's data".

**Comment by textbrowser** [comment]
Did you read the release notes? It asks that schemas be updated. Tools -> Upgrade...

**Comment by textbrowser** [comment]
The documentation also has information covering upgrading of schemas. Future releases will include persistent reminders.

**Comment by textbrowser** [comment]
Did you update your database?

**Comment by textbrowser** [comment]
Silence. Closing.

**Comment by RyanMcCoskrie** [comment]
Sorry for the silence. I'm only in the library* for one afternoon per week.

I just ran the upgrade and it seems to have worked, I can view and save books again. There were a bunch of "Column already exist" errors but those seem to be redundant. Please implement the reminder ASAP.

*It's the kind of sleepy village library that still keeps borrower accounts in a box of paper cards.

**Comment by textbrowser** [comment]
The state of the database is the customer's responsibility. Reading release notes is important. :)

Good luck.
