### ISSUE TITLE
Guard SQL queries.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#188]
Difficult to correct because BQ is very mature. The goal is to prevent SQL queries from polluting the program. As an example, SELECT title FROM book, may result in a dead process if title contains many characters. With PostgreSQL, this is simpler to prevent because of permissions. Not impossible. With SQLite, this is easy. Replace a functional database file with an infected one.

One solution: SELECT SUBSTR(title, 1, 250) FROM book.

https://www.sqlite.org/limits.html#max_length

**Comment by meteos77** [comment]
I can't help you with sql but I don't think any author or publisher would choose a title of two hundred and fifty characters or more.
There is no room on the cover and it is not attractive for a potential buyer.
 This text is 250 characters long :-)

**Comment by meteos77** [comment]
on my book base the maximum found is 69 characters
title : "QUE CROIS-TU QU'IL ARRIVA ? L'HISTOIRE DE MOUMINE, MUMLA ET PETITE MU"

SELECT title,LENGTH(title),book.myoid, book.type FROM book ORDER BY LENGTH(title) DESC

**Comment by meteos77** [comment]
title of the longest book in French
isbn : 9782917084472 (sudoc)
title : "My musician mother, died of a malignant disease at midnight, Tuesday to Wednesday, in the middle of May of the year 1997 at the Memorial Nursing Home in Manhattan"

result 146 characters

**Comment by textbrowser** [comment]
Consider:

```update book set keyword = (select keyword || keyword || keyword || keyword || keyword from book where myoid = 1) where myoid = 1;
sqlite> select length(keyword) from book;
18408000
```
So 18 million characters. BQ is dead. :)

**Comment by textbrowser** [comment]
This is a malicious attack that's impossible to prevent unless the query retrieves a reasonably-limited string.

**Comment by textbrowser** [comment]
The query itself must be of the form SUBSTR(keyword, 1, N).

**Comment by textbrowser** [comment]
sqlite> select length(keyword) from book;
575250000

Functional adaptation: "SUBSTR(keyword, 1, 2048) AS keyword".

**Comment by textbrowser** [comment]
With thousands and thousands of queries, yikes. Queries and sub-queries (WHERE keyword IN (...)), yikes again.

**Comment by textbrowser** [comment]
Diagnostic tools die too.

**Comment by meteos77** [comment]
good luck then :-)

**Comment by textbrowser** [comment]
That is why this is a ticket for an expert and diligent person. It'll serve as a warning to future people. :)

**Comment by meteos77** [comment]
thank you for this reassuring information
to make these malicious queries you have to use the BiblioteQ interface with the "Custom Database Query" feature ?

**Comment by textbrowser** [comment]
No.

> cat /dev/urandom | od -h > output
Copy some text. Then use sqlite3 tool to update a table entry. Open BQ, open the database, open the particular book and die.

**Comment by meteos77** [comment]
I'm glad I'm not networked at the library  one less thing to worry about

**Comment by textbrowser** [comment]
Your SQLite file can be easily replaced.

**Comment by textbrowser** [comment]
You mean a digest / fingerprint? That's possible with SQLite. Kind of nearly impossible with PQ.

**Comment by meteos77** [comment]
exemple : md5

**Comment by meteos77** [comment]
SQLITE version: at the beginning of your ticket, your link referred to the limit of sqlite, are not it effective?

**Comment by textbrowser** [comment]
Do you trust the operating system? Do you trust yourself remembering the fingerprint? Where does trust begin? The optimal solution (assuming that the executable is not changed) is to prevent the software from reading too much data.

**Comment by meteos77** [comment]
I trust you :-)

**Comment by textbrowser** [comment]
> I trust you :-)

I don't trust myself. :P

**Comment by meteos77** [comment]
if it's lost then let's pretend it doesn't exist :-)

**Comment by textbrowser** [comment]
Of course, the queries have to be protected from themselves. There are probably join queries which return data that is fine but the joins are critically impacted because of sizes. It's a messy world.

**Comment by meteos77** [comment]
for each record, the size of the addition is necessarily the sum of all fields filled to the maximum allowed

title : 250
author : 400
publisher : 300
...
max 15000
if > 15000 not valid

this restricts the user's freedom

**Comment by textbrowser** [comment]
I don't believe that these are necessary if the queries are intelligent.

**Comment by textbrowser** [comment]
TO-DO.
