### ISSUE TITLE
Validate numeric values read from configuration files.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#189]
Numeric values must be within valid ranges.

**Comment by textbrowser** [comment]
Numeric values in the INI files are bounded.

**Comment by textbrowser** [comment]
Z39.50 proxy port numbers are assigned to the YAZ library as text values. Does the library validate them?

**Comment by meteos77** [comment]
I don't know if this will answer your question
configurations for the 2 French servers (Sudoc et Bnf)

https://abes.fr/reseau-sudoc/reutiliser-les-donnees-sudoc/z39-50/
https://www.bnf.fr/sites/default/files/2019-01/parametres%20_config_Z3950_bnf_0.pdf

**Comment by textbrowser** [comment]
It's alright. I tested a value of 20000000000000000000000 for a port and the connection failed. This is good.

**Comment by textbrowser** [comment]
This be done.
