### ISSUE TITLE
How Can enter return of a lent book?

### ISSUE THREAD

**Issue by Pieratius** [textbrowser/biblioteq#19]
Good software, I can use SQL complex commands with SQLite.
The only disadvantage 'There is no user manual!'
How Can enter the return of a lent book?

**Comment by textbrowser** [comment]
There will be a manual someday.

As for your question. You can see an item's reservation status in the details panel. Click on the Reservation Status button. See included image.

![biblioteq](https://cloud.githubusercontent.com/assets/10701156/26110878/920f4412-3a21-11e7-82aa-aa955ab3ce37.png)
