### ISSUE TITLE
small imperfection on translatable fields

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#195]
Thank you for the version of 2022-03-30

When creating a new document, the fields: Language, Monetary Units, Location and Book Binding Type have a value "UNKNOWN" in English.
The translation does not seem to be done while in the .ts file; I have a translation of UNKNOWN in INCONNU(E)

Can you see that ... if the correction is easy and not time consuming. Thank you in advance

**Comment by textbrowser** [comment]
The defaults are UNKNOWN in English in the database. For SQLite, the string which defines the schema will need to be changed. For PostgreSQL, this isn't possible because the database is not per person. If you change the language, the SQLite defaults cannot be changed in real-time. So, English.

**Comment by textbrowser** [comment]
Source/biblioteq_sqlite_create_schema.h:    language     VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',            \

**Comment by textbrowser** [comment]
And you need to provide details. Where are you seeing the text? There are numerous places. Dynamic translation is not programmed into all of the widgets.

**Comment by meteos77** [comment]
![UNKNOWN](https://user-images.githubusercontent.com/56431039/160839743-0ed34e41-1a0d-42cf-bec4-51d71b455f15.png)

**Comment by meteos77** [comment]
it seems to be in this file biblioteq/Source/biblioteq_a.cc

line 78 : QString biblioteq::s_unknown = QObject::tr("UNKNOWN");

if I replace here UNKNOWN by UNKNOWN then recompile, I have the new text that appears

**Comment by meteos77** [comment]
![UNKNOWN-INCONNU](https://user-images.githubusercontent.com/56431039/160841495-c2a242b1-7712-4399-b10d-54e12f96c80f.png)

**Comment by textbrowser** [comment]
You must have encountered this before. Why mention it after a release? :P

**Comment by meteos77** [comment]
I'm not a machine and my testing never stops :-)
in the past, I rather imported by csv and the fields were filled with my own values.

**Comment by meteos77** [comment]
it is necessary to have new things to put in the future publication notes :-)

**Comment by textbrowser** [comment]
In the French translation file (.ts), some shortcuts are CRTL instead of CTRL. Is this correct?

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/bc722dfc288d4d3b6bf39408a148f5ccda5f24be

**Comment by meteos77** [comment]
error on my part, thank you for your vigilance
Crtl + W instead of Ctrl + W
the copy and paste is not that good :-)
I correct for the next version

**Comment by meteos77** [comment]
ticket sold out quickly
thank you
