### ISSUE TITLE
not urgent : Request for improved cover recovery with isbn13 starting at 979

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#196]
report : cover recovery does not work with isbn-13 starting with 979

example of existing coverage
ISBN13 : 9791026900948
https://www.amazon.fr/s/ref=nb_sb_noss?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Dstripbooks&field-keywords=9791026900948

ISBN13 : 9791026901679
https://www.amazon.fr/s/ref=nb_sb_noss?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Dstripbooks&field-keywords=9791026901679

ISBN13 : 9791033900214
https://www.amazon.fr/s/ref=nb_sb_noss?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Dstripbooks&field-keywords=9791033900214

according to my research going from isbn13 to isbn10 is not possible with an isbn-13 starting with 979
the site https://www.pearson.com/us/isbn-converter.html shows me "NO ISBN EQUIVALENT".

I think that the recuperator of covers asking an isbn-10 even for the isbn13 beginning with 979 calculation thus a bad isbn-10 because impossible

In the ISBN-10 and ISBN-13 converter
if in ISBN13 : 9791026901679 gives in ISBN-10 : 1-0269-0167-7
for the reverse 
if in ISBN10 : 1-0269-0167-7 gives in ISBN-13 : 978-1026-9016-70

can you modify the cover search for isbn-13 starting with 979 by taking as parameter the isbn13 and not the isbn10

**Comment by textbrowser** [comment]
979 is not backwards compatible.

**Comment by textbrowser** [comment]
The converter functions and produces an ISBN-10. It doesn't validate it.

**Comment by textbrowser** [comment]
What's the URL?

https://images.amazon.com/images/P/9791026900948.01._SCMZZZZZZZ_.jpg

Does not work.

**Comment by meteos77** [comment]
suggestion : it would be necessary to have new servers to recover the covers.
The Bibliothèque nationnale de France (BnF) with its Z39.50 and SRU servers provides a unique identifier per record.
the ark identifier

example : isbn13 : 979-1033-9002-14

- is available in Z39.50 on the field : 
003 http://catalogue.bnf.fr/ark:/12148/cb452115699

- it is available in SRU on the parameter
<srw:recordIdentifier>ark:/12148/cb452115699</srw:recordIdentifier>

with this identifier, they set up an api to recover the covers of the documents

cover recovery
front_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=1&largeur=100&hauteur=250"
back_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=4&largeur=100&hauteur=250"

reference
https://github.com/hackathonBnF/hackathon2016/wiki/API-Couverture-Service

**Comment by meteos77** [comment]
according to my research, depending on the amazon server that we query, it finds or not the document
amazon.US ;amazon.UK; amazon.FR; amazon.DE ...
After the gcstar program can determine and extract the image but I am not expert to know how to (perl language)

**Comment by textbrowser** [comment]
I'm not adding another API for images nor another library. I will add a separate HTTP(S) URL. :)

Amazon
Open Library
Other

HTTP or HTTPS only.

**Comment by meteos77** [comment]
the api is just to make a request to the http address of the Bnf the cover image with the "ark identifier" which is in zone unimarc 003 or the field <srw:recordIdentifier> in SRU

I tried to modify the biblioteq.conf by taking the example of openLibrary but the popup does not update

[National Library of France Cover Images]
# For Bnf users
# ark_identifier format= ark:/12148/cb452115699
# in Z3950
# with line 003, get the ark:...... identifier
# identifiant_ark=ark:/12148/cb452115699
# 003 http://catalogue.bnf.fr/ark:/12148/cb452115699

# in SRU
# with the field <srw:recordIdentifier> retrieve the ark identifier
# <srw:recordIdentifier>ark:/12148/cb45512621b</srw:recordIdentifier>

front_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=1&largeur=100&hauteur=250"
back_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=4&largeur=100&hauteur=250"

**Comment by textbrowser** [comment]
A new Other option is necessary.

**Comment by textbrowser** [comment]
This is completed. Available next release.

**Comment by textbrowser** [comment]
> the api is just to make a request to the http address of the Bnf the cover image with the "ark identifier" which is in zone unimarc 003 or the field srw:recordIdentifier in SRU
> 
> I tried to modify the biblioteq.conf by taking the example of openLibrary but the popup does not update
> 
> [National Library of France Cover Images] For Bnf users ark_identifier format= ark:/12148/cb452115699 in Z3950 with line 003, get the ark:...... identifier identifiant_ark=ark:/12148/cb452115699 003 http://catalogue.bnf.fr/ark:/12148/cb452115699
> 
> in SRU with the field srw:recordIdentifier retrieve the ark identifier srw:recordIdentifierark:/12148/cb45512621b</srw:recordIdentifier>
> 
> front_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=1&largeur=100&hauteur=250" back_url = "http://catalogue.bnf.fr/couverture?&appName=NE&idArk=ark:/12148/cb452115699&couverture=4&largeur=100&hauteur=250"

HTTP is forwarded to HTTPS so HTTPS is stated in biblioteq.conf. Only the front image is currently supported.

**Comment by meteos77** [comment]
it's a troubleshooting for the moment amazon does the job with some exceptions
on the 400 documents integrated in december, about ten were not on amazon
