### ISSUE TITLE
Search from main window - accession number : strict search

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#199]
FINDING : When searching on accession_number=534 on the main search
[Liste-534.csv](https://github.com/textbrowser/biblioteq/files/8441106/Liste-534.csv) - result 19 found in my database
summary
[Liste-534.pdf](https://github.com/textbrowser/biblioteq/files/8441255/Liste-534.pdf)

The type 1 request seems to be the standard operation (not the real request but in spirit)
type 1 : select * from book where accession_number **like "%534%"**

SUGGESTION : can you put an option to have a type 2 request
type 2 : select * from book where accession_number **like "534"**

like the option: Case Insensitive ; have for example: Strict Search

**Comment by textbrowser** [comment]
I'll remove the special wildcard character instead. A new tool tip too. That way patrons are required to input the character.

**Comment by textbrowser** [comment]
The entire basic search is now exact. New tool tip. New release notes.

https://github.com/textbrowser/biblioteq/commit/fe8dc8faaff49e75dcd0e42eb9dfd62dd4211349

**Comment by textbrowser** [comment]
This broke the search for PostgreSQL. The original request was too involved to make exact. Also, it's more natural to search for similar things than exact things. So now I have this mess. Ugh. It was working perfectly. I don't understand the request for the change and why I listened. :P

**Comment by meteos77** [comment]
You were convinced by the change request because my example was demonstrative :-)

it only concerned the field accession_number if I search a number, generally it is that I know it.
in my example if I search for 534 it's because I have the book in my hand and I want to lend it.

Is there a "reverse wildcard" for example $=no character ?
to search strictly 534 => $534$

if I am looking for an alphanumeric string like Title, Keywords or Category, the search must be more open.

you open on strings but close on lowercase/shift by default? (see our discussion on Case Sensitive and Case Insensitive)
I am already afraid of unsuccessful searches :-)

**Comment by textbrowser** [comment]
The more characters, the fewer results.

Let's consider the worst case. A single character. Well, neither search type will help unless you're lucky that the result ends or starts with this magic character. Let's say you know 5 characters and this creates 100,000 entries. Still a problem. Once I hit this problem, I use another search criteria. If I have the item in my hand, I scan the barcode or I type some of the least common words in the title or the author or I add a several more characters in the accession number.

I'm perplexed at this methodology. I understand that you need this. Have you considered using a better search approach?

**Comment by meteos77** [comment]
with a picture it's more demonstrative
![Exemple-Numérotation-Livres](https://user-images.githubusercontent.com/56431039/162628063-1fcebc16-a10e-418d-8722-78759470db89.png)

this number will always be a search number for us
advantages
- present on every book for 20 years
- 4 digits if there is a problem with the shower head (up to 9999 books)

future situation
- to have all the isbn-13 informed on all the internal books with the shower in working order

- to have a quick solution in case of hardware failure (4 digits to note) 
even if the computer breaks down, we note that Mr. XXXX borrowed 1024, 75 and 7002 on xx/yy/zzzz.

this solution also allows during the time of the transition to be serene, even if we do not have all the isbn-13, the time does not play against us.

**Comment by textbrowser** [comment]
The titles are unique. The authors are unique.

We have here a request to fix a problem which is a problem of the catalog and not of the software.

**Comment by textbrowser** [comment]
A single character as uniqueness is bad practice.

**Comment by textbrowser** [comment]
If I were placed with this task, I would correct this nonsense and apply proper cataloging practices that will work with any software.

**Comment by meteos77** [comment]
I never mentioned a problem, I just suggested a strict option 
because I noticed that with a different SQL query my problem didn't exist anymore

with 8 I have 2071 results
with 534 I have 19 results
but with 7070 and 7062 it's ok

**Comment by meteos77** [comment]
history : on the edge of the books there is not much space ; he probably wanted to make only one label ...

**Comment by meteos77** [comment]
for an optimal use, the final system will be based on isbn-13 with barcode reader.

**Comment by meteos77** [comment]
if there is no more computer, power, shower, computer screen ; I would like to know your recommendation ?
