### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gionapoli** [textbrowser/biblioteq#2]
I need the italian translation for the GUI,
where I can find? or how can i make by my self?

Thanks
Giorgio

**Comment by textbrowser** [comment]
Sorry for the delay. An Italian translation doesn't exist.

To create one, you'll need to become familiar with Qt's Linguist application. You'll also need to download BQ's source.

**Comment by paolofrancioso** [comment]
Hello textbrowser. I'm interested in italian translation too. If you prepear a flat file/excel I can translate everything for you.

**Comment by textbrowser** [comment]
I'll see if this is possible with the Linguist.

**Comment by textbrowser** [comment]
Please see https://github.com/textbrowser/biblioteq/tree/master/Translations for the Italian translation file (biblioteq_it_IT.ts). You'll need to learn Qt's Linguist.

**Comment by textbrowser** [comment]
Expired.
