### ISSUE TITLE
BiblioteQ Problems with Windows Operation Systems and BiblioteQ Problem with Password Selection

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#20]
############################
FIRST:
############################
"BiblioteQ & Operation Systems" Windows Problems
................................
1-
Microsoft Windows XP Professional Version 2002 Service Pack3
Here the error massage
![biblioteq1](https://cloud.githubusercontent.com/assets/7378389/26388814/4a5db5f6-405f-11e7-8bf0-7968c4bcd4b1.JPG)

2-
Windows 7 ULTIMATE       64-bit Operating System
Here the error massage
![biblioteq22](https://cloud.githubusercontent.com/assets/7378389/26388840/627acf7a-405f-11e7-900c-15baea09e7f8.jpg)

3-
Windows 7 ULTIMATE       32-bit Operating System    Service Pack 1
Here the error massage
![biblioteq3](https://cloud.githubusercontent.com/assets/7378389/26388848/6dd6d396-405f-11e7-8cab-ac06d1443808.jpg)

############################
Second:
############################

"BiblioteQ & Password Selection Problem"

Userid  field  is empty and not active

Nothing happen When I entered New Password and Confirm Password  

ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
We are testing BiblioteQ software in our library, and if there any Problems I will send it to you.

Thank you for your cooperation.

**Comment by textbrowser** [comment]
I abandoned Windows XP. So did Qt. I'll look at the Windows 7 side.

**Comment by textbrowser** [comment]
Did you try the instructions in https://github.com/textbrowser/biblioteq/tree/master/Libraries.win32/miscellaneous.d?

**Comment by textbrowser** [comment]
![biblioteq](https://cloud.githubusercontent.com/assets/10701156/26411910/1fed90e6-4075-11e7-9fd3-31469e234dc0.png)

**Comment by 2010fares** [comment]
Hello

1-
I tried the instructions in master/Libraries.win32/miscellaneous.d also the same error massge still appear

![biblioteq3](https://cloud.githubusercontent.com/assets/7378389/26436723/2e5bce52-4121-11e7-83b6-d3ffea836cbc.jpg)
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
2-
Here are the update translation attachment of the biblioteq_ar_JO.ts file
[biblioteq_ar_JO 25-5-2017.zip](https://github.com/textbrowser/biblioteq/files/1028018/biblioteq_ar_JO.25-5-2017.zip)

ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
3-
What is the difference between 
local_db   sqlite
&
xbook_db  postgresql
About  Password Selection Problem
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

Thank you very much for your cooperation.

**Comment by textbrowser** [comment]
Try installing Microsoft's Universal C Runtime from https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows.

BiblioteQ supports both PostgreSQL (networked) and SQLite (local) database engines. In biblioteq.conf, you could define one or more instances (branches) of PostgreSQL databases that BiblioteQ may access.

Also in biblioteq.conf, you'll notice a single SQLite (local) branch for local SQLite files.

**Comment by 2010fares** [comment]
Thank you very much for your help

When I installing Microsoft's Universal C Runtime from link you send it to me
The BiblioteQ Work well  and The error message has disappeared.
ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ

For Password Selection Problem with local_db sqlite
Here are a video  attachment : 
[BiblioteQ Change Password.zip](https://github.com/textbrowser/biblioteq/files/1029851/BiblioteQ.Change.Password.zip)

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
Thank you again for your help

**Comment by textbrowser** [comment]
Awesome.

Your changes have also been uploaded.

**Comment by textbrowser** [comment]
If you don't mind answering, where are you using BiblioteQ?

**Comment by 2010fares** [comment]
Currently I used BiblioteQ at Ahnaf bin Qais school library
If the test succeeded, The system will be distributed to all school libraries related to Ministry of Education in Jordan.

**Comment by textbrowser** [comment]
Great. If you need assistance, I'll be happy to help.

**Comment by textbrowser** [comment]
Does Windows XP also work now?

**Comment by 2010fares** [comment]
Thank you very much, for your kindness. Of course we will need your help and experience.

I tested the update only on Windows7 but I did not test the update on Windows XP, Currently Ahnaf school library has a Holiday, but when holiday finished I will go there for test the update on Windows XP. 

Thank you again

**Comment by 2010fares** [comment]
I tested the update on Windows XP . But unfortunately the BiblioteQ system did not work.

**Comment by textbrowser** [comment]
That's expected. I have an old XP installation disk. It would require several days to install and prepare it for Qt.

Have you considering migrating off of Windows and onto Linux?

**Comment by 2010fares** [comment]
Moving to Linux is a good step and it is under study, but there are difficulties in moving to Linux,  Librarians in Arab countries are afraid to deal with the Linux system, in addition to other reasons.

This requires a copy image CD of the Linux system that includes the BiblioteQ and its requirements, and this CD should be easy to install.
Thanks my friend for your idea.

**Comment by textbrowser** [comment]
New platforms require [re]education. Linux offers significant cost benefits. It has also become more conscious regarding internationalization support. Of course, it's open source. Reusing older hardware is another benefit.

PostgreSQL thrives on low-end laptops and high-end super servers.

**Comment by 2010fares** [comment]
Your proposal is logical and good. Of course, we will take this proposal into consideration, 
Of course I will need your help and advice in this regard.
Thanks my friend.

**Comment by textbrowser** [comment]
Linux Mint and Ubuntu are user-friendly distributions.
Good luck.
