### ISSUE TITLE
No one knows what 461$v means. That's also silly.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#201]
No one knows what 461$v means. That's also silly.

_Originally posted by @textbrowser in https://github.com/textbrowser/biblioteq/issues/167#issuecomment-1092031843_

https://multimedia-ext.bnf.fr/pdf/aide_memoire_unimarc.pdf

**Comment by meteos77** [comment]
it's a bad manipulation on my part
I remind you that the github interface is not in my language, it should stay in the other ticket

**Comment by textbrowser** [comment]
You created a meme.

**Comment by textbrowser** [comment]
For librarians and eggheads.

**Comment by meteos77** [comment]
we are co-authors :-)

**Comment by textbrowser** [comment]
![6bs1sv](https://user-images.githubusercontent.com/10701156/162272701-20ceaf12-fee3-481e-af3f-d8ef2a4a6733.jpg)

**Comment by meteos77** [comment]
tonight I would have spent a good evening laughing
thanks textbrowser!
