### ISSUE TITLE
Alternative Identifier field in the CSV import model 1

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#209]
With the imports of the Bibliothèque Départementale I have the chance to have access to the Ark:// identifier by script for a part of my data recovery.

Can we have in the csv import tool (Templace 1 - the BiblioteQ Books(All Fields) Alternative ID field?
thank you in advance if it is possible of course

**Comment by textbrowser** [comment]
Completed.

https://github.com/textbrowser/biblioteq/commit/1ea0ac93d8a2f1b9ae75512c2b4315a2872772d1

Also added the multi-volume field so be careful.

**Comment by meteos77** [comment]
I did not understand how the field works multi-volume-set-isbn field works?

https://github.com/textbrowser/biblioteq/issues/167

I did not manage to create 2 books with identical isbn-13 even in 
1 - copying the isbn13 in Multi-Volume Set ISBN
2 - putting the volume number 1 . 2 .. ( the famous 461$v) in Multi-Volume Set ISBN

can you explain how this feature works ?

**Comment by meteos77** [comment]
Rapport on Multi-Volume Set ISBN
[2022-04-16_Catmandu-avec-prets-permanents.zip](https://github.com/textbrowser/biblioteq/files/8501428/2022-04-16_Catmandu-avec-prets-permanents.zip)

it seems to accept that isbn-10
if 2 isbn-10 => both OK (exemple 1)
if 2 isbn-13 => both KO (exemple 2)
if 1 isbn-10 and 1 isbn-13 only isbn-10 is taken into account whatever the order isbn-10 before (exemple 3) or after isbn-13 (exemple 4)

the error message is about book.edition is not about multi_volume_set_isbn as expected?
Database error (NOT NULL constraint failed: **book.edition** Unable to fetch row) at row 3.

**Comment by meteos77** [comment]
the import works perfectly on one condition
if isbn-10 is in multi_volume_set_isbn -> OK 
if isbn-13 is in multi_volume_set_isbn -> it doesn't work

**Comment by textbrowser** [comment]
Most likely caused by UNIQUE constraint. As I don't use this value, I would have expected the person requesting it to validate the state before it was published.

**Comment by textbrowser** [comment]
Again, this is what happens when users want things without deep considerations. SQLite does not allow you to drop constraints, so those databases are quite incorrect. And I'm not going to write a mechanism to fix that.

With PQ, this is easy to resolve.

**Comment by textbrowser** [comment]
OK, removed the UNIQUE constraint. With SQLite, you'll have to create a new database and merge the original.

**Comment by meteos77** [comment]
let's take some time to think,

 we may have gone the wrong way in managing these multiple document types.
for me this field should host the volume number and not isbn-10 or isbn13

**Comment by textbrowser** [comment]
To me, it's clear. MVI is optional and its oversight should be managed by the site and not by BQ. If you assign an MVI incorrectly, that is something you need to correct.

1. MVI cannot be unique because multiple items cannot have a UNIQUE value.
2. MVI can be NULL, so a NOT NULL constraint is not appropriate.

I am curious about a unique field applied to a set of items. How would that work for a database? How do you tell it that these items in the set are part of the set but these items are not? Perhaps creating a "unique" table, separate of the database engine. So, something you have to invent.

**Comment by meteos77** [comment]
what is an MVI?

**Comment by meteos77** [comment]
the problem does not come from the single constraint
he doesn't want isbn13 in the multivolume?

but the error is 
Database error (NOT NULL constraint failed: **book.edition** Unable to fetch row) at row 2. and not from the field  multi_volume_set_isbn ?


my test file
[KO-import_2-with-isbn13.csv](https://github.com/textbrowser/biblioteq/files/8501757/KO-import_2-with-isbn13.csv)

**Comment by textbrowser** [comment]
> what is an MVI?

Multi-Volume ISBN

**Comment by textbrowser** [comment]
After this and the other import request, I will not be working on imports. Anyone is welcome to submit requests, and I'll ignore them. This work is beyond the scope of BiblioteQ.

**Comment by textbrowser** [comment]
The proper solution is not BiblioteQ. It isn't an import tool.

**Comment by meteos77** [comment]
abandonment of the management of multiple documents with the same isbn.

**Comment by textbrowser** [comment]
Import correction completed.

https://github.com/textbrowser/biblioteq/commit/bfd5a926a0d2f619dca6d3cc52c04620350fb35e

**Comment by textbrowser** [comment]
In the KO-... CSV, you have descriptions. These now need to be imported.

**Comment by meteos77** [comment]
if I remember, there is something impossible with
Summary / Description so we had abandoned the import of the summary.
I try to find the discussion or the ticket

after my files are files which are **formatted by the departmental library for all the libraries of the department**,
Some information is essential for us to manage our library;
 other libraries have software that presents a web portal where the summary is presented to potential readers ...

**Comment by textbrowser** [comment]
The function was never implemented.

**Comment by meteos77** [comment]
we don't have internet at the library so no web server :-)

**Comment by meteos77** [comment]
To avoid losing information from the old software, I concatenate in the field "Keywords" all these information.
Date of Arrival : YYYY/MM/DD
Origin : Purchases, Private donation, BDP donation
Format : Standard ; Pockets ; Large format
Public : Youth, Adolescents, Adults

with the following formatting
BEGINNING; Arrival Date= 1995/12/15; Origin = BDP; Format = Pocket; Audience = Youth; END

Is this relevant in your opinion?

**Comment by textbrowser** [comment]
It's your data. That's my opinion.

**Comment by meteos77** [comment]
I am asking for your opinion about the management in BiblioteQ

for example, I want to have a statistic on how many documents for the public "Young" we hold in the year 2022?

I would like to know how many documents for the young public we have in 2022, as a result of the annual purchase, we take adult books or books for the young public.

**Comment by meteos77** [comment]
the year of arrival is for the Weeding
to have the list of all the books that are more than 15 years old for example

**Comment by textbrowser** [comment]
My answer: my opinion is irrelevant.

**Comment by meteos77** [comment]
Origin: belongs to the Bibliothèque Départementale, we can return them after 10 years for example

**Comment by textbrowser** [comment]
Consider BiblioteQ as an open world where it has as few constraints as possible. It can't be constraint-less because the Universe isn't and neither are we. But, it can let you think for yourself.

Anyway, the other description business is done too.

**Comment by textbrowser** [comment]
> I am asking for your opinion about the management in BiblioteQ
> 
> for example, I want to have a statistic on how many documents for the public "Young" we hold in the year 2022?
> 
> I would like to know how many documents for the young public we have in 2022, as a result of the annual purchase, we take adult books or books for the young public.

There exists a reminder for statistics. But, this isn't an open solution. It's for basics. An all-you-can-eat solution is site-specific. Since SQL is open, you know your data and you know what your patrons are interested in and you know what the purpose of the library is. Therefore, you know what statistics you need. BQ's business is to remove itself. Of course, it could have favorites and notes for queries. Those are other possibilities. But if I am asked for special queries, I'll say stop and think for yourself. BQ is for everyone. Site-specific things don't belong in it.

**Comment by meteos77** [comment]
it's not every day that I have the chance to exchange with a specialist developer :-)

**Comment by meteos77** [comment]
for the SQL requests, I have filled the discussion  https://github.com/textbrowser/biblioteq/discussions/179 and you helped me for the most complex ones.

I have a problem with my information, because the corresponding fields do not exist.
I have to find a way to place them in the database it is done in keywords.

Now I'm at the stage where I'm thinking about how to use this data.

Is it possible in SQL to extract a part of an answer from inside it?
I searched on the net but I didn't find it,

**Comment by meteos77** [comment]
I'm interested in BiblioteQ because it presents the SQL language + SQLite : for me the best of both worlds
- no server to manage
- opening with SQL

**Comment by textbrowser** [comment]
PostgreSQL doesn't require management. Sure, for large corporations there is tweaking and review and thinking. For smaller projects it's not much work. The database is configurable. SQLite is a poor choice for important data.

**Comment by textbrowser** [comment]
> for the SQL requests, I have filled the discussion #179 and you helped me for the most complex ones.
> 
> I have a problem with my information, because the corresponding fields do not exist. I have to find a way to place them in the database it is done in keywords.
> 
> Now I'm at the stage where I'm thinking about how to use this data.
> 
> Is it possible in SQL to extract a part of an answer from inside it? I searched on the net but I didn't find it,

I need an example of your request.

**Comment by meteos77** [comment]
[2022-06-Bibliothèque.sqlite.zip](https://github.com/textbrowser/biblioteq/files/8502116/2022-06-Bibliotheque.sqlite.zip)

**Comment by meteos77** [comment]
With the progress of the past weeks, I will redo all the different imports for my total base.
I think I'll come up with something really good

**Comment by textbrowser** [comment]
An example of what you want the query to do.

**Comment by meteos77** [comment]
displays the list of books that have a purchase date < 2015/01/01
SELECT keywords, accession_number, title, authors FROM book WHERE keyword."Date d'achat" < 42005

**Comment by textbrowser** [comment]
SUBSTR(keyword, x, y) to extract the date. Then you have to perform a string comparison. YYYYMMDD should be your string format. So: NOT_A_REAL_FUNCTION_DATE(SUBSTR(keyword, x, y) ...) < '20150101'.

**Comment by meteos77** [comment]
thank you for giving me the basics, I'll see how I can make the most of my data
good sunday
