### ISSUE TITLE
French Documentation

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#212]
[French-Package-edition-Mai 15, 2022.zip](https://github.com/textbrowser/biblioteq/files/8689561/French-Package-edition-Mai.15.2022.zip)

changes
- screenshots in French in the French documentation.
- optimization of .odt (images)
- Welcome file
- Real xhtml file for the link to the french documentation
- Release Note to date

Thanks for the integration in the future packages
update paperback and hardcover

**Comment by textbrowser** [comment]
Committed. :)
