### ISSUE TITLE
.deb package not installable on Debian.

### ISSUE THREAD

**Issue by yasbean** [textbrowser/biblioteq#217]
Beginning with the 2022.05.30 release, the amd64.deb package will not install on Debian because the control file is compressed using zst, but Debian dpkg has still not incorporated zst support in dpkg.  Could you please continue packaging with .xz until Debian finally includes .zst?

**Comment by textbrowser** [comment]
Remember, the release files are free courtesies. :) I spend about two to fours hours preparing all of them. If they do not suit you, build from source!

**Comment by FriedrichFroebel** [comment]
Given that you obviously have to do lots of manual stuff, wouldn't it be feasible to check out GitHub Actions as continuous integration system for this? This should resolve at least the Debian issue (although I did not test it). I am not sure about the different architectures (apart from x86_64) as well as Android and Apple nevertheless. For Windows this depends on how you are able to install the requirements, as this proved to be difficult sometimes as far as I remember.

**Comment by textbrowser** [comment]
Android, PowerPC, Mac, Windows cannot be automated unless I create a configuration platform for the systems. This would require that I have one or more devices persistently active. Quite expensive.

Pi yes. Debian, perhaps.

**Comment by textbrowser** [comment]
I work as following. For Windows, a virtual machine which requires Qt and GH's Git program to be current. PowerPC is quite dead with respect to Debian. However, that requires that the machine be powered on. Compilation is quite slow. Pi, not expensive as I power it from a laptop. Mac, another laptop that is obsolete and compilations are dreadfully slow. Android, it can be built from a terminal perhaps. Although QtCreator will update itself and dependencies. Mac, Homebrew. It's messy and it's all a lot of work and people generally are not happy.

**Comment by yasbean** [comment]
Here is a Debian amd64.deb package, just in case anyone wants.  I had to gzip it to be able to attach it here. 
@textbrowser Delete this post if it is inappropriate.
[BiblioteQ-2022.05.30_amd64.deb.gz](https://github.com/textbrowser/biblioteq/files/8817919/BiblioteQ-2022.05.30_amd64.deb.gz)

**Comment by textbrowser** [comment]
Included with the release.
