### ISSUE TITLE
Request: Add an "Express Reserve" dialogue.

### ISSUE THREAD

**Issue by RyanMcCoskrie** [textbrowser/biblioteq#218]
The library that I volunteer would like to use Biblioteq in conjunction with a barcode scanner. As far as I can tell presently books are reserved one at a time. Would you be open to adding a dialogue where multiple copies of books can be found by their barcodes and then reserved to one member together? A similar dialogue for scanning in books that have been returned would also be well appreciated.

I have started making a prototype for this dialogue but have got a bit lost on how classes such as biblioteq_borrowers_editor and Ui_membersBrowser become connected. I've worked with Qt5 before but the code had a very different architecture.

**Comment by textbrowser** [comment]
A function similar to this exists. See image. It works for a single item. You'd like multiple items. It's possible. I'll see if I can complete it for the next release. Maybe July.

![Screenshot_20220623_081425](https://user-images.githubusercontent.com/10701156/175296464-9d9ccf5a-32a4-49e4-bcda-c762709d785c.png)

**Comment by RyanMcCoskrie** [comment]
What I mean is not searching for the book by title, accession number, etc because the borrower has already selected a copy.

**Comment by RyanMcCoskrie** [comment]
So instead of:
Search for book 1 -> Search for member -> Choose copy -> Reserve
Search for book 2 -> Search for member -> Choose copy -> Reserve

Simply:
Search for member -> Enter copy-id 1, Enter copy-id 2 -> Reserve

**Comment by textbrowser** [comment]
This is part of batch processing which has been discussed numerous times with BQ. We shall see. :)

**Comment by RyanMcCoskrie** [comment]
After giving it some consideration I have decided to continue developing this feature for my own library's use. If you are interested I will provide the source once it is complete otherwise it will be a private local patch.


I hope I don't sound rude but this is a must have feature for a public lending library, we are too small to use server orientated software and our team of mostly retired volunteers are tired of handling borrower information on paper.

**Comment by textbrowser** [comment]
I'm working on another hobby project (Glitch) now. I will look in July for this request. It's easy conceptually.

**Comment by meteos77** [comment]
I am also a volunteer in an associative library (in France) and it would be interesting for us to have your development shared because this functionality is also expected to manage the loans / returns.
thank you in advance

**Comment by textbrowser** [comment]
Started!

**Comment by RyanMcCoskrie** [comment]
> Copy identifiers are unique to an item but not to the database.
How are those different?

Also for what it's worth here's some highlights of what I've made so far:

[Express Window screenshot](https://imgur.com/a/nBvPrHJ) - It should have item type selector of course but I'm aiming for something that works well enough for my library first.

Adding an item to the queue:
`QString barcode = ex.barcodeEdit->text();
query.prepare("SELECT item_oid FROM book_copy_info WHERE copyid = ?");`
_skip_
`QString item_oid = query.value(0).toString();
 query.prepare("SELECT title, author, accession_number FROM book WHERE myoid = ?");`

**Comment by textbrowser** [comment]
Checkout the new .ui file. It resembles your panel. (Batch Activities)

**Comment by textbrowser** [comment]
I <may> complete this request before the end of July unless I melt.

**Comment by textbrowser** [comment]
BQ over Pi!

BQPi.

**Comment by textbrowser** [comment]
Done.

https://user-images.githubusercontent.com/10701156/195208497-9bf23812-0913-466a-8851-8c0eac9759a5.mp4
