### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#22]
Greetings
In BiblioteQ General Database Search We always faced a problem when searching in any field for example:
 if we know the title but we do not know the date of publication will not show results 
This problem is repeated in all search windows
![image1](https://user-images.githubusercontent.com/7378389/28749692-fbb71ed4-74d8-11e7-97ad-9a45a3ccfcfe.jpg)
So I suggest
The user should have the option to cancel fields (date of publication - Price - copies) when searching
Thank you very much

**Comment by textbrowser** [comment]
It's working as intended. Search fields such as dates include special values which instruct the search engines to ignore the fields. For example, if a Publication Date of 7999-01-01 is provided, the Publication Date is not included in the query. You'll also notice some menu-like fields have values of Any. If Any is selected, the particular field may be of any value.

**Comment by 2010fares** [comment]
I've tried (tested) on more than one computer (32-bit Windows operating system) and I found:
Search Windows in BiblioteQ Version 6.65 work well
but BiblioteQ Version 6.65 No Reasult
Please help me solve this important problem
Thank you

**Comment by textbrowser** [comment]
Please paste an image of your search window. Include the exact search criteria.

**Comment by 2010fares** [comment]
[01-08-2017 06-58-40 م.zip](https://github.com/textbrowser/biblioteq/files/1191222/01-08-2017.06-58-40.zip)
This video shows the problem

**Comment by textbrowser** [comment]
Will investigate shortly.

**Comment by textbrowser** [comment]
Do you have your Language set to English? The Publication Date, Copies, Price look strange.

Here's what I tested:
1. Set my language to Arabic.
2. Restarted BQ.
3. Created a new SQLite database.
4. Created a dummy book with the WARREN title.
5. Executed the General Search using the title WARREN.
6. Item listed.

See attached image.

![bq](https://user-images.githubusercontent.com/10701156/28835822-b75330ce-76b4-11e7-89f5-2fd85201594c.png)

**Comment by 2010fares** [comment]
![01-08-2017 07-35-40](https://user-images.githubusercontent.com/7378389/28836446-9db15c8a-76f1-11e7-8ded-1300c8876c2a.jpg)

**Comment by textbrowser** [comment]
I think the special values are causing the failure. Can you test the search by providing the Publication Date and see if the query returns the WARREN item?

**Comment by 2010fares** [comment]
Yes the query with the date ٢٠٠٠/٠١/٠١   returns the WARREN item.

**Comment by textbrowser** [comment]
OK, so there is a functional workaround. I'll add check boxes to date widgets for the various searches. The prices should be OK because a negative 0.01 is language-agnostic. Copies should also be fine as they represent integer values. I don't know when the new changes will be available.

**Comment by textbrowser** [comment]
A new general-search widget for publication dates.

https://github.com/textbrowser/biblioteq/commit/fae4701ba435e91260ac0f3fa01bf00b961e4a55

**Comment by 2010fares** [comment]
It is Wonderful work.
Thanks

**Comment by 2010fares** [comment]
Important note:
When searching According to the publication date, it is preferred to have a date of publication yyyy
Thanks

**Comment by textbrowser** [comment]
All searches have been upgraded with new date check boxes.

**Comment by 2010fares** [comment]
It is Wonderful.Thanks

**Comment by textbrowser** [comment]
Last request (year only) also completed.

**Comment by textbrowser** [comment]
Changes will be available in the 2017.08.19 release.
