### ISSUE TITLE
close Report : import csv isbn10 and isbn13 empty : difference between the 1st and the following

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#222]
report : if csv import with 2 documents with isbn10 empty and isbn13 empty => only the first document is imported 

in the example
line 4  imported
only lines 5 and 6 are not imported

neither of them should be imported

[examples.csv.zip](https://github.com/textbrowser/biblioteq/files/9216345/examples.csv.zip)
thank you in advance

**Comment by textbrowser** [comment]
Clear the Substitute Value for I-10 and I-13 before the import.
ISBNs are optional.

**Comment by meteos77** [comment]
are you still up?

**Comment by textbrowser** [comment]
The robots never sleep.

**Comment by meteos77** [comment]
Clear the Substitute Value for I-10 and I-13 before the import. 
but there is no value ?

**Comment by textbrowser** [comment]
Where is the Substitute Value column? Is it in the CSV or is it in the software?

**Comment by meteos77** [comment]
the csv file contains in position 11 and position 12 : nothing
%% for the field separators in my example file

**Comment by meteos77** [comment]
BiblioteQ adds the value N/A without isbn13 for the 1st

**Comment by textbrowser** [comment]
N/A -> Substitute Value. Part of the import tool. In the software. Clear the two substitute values.

**Comment by meteos77** [comment]
sorry I didn't understand the solution

**Comment by meteos77** [comment]
explanation : as by default the csv import tool adds a substitution value for isbn10 and isbn13 , the substitution works once by putting the N/A value then at the 2nd document the N/A value being already attributed to the 1st document the tool detects a duplication on isbn

**Comment by meteos77** [comment]
suggestion: collapse the 1st column of the csv import tool
"CSV Column Number" to show a piece of the "Substitude Value" column

for me the subject is closed thanks for the explanations.

**Comment by textbrowser** [comment]
The software is precisely clear. It's the fault of the operator if they're unwilling to discover it. One could suppose that introducing alarms and colors and large fonts would produce better results. My experience is that people will focus on one thing while ignoring all the remaining evidence.

Importing data is a process which requires extra care. There is regular care, normal care, elevated care, and extra care. One should be extra careful when performing tasks that are unfamiliar, somewhat difficult, and generic.

I added new text.

**Comment by meteos77** [comment]
you are hard on the operators :-)
we don't know the software as well as its designer.

with the new text, as it says "substitute value" the user has at least the notion to look for.

thanks for this addition

**Comment by textbrowser** [comment]
There is a scrollbar also. Unfortunately scrollbars are whims of the window managers. Sometimes they're visible, sometimes they're visible if you attempt to interact with them.
