### ISSUE TITLE
Close - Report import function: import balance message.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#224]
a csv import file with 2 documents with the same isbn13 

BQ imports 2 documents but if isbn13 is duplicated, only one is imported -> normal 

except that the final message of the import tool indicates
Imported : 2. not imported : 0

example with file
[1-import-file.csv](https://github.com/textbrowser/biblioteq/files/9292260/1-import-file.csv)

**Comment by textbrowser** [comment]
If a copy is created for a duplicate, an item is considered imported.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/releases

Book imports will now create copies upon discovering duplicate ISBNs.

**Comment by textbrowser** [comment]
Something you requested.

https://github.com/textbrowser/biblioteq/issues/205

**Comment by meteos77** [comment]
it's great the creation of a copy but I didn't find how to manage the second document

- the quantity is always equal to 1
- when I look in copy by the 1st document, there is only one document

- how do I access the file with accession_number of the copy (in my example the document n° 2) ?

if I do a search on isbn13 I have only one document

thank you in advance for your help , good day

**Comment by textbrowser** [comment]
I'm wondering if you'll ever be happy with the import or will it have to change based on the phase of the Moon?

**Comment by textbrowser** [comment]
Will look.

**Comment by meteos77** [comment]
it is while using BiblioteQ that I ask myself other questions more precise than the previous ones
The import of > 5000 documents is going perfectly and I am very very very happy with it. (full moon like ... every quarter)

but when I ask for all the documents I am missing 11 documents compared to the import... so I dig and I realize that it is the duplicates in isbn13 that are not accessible.

it's not serious if no evolution of BQ on the importation, I will manage its documents otherments, their percentage being tiny.

I am only doing my job as a user by reporting what I see, it can be useful to other users.

your help is precious : you did teach me last week the "N/A" substitution value so I may have missed another option

**Comment by textbrowser** [comment]
> it's great the creation of a copy but I didn't find how to manage the second document
> 
>     * the quantity is always equal to 1
> 
>     * when I look in copy by the 1st document, there is only one document
> 
>     * how do I access the file with accession_number of the copy (in my example the document n° 2) ?
> 
> 
> if I do a search on isbn13 I have only one document
> 
> thank you in advance for your help , good day

Without reviewing the source, the first problem is your interpretation of the Accession Number. As I've written numerous times, the ISBN fields offer uniqueness. You can see this in the database definition. The Accession Number is an inconsequential field to BiblioteQ. The Import mechanism follows the database schema with respect to uniqueness. Your example CSV file believes that the Accession Number should be considered as a secondary unique field while also considering the ISBN (ISBN-13) as a primary unique field. Copies do not include Accession Number fields, parent book items do. I suspected many years ago that this would happen if I entertained an import. It would transform into an endless request where people would place logic into the names and values of fields while expecting BQ to magically interpret that logic. This is not possible.

**Comment by textbrowser** [comment]
The problem is that you do not have two copies for this sample file. :P

**Comment by textbrowser** [comment]
I understand the cause. The ID field is empty. BQ will now have to select which ISBN should be considered when creating copies. Of course, it will have to:
a) If ID is present, consider it.
b) If ID is not present, consider ISBN-13.
c) If neither are present, it cannot create a copy.
d) If both are present, consider ID.

**Comment by meteos77** [comment]
thank you for clarifying my point

**Comment by meteos77** [comment]
if the id field is filled, it's OK

additional question : can we manually modify the barcode field (id-x) in the copies to put for example the accession_number because it's this information that identifies the copy in our library 

this will not be a problem for BQ ?

**Comment by textbrowser** [comment]
I know the simplest form of finding answers is asking someone for them. You have access to the source of the database schemas. In the schemas are definitions. In the definitions, there is information concerning book copies. The definition will answer your question. One answer will inform you that you cannot. Another answer is that you cannot because the field is not defined. Another answer is that you can if the software was modified. So the true answer is: it depends. Now, you cannot. In another time, perhaps.

Perhaps I'm misbehaving, but I'm not familiar with this form of thinking. For instance, I have many questions. I don't have people to answer them. So, what do I do? Read, experiment, discover, interpret. I find this natural. Perhaps it isn't natural. Anyway, have fun.

**Comment by meteos77** [comment]
with my file > 5000 documents, the modifications of BiblioteQ have created the quantities on the duplicate documents with the isbn13 field as data source.

thank you for this evolution

**Comment by meteos77** [comment]
Of course I can look at the sources but it won't give me the answer because I have to be able to interpret them.

- for the experimentation: I clicked in copy and saw that I could modify barcode so for the user a number or another number: it is possible otherwise why BQ authorizes the modification of this field "barcode"?

In addition I have access to the developer who has the kindness to answer and explain the reason for the choices. This is a very positive attraction for me (without the exchanges with you, I would certainly have given up on BQ)

- I read English more regularly (learning a foreign language)
- I learn bash for my script for the import file
- the sql language

it's true I didn't start learning qt and c++ because I find it a bit too hard for me and it would be too time consuming.

to finish, I will never forget that you make all the software by hobby and that you share it with all of us.
Have a nice day

Translated with www.DeepL.com/Translator (free version)

**Comment by textbrowser** [comment]
You should not abandon software because it lacks interaction with developers. Some are silent because of privacy. Some are silent because it's exhausting to satisfy people. Open Source is difficult because there are many expectations of people.

**Comment by meteos77** [comment]
make a balance of the number of evolution I asked you :-)

**Comment by meteos77** [comment]
I put back my 1st message ... you have advanced well even if some features are not yet present

Hello
I need to study your software to see what features they offer,

I'm looking at software like MesLivrePro , Tellico and Gcstar and then BiblioteQ.
The comparison is interesting because some functions are great on 1 and not so good on the other and vice versa. The ideal will be a fusion of the best of 4 :-)

for example the management of the csv import is from my point of view "really difficult to understand" compared to gcstar and tellico.

For the management of users, BibloteQ is far ahead

I am ready to invest in BiblioteQ to make tests (I managed to compile it with qtcreator ... and give tracks but for our choice we are looking for a software that provides the maximum of the following:

Unimarc import (Unimarc with field 995)
Batch import .CSV
Batch record deletion (BDP return)
Batch export .CSV
User management
User Management Import .csv
User management Export to .cvs
Backup of the database simply / automatically (basic user)
Contribution management
Loans management with handheld
Returns management with handheld
Loans management with internal barcode
Returns management with internal barcode
Loans in progress report

Question: what function(s) do you expect to add by June 2022 when we choose our software.

**Comment by meteos77** [comment]
BiblioteQ has some features not listed in my initial request but I find that they represent strong points of BiblioteQ

- Z3950/SRU/OpenLibrary to retrieve records
- SQL -> magical discovery for me
- Functionality concerning the book covers : export in PNG

**Comment by textbrowser** [comment]
It's far more important for software to be present on multi-platforms. New Zelda games essentially require Nintendo hardware. The games may be fantastic, but they're only accessible to people on those platforms.

**Comment by textbrowser** [comment]
Imagine if Linux only worked on AMD. OpenBSD is one of the few systems, if not the only, which continues to support PowerPC and Sparc.

**Comment by textbrowser** [comment]
A simple house is better than a missing house.

**Comment by meteos77** [comment]
I was talking about the features of BiblioteQ

of course : Super Quality (no crash), user-friendly interface, MultiOS, OpenSource , License, Price ...

updates : via git continuously
in package distribution for 2022 : 4 or 5 releases in 8 months

and above all a developer who listens to requests and corrections
example of #224 : fixed in 24 hours (due to the time difference) otherwise a few minutes ; this is fantastic

Translated with www.DeepL.com/Translator (free version)

**Comment by textbrowser** [comment]
I understand that you're comparing features. But features are irrelevant if you cannot use the software.

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/Category:Free_library_and_information_science_software

BQ is not mentioned. Why? Not notable.

**Comment by meteos77** [comment]
[vivons heureux vivons caché](https://citations.ouest-france.fr/citation-jean-pierre-florian/vivre-heureux-vivons-cache-8517.html)

quote: let's live happily, let's live hidden

**Comment by meteos77** [comment]
[on a free software directory site in French BiblioteQ is referenced]( https://framalibre.org/content/biblioteq)

you can't find everything in wikipedia ... the proof
