### ISSUE TITLE
Close : Translation with linguist tools.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#225]
the new translated texts are not taken into account during the compilation ?

with linguist interface version 5.12.8 or 5.15.3 the presentation has been modified, now the "Sources and Forms" part is displayed

the .ts file is well modified
the .qm file has been modified (date changed

[French_biblioteq.tar.gz](https://github.com/textbrowser/biblioteq/files/9314981/French_biblioteq.tar.gz)

example of a modification line 5054 5055 .ts file or line 10559 10560
Fine -> Correct (new translation)
Fine -> Fin (old translation)

- reset local git repository on my machine with git clone
- with dooble : the translation is going well

**Comment by meteos77** [comment]
complement
I took the sources from 2022-05-30 same problem.
with the sources of 2022-03-30 everything works fin

**Comment by meteos77** [comment]
the problem concerns only the French language
if I make a modification on another language it is well taken into account.

**Comment by textbrowser** [comment]
> lupdate biblioteq.pro
> lrelease biblioteq.pro

**Comment by meteos77** [comment]
I don't understand what's going on
I changed my LinuxMint 20.3 distribution to 21 so I reinstalled everything.

I can translate another language but French is impossible :-(

**Comment by textbrowser** [comment]
You updated your distribution and put in a ticket against BiblioteQ?

**Comment by meteos77** [comment]
I can translate another language or dooble

**Comment by textbrowser** [comment]
I don't know what this means.

**Comment by meteos77** [comment]
I'll keep looking

**Comment by textbrowser** [comment]
https://doc.qt.io/qt-6/linguist-manager.html

**Comment by textbrowser** [comment]
Translation files (system and ones provided by translators) are embedded into the application.

**Comment by textbrowser** [comment]
If you modify a QM file, you need to build BiblioteQ.

**Comment by meteos77** [comment]
cat biblioteq_fr_FR.ts | grep Pauvre -> 0 result
cat biblioteq_fr_FR.ts | grep Fin -> 0 result

while BiblioteQ presents "Pauvre" as Condition of the books
while BiblioteQ presents "Fin" as Condition of the books
of course I recompile BQ
make clean ; make

it keeps the old translation without taking the new one?

**Comment by textbrowser** [comment]
A TS file is human-readable. You need to <release> it. Hence, lrelease.

**Comment by textbrowser** [comment]
Did you read Documentation/TRANSLATIONS?

**Comment by textbrowser** [comment]
Modifying the TS file will not automatically modify its QM counterpart. You cannot expect that your Linguist changes will magically appear in BQ.

**Comment by meteos77** [comment]
I know how .ts -> .qm works usually no problem
with another language at the moment it works

**Comment by textbrowser** [comment]
Did this work before you upgraded your system?

**Comment by meteos77** [comment]
I have done it dozens of times
still now it works for another language with BiblioteQ but French ... it keeps the old ones as if a cache was not updated

**Comment by textbrowser** [comment]
Are you modifying the correct file?

**Comment by meteos77** [comment]
yes good file, the date is updated

can you please make the compilation with my file in the 1st mail and see if in French the condition is Fine or Correct

that will allow to know if it is my installation which does not function

**Comment by textbrowser** [comment]
![Screenshot_20220812_124021](https://user-images.githubusercontent.com/10701156/184404689-07d334c1-781d-4a4c-8ef4-9c086f80cb06.png)

**Comment by textbrowser** [comment]
What does ```qmake --version``` report?

**Comment by meteos77** [comment]
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu

**Comment by textbrowser** [comment]
Perhaps Qt's base files are a problem.

**Comment by textbrowser** [comment]
I'm also at Qt 5.15.3.

**Comment by meteos77** [comment]
in French the condition is Fine or Correct for a new book

**Comment by textbrowser** [comment]
> make distclean
> git pull
> qmake -o Makefile biblioteq.pro
> make
> ./biblioteq.sh

**Comment by meteos77** [comment]
it's okay you're a magician

**Comment by meteos77** [comment]
what was my problem?

**Comment by textbrowser** [comment]
You?

**Comment by meteos77** [comment]
the problem encountered by me

**Comment by textbrowser** [comment]
1. The base Qt translation file was not current. If so, this did not pose a problem on my system.
2. Your compilation did not utilize the most current QM file.
3. You were not executing the current version of BiblioteQ.
4. Your generated Makefile was generated using a qmake which is not the qmake you have now. That is, your Qt changed while the Makefile referenced an older Qt.

Some possibilities.

1. If the translations are functional before you upgrade your system, inspect your system.
2. If another person is not able to reproduce your problem, inspect your system.
3. Evaluate your behavior and environment before submitting a ticket.

**Comment by textbrowser** [comment]
The second #3 is perhaps the cause of all system failures.

**Comment by meteos77** [comment]
thank you for all these explanations

the French was not in the update of May 16, 2022 
So the file qtbase_fr.qm was weird because in the package version of 2022-05-30, the content was the translation of BiblioteQ and not the qtbase.
and since this date not too much translation until now so I didn't notice it.

Thanks again for solving the problem without you I would not have found it.

**Comment by meteos77** [comment]
I think I understood my mistake

in the French translation archive [ticket French Traduction](https://github.com/textbrowser/biblioteq/issues/212#issue-1216883212)
I included a "dumpling", the file qtbase_fr.qm. It is not the real qtbase_fr.qm file of the qt distribution but a simple copy of biblioteq_fr.qm (with name change to qtbase_fr.qm).
at the time I didn't know what was the purpose of the qtbase_en.qm file and took it for a component of BiblioteQ.

Sorry for the loss of your precious time.

**Comment by textbrowser** [comment]
I don't have a facepalm emoji, but if I did, I would attach it.

**Comment by meteos77** [comment]
This is good I have in stock :-)
![oh-no-emoji](https://user-images.githubusercontent.com/56431039/184530260-ef72ccb7-577f-422d-8ca2-794f89eef0bc.gif)

good sunday

**Comment by textbrowser** [comment]
Can you please create a list of item that you'd like and create a ticket for them? Please do not include items that already exist. Be very descriptive. :)

**Comment by meteos77** [comment]
what do you mean by a list of items?

**Comment by textbrowser** [comment]
You've had many, many requests. Create a list of remaining requests and put them into a ticket.

**Comment by meteos77** [comment]
I feel like I'm making my list to Santa Claus :-) with your request to get all the tickets going

so don't forget
- for me it's a voluntary hobby, 
- for you it's probably a great passion to code.

Take my requests as ideas for the future that can give new features to BiblioteQ.
If they come true: so much the better, if it is not the case it is not a problem.

having a good time is the main thing in life

good end of day

**Comment by meteos77** [comment]
![pere-noel-emoji](https://user-images.githubusercontent.com/56431039/186235537-7f85a0b4-21ed-4e23-8014-46d4d6770610.gif)
