### ISSUE TITLE
Series management and volume number.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#227]
use of when you have to read in order to understand a story.

the marc_tags field retrieved by z3950 or sru contains the information.

in unimarc the privileged zone is the  461 $t for the title of the series and 461 $v for the volume number.

if not present in 461 go to the field 225 $a for the series title and 225 $v for the volume number.

The management can be done with 2 distinct zones
UNIMARC -> MARC21
225 -> 490
461 -> 774

![225 and 490_Unimarc_Marc21](https://user-images.githubusercontent.com/56431039/186173783-e7f420aa-36f6-483c-ab68-43b63e2c1b1b.png)
![461$v and  774$g_Unimarc-Marc21](https://user-images.githubusercontent.com/56431039/186173805-c4195049-c3f9-4acd-8dc3-a9f4a811ff74.png)

example of a base with 9 books and 2 series, one French, one English : the marc_tags field retrieved by z3950 or sru contains the information.
[multi_volume_with_different_isbn-461and490fields.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/9402975/multi_volume_with_different_isbn-461and490fields.sqlite.tar.gz)

[exemple_461_and_225fields_unimarc.tar.gz](https://github.com/textbrowser/biblioteq/files/9402983/exemple_461_and_225fields_unimarc.tar.gz)

in UNIMARC
base example with 5 books French series "Les Romains 
the field 461 $t present and 461 $v present
the field 225 $a and 225 $v are also present

in MARC21
4 books English series "The stone of light
the field 490 $a present and 490 $v present
the field 774 $t not present and 774 $g not present

**Comment by textbrowser** [comment]
225 $v, 461 $v, 490 $v completed for Z39.50. All other fields ignored.

**Comment by meteos77** [comment]
Super a new storage field.

Thanks a lot.

**Comment by meteos77** [comment]
![461-to774](https://user-images.githubusercontent.com/56431039/235983567-19cfb3d9-97ed-4ae0-8f65-00361292269a.png)

in my new database, the new field does not seem to be fed by the parser?

-can you please add the volume to the model-1 import

**Comment by meteos77** [comment]
[TEST-Volumes.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/11384953/TEST-Volumes.sqlite.tar.gz)

**Comment by meteos77** [comment]
Today, I made a demonstration to the volunteer, they found BiblioteQ very intuitive !
Bravo

**Comment by textbrowser** [comment]
An ISBN is easier for me. I don't have to download the file, decompress it, execute sqlite3, query, etc.

**Comment by textbrowser** [comment]
> ![461-to774](https://user-images.githubusercontent.com/56431039/235983567-19cfb3d9-97ed-4ae0-8f65-00361292269a.png)
> 
> in my new database, the new field does not seem to be fed by the parser?
> 
> -can you please add the volume to the model-1 import

774 was not added.

**Comment by meteos77** [comment]
I thought the opposite, so here are the isbn13 (Bnf)

9782070624560
9782070624911
9782070624904
9782070624546
9782070624553
9782075117449
9782070624522

**Comment by textbrowser** [comment]
So I'm testing a remote query and not a query on SQLite, yes?

**Comment by meteos77** [comment]
I don't understand you?

**Comment by textbrowser** [comment]
Do you have an ISBN which has any of these fields?

**Comment by textbrowser** [comment]
9782070624560 doesn't have any of the fields... So this doesn't help me in testing your request. I cannot spend time searching for an ISBN to test your request. It's beneficial that you help me, right?

**Comment by meteos77** [comment]
9782845630031 : 490 0  $a La Pierre de lumière ; $v 3
9782070624560 : 490 0  $a Harry Potter ; $v 5

**Comment by textbrowser** [comment]
9782845630031 does not exist in Sudoc and Library of France. Or I cannot query them (it).

**Comment by textbrowser** [comment]
9782070624560 returns data. :P

**Comment by meteos77** [comment]
I have documents that come from my central library which has the information but not necessarily from the sudoc or the Bnf.

they have fields filled in but by their own sources hence the problem.

**Comment by meteos77** [comment]
9782845630017 : 225 19 $a La pierre de lumière. $v 1

**Comment by textbrowser** [comment]
See SRU for 9782070624560. 225 does not exist. "v" is elsewhere.

**Comment by textbrowser** [comment]
And if you're correct, 225 is UNIMARC and not MARC21.

**Comment by meteos77** [comment]
Great, it works well for me, thank you very much for this improvement

**Comment by textbrowser** [comment]
Logic added for MARC21 on SRU and Z39.50 and UNIMARC Z39.50!

**Comment by textbrowser** [comment]
Z39.50 is optional and SRU and OpenLibrary are therefore redundancies.

**Comment by textbrowser** [comment]
Of course there are also methods for books, journals, and magazines for parsing information for provided text. For example, an administrator may provide a SRU text paragraph and BQ will parse it as if it performed the query.

**Comment by meteos77** [comment]
We have just had a donation of 115 children's books, and to integrate them I use external tools (a website to retrieve in (unimarc iso), my unimarc to BQ csv mill and I import by Import_csv functionality.
It works well. I complete some records if needed by Z3950 or SRU.

[104_Fichier-scanner_isbn13_2023-05-03_DONS-2023-2eme-partie.txt](https://github.com/textbrowser/biblioteq/files/11399144/104_Fichier-scanner_isbn13_2023-05-03_DONS-2023-2eme-partie.txt)

**Comment by meteos77** [comment]
I'm starting to make my videos

https://user-images.githubusercontent.com/56431039/236257816-0aff7d18-a25c-47c2-91c8-6b14e2629747.mp4
