### ISSUE TITLE
Mass Update

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#228]
Mass update: 
To be able to select records (with the mouse or the SQL module) and modify a field en masse.

by examples of work to do :
- I have an isbn13 list of 100 documents and I want to update the binding type to cardboard.

- after inventory I have the list of all the documents of type "Crime novel"; I want to update the fields "location" and "target_audience".

**Comment by textbrowser** [comment]
This is achieved by SQL and is not a responsibility of the application. Custom data transactions require customization which is already provided by SQL for PQ and SQLite. BQ is not responsible for such updates. I'm referring to custom SQL queries in the application. That is mostly read-only.

**Comment by textbrowser** [comment]
The UPDATE statement provides plenty of richness for updating data sets. There is nothing gained by placing custom update statements in the software. These additions would simply duplicate PostgreSQL and SQLite. I understand the benefit of applying specific UPDATE statements on selected display items. "For the selected items, apply the following statement." This is nice but essentially duplicates SQL.

**Comment by meteos77** [comment]
I'm thinking more about the usability of the application.

I don't know how to update by sql the proposal of my 1st message.

BiblioteQ users are not all SQL experts and even BQ says Even BQ specifies : This panel is intended for advanced users who have an intimate knowledge of SQL and the database layout of BiblioteQ.

**Comment by textbrowser** [comment]
This is not a fault of the application. It's an expectation of the application. There are an infinite number of SQL queries and an application cannot cover them. One purpose of BQ is to educate people in SQL. If someone is interested in their data, then they must assume that this interest requires time to learn how to survey it.

**Comment by textbrowser** [comment]
The idea that SQL is a development language is super poor. SQL and an application's usability are separate. Why replicate SQL in the application when there are official interfaces? For easing a person's learning? That's silly. Today, we will remove all mathematics from Quantum Mechanics because Quantum Mechanics is not usable because of them. We want usability!

**Comment by meteos77** [comment]
I can explain to the volunteers that they have to go to such and such a menu after selecting the documents to be modified and the software will guide them to update certain fields for example, but I cannot tell them to go and see another tool, to learn the SQL language and then you can do what you want with the database.

**Comment by textbrowser** [comment]
As I wrote, I convinced myself of the perceived benefits. A know-it-all program.

However, it makes people stupid.

**Comment by meteos77** [comment]
Is it better to master a program that makes you stupid or to know how to use 10 percent of a program that makes you smart?

**Comment by meteos77** [comment]
I think you have identified the problem.
but a little clarification, the book is in a field that does not interest you.

**Comment by textbrowser** [comment]
Do-it-yourself or do-it-for-me.

**Comment by textbrowser** [comment]
The end result is that the person learns nothing and I learn nothing. No one learns.

**Comment by meteos77** [comment]
You are not in the same frame of mind as the library volunteers.

- I agree that for you, learning is non-existent because you know it all, but you are doing the library volunteers a favor.

- The volunteer gives his time so that the population can have a local library.

Their needs are not to learn computers but to have a software that manages the library and its loans, to welcome people, to go to the bookstore to buy books, to cover the books, to classify the books, ...

it's people like you who give their time for others but in a different field.

**Comment by textbrowser** [comment]
And that's why my position is clearer. I'm looking for a future gain: learning. Not a quick gain: satisfying the volunteer.

**Comment by textbrowser** [comment]
There's a really helpful outcome when a person learns how to do something for themselves, especially with technology.

**Comment by textbrowser** [comment]
"Apply specified query to selected entries."

That's a grand plan which requires the person undertaking it to understand the query, the data, and the mechanisms to create a meaningful relationship between the two. Even a descriptive text will not be sufficient.

For example, suppose you create a query which modifies several fields for selected items which have other criteria. Like, set the binding if the ISBN is within this set and if the item has also a publication date within a range. Your query naming will require specific text to inform the person applying it. That descriptive text may be totally useless if the person does not comprehend the SQL.

**Comment by textbrowser** [comment]
SQL literacy is the best solution.

**Comment by meteos77** [comment]
I thought that sql was a plus for the program because it allowed to do things not foreseen by the graphical interface for the specialists.

now I think the opposite

The sql replaces the GUI and asks users to know the kitchen without them wanting to know it and to do things that are fairly simple from the user's perspective).

for standard use : UPDATE book SET binding_type = 'Binding' WHERE isbn13 IN ('1', '2', '3');  ?

**Comment by meteos77** [comment]
That I am interested in SQL and that I discover it thanks to BQ and its SQL is great (many thanks to you)

But don't forget that I am testing BiblioteQ for the people in my library.
(some of them don't know how to open the windows command prompt)

If they know how to use the GUI version of BQ at 60-70% of its possibilities it will be great. 
Nobody in the 9 volunteers has the technical profile so the GUI version should allow to manage a library with the maximum of possibilities.

**Comment by meteos77** [comment]
even with a GUI version of this feature (UPDATE book SET binding_type = 'Binding' WHERE isbn13 IN ('1', '2', '3'); )
could be a source of error with a wrong selection of documents

**Comment by meteos77** [comment]
Press that button to do something with the data. Since you don't understand the mechanics behind the function, trust us."

**Comment by textbrowser** [comment]
It's not a problem, it's an adventure and it exists in all disciplines.

**Comment by textbrowser** [comment]
:)

**Comment by meteos77** [comment]
Are the tags useful to you afterwards?

**Comment by textbrowser** [comment]
No. They're busy colors.

**Comment by textbrowser** [comment]
This can be solved by allowing update queries in Custom Query. It would require that MYOID values are available in the current view which they are unless another custom query was recently executed and the custom query did not include MYOID values. Not sure about complex update statements. The statements would need to be rudimentary. This is actually a simple problem as long as it doesn't require a sophisticated solution.

1. Select some items.
2. Define a custom query. Example: UPDATE book SET binding_type = 'Value'. Notice that the query does not include a WHERE clause. If a WHERE clause is included, the query would work but would ignore the selected items.
3. Save custom query.
4. Execute custom query.

**Comment by textbrowser** [comment]
Completed!
