### ISSUE TITLE
Close : Merge SQL Database improvements.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#229]
- After mouse or sql selection, you can copy records to another database.

    - After mouse or sql selection, you can move records to another database.

**Comment by textbrowser** [comment]
Can you please provide more information?

**Comment by meteos77** [comment]
Request : to be able to move or copy documents in another database after a standard selection (with the mouse) or (with SQL query)

currently the "Merge Sqlite Database" feature allows us to copy the whole source database to another database.

for the moment, 4 actions are necessary to copy the documents in another database
at the moment, 7 actions are needed to move the documents to another database

steps :
1 - The selection of documents by isbn13 by SQL queries : SELECT accession_number, alternate_id_1, author, binding_type, callnumber, category, condition, description, deweynumber, edition, id, isbn13, keyword, language, lccontrolnumber, location, marc_tags, monetary_units, multivolume_set_isbn, originality, pdate, place, price, publisher, quantity, target_audience, title, url FROM book WHERE isbn13 IN ('9782075139106','9782702182895')

2 - Export via File/Export csv
3 - Creation of a database or opening of the home database
4 - Import via Tools/Import csv
5 - Reopen the source database
6 - re-selection via SQL query
7 - delete

I think that if we manage this internally BiblioteQ, we will do this same action in 3 steps (document selection, destination base selection and copy action or move action)


of course it's an action we won't do every day so evaluate the ratio between development time and BQ improvement.
![montagne-coline](https://user-images.githubusercontent.com/56431039/188300889-83a94b9d-58e5-4394-9e60-a4bb0f811844.jpg)

**Comment by textbrowser** [comment]
That's a new project.

https://sqlitestudio.pl/

**Comment by textbrowser** [comment]
https://sqlitestudio.pl/features/

D&D between databases

You can Drag & Drop objects (tables, indexes, ...) between databases in order to copy or move them, with or without data.

**Comment by meteos77** [comment]
thank you for this discovery.
the tool is surely great but it doesn't go in the direction of simplifying the task :-)

**Comment by textbrowser** [comment]
Your request requires thousands of work hours. This other application allows you to open two databases and drag content from one into another.

**Comment by meteos77** [comment]
I managed to do the SQL SELECT with the 2 results but I can't copy them to the other empty BQ database?

**Comment by textbrowser** [comment]
Where?

> I managed to do the SQL SELECT with the 2 results but I can't copy them to the other empty BQ database?

**Comment by meteos77** [comment]
in sqlitestudio
menu : OpenSQL & Editor  (Alt+E)
SELECT accession_number, alternate_id_1, author, binding_type, callnumber, category, condition, description, deweynumber, edition, id, isbn13, keyword, language, lccontrolnumber, location, marc_tags, monetary_units, multivolume_set_isbn, originality, pdate, place, price, publisher, quantity, target_audience, title, url FROM book WHERE isbn13 IN ('9782075139106','9782702182895')

-> it gives me the 2 results like BQ

**Comment by textbrowser** [comment]
I don't use the Studio. :P

**Comment by textbrowser** [comment]
OK. Let me see.

**Comment by textbrowser** [comment]
Creating a video.

**Comment by textbrowser** [comment]
First, lunch.

**Comment by meteos77** [comment]
a good idea to improve the SQL queries part of BQ would be like sqlitestudio to put in bold the SQL keywords and in green the user data.
the query is more readable and if the keyword is not good, as it is not in bold it means that the user made a mistake

**Comment by meteos77** [comment]
Enjoy lunch!

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/discussions/233

**Comment by textbrowser** [comment]
> a good idea to improve the SQL queries part of BQ would be like sqlitestudio to put in bold the SQL keywords and in green the user data. the query is more readable and if the keyword is not good, as it is not in bold it means that the user made a mistake

https://github.com/textbrowser/biblioteq/commit/0adf5c631bb44c59c87840701131455c76318397

**Comment by meteos77** [comment]
Thank you but I did not succeed despite your video, it does not want to copy and paste.
I still prefer to go through the csv export and import from BQ it's more convenient.

**Comment by textbrowser** [comment]
To select multiple rows, hold the usual Control key while pressing the desired row number. Then create the rows in the other database. Click the left-most column in the top-most row, right-click for the context menu, and paste.

**Comment by textbrowser** [comment]
SQLiteStudio has export and import.

**Comment by meteos77** [comment]
I prefer the quality 6 ****** of BQ (thanks to csv import/export and SQL)

here you have to create the lines first ?
if i want to paste 10 rows, it should paste 10 rows and not ask create 10 rows then paste the 10 rows?
I don't understand the point of this step

**Comment by meteos77** [comment]
I don't want to replace the 7 steps in BQ by 8 steps in SqliteStudio.

1 - Open another software
2 - Connect the source database
3 - Connect the destination database
4 - Perform the same SQL query as in BQ
5 - copy the result
6 - Create the rows
7 - Copy the rows
8 - Delete rows in source database

**Comment by textbrowser** [comment]
Studio is better because copying and pasting is part of its core.

**Comment by meteos77** [comment]
I agree that it is more specialized in this task but for the user,  BQ with export/import, does it achieve the same result?

**Comment by textbrowser** [comment]
No. Export in BQ is of what you see.

**Comment by meteos77** [comment]
what you see, is not what is in the database?

**Comment by textbrowser** [comment]
Export Table View. Not Export Database...

**Comment by textbrowser** [comment]
Both PostgreSQL and SQLite offer dump utilities. I will not reproduce them in BQ.

**Comment by meteos77** [comment]
it's interesting but, what information I lose when I do a csv export (table view) and a database dump.

**Comment by textbrowser** [comment]
Files, child tables, etc.
