### ISSUE TITLE
Create a database backup

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#23]
Greetings

When librarians tested BiblioteQ:
 An error often occurs when WE create a new database, the old one is replaced by the new one by mistake.
So Having New SQLite Database button in main window causes errors
Can You add a button for create a database backup?
Or
Can You make an option that (Hides or shows) or (active or non-active) the New SQLite Database button.

Thank you so much

**Comment by textbrowser** [comment]
BQ displays a confirmation dialog if an existing SQLite file is about to be recreated. Someone else requested a backup process. I'm not sure how one would work.

**Comment by 2010fares** [comment]
Thank you for your patience
I would like to ask about the password window and permissions, could work with local_db sqlite.
Because Userid field is empty and not active when I open "BiblioteQ & Password Selection Window"
And When I entered New Password and Confirm Password Nothing happened.
I reiterate my thanks to you for your patience

**Comment by textbrowser** [comment]
You're right! That's a flaw. The credentials dialog should only appear when a person is connected to a PQ database. Will correct it.

**Comment by textbrowser** [comment]
Corrected. The password dialog is now only accessible with PostgreSQL databases.

**Comment by textbrowser** [comment]
Resolved. The backup request exists in another open ticket. We'll see what can be done.
