### ISSUE TITLE
Creation of statistical features.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#230]
I have redone a part of the table that we have to fill in every year
I think that BiblioteQ should be able to help us to fill it in 0,0001 second :-)

I started to use python and pyqt5 language, that allows me to use qtcreator
I have not yet succeeded in creating the i18n to present it to you in English. but this gives you an idea of presentation.

there are 2 parts of the table

the first one is about Collections (letter D) because we only have printed books)
if I analyze "D1 - Printed books" : some fields need information that we can't store in the BiblioteQ database yet

the target_audience field : allows to make the difference between adults and young people

- no fields yet for the origin of the documents (Purchases, Loans, Donations)
- no field yet for the date of entry/exit in the library
- no way yet to delete an item from the library

the 2nd part concerns the uses and the users (letter E)

I think that the database will allow to fill the part E1 - Users
concerning the part E2 (it asks the separation of the documents in own funds and the documents lent by the central library)
so same request as for D1

[UI-statistical.tar.gz](https://github.com/textbrowser/biblioteq/files/9409457/UI-statistical.tar.gz)

**Comment by meteos77** [comment]
to manage the statistics (anonymization, I think it would be necessary to create additional fields.

- text fields "document origin" (Purchases; Donations; Loans)
- date fields: (Date_Arrival ; Date_Departure)

- Adding in the field "Condition" of the value: "reformed".

I will try to work on this part that I haven't explored too much for the moment

**Comment by meteos77** [comment]
sorry it's in python language, but it's for the example

[Statistique-Dxx-Python.tar.gz](https://github.com/textbrowser/biblioteq/files/9416523/Statistique-Dxx-Python.tar.gz)

**Comment by meteos77** [comment]
For the annual statistics I would like to know the origin of the document with 5 possibilities

- Purchase
- Donation
- Permanent loan
- Temporary loan
- Reformatted

Can you add these values in the Originality field.

For us, the Originality field is useless because we only have originals and no copies (black or color).

**Comment by textbrowser** [comment]
A reminder is listed in the TO-DO and briefly summarizes this request. Statistics information is very custom. Have you looked at an SQLite Web interface? For BQ, it would be a huge mini-project because it's (a) custom and (b) large in scope and (c) requires graphs and (d) would include special queries and (e) would prefer export and (f) probably integration of dynamic queries.

**Comment by meteos77** [comment]
even if BiblioteQ doesn't offer statistics (because it's too personal), I will develop my own statistics (with python and the sqlite module) as indicated in the previous message but I need to be able to put the information in the BiblioteQ fields to be able to use them in my statistics program.

**Comment by textbrowser** [comment]
> even if BiblioteQ doesn't offer statistics (because it's too personal), I will develop my own statistics (with python and the sqlite module) as indicated in the previous message but I need to be able to put the information in the BiblioteQ fields to be able to use them in my statistics program.

That's precisely my argument. SQL is perfect for gathering information on a set of data. The application is not the place in my opinion.

**Comment by meteos77** [comment]
I understood that my statistics were particular so I would work on them in python in my corner.
I would certainly need your help on some complicated SQL queries.

The statistics are for the past year so I really have time to do this.

on the other hand, I think I'm missing some fields to store information to create statistics when importing the old database.

for example : 
the documents are they in own funds or the documents come from a loan of the central library or a donation.
1 - a new field : origin of the document (Library, Central Library, Private donation, Brocante)

the date of arrival: it asks us how many were bought in the year.
2 - a new field: date of arrival

how many have been removed from the library during the year.
3- a new field: date of disposal

With these 3 new fields, I think that I answer all the questionnaire concerning the documents. with the crossing of target_audience
