### ISSUE TITLE
French translation for 2022-09-15 version.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#231]
thank you in advance for the integration of French in the future version.

[2022-09-11_Translation_fr_FR.tar.gz](https://github.com/textbrowser/biblioteq/files/9542717/2022-09-11_Translation_fr_FR.tar.gz)

**Comment by textbrowser** [comment]
Please update your translations.

**Comment by meteos77** [comment]
update made in the 1st message

**Comment by textbrowser** [comment]
Does that include the most recent text? Like, from 2 days ago?

https://github.com/textbrowser/biblioteq/commits/master/Source

**Comment by meteos77** [comment]
redid the entire translation process
lupdate biblioteq.pro
linguist /Translations/biblioteq_en_FR.ts

**Comment by textbrowser** [comment]
Uploaded. Good job.

**Comment by meteos77** [comment]
the most beautiful work, it is you who do it :-)

**Comment by textbrowser** [comment]
Maybe.
