### ISSUE TITLE
No "Alternate Identifier" in "Select Viewable Columns" in coresponding view(s).

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#232]

**Comment by textbrowser** [comment]
Completed. :)

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/1833cdfa2bc117dd75e30243834d53e3ad23c488
https://github.com/textbrowser/biblioteq/commit/6fe21bdcd0991156aebfa5b5cebe53ee2dc873b7
