### ISSUE TITLE
The book search function has a problem.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#234]
description : if we search by "table search", it finds and we can open the book file in details.
"on the other hand"
if we search with the 'magnifying glass icon' function, the search is successful but we can't go into the details of the book (message: Unable to determine the selected item's type

after the search in the table, there is "book" in the Alternative identifier field

**Comment by textbrowser** [comment]
Done. New column. :)

**Comment by meteos77** [comment]
thank you for the correction
