### ISSUE TITLE
Strange behavior after a selection via SQL.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#236]
After an SQL selection (via the star) :  SELECT accession_number, title, author, myoid, type FROM book

Editing a field : for example the url field

At the time of registration, BiblioteQ tells me:
"You have increased the number of copies. Would you like to modify the information about the copies ?

This only happens after the selection by SQL

If I edit the document via the view menu : no problem

**Comment by textbrowser** [comment]
Star = Custom Database Query.

**Comment by textbrowser** [comment]
Done. :) See recent commit.

**Comment by meteos77** [comment]
thank you very much, always so fast :-)

if I understood your explanation correctly, I should have added the quantity field in the SQL query
SELECT accession_number, title, author, quantity, myoid, type FROM book , and I would not have had any problem ?

**Comment by textbrowser** [comment]
Right. The original BQ was kind enough in that it reminded you of the new quantity and would adjust the copies if needed.

**Comment by meteos77** [comment]
The new one is even nicer :-)
