### ISSUE TITLE
Crash on Mac OS 10.13.6 due to missing symbol ____chkstk_darwin

### ISSUE THREAD

**Issue by daviewales** [textbrowser/biblioteq#244]
I'm trying to launch BiblioteQ on Mac OS 10.13.6.
However, it crashes with the following error due to a missing ____chkstk_darwin symbol:

```
Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/BiblioteQ.app/Contents/MacOS/../Frameworks/libpcre2-16.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

This symbol was introduced with Mac OS 10.15.

**Comment by textbrowser** [comment]
Thanks for the report. I cannot do anything about it because I don't have 10.13. I can guide you in building BiblioteQ.

The minimum MacOS build target is 10.13 in my build process, however, that is not guaranteed.

**Comment by textbrowser** [comment]
Hello? I can see you're active! If you are not interested in resolving this or whatever, close the ticket!

Thanks again but follow through. :)

**Comment by daviewales** [comment]
Thanks for the offer of support. Unfortunately I don't have time to take you up on it at the moment, so I'll close the issue.

**Comment by textbrowser** [comment]
Good luck!
