### ISSUE TITLE
Z39.50 site (server) for Arabic Records

### ISSUE THREAD

**Issue by 2010fares** [textbrowser/biblioteq#25]
Hello
1-
Can you add "ARABIC UNION CATALOG" as a custom Z39.50 site (server). (Its important for Arabic Records)
ARABIC UNION CATALOG web site is:
http://www.aruc.org/en/web/auc/home

2-
 Here is Attachment of Updated translation file (biblioteq_ar_JO 10-8-2017)
[biblioteq_ar_JO 10-8-2017.zip](https://github.com/textbrowser/biblioteq/files/1217226/biblioteq_ar_JO.10-8-2017.zip)

Thank you so much

**Comment by textbrowser** [comment]
Sure. It'll take me a bit to discover the server information.

**Comment by textbrowser** [comment]
OK, I'll need you to locate the server's details:
hostname
port
database name
format
record syntax

**Comment by textbrowser** [comment]
TS file committed. Thanks!

**Comment by 2010fares** [comment]
Hello
I have contacted the Jordan Library and Information Association to send an e-mail to the "ARABIC UNION CATALOG" regarding the information you have requested.
No response has been received so far
Thank you so much

**Comment by textbrowser** [comment]
I also looked throughout the site. Also checked other sites. Was not able to find Z39.50 information.

**Comment by 2010fares** [comment]
Greetings
Note1: When I change to Arabic language, the system interfaces are not shown right to left (RTL).
The previous version of the system interfaces were from right to left (rtl) when we change the language into Arabic
Note2: Thank to My friend Rabie Abdi from Morocco, Because he gave me the:
National Library of Morocco server's details:
hostname:        National Library of Morocco
Use:             CATALOG
port:            1111
database name:   DEFAULT
URL:             opac.bnrm.ma 
format:          UNIMARC
Password:        bnrm2015
Note3: I have attached the translation file of Arabic-Translation-8-7-2018-biblioteq_ar_JO
[Arabic-Translation-7-2018-biblioteq_ar_JO.zip](https://github.com/textbrowser/biblioteq/files/2173428/Arabic-Translation-7-2018-biblioteq_ar_JO.zip)
.......................................
Thank you very much

**Comment by textbrowser** [comment]
Tested the new site using the ISBN 9789981257122. Thanks!

**Comment by textbrowser** [comment]
Site now defined in biblioteq.conf.
https://github.com/textbrowser/biblioteq/commit/bf6457a39253876e417e4f5dbef972cfc2d86759

**Comment by textbrowser** [comment]
And translation files are now current. Will look at the orientation problem as soon as possible.

**Comment by textbrowser** [comment]
Language settings were not changed since May 5, 2017. Can you please post some images depicting the problem areas?

**Comment by 2010fares** [comment]
When I replace the file qt_ar.qm with the same file from last version, the
RTL works well.

2018-07-23 12:42 GMT+03:00 textbrowser <notifications@github.com>:

**Comment by textbrowser** [comment]
OK. I'll include the translation files from Qt 5.9.6 on Windows in the next release.

**Comment by textbrowser** [comment]
Closing!
