### ISSUE TITLE
Crashes at launch (missing libpq.5.dylib).

### ISSUE THREAD

**Issue by macbugs** [textbrowser/biblioteq#251]
Mac OS 13.0.1

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/lib/libpq.5.dylib
Referenced from: <EC688CAA-DFEE-302E-A018-A095A5406DB9> /private/var/folders/*/BiblioteQ.app/Contents/MacOS/BiblioteQ
Reason: tried: '/usr/lib/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file, not in dyld cache), '/usr/local/lib/libpq.5.dylib' (no such file)
(terminated at launch; ignore backtrace)
```

**Comment by textbrowser** [comment]
Perhaps there is a missing or incompatible dependency.

**Comment by textbrowser** [comment]
My Homebrew doesn't have Qt's PQ driver. I will see if I can install it. The machine is super slow and old. Macs are expensive and the best solution is for you to build it from source.

**Comment by textbrowser** [comment]
BQ launches on my Mac however. I'm at 10.15.

**Comment by macbugs** [comment]
> **_Macs are expensive and the best solution is for you to build it from source._**

I understand.  Its always a love/hate relationship with Apple.  Bought a new one because 12-year old Mac had a logic board failure and new Intel PC kit that I wanted was temporarily unavailable due to supply-chain issues.  Have to admit, the [hardware ML support](https://developer.apple.com/machine-learning/api/) is impressive: it enables local deployment of some larger AI models which typically run in the cloud (where you are billed for resource usage.)  And power consumption is so low, the machine will probably pay for itself in energy savings.  But I am now cursing the soldered-down SSD / RAM, and had to move Xcode to an external volume, due to a lack of free space.  So there are always pros & cons.  (Still have a G4 with 10.5.8, BTW.)

I really just installed this app out of curiosity, because I was so impressed with the specs (and cross-platform support) of Spot-On, but it crashed at launch and I just realized it has the same issue with that missing library.  Truth be told, its _Spot-On_ that I would like to see supported the most: I see similar projects in the same category that are less feature-rich, despite more developers (and in some cases, sponsorship).

**Comment by textbrowser** [comment]
You're interested in Spot-On?

**Comment by textbrowser** [comment]
Does Spot-On crash?

**Comment by textbrowser** [comment]
HB deprecated my system as it's not supported by Apple.

**Comment by textbrowser** [comment]
Deprecated in 3 days.
https://en.wikipedia.org/wiki/MacOS_Catalina

**Comment by textbrowser** [comment]
I can build SO without PQ for the Mac as macdeployqt doesn't capture all of the dependencies.

**Comment by textbrowser** [comment]
I'll put a DMG here when it's ready and you can test it.

**Comment by textbrowser** [comment]
Debian has a G4 release. Gentoo and OpenBSD are the remaining systems which support PowerPC.

**Comment by textbrowser** [comment]
Building now.

**Comment by textbrowser** [comment]
It's too big.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/spot-on/releases/tag/2022.12.10

**Comment by macbugs** [comment]
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib
Referenced from: <FA130736-4E1F-3071-85CE-160BB35DA884> /Volumes/VOLUME/*/Spot-On.app/Contents/Frameworks/libssl.1.1.dylib
Reason: tried: '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```
I see `libcrypto.1.1.dylib` in the application bundle, but its looking in homebrew cellar?

(btw, the actual path on my platform is `/opt/homebrew/Cellar/openssl@1.1/1.1.1q/lib/libcrypto.1.1.dylib` (not `/usr/local/Cellar/`)

**Comment by textbrowser** [comment]
Will look later. Thanks.

**Comment by textbrowser** [comment]
I have /usr/local/opt and opt is not a symbolic link. I also have /usr/local/Cellar. Entries in opt are symbolic links to entries in Cellar.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/releases/tag/2022.12.25

Free of Poppler, PostgreSQL, YAZ. Just Qt.

**Comment by macbugs** [comment]
![Screenshot 2022-11-28 at 11 22 34](https://user-images.githubusercontent.com/101867641/204328842-32fa2af3-85b0-4bf8-a2d9-5e77378b1faa.png)
works in Rosetta, now to build for aarch64

**Comment by textbrowser** [comment]
What's Rosetta?

**Comment by textbrowser** [comment]
Neat.

**Comment by textbrowser** [comment]
Littering specific version information in the project file is annoying.

**Comment by macbugs** [comment]
> _**Deprecated in 3 days.**_

- [OpenCore Legacy Patcher delivers unofficial Ventura support for older Macs](https://arstechnica.com/gadgets/2022/10/opencore-legacy-patcher-delivers-unofficial-ventura-support-for-older-macs/
)
- [Disable junk services in Ventura](https://gist.github.com/b0gdanw/c99e5b2eefad19932554a713384dcc70)
___
> **_Neat._**

Some other neat things...

- [Flutter vs Qt](https://www.tqcs.io/flutterqt.html)

https://flutter.dev/
https://flutter.dev/multi-platform/desktop
https://flutter.gskinner.com/folio/
https://docs.flutter.dev/get-started/install/macos
___

- [A Short introduction to Fuchsia](https://medium.com/@allansrc/a-short-introduction-to-fuchsia-fuchsiaos-8a3b5de2dbe0)
- _["resolving dependencies at runtime instead of at install time"](https://blog.codemagic.io/fuchsia-os-preview/)_
- [Unix technical legacy in Fuchsia](https://pnote.eu/notes/fuchsia-unix-legacy/)

https://dahliaos.io/
([4 GB RAM / 64-bit quad-core CPU with Intel HD graphics](https://docs.dahliaos.io/live-boot/x86_64#recommended-requirements))

**Comment by textbrowser** [comment]
> ```
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> 
> Termination Reason:    Namespace DYLD, Code 1 Library missing
> Library not loaded: /usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib
> Referenced from: <FA130736-4E1F-3071-85CE-160BB35DA884> /Volumes/VOLUME/*/Spot-On.app/Contents/Frameworks/libssl.1.1.dylib
> Reason: tried: '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file, not in dyld cache)
> (terminated at launch; ignore backtrace)
> ```
> 
> I see `libcrypto.1.1.dylib` in the application bundle, but its looking in homebrew cellar?
> 
> (btw, the actual path on my platform is `/opt/homebrew/Cellar/openssl@1.1/1.1.1q/lib/libcrypto.1.1.dylib` (not `/usr/local/Cellar/`)

https://github.com/textbrowser/spot-on/releases/edit/2022.12.10

Uploading now. I removed /usr/local/Cellar (/usr/local/opt includes symbolic links to Cellar) before launching SO on my Mac. Both the interface and kernel launched successfully. Please test.

**Comment by macbugs** [comment]
hmm, looks like a test platform -- not quite the replacement for Signal / Telegram / Retroshare / Onionshare that I expected... but yes, it works.

**Comment by textbrowser** [comment]
Spot-On is not a test platform.

I use it for GPG and downloading RSS links and content. Years ago, I communicated via e-mail in near real-time in a restricted environment.

If you'd like revisions, leave notes and perhaps they'll be considered.

Thanks you!

**Comment by textbrowser** [comment]
SO builds natively on Sparc64, PowerPC, and ARM. Old hardware? Small devices?

**Comment by textbrowser** [comment]
> > _**Deprecated in 3 days.**_
> 
>     * [OpenCore Legacy Patcher delivers unofficial Ventura support for older Macs](https://arstechnica.com/gadgets/2022/10/opencore-legacy-patcher-delivers-unofficial-ventura-support-for-older-macs/)
> 
>     * [Disable junk services in Ventura](https://gist.github.com/b0gdanw/c99e5b2eefad19932554a713384dcc70)
> 
> 
> > **_Neat._**
> 
> Some other neat things...
> 
>     * [Flutter vs Qt](https://www.tqcs.io/flutterqt.html)
> 
> 
> https://flutter.dev/ https://flutter.dev/multi-platform/desktop https://flutter.gskinner.com/folio/ https://docs.flutter.dev/get-started/install/macos
> 
>     * [A Short introduction to Fuchsia](https://medium.com/@allansrc/a-short-introduction-to-fuchsia-fuchsiaos-8a3b5de2dbe0)
> 
>     * _["resolving dependencies at runtime instead of at install time"](https://blog.codemagic.io/fuchsia-os-preview/)_
> 
>     * [Unix technical legacy in Fuchsia](https://pnote.eu/notes/fuchsia-unix-legacy/)
> 
> 
> https://dahliaos.io/ ([4 GB RAM / 64-bit quad-core CPU with Intel HD graphics](https://docs.dahliaos.io/live-boot/x86_64#recommended-requirements))

https://en.wikipedia.org/wiki/Fuchsia_(operating_system)

"It is heavily inspired by [Unix](https://en.wikipedia.org/wiki/Unix) kernels but differs greatly. For example, it does not support [Unix-like](https://en.wikipedia.org/wiki/Unix-like) signals but incorporates [event-driven programming](https://en.wikipedia.org/wiki/Event-driven_programming) and the [observer pattern](https://en.wikipedia.org/wiki/Observer_pattern). Most system calls do not block the main thread. Resources are represented as [objects](https://en.wikipedia.org/wiki/Object_(computer_science)) rather than files, unlike traditional Unix systems."

Interesting indeed.

**Comment by textbrowser** [comment]
There are components in Spot-On (both the interface and the kernel) which observe events and react accordingly. I prefer this model.

**Comment by macbugs** [comment]
> _**If you'd like revisions, leave notes and perhaps they'll be considered.**_

...just some opinions about user interface design ; will continue in 'Discussions' area

> **_SO builds natively on Sparc64, PowerPC, and ARM. Old hardware? Small devices?_**

Oh absolutely, I agree that stuff is quite useful -- an old laptop or Raspberry Pi would make a nice dedicated communications console.  Any working display will be pressed into service here... 😁

**Comment by textbrowser** [comment]
A Spot-On-Kernel process does not require an interface so you can launch it (after configuration) on a remote machine.
