### ISSUE TITLE
Additional fields for document management.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#256]
to manage the documents properly, we would need 3 additional fields:
- purchase date (date type fields)
- date of reform (exit) (date type fields)
- origin of the documents (text - if possible enumeration database)

thank you in advance

**Comment by textbrowser** [comment]
Do you need editable Condition and Originality for books? That's my interpretation of the discussion.

**Comment by meteos77** [comment]
BQ has an originality field that is blocked with 2 copies W/B and colors and origin

as a library we only have originals. so if the "originality" field became more open to modification, I could use it to store "provenance".

Concerning the condition field, it is also blocked with your typical values.
if it became more open, it would correspond more to our criteria.
Hence my request to have rich fields (with enumeration database) that let the user define his own typical values.

**Comment by meteos77** [comment]
I like in biblioteQ the relation between the database enumeration and the pop-up
it makes filling and searching easier because the values are free and at the same time directed enough to have the most homogeneous database possible.

**Comment by textbrowser** [comment]
Will add new condition and originality enumerations. The interface fields will remain as they are.

**Comment by textbrowser** [comment]
Target Audience is an exception as it's editable.

**Comment by meteos77** [comment]
![database-enumeration](https://user-images.githubusercontent.com/56431039/205098564-cf436b6e-8980-4054-9506-2018e0cf7156.png)

**Comment by meteos77** [comment]
I don't use the editing feature because it prevents me from using the search function after

**Comment by textbrowser** [comment]
What do you mean?

**Comment by textbrowser** [comment]
![Screenshot_20221201_110910](https://user-images.githubusercontent.com/10701156/205102528-67feffbf-0c43-410e-975b-c8f20ead1c47.png)
![Screenshot_20221201_111011](https://user-images.githubusercontent.com/10701156/205102712-0776286d-5e09-4317-8fe4-d08329a1ce73.png)

**Comment by textbrowser** [comment]
It works.

**Comment by meteos77** [comment]
the direct modification in the field is a freedom I don't use for target_audience.
In fact it is this feature that I would have liked to have for custom queries :-)

**Comment by textbrowser** [comment]
I knew you were going to say this!

**Comment by textbrowser** [comment]
So. The editable Target Audience field implies that your new value is only applicable to that particular item and should not be part of the enumerations table. This is a natural and clear understanding because you're applying an exceptional value. The belief that all values should not be available in the combination box for a search function is... exceptional. BQ would have to detect all distinct values from all books and populate the widget while also retrieving the enumerated values.

**Comment by textbrowser** [comment]
The editable field implies that your particular value is specific to that book. If it is not, enumeration! If you're interested in the unique values in future searches, custom query will aid.

**Comment by textbrowser** [comment]
I didn't want an editable field and if I did, I was a moron. It's not a suitable property because an enumeration exists. It added complexity and confuses you.

**Comment by meteos77** [comment]
in any case, I prefer the easy search with popup 
near-configured by enumeration database than to make SQL queries to see where the execeptions would be hidden
the library people want simple actions

**Comment by meteos77** [comment]
> Target Audience is an exception as it's editable.

I think I finally understood your phrase :-)

tell me if it is good : the field is not managed in a table of the database but in another way while all the others are.

**Comment by textbrowser** [comment]
> in any case, I prefer the easy search with popup near-configured by enumeration database than to make SQL queries to see where the execeptions would be hidden the library people want simple actions

Libraries catalog human culture. The expectation that the software and science which aids in that act should be simple is absurd.

**Comment by textbrowser** [comment]
I want to go to the Moon and I want a simple and safe solution. Simple before safe.

**Comment by meteos77** [comment]
Library managers are not computer people but rather literary people.
You can drive an everyday car without wanting to drive a Formula 1 car.

BiblioteQ is successful with its GUI that makes it easy to use and the pros can use SQL to do more.

**Comment by textbrowser** [comment]
If you want richness, you're going to have options. But you see, you asked for an editable target audience and are confused of the results because you didn't understand your original request. Perhaps you understood it and expected that the software should perform an additional query.

So here's the thing. If you have 10,000 target audiences, there's an expectation that those will be shown somewhere. So here's the other thing. If you have hidden audiences, that expectation that they'll be gathered and shown is not a natural expectation. Like if I'm going to look for a specific book or a set, I don't expect a weird field that I'm not using to be populated with items that are hidden.

**Comment by textbrowser** [comment]
Having 10,000 audiences or any other burdensome enumeration is also moronic. Your database should not house values that will burden the processes of searching for values. Retrieving and populating 10,000 items is not wise. There's a reason, for example, there are categories within categories instead of a single category housing a union of sub-categories. Enumerations need to be mindful of practical purpose. If they're not, they're nuisances.

**Comment by textbrowser** [comment]
Imagine a book's index that has the indefinite article an as an entry. You'd go insane.

**Comment by meteos77** [comment]
the librarian has to answer quickly to 
can you tell me if you have a children's book about this subject.

or do you have other books by such authors because I enjoyed this one.

**Comment by textbrowser** [comment]
You can do both in BQ. BQ has embedded hyperlinks yo! Hyyyypeeeeeerrrrrrrrlinks. It's wild.

**Comment by meteos77** [comment]
we already talked about hyperlinks but I never managed to make one.

**Comment by textbrowser** [comment]
Hyppppppppppperlinks. You can visit another galactic galaxy.

**Comment by meteos77** [comment]
anyway BQ is magic, if I look for a title with an article  the or a
 it takes only 1 second to find 520 documents

**Comment by meteos77** [comment]
Is hyperlinks reserved for PostgreSQL users?

**Comment by textbrowser** [comment]
PostgreSQL has a non-editable view mode while SQLite does not. I don't know if it's possible to implement editable hyperlinks. I think it is but would require fields detect immediate revisions.

**Comment by textbrowser** [comment]
Maybe not immediate. Maybe after the Return key is pressed.

**Comment by textbrowser** [comment]
Both are unique and necessary. PQ sounds nicer than SQ.

**Comment by meteos77** [comment]
I knew that PostgreSQL had additional possibilities, you pointed this out to me at the beginning.

We don't have the possibility to manage this possibility.

I will test for my pleasure BQ/PostgreSQL as soon as I have a moment to know the differences between the 2.

**Comment by textbrowser** [comment]
Oh yes you do! Locally right there on the laptop or desktop computer. It'll listen on 127.0.0.1:5432. Or, like previously discussed, on a Pi connected directly with the laptop / desktop and powered by USB. Super. Complete. Happy.

**Comment by meteos77** [comment]
who manages it in case of problems?

**Comment by meteos77** [comment]
it is not a material problem with the PI but a human resource problem
we are volunteers, 1 person per shift,
9/10 who know almost nothing about computers

the following request is already difficult: create a text file on the desktop and scan the isbn13.

you see the difficulty.

**Comment by textbrowser** [comment]
> who manages it in case of problems?

The database? People do. Or, purchase PostgreSQL support.

**Comment by textbrowser** [comment]
https://www.pgadmin.org/

**Comment by textbrowser** [comment]
Will not be addressed this year. Perhaps mid 2023. Too many requests.

**Comment by textbrowser** [comment]
Start of 2023, maybe. Yah, too many requests. Remember, hobby.

**Comment by meteos77** [comment]
My requests are related to the discovery through the use of BiblioteQ as the SQL.

It will take as long as it takes you and your desire.
I never forget that this is one of your many hobbies.

THANK YOU FOR ALL that you have already done

**Comment by textbrowser** [comment]
Please test the new condition and originality enumerators.

**Comment by meteos77** [comment]
Great thanks a lot
according to my tests it works well

can you add the option automatic creation of values in enumeration database for the field: originality (like for location).
If it doesn't take too much time of course
thanks in advance

**Comment by textbrowser** [comment]
Location is a pair. Condition and originality are singletons of books.

**Comment by textbrowser** [comment]
I'm not adding default values because of translations and because that's the entire purpose I spent time to do this change.

**Comment by meteos77** [comment]
ok, I think I understood the difference between location and the rest which is specific to a category

this will make me an SQL exercise : to find the non present in the enumerations :-)

**Comment by textbrowser** [comment]
You're going to ask for import changes too.

**Comment by meteos77** [comment]
no because little value, once entered in the general database we do not touch anything more

**Comment by textbrowser** [comment]
What if you have 100 different unique conditions in your CSV?

**Comment by meteos77** [comment]
I don't think I have 100 conditions
I could have maybe 100 origins
because
- 12 deliveries per year from the central library
- 2-5 donations per year
- 1 bookstore purchase

so over several years, we will get this unless we have the date_arrival field
it will give
the 12 will be noted: BDP (central library)
the 2-5 will be noted DONS
the purchases LIBRARY 
and the date will be put in its own field
otherwise
BDP-2023-01
BDP-2023-02
BDP-2023-..
BDP-2023-12
...
DONS-2024-02
DONS-2023-07
DONS-2023-11
LIBRARY-2023
LIBRARY-2024
...

**Comment by textbrowser** [comment]
Happy typing.

**Comment by meteos77** [comment]
I don't know if it's being created but for info: We don't have access in Custom Query to the new tables book_conditions ; book_originality and target_audience

**Comment by textbrowser** [comment]
Perhaps it's possible to query the schema for all tables instead of requiring a software revision.

**Comment by meteos77** [comment]
it would change a lot for you?
do the best with the least effort :-)

**Comment by meteos77** [comment]
For me it is the end: Have a nice day

**Comment by textbrowser** [comment]
You too.

**Comment by meteos77** [comment]
I start the translation is what : Woody tree widgets ?
![woody](https://user-images.githubusercontent.com/56431039/205952302-1cd74006-9be5-4a96-8ddc-11aa241017ff.jpg)

**Comment by textbrowser** [comment]
Woody is growth and collapse. Plus and minus.

https://github.com/textbrowser/woody

**Comment by meteos77** [comment]
> What if you have 100 different unique conditions in your CSV?

SELECT COUNT(*) AS "book originality" FROM book_originality ;

result for the moment, I'm going to do some cleaning :  405

**Comment by meteos77** [comment]
> Hyppppppppppperlinks. You can visit another galactic galaxy.

I saw it working on my compilation this morning on Raspberry
 but
On my LinuxMint impossible to have the links working :-(

**Comment by textbrowser** [comment]
Links can only be clicked on read-only fields. Read the attached tool tip. Press and hold the Alt key and then activate the link. Clearly links are only created after a value is saved.

**Comment by meteos77** [comment]
It works very well on Raspberry

but I can't get the same result with LinuxMint and Windows10.

- the 3 versions have been compiled this morning
- I take the same base for the 3 machines :  [TEST-HYPERLINK.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/10175830/TEST-HYPERLINK.sqlite.tar.gz)
- The links are well underlined in blue
- The icon of the cursor is transformed well after pressing the alt key

Is there a particular software dependency for this feature?

**Comment by meteos77** [comment]
solution under linux (control + alt) = alt (raspberry)

**Comment by textbrowser** [comment]
Added test for AltModifier. Perhaps it'll help. If not, it's your locale, keyboard, computer, operating system, CPU, French, county, ISP, bulbs, wires.

**Comment by meteos77** [comment]
it must come from the locale / keymap; I'll see if I can do better.

It works great, it's a very nice feature BRAVO

**Comment by meteos77** [comment]
small remarks
some signs prevent the search from being done correctly and return an empty result
depending on the system, it is not the same

on Linux
Author with  '  :  (  ex: Amboise Valéry D'  ) or  Publisher : ' :   (ex :  J'AI LU  )

on Windows
Author with -  ( ex : Appleman-Jurman Alicia  )
Publisher with  /    (ex :  10/18  )

**Comment by meteos77** [comment]
NO AFTER TESTING IT WORKS FOR WINDOWS EXCEPT THE '

**Comment by textbrowser** [comment]
Which signs?

**Comment by meteos77** [comment]
The result is 0

**Comment by textbrowser** [comment]
https://www.sqlite.org/faq.html#q14

**Comment by meteos77** [comment]
I don't ask for anything.

**Comment by textbrowser** [comment]
All search queries have to be reviewed now.

**Comment by textbrowser** [comment]
OK, this ticket has now transformed into nothing related to the ticket.

**Comment by textbrowser** [comment]
Create new tickets for specific problems and remain on topic. 83+ comments most of which are unrelated.

**Comment by textbrowser** [comment]
Thanks. :)

**Comment by textbrowser** [comment]
Will you reopen this as a new ticket?

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/issues/260
