### ISSUE TITLE
Hyperlinks. You can visit another galactic galaxy.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#259]
Specific problem in SQLITE

exemple : ISBN13 : 9780596521189 - Z3950 : National Library of the Czeh Republic
Publisher : O'Reilly

when you click on the O'Reilley link with the Alt key activated the result is 0

**Comment by textbrowser** [comment]
Let's hope this corrects the problem.

https://github.com/textbrowser/biblioteq/commit/4455e263211125a61a8463167ff4f11dda8279ca

**Comment by meteos77** [comment]
Resolved,
thank you very much

**Comment by textbrowser** [comment]
Cool lentils.
