### ISSUE TITLE
Inclusion of "documents" category

### ISSUE THREAD

**Issue by thornybob** [textbrowser/biblioteq#26]
G'day,
this could probably be easily included as more or less a repeat of the "photographs" category -  or even as a subset ?
I note that this category is based on an 'album' premise, it would be more convenient for the user to have the facility for a single item entry rather than an album of items.  Perhaps the 'photographs' category could be replaced with two 'photo/document' categories, one singular and the other an album or set of documents.
With this enhancement it would be much more useful for the small archives of local historical societies and the like.
BiblioQ is generally great stuff, many thanks !
thanks,
Bob Thornton

**Comment by textbrowser** [comment]
One could define single-photograph collections.

**Comment by thornybob** [comment]
G'day,
I guess one could, but it becomes a bit involved in that the data entry process gets repeated with two images required before you can access the details bits ?  It suits the album premise rather well.
The addition of a separate 'type' for singular photos & documents would make life easier, they could live together I would think, but would of course be better with their own 'type' title.  As the data entry screens could be the same for both perhaps a drop down field to select either 'type' within the data entry screen ?
Or, perhaps, better still, separate 'add' listings for photos & docs with the next screen a radio button choice of collection or singular - then proceeding to the appropriate data entry screen ?
I see that you have Journals & Mags separate - in the book world here they are the same thing with 'journal' being regarded as the "proper" word.  I guess that there's a reason, but it would appear that these could be similarly treated with a drop down 'type' selection and simplify the add list ?
Thanks for your interest in my rambles.
Bob Thornton

**Comment by textbrowser** [comment]
Yes, it's a good idea. See https://github.com/textbrowser/biblioteq/issues/3 for documenting documents. It may be completed next year. Adding new categories requires a lot of work: database changes, new classes, search changes, etc.

**Comment by thornybob** [comment]
G'day,
oooooh, your #3 above is complex, the current 'photo' style item entry screen has more than enough to satisfy what I was thinking of for 'document'.  Would work for 'plans' as well I would think, at least for normal home use, they are just another document & there are plenty of fields to bend to personal needs - maybe industrialists could pay someone to create their perfect database... :-))
I think that you already have the basics there, the option of adding a singular item would likely fill the bill for me - the type selection in both album & singular is whatever works best for you, a drop down 'document', 'photo', 'plan' etc list within the item entry screen would work for me ?  Is that list something that would maybe work better within your existing user defined drop downs ?
Having spent a lot of time in visual studio many years ago when I was working I realise the work involved , I reckon you are making an admirable effort.
Bob Thornton

**Comment by textbrowser** [comment]
The person is not interested in complexity. Complexity is dead.

**Comment by textbrowser** [comment]
When the document category is complete, it'll support files. Users will be able to attach infinitely-many files to their document items.

**Comment by textbrowser** [comment]
Grey Literature category is done! See ticket #3 too.
