### ISSUE TITLE
New fields, a request.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#260]
To manage the documents properly, we would need 3 additional fields:

    purchase date (date type fields)
    date of reform (exit) (date type fields)
    origin of the documents (text - if possible enumeration database)

**Comment by meteos77** [comment]
Distinguishing fields between
the material description (unimarc 215) 
and 
the literary description (unimarc 330)

**Comment by meteos77** [comment]
the material description
![Unimarc_215_to_Marc21_300](https://user-images.githubusercontent.com/56431039/236123366-0474dd72-1a15-4d5d-81a8-e3316db729a2.png)

**Comment by meteos77** [comment]
the literary description
![Unimarc_330-to_Marc21_520](https://user-images.githubusercontent.com/56431039/236123424-d5094227-c306-487b-b118-6ea4c8428db2.png)

**Comment by textbrowser** [comment]
Print revisions.

**Comment by meteos77** [comment]
Every library wants to have software that can store all the elements it needs to manage its requirements.
We know that it's a big job for you to add fields, as many functionalities are affected each time, and we thank you very much for adding some of them (public, volume_number).

With your description of things to do and the example of the new volume_number field, I've tried to create a new field
physical_description.

Status:
two database engines. 
----------------------------------------
PQ: two files. 
file: SQL/postgresql_create_schema.sql -> not tested.
file: SQL/postgresql_update_schema.sql -> untested.
----------------------------------------
SQ: two files. => OK
SQ: upgrade process. => OK
Display fields in main table. => OK
Search revisions. => NOK
Export revisions. => OK
Import revisions. => OK
Book revisions (interface and logic)
interface UI => OK
logic ??

MARC / UNI parsers. -> It's hard!
And maybe enumerations too which require database, interface, and logic revisions. Then assignment into book items.
Print revisions.

Could you please help me with the Search functionality as I haven't found what's causing the problem.

**Comment by meteos77** [comment]
It will be great to have the commit in the form of documentation.
I'm already pretty happy with myself ... even if it's just a copy of volume_number :-)

https://github.com/meteos77/biblioteq/commits/master

**Comment by meteos77** [comment]
date_of_reformation; origin; date_of_purchase are information such as condition or location, it is the library that knows when it bought the book or when it was reformed, and where the book comes from.

I intend to use these fields for the unimarc 995$a (origin) ; 995$m (purchase_date) ; 995$n (date_of_reform) but this concerns the unimarc files (.pan) supplied by our central library with the French recommendation (995) for the exchange of information between libraries.

**Comment by meteos77** [comment]
Marc21 300 : Physical Description
Marc21 520 : Description (Summary)


Unimarc 215 : Physical Description
Unimarc 330 : Description (Summary)

To test the 330, you need to add the info (biblioteq.conf) for the Bnf server that provides this field with the TOUT-ANA1-UTF8 database.

**Comment by textbrowser** [comment]
:)

**Comment by meteos77** [comment]
Is my answer right?

**Comment by meteos77** [comment]
![Zone300](https://github.com/textbrowser/biblioteq/assets/56431039/2198ed54-ef7c-43db-8e5d-5ea614fa6686)

**Comment by meteos77** [comment]
![Zone520](https://github.com/textbrowser/biblioteq/assets/56431039/ff5cfb4b-07f2-4831-833f-f9bdfa1f5b09)

**Comment by textbrowser** [comment]
Nope not yet.

**Comment by textbrowser** [comment]
OK, so if the librarian will be supplying the information, we don't need to modify the queries to retrieve that information. All done!

**Comment by textbrowser** [comment]
OK, now I can include your new translations after you're set and then prepare a release.
