### ISSUE TITLE
Batch Activities / Discover : intensive use.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#261]
I used BA/Discover and it's very useful: 590 documents arrived to test BA

3 observations
- Having the title of the document would be useful

- To be able to save the scanned list of not found because no way to keep this list (the list of found is OK).

- The visibility if the number of scanned documents is higher than the screen size (maximum 15-20 lines depending on the screen resolution) is not adapted.

After the number 15 a scrollbar appears to scroll the new scanned documents. Except that you have to intervene at each new document to make it go down.

suggestion : 
is it possible to make appear in reverse order :
the oldest scanned document goes down one notch and the new one always appears on the first line?

Thank you for the evolutions that you can bring if it is not too much mountain/time

**Comment by meteos77** [comment]
I have problems to compile the new version with windows10 :-(

This afternoon I'm going to the library, I'll test again with the linux compilation which is OK.

**Comment by meteos77** [comment]
scroll To Bottom super cool

**Comment by textbrowser** [comment]
> I have problems to compile the new version with windows10 :-(
> 
> This afternoon I'm going to the library, I'll test again with the linux compilation which is OK.

Which problems?

**Comment by textbrowser** [comment]
Done.

**Comment by meteos77** [comment]
A great feature this BA/Discover : Thanks you for all these evolutions

**Comment by meteos77** [comment]
Detail : the result of the document type remain in English -> book instead of "livre"

**Comment by textbrowser** [comment]
OK.

**Comment by textbrowser** [comment]
"grey_literature" -> table name
"book" -> table name

Etc. I cannot rename the database tables to suit the locale.

**Comment by textbrowser** [comment]
The type fields are in English in the database.

**Comment by meteos77** [comment]
it is well hidden because we never notice it

**Comment by textbrowser** [comment]
https://www.gigamic.com/

**Comment by meteos77** [comment]
I like to make puzzles, small scale models.

it's true that computers take up too much space :-(

at the library we decided to postpone our software changeover to June/July 2023 because of the delay on the inventory, Papys90 is holding the shock ... but after I will find more diversified activities than computer.
Well, if the snow comes, I'll go to the cross-country ski tracks :-)

**Comment by textbrowser** [comment]
Is that a pizza company?

**Comment by meteos77** [comment]
why a pizeria ?

**Comment by textbrowser** [comment]
Italy would not have had modern pizza had it not been for the Aztecs.

**Comment by textbrowser** [comment]
Papy, sounds like a pizza shop.

**Comment by meteos77** [comment]
Sorry we are located in the old school.

**Comment by meteos77** [comment]
the tomato :-)

**Comment by textbrowser** [comment]
Old school? Is that like traditionalists standing still while only looking into the past?

**Comment by meteos77** [comment]
It is difficult to attract young people. Reading is unfortunately an activity that is being lost.

We made a drop to bring the children of the school : 4 years - 8 years.

The screens are more attractive.

**Comment by textbrowser** [comment]
You should upgrade your Android device. That version is totally dead. And look into Nintendo or PC gaming. Lots of brain activity there. Or play the piano.

**Comment by meteos77** [comment]
old schold it is the building that is old not the volunteers :-)

**Comment by textbrowser** [comment]
Social media is a good drug.

**Comment by textbrowser** [comment]
Introduce comic books, Manga, graphic novels. They'll attract everyone. Books with pictures are awesome.

**Comment by textbrowser** [comment]
Lego is a good library activity too.

**Comment by meteos77** [comment]
We can always improve our offer but the library is in a village with 600 inhabitants, With the deliveries of the central library we have books with pictures.

**Comment by textbrowser** [comment]
https://www.ankama-shop.com/en/100-radiant

**Comment by meteos77** [comment]
In our region, most people are sportsmen
Running, skiing, hiking, we are in the middle of nature
There are more forests and fields than building areas, so the inhabitants take advantage of this to get some fresh air.
The "intellectual" culture is not as present as in the cities. In my village, there is a school and even a music school.
In summer there is a lumberjack competition :-)

**Comment by meteos77** [comment]
I like your sites, I always find nice things :-)

![1](https://user-images.githubusercontent.com/56431039/208141302-f6d53861-48e4-483f-9d4a-02a3c1f21128.png)

**Comment by textbrowser** [comment]
https://www.foliosociety.com/uk/silent-spring.html

**Comment by textbrowser** [comment]
Do you ban any books in your library?

**Comment by meteos77** [comment]
https://en.wikipedia.org/wiki/Soylent_Green

**Comment by meteos77** [comment]
not to my knowledge

**Comment by textbrowser** [comment]
The book which that movie is based on is silly but good.

**Comment by textbrowser** [comment]
We have a twisted movement in the US of book bans and threatening librarians.

**Comment by meteos77** [comment]
It makes you feel uncomfortable because people were already denouncing the wrong direction for the planet at that time.

**Comment by textbrowser** [comment]
Can you ask your head office for Folio Society books? They're pricey but really nice to read. Kind of snobbish. Maybe they'll attract more readers because they often have nice illustrations.

**Comment by textbrowser** [comment]
They're printed in Germany and Italy, sometimes Spain.

**Comment by meteos77** [comment]
This is what I understood from one of your previous posts...

https://github.com/textbrowser/biblioteq/discussions/237

**Comment by meteos77** [comment]
you are not the country of freedom?

**Comment by textbrowser** [comment]
We find them for cheap at used book stores and libraries selling donated books.

**Comment by textbrowser** [comment]
There is always freedom for authoritarians. Not so much for people on the margins.

**Comment by meteos77** [comment]
I find it hard to understand your country

**Comment by meteos77** [comment]
related to your book : https://www.lemonde.fr/planete/article/2018/06/06/scandale-sanitaire-aux-antilles-qu-est-ce-que-le-chlordecone_5310485_3244.html

**Comment by textbrowser** [comment]
That's right.

**Comment by meteos77** [comment]
Which android tablet would you recommend?

**Comment by meteos77** [comment]
I had a question about the compilation of the android version; on which machine do you do this?

**Comment by textbrowser** [comment]
The applications are not always compatible. Which tablet? An Android 8.1 Samsung tablet is alright. I would review the newest Android models carefully. Review for warranty and battery.

**Comment by textbrowser** [comment]
I build on a virtual Ubuntu 20.04 using Qt Creator.

**Comment by textbrowser** [comment]
The process of preparing Qt Creator and the Ubuntu machine for Android is not simple. That's the reason I didn't document it. :D

**Comment by textbrowser** [comment]
You can also upload the APK directly from Qt Creator. I think it includes Android virtual machines.

**Comment by meteos77** [comment]
my current tablet : I am very happy with it 
https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_S_10.5

**Comment by textbrowser** [comment]
Android 8.1?

**Comment by textbrowser** [comment]
The Tabs are nice.

**Comment by meteos77** [comment]
Android 4.4.2 
![1](https://user-images.githubusercontent.com/56431039/208157453-e2b70e53-1c94-45df-b642-b597a1c10229.png)

**Comment by textbrowser** [comment]
Brilliant!
