### ISSUE TITLE
SQL database merge functionality : duplicate myoid

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#262]
I have encountered a problem with merging several databases because I can't edit some documents after the merge

it seems that the documents with the problem have the same "myoid" field

error message : "Unable to create or update the entry. Please verify that the entry does not already exist."

I join you the error file
[erreur-messages-fusion.txt.zip](https://github.com/textbrowser/biblioteq/files/10216200/erreur-messages-fusion.txt.zip)

precision : I create databases from scratch then I merge so the numbering always starts with 1 in the myoid field.

**Comment by meteos77** [comment]
herewith the bases concerned
[base1.sqlite.zip](https://github.com/textbrowser/biblioteq/files/10216266/base1.sqlite.zip)
[base2.sqlite.zip](https://github.com/textbrowser/biblioteq/files/10216268/base2.sqlite.zip)

**Comment by textbrowser** [comment]
If the myoid field is the problem, I cannot do anything about that.

**Comment by meteos77** [comment]
I know, I read the log which apparently makes mistakes without consequences.

**Comment by meteos77** [comment]
on the other hand I do not know if the functionality must change the myoid because with 2 merged bases there is a risk to find the same myoid?

**Comment by textbrowser** [comment]
Sure and change the foreign key of all dependent database entries.

**Comment by textbrowser** [comment]
There is nothing in SQLite which allows you to merge multiple databases.

**Comment by textbrowser** [comment]
https://sqlitestudio.pl/

**Comment by textbrowser** [comment]
The merge tool is complete. If there are problems, those will be addressed.

I will not be adding logic to invent values for unique fields.

**Comment by textbrowser** [comment]
> I know, I read the log which apparently makes mistakes without consequences.

The log denotes duplicates. 

BQ cannot manufacture data or correct entries because of your particular data. Unique identifiers identify child-parent relationships. Detecting a duplicate OID, remembering it, and then applying it to future children is beyond the scope of the merge process.

**Comment by textbrowser** [comment]
I do not see any mention of a merge process.

https://github.com/pawelsalawa/sqlitestudio/blob/master/ChangeLog.md

**Comment by textbrowser** [comment]
So, whatever BQ is doing, it's unique and complete.

**Comment by meteos77** [comment]
What I don't understand is that the myoids are assigned by BQ?
the process does not work because there are errors reported that prevent the proper functioning?

**Comment by meteos77** [comment]
I agree but I'm not clear on what is causing the conflict, hence my problem.

This is not the first time I have merged 2 bases and usually it worked.

I need to find out why, now that it doesn't work.
I have the documents created in the reception base but I can't edit some of them?

**Comment by textbrowser** [comment]
Again, we're going to argue semantics over a utility that does not exist elsewhere. If you have a better implementation, implement it. :)

I'm not going to implement a mechanism which detects duplicates with relationship fields and modifies them. If myoid 1 exists in database A and database B for book X, I will not invent an myoid because the invented myoid may exist in a subsequent query. In addition, the invented myoid needs to be assigned to child entries of the original myoid.

**Comment by textbrowser** [comment]
"Error 24: unique constraint failed: locations.location, locations.type unable to fetch row. Statement: INSERT INTO locations (location,type) VALUES (?,?)."

This clearly indicates that a duplicate location cannot be inserted into the locations table.

**Comment by meteos77** [comment]
I am not asking for further development, I am looking for an explanation for the non functioningent supplémentaire, je cherche une explication au non fonctionnement

**Comment by textbrowser** [comment]
I myself don't know what causes a failure and the log helps me with it. There are many, many, many possible errors that SQLite may report and you have to review them and think about them. So I cannot tell you what to do.

**Comment by meteos77** [comment]
thank you with your translation in clear, I begin to understand :-)

**Comment by textbrowser** [comment]
Consider a complex process that may result in many failures. And suppose I design the process. You're asking me: list all 3 trillion error possibilities and how I may correct them. My response: no.

**Comment by meteos77** [comment]
For this afternoon, I go back to the library for the news is the beautiful function BQ/Request

I will keep you informed of my progress
have a nice day

**Comment by textbrowser** [comment]
I am not upset nor perplexed. I am confused about the request. Have you read the warnings about Tylenol, for example? It's like that. Many, many possibilities and many, many decisions.

**Comment by textbrowser** [comment]
I'm asking you to think for yourself about what you see in the report. Make decisions and learn how to correct them. If you believe a problem exists, then report it. Reporting something because you see red does not mean it's a problem with BQ.

**Comment by textbrowser** [comment]
"I am not programmed to invent data."

**Comment by textbrowser** [comment]
> For this afternoon, I go back to the library for the news is the beautiful function BQ/Request
> 
> I will keep you informed of my progress have a nice day

Good luck and a nice day.

**Comment by textbrowser** [comment]
If an enumeration exists, that's fine. What's the problem?
