### ISSUE TITLE
Compilation Windows - version 2022-12-14

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#263]
on my machine but the git version has an error. It continues to create the executable but it is not usable
extract from the errors
![PB-WIN](https://user-images.githubusercontent.com/56431039/207636322-f5ea55dc-fc3b-4983-a794-bbbe910fea2b.png)

the 2022-11-25 version compiles without problem
![WIN-OK](https://user-images.githubusercontent.com/56431039/207636533-920b4851-9b95-4308-b943-b1a51bc29366.png)

**Comment by textbrowser** [comment]
Have not compiled on Windows. You requested audio and the new module requires new libraries. Therefore, these problems are expected. I'm not going to look at it now because I'm not releasing it now.

Again, too many requests and too many platforms. Another reason I'm dropping packages.

**Comment by textbrowser** [comment]
Closing as this is not an issue.

**Comment by textbrowser** [comment]
I compile on a single platform with its preferred compiler and preferred compiler options. Other operating systems will be different.

**Comment by meteos77** [comment]
No request it was just to point out the problem.
I have a linux laptop that I can move to the library

**Comment by meteos77** [comment]
I was able to test the sound feature and it's really great!
a big thank you for the evolution of BA/Discover

**Comment by textbrowser** [comment]
Sure. I would have encountered this problem during a Windows trial. :P It's nice, I suppose, that you submit a ticket, but I would have encountered the compilation error. Tickets are supposed to be for released software or things that are related to a request which is being tested on a requested system. Submitting a ticket for each commit is really silly.

I don't have a release team or a release engineer. As I release for systems, I correct their peculiarities during the release process. I don't test all revisions for each platform because that's a lot of time.

**Comment by meteos77** [comment]
I'm doing a little more testing because I'm trying to get the same functionality between the library's windows machine and my personal machine which is under linux.
So when I go to the library -> I usually do a build for windows to synchronize.

Until now, there was no problem.

**Comment by textbrowser** [comment]
With a real database, access can be national or regional or local.

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/Tethering

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/TrueNAS

**Comment by meteos77** [comment]
This is not a technical issue but a financial reason
the internet package is 360€ / year   -> we ask 7€ of contribution per family per year

It would take 51 families to just pay for this feature and there would be almost nothing left to buy new books which is the goal of our structure.

**Comment by textbrowser** [comment]
Libraries in the US accept donated books.

**Comment by meteos77** [comment]
We average about 50 books purchased per year 
We have an average of 50 donated books per year
the central library lends us : about 500 per semester

**Comment by textbrowser** [comment]
I'm now building Windows and except for the warnings, I am not encountering any errors.

**Comment by meteos77** [comment]
thank you very much : it works perfectly

**have a nice christmas with your family**
