### ISSUE TITLE
Creation of a book with isbn13 starting with 979 : problem during validation

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#269]
When creating a book with isbn-13 in 979 the validation cannot be done because BQ asks for ISBN13 **and** ISBN10.
message : "Please complete both the ISBN-10 and ISBN-13 fields.

On the other hand no problem when importing csv

Can you allow saving if there is only the ISBN-13?
Thank you in advance for the evolution.

**Comment by textbrowser** [comment]
Someone once requested a conversion from 979. This is not allowed.
Anyway, the behavior is now different.

**Comment by textbrowser** [comment]
The change is with respect to the next release. Previous releases allowed 979 conversions. Remember, these conversions are not logical.

**Comment by meteos77** [comment]
It's always great to get the fix within 24 hours. We can't thank you enough for this performance!

summary: 
isbn10 -> isbn13 : OK
isbn13 (978) -> isbn10 : OK
isbn13 (979) -> no isbn10 : OK with information message

the point of converting isbn13(978) to isbn10 is to allow image search on amazon otherwise we have the message "In order to download a cover image, alternate Identifier or ISBN-10 must be provided."

I have almost had every book in my library and very few books have an isbn-10 in barcode format.

Either the isbn10 is just listed inside in numeric format, or it wasn't even listed.

The real change was with the 978 that are now printed as a barcode on the back cover and retailers had to switch to the world of scanners which made barcodes widespread.

Translated with www.DeepL.com/Translator (free version)
