### ISSUE TITLE
The publication date field (pdate)

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#270]
note : We never have a precise date for the publication date, only YYYY is specified.

Management in BiblioteQ
When importing csv, BQ accepts the format MM/DD/YYYY ; MM/DD/YYYY ; YYYY/MM/DD ; YYYY-MM/DD ; DD/MM/YYYY ; DD-MM/YYYY

Display in the main window : only YYYY and MM/DD/YYYY is taken into account with the "Publication date format" option.

When editing : only MM/DD/YYYY format is taken into account by the date widget otherwise date = 2000.

The european format for dates is DD/MM/YYYY or YYYY-MM-DD
For sorting YYYY or YYYY-MM-DD columns is interesting.

![pdate](https://user-images.githubusercontent.com/56431039/211278943-574f1017-5ad8-45d4-b72a-8b8ae56bee8f.png)

**Comment by meteos77** [comment]
Request for improvement
- The edit widget should take into account the YYYY format and the DD/MM/YYYY format
- the "Publication date format" option should take into account the DD/MM/YYYY format as a date

**Comment by textbrowser** [comment]
Done.

https://github.com/textbrowser/biblioteq/commit/9dd696ea31f605bd7658a7f92b431c620ca3ca31

**Comment by meteos77** [comment]
I knew that my request would be difficult to understand :-)

thanks for the modification, it makes the display more flexible.


However, if you import a date in YYYY (e.g. 2020), (all the cases for me).

when editing the book the date is always "blocked" at 2000 as if BibliotheQ didn't look at what's in the database or didn't understand it?

The only time BQ does the retrieval and display well is if the date is in the MM/DD/YYYY format.
![PB-pdate](https://user-images.githubusercontent.com/56431039/211371848-779d8bba-c1e8-4201-af39-e71915968846.png)

**Comment by textbrowser** [comment]
And a year is not a publication date. It's a publication year. So, that's busted data. Qt cannot ascertain the format from a value. There is a display format and there is a database format. Since the publication date is a text field, the text must be stored in some universal format in the database. Universal for BQ. The display format is separate. BQ cannot guess your format. 2020 is a year or perhaps a day and a year. Or perhaps it's nonsense. Hence the results. Ticket closed!

**Comment by textbrowser** [comment]
Revised documentation to specify database format.

**Comment by textbrowser** [comment]
Again, this is a data problem caused by ignorance of internal aspects of BQ and expecting the import to deduce values without any meaningful information.

1. Correct the publication years.
2. Import.

Or.

1. Correct the data through SQLite.

**Comment by textbrowser** [comment]
This is an import-free future.

**Comment by meteos77** [comment]
I do not agree with publication date = MM/DD/YYYY  (in the context of book publishing date)
I don't know if in America the books indicate the exact date?

look at all the z3950 or SRU servers, the marc records are in YYYY (unimarc format : 210$d or 214$d) and therefore the publication date (book context) is indeed a year in YYYY format.

In any book, the date of publication or printing does not go into detail until the day but remains on the year.
ditto for CD, DVD, VIDEO GAMES.

BiblioteQ is still smart enough to deduce that a sequence of 4 digits between 1450 and 2100 is necessarily a year of publication.

**Comment by textbrowser** [comment]
More information is always better than less information. If one accepts that, my format is sugar.

**Comment by textbrowser** [comment]
And I don't care for the format of legacy systems. It's a publication date. Not a publication year.

**Comment by textbrowser** [comment]
I'm not adjusting BQ regarding this topic. The formats are now open. This is your data problem. Good luck!

**Comment by textbrowser** [comment]
And don't get upset. My time is valuable and tweaking BQ to, again, fulfill something which you can do is not interesting for me. BQ is, again, completed. I'm only working on things I find interesting. If it doesn't fit my curiosity, I will place it on the high TO-DO pile.

**Comment by textbrowser** [comment]
For example, you can correct the original file. Copy & paste. Or you can write an UPDATE statement to correct it. If BQ does not tolerate your data, fix the data. It's like eating. If you cannot tolerate something, you don't eat it. You don't go tweaking yourself with medications and brain remedies just to eat garlic.

**Comment by meteos77** [comment]
_Some operators believe that BiblioteQ should correct their malformed data regardless of the effort, interest, and time_

I react to this line in the release notes because :
1 - I am targeted by "Some operators believe ..."
2 - I find this sentence unjustified to present the functionality.

**Comment by meteos77** [comment]
Summary of my vision as a French user
the importation was perfect, it took into account many formats examples: YYYYY-MM-DD; DD-MM-YYYY; DD/MM/YYYYY; MM-DD-YYYY; MM/DD/YYYYY (all the planet finds its format)

I would like to point out that the editing widget only displays the correct value for a date with the format MM/DD/YYYY; so BQ accepts everything in import and then displays almost nothing in the edition of a book.

**Comment by meteos77** [comment]
BQ is a software used in the world, you force us to use a date format that is not ours
![Date](https://user-images.githubusercontent.com/56431039/212287680-409a8ada-a794-4709-881a-e85e914ec1b3.png)

**Comment by meteos77** [comment]
I never asked that the csv import from BQ modify my data. (by the way, the import = export principle is broken, which I do not want).

**Comment by meteos77** [comment]
A standard to avoid date confusion in the international system exists: ISO8601 (I think BQ uses it in the fields 
"Members since"; "Date of birth" and "Date of expiration" for the management of the members).

https://en.wikipedia.org/wiki/ISO_8601

**Comment by meteos77** [comment]
I am not a developer and my vision is therefore that of a user of a foreign language compared to you developer. This is the first time I have encountered a software that does not adapt to the date format of my language.

**Comment by meteos77** [comment]
**Of course, this is in no way a criticism of the extraordinary work you do to improve BQ from day to day, month to month, and year to year.**

**Comment by textbrowser** [comment]
> _Some operators believe that BiblioteQ should correct their malformed data regardless of the effort, interest, and time_
> 
> I react to this line in the release notes because : 1 - I am targeted by "Some operators believe ..." 2 - I find this sentence unjustified to present the functionality.

New year. I suggest migrating away from BQ.

**Comment by textbrowser** [comment]
> BQ is a software used in the world, you force us to use a date format that is not ours ![Date](https://user-images.githubusercontent.com/56431039/212287680-409a8ada-a794-4709-881a-e85e914ec1b3.png)

Not true. Again, display and data are different ideas. If your data cannot be interpreted as a date, BQ cannot display it accordingly.

**Comment by textbrowser** [comment]
Dates must be stored in some format. BQ is 23 years old. The format was decided 23 years ago. This is not a death sentence. It's a date. A date. A D.A.T.E.

Again, migrate from BQ because you're obviously unhappy and I am not going to waste time convincing you that BQ works.

See you.

**Comment by textbrowser** [comment]
https://doc.qt.io/qt-6/qdate.html#fromString-4

Returns the [QDate](https://doc.qt.io/qt-6/qdate.html) represented by the string, using the format given, **or an invalid date if the string cannot be parsed**.

**Comment by textbrowser** [comment]
The format of the data in the database, again, is MM/dd/yyyy. This is not important but is important. It's important because that format contains everything required for interpreting a date into any other format. If you violate that format in the database, then you're actively deciding to ignore BQ and QDate. You are actively deciding that. So whether you do this via an import, beyond BQ, or through a modified BQ, it's a deliberate decision. If QDate cannot ascertain your data, that's not a fault of Qt and BQ. It's that simple. Really, really, that simple.

**Comment by textbrowser** [comment]
So again, let me repeat. Again. You need to store your date as MM/dd/yyyy. Store it in that format and display it in any other format that Qt understands. Really that simple.

**Comment by textbrowser** [comment]
And, the print utility already performs an ISO-Date conversion to the date. That was a future-proofing decision made many years ago.

The expectation that I would be harassed and murdered over a date (a date!) was not something I was anticipating 23 years ago. A date!

**Comment by textbrowser** [comment]
Everyone is welcome to contribute and I'm not obligated to resolve every request.
