### ISSUE TITLE
French translation for 2023-01-16 version.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#271]
Thank you in advance for the integration of French in the future version.
[BiblioteQ_French-Package-Edition_2023-01-16.tar.gz](https://github.com/textbrowser/biblioteq/files/10410487/BiblioteQ_French-Package-Edition_2023-01-16.tar.gz)

**Comment by textbrowser** [comment]
Not interested, but thanks.

**Comment by textbrowser** [comment]
Uploaded. Thanks.
