### ISSUE TITLE
Change the start program window colors.

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#275]
Please change the start program window with the annoying blue-yellow colors.
This is not the right place for politics or to present your views. Keep it to yourself, please.

**Comment by textbrowser** [comment]
Say what?

**Comment by textbrowser** [comment]
Software is art and art is always full of colorful statements. Suggestion! Do not use BQ if it offends you. Or, enjoy it because it offends you!

**Comment by jerzyPL** [comment]
So, bye bye. Enjoy your new avatar, it's a work of art too. 
![10701156](https://user-images.githubusercontent.com/66644295/219143790-9e6c6e7e-fbaa-4b2f-977f-75c0f48eab1a.png)

**Comment by textbrowser** [comment]
Great job!

Don't forget to de-fork BQ! It'll help you complete your resentment of it and its ever-so-wonderful colors.

Teee-heeeeeeeeeeeeeee!

**Comment by textbrowser** [comment]
And the colors are in About. Say whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaat!
