### ISSUE TITLE
Black field background.

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#276]
2023.02.25 build done according to `Windows Installation.pdf`. What may cause the black backgrounds in the forms fields? Thanks.

![image](https://user-images.githubusercontent.com/50261477/222437527-ccd02cb5-a58c-4cfb-adeb-00db5390d71e.png)
![image](https://user-images.githubusercontent.com/50261477/222437781-c37fbb31-3a48-4f76-9ad5-0e0fec2e6dcb.png)

**Comment by textbrowser** [comment]
Did you read the release notes?

2023.01.16

Item field colors. New options in Other Options. GitHub ticket #272.

**Comment by textbrowser** [comment]
![fields](https://user-images.githubusercontent.com/10701156/222462948-424e012a-50ab-4f0a-bf4f-0aa6414dd645.png)

**Comment by textbrowser** [comment]
Aha, you did uncover a problem! Thanks a bunch. The retrieval methods for those colors should not retrieve INI values because the INI may not be current. Awesome.

**Comment by textbrowser** [comment]
Committed!

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/140e4369044a01c1c5341cdd683ccc836828c4a9

**Comment by textbrowser** [comment]
And very nice that you built your own BQ. Very excellent. If you need to revise the document, please submit changes and/or push requests.

**Comment by tamascz** [comment]
> Did you read the release notes?
> Item field colors. New options in Other Options. GitHub ticket #272.

Yes, and I wanted to further investigate it, but something come in between, and I forget, sorry. (.ini inspection wasn't part of my update routine until now, but it will be in the futur.)

**Comment by textbrowser** [comment]
Releasing! Test the new biblioteq-darkmode.bat if you'd like.

**Comment by textbrowser** [comment]
It's very import that everyone has access to build instructions for software. It's quite difficult to limit programs from numerous dependencies, particularly on Mac and Windows. On Mac, Brew exists, however, it deprecates hardware as well as suffering from the madness of Mac. Windows, well, Windows.
