### ISSUE TITLE
Customizable Menu

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#278]
Allow to integrate little extras without having to leave BQ.

Have a "plugins" menu where the user can launch his own complementary programs (for me python scripts for statistics)

it would be necessary to have access to a variable that will give the current database (with path) to retrieve it in the scripts.

**Comment by textbrowser** [comment]
Would a terminal option include all possible programs? From a terminal, one would be able to start other programs. As for a variable, perhaps setting an environment variable prior to launching the terminal would suffice. For example, BIBLIOTEQ_CURRENT_SQLITE_FILE.

**Comment by meteos77** [comment]
do you offer this?
launch with ./biblioteq --programs=prog1.py prog2.py prog3.sh

 and a menu would display
"SupplementaryMenu/prog1
"SupplementaryMenu/prog2"
"SupplementaryMenu/prog3"

**Comment by meteos77** [comment]
python example (pyqt5 request)
[Statistique-Dxx-Python.tar.gz](https://github.com/textbrowser/biblioteq/files/10970736/Statistique-Dxx-Python.tar.gz)

**Comment by textbrowser** [comment]
When BQ launches the program, how should it pass arguments to the command(s)? Other Options requires an External Commands section.

Program Executable Path | Arguments
/path/to/prog1.py                 --sqlite-path %1

If programs are defined, an External Commands menu becomes available in the main window.

**Comment by meteos77** [comment]
If for example I change my database through the graphical interface of BQ (Menu / File / Connect ... ) the variable BIBLIOTEQ_CURRENT_SQLITE_FILE will be updated ?

**Comment by meteos77** [comment]
Typing error

in the ticket I put #278 but it is the item_278 of the TODO file not the ticket number on github

**Comment by textbrowser** [comment]
Completed. See official documentation and commit text for details. :)

**Comment by meteos77** [comment]
Thank you very much.
it works well, now I just need to make my personal statistics panels.
