### ISSUE TITLE
A Super Custom Query

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#279]
Be able to declare "HIS favorite query" and that it is accessible via a function key ex : F6

**Comment by meteos77** [comment]
Many thanks for this great feature


for my case it allows to solve the TODO #278 because I wished with accession number in 1st column what can be done by 


1 - create a personal query (SELECT accession_number,title ...)

2 - set this query as favorite

3 - quick access key (F6) instead of F5 usually.

**Comment by textbrowser** [comment]
Mapping the results of a select with table columns require a model / view approach. Someday when I'm 94.

**Comment by meteos77** [comment]
either you are 93 years old, or you wait for chatgtp version 200 to program for you :-)
