### ISSUE TITLE
How can i have an export xls?

### ISSUE THREAD

**Issue by nikoscrete** [textbrowser/biblioteq#28]
i try to export my database to xls. The programm has only to csv. I convert the csv to xls but i loose the greek characters. Have anyone an idea?

**Comment by textbrowser** [comment]
Let me see if the export preserves the data.

**Comment by textbrowser** [comment]
OK, I was able to import a CSV file using LibreOffice. What did you use as the delimiter during the import? Fields in a CSV file are delimited by commas.

**Comment by nikoscrete** [comment]
I didn't know the LibreOffice. I wanted to make export from biblioteq to xls.
Ok, i can use the LibreOffice.

thank you!!!

**Comment by textbrowser** [comment]
So BQ cannot export to XLS, only CSV. Let me know if the import also works for you.

**Comment by textbrowser** [comment]
Please open a new ticket if the solution is incorrect.
