### ISSUE TITLE
Batch Activities : Return via Shower

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#280]
Have a new tab that allows via the shower to create a list of documents returned in batches.

A return from BQ would be a plus (Title and Borrower fields).

**Comment by textbrowser** [comment]
The All Reserved category includes accession numbers and identifiers. I will add a new option to the Find panel (bottom of the main window) to select discovered items. Also added will be a scanner-friendly option to the Find panel.

1. Activate All Reserved.
2. Scan item.
3. Item located and selected.
4. ...
5. Press the Return Selected Item(s) button.

I do not wish to duplicate all of the logic with returning an item.

**Comment by meteos77** [comment]
The purpose of the request is to not have to manipulate the mouse to render 10 items; if your proposal improves the existing one that's cool.

If you have to juggle between scanner, mouse for each book: we'll settle for what exists.

**Comment by textbrowser** [comment]
1. Activate All Reserved. One click.
2. Activate Scanner-Friendly (does not exist in your view). One click.
3. Activate Select Discovered (does not exist in your view). One click.
4. Place focus on Find text field. One click.

Four clicks. Scan items. Click the respective button to return selected items. Five clicks total.

**Comment by textbrowser** [comment]
The Batch Activities would require at least two clicks. Then, it would require the entire framework of returning items. You can imagine that I would have to rewrite a musical composition just to get 3 fewer clicks. This is what ChatBot would do. Zero imagination.

**Comment by textbrowser** [comment]
> The purpose of the request is to not have to manipulate the mouse to render 10 items; if your proposal improves the existing one that's cool.
> 
> If you have to juggle between scanner, mouse for each book: we'll settle for what exists.

Yes, I surmised that. :P

**Comment by meteos77** [comment]
Done for the best as usual (time / interest / difficulty).

**Comment by textbrowser** [comment]
The main window is insufficient because I must support Qt 5.5.1 and the necessary regular expression search is not available for Qt 5.5.1. The new panel in Batch Activities will activate the All Reserved category and include only the items in the new Batch Activities panel. This will minimize my work in implementing a duplicate framework. The Batch Activities browser does contain a relationship with the main window so the new addition will not introduce strange behavior.

**Comment by meteos77** [comment]
Too bad, I just tried the commit: 561c0f9 -> Returns adapted to scanners. GH ticket #280.
and the 2 features were great.

it allowed me to learn "git checkout num_commit".

Qt5.5.1 ? -> 2015 

Suggestion: reserve this feature for users with version qt > 5.?

**Comment by textbrowser** [comment]
Cannot add batch returns. Reproducing vast amounts of work. Instead:

1. Members Browser.
2. Locate member.
3. Show selected member's reserved items.
4. Scan work in main table.
5. Return selected items button.

I'm not quantifying the progress by optimizing clicks. You can, but I'm not. Looked at batching the return process and it involves complex queries with all sorts of weird exceptions. Some people have cards, some don't. Multiple copies for different patrons. Items without barcodes. Etc.

**Comment by meteos77** [comment]
Thanks for trying.

What you had done just before was really great (the 2 check marks in the main window, and it seemed to work well
can you make it optional for people who have qt> 5.5.1?

thanks in advance

**Comment by textbrowser** [comment]
I had a day dream and am reverting my previous post. It'll be possible. The annoying part will be to modify the large main-window query so that it allows for a WHERE clause.

**Comment by meteos77** [comment]
Great, I hope this won't be too time consuming for you.

**Comment by textbrowser** [comment]
Done.

1. Scan items.
2. Press Go!.
3. All Reserved category set in the main window containing discovered items.
4. Select desired items.
5. Press the Return Selected Item(s) button.

**Comment by meteos77** [comment]
It doesn't seem to work with my version or my test base?

When I scan the accession number or isbn13 I get a beep but no document is added in the "Return" window ?

**Comment by textbrowser** [comment]
Only works with copy-ids that are correct. If item_borrower does not contain the correct copy-id, then it cannot locate the item. See label widget.

**Comment by textbrowser** [comment]
And it only returns things that are actually reserved.

**Comment by textbrowser** [comment]
select * from item_borrower where copyid like '%?%'

If that doesn't produce an entry, use All Reserved. Or correct your data.

**Comment by textbrowser** [comment]
The alternative is that I have to create a very complex query (which I already have for the actual Go!). The other query would have to query item_borrower for items in 7 other tables with multiple keys. So another big query. Kind of tired with the batch. It's yet another duplicate. Any time someone modifies important queries, they'll forget about batch processes.

**Comment by textbrowser** [comment]
I'll think about it, but for now, it's done.

**Comment by meteos77** [comment]
I understood how it works

select * from item_borrower where copyid like '%?%'
no result

The barcode on the isbn13 books 978xxxxxxxxxx or 979xxxxxxx or the accession number xxxxxxxxxxx does not contain a -1 at the end ?
Is it BiblioteQ that creates the "-1" by itself ?

In the 2 other tabs Borrow and Discover, BiblioteQ finds the documents well though ?

**Comment by meteos77** [comment]
a suggestion can be idote

instead of recreating queries that work well if you place  the copyid to manual

Transform isbn-13 to isbn10 and add "-1".
If isbn-10 add "-1"
if accession number -> get isbn-10 and add "-1".

And give this result to your great request


complementary question : what does "%?%" mean ? I can't find the meaning of the "?

**Comment by textbrowser** [comment]
Parameterized queries (?).

**Comment by meteos77** [comment]
the "?" is valid in sqlite ?

select * from item_borrower where copyid like '%'
![copyid-sans%?%](https://user-images.githubusercontent.com/56431039/235156634-1dd0a263-c00c-426c-825d-8daf729e31e4.png)



select * from item_borrower where copyid like '%?%'
no result

**Comment by textbrowser** [comment]
Complex query completed.

**Comment by textbrowser** [comment]
https://en.wikipedia.org/wiki/Prepared_statement

**Comment by meteos77** [comment]
Thank you very much for this feature.

It allows to distinguish BiblioteQ from other softwares that do not offer it.

Volunteers are going to be very, very happy : A thousand bravo !

**Comment by textbrowser** [comment]
> I understood how it works
> 
> select * from item_borrower where copyid like '%?%' no result
> 
> The barcode on the isbn13 books 978xxxxxxxxxx or 979xxxxxxx or the accession number xxxxxxxxxxx does not contain a -1 at the end ? Is it BiblioteQ that creates the "-1" by itself ?
> 
> In the 2 other tabs Borrow and Discover, BiblioteQ finds the documents well though ?

No. If you need to think this, there is a problem. :)

**Comment by meteos77** [comment]
I'm still not on top ? :-)

**Comment by textbrowser** [comment]
There is a slight possibility that item_oid may occur in multiple parent tables but through inspection the correct parent is identified by a person. item_borrower has two parents: item and member.

**Comment by meteos77** [comment]
BQ creates the copyid by adding "-1" for the first copy and "-2" for the second ... ?

I still can't figure out how to move from one table to another.
I need to practice

**Comment by textbrowser** [comment]
And item_borrower contains type.

**Comment by textbrowser** [comment]
![bq](https://user-images.githubusercontent.com/10701156/235167020-cb042c2f-64df-44f6-8734-edeec93e7e9a.png)

**Comment by meteos77** [comment]
You don't use the barcode on the book?

**Comment by meteos77** [comment]
we can modify the barcode only from the 2nd.

I did not go too much in the window management copies.

Thank you for all the information SQL, I just have to read and understand the documents.

**Comment by textbrowser** [comment]
Only from the second...

I can modify the first, second, etc. barcodes.

**Comment by textbrowser** [comment]
A barcode should be related to the original but does not have to be. BQ provides a barcode if an ISBN is available. If one is not available, it invents a barcode. Barcodes are then sequential. Barcodes are helpful if you have an item with many copies. Instead of many accession numbers, you have a single primary virtual representation and multiple physical representations via barcodes. Each copy has some unique characteristics.

**Comment by textbrowser** [comment]
Physical copies can be tagged with labels via barcodes in addition to other identifiers.
