### ISSUE TITLE
Problem Saving Additions in Database Enumerations

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#281]
I don't know if it's my QB but the database enumerations don't seem to save after closing the database enumerations?

the lists are empty when opening ?

**Comment by textbrowser** [comment]
Did you save?

**Comment by textbrowser** [comment]
Which values?

**Comment by meteos77** [comment]
Book Conditions ; Book Originality , Book Target Audiences

at the time of saving, BQ reclassifies them well in alphabetical order
but if I close the window and open it again ... empty

**Comment by meteos77** [comment]
[base-BiblioteQ.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/10971565/base-BiblioteQ.sqlite.tar.gz)

at the time of registration
![111](https://user-images.githubusercontent.com/56431039/225080078-ba9cda49-59e7-49cb-8d05-556883335549.png)

**Comment by textbrowser** [comment]
Oh. You disabled on option. See Options menu.

**Comment by textbrowser** [comment]
![bq](https://user-images.githubusercontent.com/10701156/225082702-52f21141-9bee-43ad-8364-c48fb8d27865.png)

**Comment by meteos77** [comment]
Indeed,  I reinstalled my pc and didn't save the BiblioteQ.ini file
so all my parameters are at zero :-(

thanks for the troubleshooting

**Comment by textbrowser** [comment]
![reminder](https://user-images.githubusercontent.com/10701156/225134749-a4488aa4-4098-492d-8765-ea4774845945.png)

**Comment by meteos77** [comment]
I think it's great to have a tip or recommendation right next to the feature.

on the other hand, if the texts are more numerous 
(like for example, you can add did you save ? in database enumeration )

suggestion: have a "question mark" icon and 
or have a tooltype that indicates the text
or a window opens in the style of the documentation

this kind of help could be applied to all features and the user will read what is in the application help window before calling for help in the forum.
A kind of "release note" but dedicated to the functionality and user help.

the idea was present in csv import with menu Help/Documentation

this is just a suggestion

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/a28cc8faf7747cae7c15436bee2c25e85e313f56

Future installations will be enabled.
