### ISSUE TITLE
Cover image functionality - copy/paste.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#284]
Have the ability to paste an image (right click/paste) from the clipboard. 

Currently, I search for an image on the internet, save it and then transform it into .png (because a lot of webp) and then import it into BQ.

This would avoid having to go through an image file to load it into BQ.

Thanks in advance.

I have no idea how much effort it would take to create this feature, so as usual and not urgent.

**Comment by textbrowser** [comment]
Did you know that you can drag an image onto the view?

**Comment by textbrowser** [comment]
It needs correction!

**Comment by textbrowser** [comment]
No, I'm wrong. It's working fine.

**Comment by textbrowser** [comment]
https://user-images.githubusercontent.com/10701156/230790534-bed34b61-db56-4d5c-9166-07b5ce83598b.mp4

**Comment by textbrowser** [comment]
I'll add many Paste buttons.

**Comment by meteos77** [comment]
I didn't know about the "drag an image" feature Thank you for this presentation.

my request is to switch from the web browser image by "copy image" to BiblioteQ with "paste image" without saving the image file.

**Comment by textbrowser** [comment]
Ctrl + V is complete. Paste buttons are probably not necessary. Completed!

**Comment by textbrowser** [comment]
Test and close, OK?

**Comment by textbrowser** [comment]
Paste buttons are in the TO-DO. Two buttons for each category, plus the signals. A future add-on.
