### ISSUE TITLE
Mass Update - GUI

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#285]
After some tests with the Mass Update - SQL
1 - creation of SQL UPDATE request.
2 - selection of the documents.
3 - application of the query.

Can you create something simple for the updates of the fields managed by database_enumerations.

I have made a small python program to give you an example of what would be good for us simple user.

In my example

- select the database but for your BQ it will be transparent
- the user selects the item type, the field and the value.
- instead of displaying the query, just apply the query to the selection

https://user-images.githubusercontent.com/56431039/230873376-1bd05dd4-90a1-4e4a-87f1-efb9e5de33c5.mp4

thanks for your attention

**Comment by textbrowser** [comment]
Custom Query -> Update.

**Comment by textbrowser** [comment]
I don't have an interest in duplicating Custom Query, PostgreSQL prompt, SQLite prompt, and many other applications for updating many values.

**Comment by textbrowser** [comment]
Describe an UPDATE query which cannot be achieved by Custom Query.

**Comment by meteos77** [comment]
The custom query feature works really well.
It is the access to the functionality that is not practical because a lot of text must be entered.

I have a location field for example that must be filled with  
"Class 000 - Documentaries Computer, information, general works". (DEWEY description)
...
"Classe 900 - Documentaires Géographie, Histoire et disciplines auxiliaires"
...

I have to create an UPDATE query, save it and then apply it to the selection.
I have 41 locations today, so I have to create 41 queries. 

If I create 41 queries my "View Custom Queries" menu will become unusable because I have to do this for each database enumeration which can contain 3, 5, 10, 41 values.

Hence my request to have something dynamic.
BQ analyzes the different values contained in the database and allows to apply the built queries.
I do them in python for the books but an external tool is always less usable than integrating with BiblioteQ.

**Comment by textbrowser** [comment]
Custom Query is dynamic. And it exists to dissuade such requests. Really, balance.

**Comment by textbrowser** [comment]
There are literally trillions of possible queries. No, more. Trillions of trillions. Your request is essentially: I want BQ to perform every possible request even if I'm the only person interested in them. This is not a practical request. As written, utilize Custom Query. How can it benefit you more? What needs improvement of it? Not - create a new tool which I will then request more features and forget about Custom Query. Zero balance here.

**Comment by meteos77** [comment]
We'll stay that way.

I make requests without knowing the work behind but I am aware of the great efforts to improve BQ.

**Comment by textbrowser** [comment]
How does yet-another-query-system improve BQ? Imagine if I requested PQ people to create a special system to suit me and they respond: you an do it this way. And then I say, but I want to ```improve``` PQ by doing it my way.

**Comment by textbrowser** [comment]
There are tools like SQL Studio where you can modify lots of data. So, request improvements on existing solutions. Imagine building a door in a house because an existing door doesn't suit you. So, let's make new holes instead of improving the existing door. CQ can be improved.

**Comment by meteos77** [comment]
what is CQ ?

**Comment by textbrowser** [comment]
Anyway, peace out. You stress me out.

**Comment by meteos77** [comment]
Sorry, I'm really sorry, this is not the point.

I close ticket

**Comment by textbrowser** [comment]
Multiple custom queries, custom query histories, etc. Build upon it instead of instinct to recreate.

**Comment by meteos77** [comment]
I'm going for a walk for about 10 days without IT, I'll have time to ponder your conclusion.

**Comment by textbrowser** [comment]
BQ compiles on SPARC Ultra 60. It works well too. It's intended to be small, not grand.

**Comment by meteos77** [comment]
Fortunately, you are the keeper of the trend of small, elegant and efficient systems

**Comment by textbrowser** [comment]
> Today, training day : 3 volunteers, satisfaction with the simple use of the software.
> 
> Back : Creation of users, (the 3 had trouble with the date widget because you have to select by YYYY or MM or DD). everything else is great.
> 
> The different display / categories -> OK Explanation of the "%" in the searches -> OK
> 
> ID doesn't mean anything for the people (I'll put the translation in ISBN) for the French one doesn't find it elsewhere.

Create a separate ticket describing in detail the date discomfort.
