### ISSUE TITLE
French translation for next version.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#289]
I don't know the future release date, I will update as I go along.

Thanks for the integration.

[BiblioteQ_French-Package-Edition_2023-05-05.tar.gz](https://github.com/textbrowser/biblioteq/files/11406272/BiblioteQ_French-Package-Edition_2023-05-05.tar.gz)

**Comment by textbrowser** [comment]
Can you fork and issue pull requests instead? Lots of work for me otherwise.

**Comment by textbrowser** [comment]
Documentation.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by meteos77** [comment]
Of course, I will try to make

**Comment by textbrowser** [comment]
Closing as this is a fork-and-pull request.

**Comment by meteos77** [comment]
Hi meteos77! You've successfully authenticated, but GitHub does not provide shell access.

can you please help him ?

**Comment by textbrowser** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
