### ISSUE TITLE
[Linux] Can not reserve items

### ISSUE THREAD

**Issue by Strit** [textbrowser/biblioteq#29]
Hi.
I'm just trying out the software and it's really amazing. But I have one issue though.
When I have selected an item and press the "Reserve Selected Item" button, I just get a Member browser window and a popup that asks if I want to see the Member browser window, either yes or no gives me the member browser, where I can't "apply" any as the borrower.

What am I doing wrong?

I'm using the git source, downloaded and compiled today 12/12 2017.

**Comment by textbrowser** [comment]
Hi. Are you connected to an SQLite database?

**Comment by textbrowser** [comment]
OK, so I can't see what you're seeing. See image.
![bq](https://user-images.githubusercontent.com/10701156/33907015-bacf9ca0-df51-11e7-86f7-5015bfe2a982.png)

**Comment by textbrowser** [comment]
As this is a new installation, the Populate Members Browser on Display option in the Options menu is off. I don't see a message about "seeing the Members Browser". The question is asking if you'd like BQ to retrieve the list of members. I also don't know what "Any" refers to. You need to create members before lending items.

I'm working on a user document. It'll take some weeks.

**Comment by Strit** [comment]
I think I figured it out. Will have to try abit more though.

**Comment by textbrowser** [comment]
So what was the problem?

**Comment by Strit** [comment]
Properly didn't select the item, like I thought I did.

Btw, maybe some quick actions via right click could be added? 🙂

**Comment by textbrowser** [comment]
Context menus?

**Comment by Strit** [comment]
Yeah. Like:
* Reserve Item
* Return Item
Maybe some more that makes sense.

**Comment by textbrowser** [comment]
Sure. After the next release. Documentation and grey literature are scheduled. Both requires lots of changes. Yes, after the next release.

**Comment by Strit** [comment]
Cool. Thanks. 😄

**Comment by textbrowser** [comment]
Thanks for the ideas.
