### ISSUE TITLE
New customizable shortcuts.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#291]
Can you please add, in the customizable shortcuts options to access the features :
1 - Help/Documentation/French and Help/Documentation/English (F1)
2 - Batch Activities / Borrow (F2)
3 - Batch Activities / Discover (F3)
4 - Batch Activities / Return (F4)
5 - Book Search (F9)
5 - Custom Query (F12)

Use of function keys for essential BiblioteQ features would be a plus.

Thank you in advance

**Comment by textbrowser** [comment]
No one should request custom shortcuts because I like my own. Everyone does. KDE has a shortcut thingy and you an add applications. Did you try it? I didn't. Perhaps it works.

**Comment by meteos77** [comment]
Sorry for my late reply, long vacation without computer :-)
Thanks for all the explanations on how to create shortcuts in an application.

In fact, I had asked for personalized shortcuts so that everyone could define their own according to their preferences.

I'll ask again but with shortcuts set by you (without the possibility of modifying them) if that's easier to implement. 

Otherwise (too much development time), close the ticket and make do with the existing shortcuts.

**Comment by textbrowser** [comment]
How was you{r} vacation?

**Comment by meteos77** [comment]
Quiet vacation, it did me good to get away and see other landscapes.
it was the first time I'd been away for a month.
great experience, to see what I really miss... nothing except my environment with trees.

on the way back, a little gene to use the mouse (same feeling when you haven't used a pen for a long time) :-)
it was back to normal in a few minutes.

Do you go away sometimes?

**Comment by textbrowser** [comment]
Cool beans. Yes, when I meemee to sleep. Otherwise, Americans work until they die. Our sole purpose is work. What do you do? I work. Defined by work culture. Entire existence is work. It originated from religious zealots many years ago and continues today. It's a myth continued by megalomaniac capitalists.

**Comment by textbrowser** [comment]
Right, lunatics like Adam Smith. :)

**Comment by meteos77** [comment]
is it true that Americans don't take all their paid vacations?

**Comment by textbrowser** [comment]
The so-called non-wealth classes are prohibited from voting, leisure, and rebelling by connecting healthcare to work. So if you do not work, you cannot go to a doctor.

**Comment by textbrowser** [comment]
And you're going to be told lots of numbers contrary to what I wrote, but the actual people living under said conditions exist and exist through said conditions. Massive and expensive propaganda paint a rosy yellow-brick road to hope and happiness and everything being swell. :)

**Comment by meteos77** [comment]
So if an American is rich = vacation OK (those we see in Europe)
if an American is poor = work for a healthcare system.

**Comment by textbrowser** [comment]
All you have to do is work 3 jobs and someday you'll be in the in club. Work lots and lots and be happy for the work and be actively working and forget about the sadness and inequality. Just work and you'll do it and succeed and everything will be fine. Meanwhile, Greece is on fire and Rhianna is not there singing about it.

**Comment by meteos77** [comment]
if it were only Greece :(
But why don't poor Americans vote for a collective social security system like in Europe?

**Comment by textbrowser** [comment]
Don't know. Maybe they're rich maybe they're desperate to waste all they have in a burning continent. Travel is bad. There are like 20,000 airplanes in the air right now. Now and a few moments ago, and still in the air after I press Comment.

**Comment by textbrowser** [comment]
Why? Propaganda. Lack of empathy. Ignorance. Who knows. Not impossible to ask them all. :)

**Comment by meteos77** [comment]
I once took a plane to see a solar eclipse but it's not my thing. I prefer the train.
it's easier in my country because it's only 1000 x 900 km.

**Comment by textbrowser** [comment]
Arduino is great for low-power computations in the environment. Pi too. Ultimately, smarter software is necessary. New low-power thinking. It's a fabulous future there. To think. Like, this algorithm is better in this architecture or this algorithm is architecturally-agnostic and is low-power smart. Super cool.

**Comment by meteos77** [comment]
my "video recorder" runs on raspi with [libreelect](https://libreelec.tv/)
it's super optimize, it works great.

What do you do with arduino because uno is limited?

**Comment by textbrowser** [comment]
Monitor humidity and temperature.

**Comment by textbrowser** [comment]
One can also program Arduino's for turning on computers. Or turning valves. Or reporting information to other computers via the ether. Or responding to light / noise / etc.

**Comment by textbrowser** [comment]
And they can live in the outdoors. No need to spend thousands on these expensive embedded "military-grade" computers.

**Comment by meteos77** [comment]
some time ago I built myself an arduino-based electric train control unit (DCC standard).
https://github.com/DccPlusPlus
it worked quite well, but I had to make choices due to lack of space -> no more train layout :-(

**Comment by textbrowser** [comment]
> some time ago I built myself an arduino-based electric train control unit (DCC standard). https://github.com/DccPlusPlus it worked quite well, but I had to make choices due to lack of space -> no more train layout :-(

That's super cool. You could. Train someone on Arduino. And, not to blow a whistle, but this creates a track of ideas.

**Comment by meteos77** [comment]
Careful! Modeling is as time-consuming as computing!

**Comment by meteos77** [comment]
Complex programs can be interfaced with arduino and the dccpp or dcc++ program.
for example: https://www.jmri.org/index_fr.shtml
and so lots of sensors/actuators are used to manage train traffic, lights ... sounds ...
for me, it was more fun to discover arduino this way.

**Comment by meteos77** [comment]
I just compiled glitch ... pff wonderful program!

**Comment by textbrowser** [comment]
Some of the double-click things must be remade for Android and some of the menus required special considerations. However! I don't have to rewrite it in Java or Kotlin. That's superb.

**Comment by textbrowser** [comment]
Batch Activities is now Ctrl + B.

**Comment by meteos77** [comment]
Great, thanks for the example: I've learned how to modify existing shortcuts with qtcreator. 
you need to find the right "object name" and place the desired shortcut.
example: actionBatchActivitiesBrowser -> in biblioteq_mainwindow.ui -> Ctrl+B (BatchActivities)

I've added
customQueryTool -> in biblioteq_mainwindow.ui -> F12 (Custom SQL Queries)
action_French -> in biblioteq_mainwindow.ui -> F1 (French Documentation)

However, I couldn't find the object name for the book search :(
isn't there an associated action?
action_book -> add book and not search

**Comment by textbrowser** [comment]
CQF is editable so you may configure your own shortcut without Designer.

**Comment by textbrowser** [comment]
What's the standard search shortcut? I will try adding it to the search tool. When activated, the tool's menu will become visible. I cannot add it solely to the Book Search category because the other searches would be ignored.

**Comment by meteos77** [comment]
The standard search is Ctrl+F, but we're only searching in the books category, so certain fields don't appear, such as "author" or "public".
This also allows us to have the same window between creation and search.
It's great because the shortcut table is updated.

**Comment by meteos77** [comment]
I'm looking to add "actions" for which you haven't activated shortcuts? 
such as customQueryTool or help in the current language.


Of course, the "Prefer" command is activated in F6 for me via the option/shortcut menu.

**Comment by textbrowser** [comment]
Closing. Completed some shortcuts.
