### ISSUE TITLE
Editing with a date widget.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#297]
I give you a feedback, people are not comfortable with computers. It was hard to find the % on the keyboard of a pi400.

No need to do more than 2 minutes of development, for that. It was the first contact with BQ.

From my observations: 
They expected to delete the entire date by selecting
YYYY-MM-DD then the delete key.

They tried changing the YYYY, then the month, then the day but as they were electing with the dash, it was blocking.

Knitting is more flexible than computers.

**Comment by textbrowser** [comment]
All date widgets or some?

**Comment by textbrowser** [comment]
The date widgets are standard and display dates in an ISO format. Nothing special about them. People need education on proper use.

The percent is an SQL wildcard symbol and most likely a standard.

**Comment by meteos77** [comment]
I have emphasized the % with many examples of research.

it was the 2 creation dates of the members

- Date of birth
- Expiration date

For the date widget, people will get used to it but Qt could propose to delete and validate all of them according to a YYYY-MM-DD or YYYY-MM-DD pattern.

**Comment by meteos77** [comment]
An idea came to me by default BQ writes as date 3000-01-01 :

in biblioteq_a.cc
`userinfo_diag->m_userinfo.expirationdate->setMaximumDate(QDate(3000, 1, 1));`

and
```
userinfo_diag->m_userinfo.expirationdate->setDate
    (QDate::fromString("01/01/3000", s_databaseDateFormat));
```

in biblioteq_b.cc
```
list.append("ALTER TABLE member ADD expiration_date VARCHAR(32) "
	      "NOT NULL DEFAULT '01/0/3000'");
```

**Comment by meteos77** [comment]
Can I put 2023 instead of 3000 without unexpected side effects?

**Comment by textbrowser** [comment]
Patron dates are displayed in ISO format.

**Comment by textbrowser** [comment]
Special Data
Dates are recorded in MM/dd/yyyy format.
ISBNs are recorded without hyphens.

**Comment by textbrowser** [comment]
In the documentation.

**Comment by textbrowser** [comment]
3000 is a year indicating that a patron's account does not expire. It's a default. May be changed.

I really don't understand the hangup here. The date is displayed in an ISO format, may be changed. The format in which a date is stored is documented. It all works.

Does not warrant a ticket. I thought there was a major problem.

**Comment by meteos77** [comment]
Not at all, I was surprised that you asked me for a ticket.

Thanks for all the explanations.
I will modify the sources to put a date of the current year.

**Comment by textbrowser** [comment]
Oh, you want a new default expiration year? Why does that need a change? Just change it when you add a new member. You're asking to change it for everyone. Another option for a default year is kind of unnecessary. It's just an year. Are you adding 10,000 patrons per day?

**Comment by textbrowser** [comment]
Will add a default expiration year somewhere.

**Comment by meteos77** [comment]
I don't ask for anything, I closed the ticket.

Initially it was to know if there was in the date widget a way to improve the input that is not "natural" for people in our library.

Once a cross more or less in the configuration of the widget and that can change the widget.

**Comment by meteos77** [comment]
The discovery of a software is a difficult thing because when you have followed the evolution from version 1 to version 100, the newcomers arrive little by little.

In this case, they have to discover some features to make the loans / returns work in a multitude of features.

They have the 100 possibilities directly in hand.

**Comment by textbrowser** [comment]
Natural? Some write from left to right and some from right to left and some from up to down and down to up. Natural? There is no natural way of doing things.

**Comment by meteos77** [comment]
natural: unthinking; mechanical; spontaneous; instinctive

When faced with the situation of changing the date, nobody had the reflex to choose the year because they had to change the three YYYY-MM-DD.

**Comment by textbrowser** [comment]
Amazing they're still breathing.

**Comment by meteos77** [comment]
You know they talked to me about knitting one day... I was completely over the moon :-)

**Comment by textbrowser** [comment]
Knitting -> practice.
Piano -> practice.
Walking and chewing gum -> practice.

Old timers like to think about the easy good old days without remembering that there were bad days and lots of failure.

**Comment by meteos77** [comment]
I am happy, the training went well.

They discovered BQ and were seduced by the interface.
The most gifted was in the BA interface to borrow/return.
Made some mistakes but found out which ones...
A good afternoon of training.

I think they will be up to speed in July on D-Day.

**Comment by textbrowser** [comment]
Adding a new tool next to the expiration date. End-of-year. Next-year. Some functions connected to the expiration date.

**Comment by textbrowser** [comment]
![bq](https://github.com/textbrowser/biblioteq/assets/10701156/e9751e88-cc7e-4526-8494-ecf5effd4c67)

**Comment by meteos77** [comment]
Thanks for the new feature : It's a great idea, the +year popup.

I will be gone for about 10 days, so no message from me :-)

Good continuation in your projects.

**Comment by meteos77** [comment]
On the BiblioteQ website, the link Donate (to sourceforge). 

message : "We are unable to make your donation. This organization's account is inactive."
