### ISSUE TITLE
SQL update; Bq update too many documents

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#299]
situation : I use BA/Discover.

1 - I scan the "Crime novel" row.
2 - "List Discover Item" button.
3 - The main table lists the scanned documents.
4 - I want to update the location to Mystery Novel (for these documents).
5 - An SQL UPDATE request is already created so I apply it.
6 - Disaster : I forgot to select the present table.
7 - BQ has placed all the documents in the database in "Crime novel".

Suggestion : Have an alert if the user doesn't select anything in the current table (forgot), BQ asks "Didn't you select anything ?" rather than applying the query to the whole database.

**Comment by textbrowser** [comment]
At the sqlite3 and psql prompts, I can delete all entries. It's my fault if I do it. If I'm the root account in Unix, I can wipe /etc. Still my fault.

If you don't select, you can specify specific items - modify the query.

There are ideas that you're going to have to actually think before executing a query. It's a custom query. New thinking. It's like when a pharmacist dispenses drugs. There are overrides in special circumstances. Or when you disengage safety for a process. There are no undos. You have to be careful. So be careful.

**Comment by textbrowser** [comment]
If I introduce a question, then it'll be displayed whenever. Are you sure? Are you really sure? Well, you see, you're in a special zone where it's assumed you have more awareness than a vegetable. Why ask?

**Comment by textbrowser** [comment]
I wish people had as much awareness as vegetables. I'm now insulting vegetables.

**Comment by meteos77** [comment]
I like pickles :-)

**Comment by textbrowser** [comment]
https://uxplanet.org/the-magic-of-flow-and-why-dialogs-frustrate-people-9408e08b7f3d

**Comment by textbrowser** [comment]
The point is. The software has verification in some places and not in others? I'm sure, absolutely, that you consider it inconsistent. It isn't. It assumes you have awareness in some places and are careless in others. It kind of strokes your ego. Makes you feel understood. Gives you liberty here and warns you there. It doesn't make you a child. Respects you.

Like a big person, you'll have to think differently and assume responsibility in life.

**Comment by meteos77** [comment]
Very interesting.

I was not 100% focused on the task because I was doing several things.

**Comment by textbrowser** [comment]
Don't cook.

**Comment by textbrowser** [comment]
Or use sharp knives. Why doesn't my knife warn me before slicing my fingers off?

**Comment by textbrowser** [comment]
And yes, I've always been grumpy. Was born that way.

**Comment by textbrowser** [comment]
Old timers. Actually even young timers. Every timer should play video games and notice how weird video games are in three-dimensional interactions. Worlds glitch. The interactions remain happy. What's the alternative to something that isn't natural to you? You make it yourself or you hate it. Too many silly criticisms of things make decreases value of people and their work. Bugs are bugs. One should have introspection when visiting a garden. Just because it isn't natural doesn't mean it's not a loved garden.

**Comment by meteos77** [comment]
I would like to know the definition of "old timers for you"?

**Comment by textbrowser** [comment]
Anyone who doesn't want to learn. So you could be a toddler with the mindset of a vegetable.

**Comment by textbrowser** [comment]
And people from the smart clubs and the general clubs adopt and worship the ideas of Google and Apple. Idolize them. F11 must do this because that is how Moses inscribed it in his commandments before he split Unix into BSD and Linux.

**Comment by textbrowser** [comment]
User experience has become ordained religion and my God is better than your God. If your software is orderly and there are signs of intelligence behind it, great. It's good. It has purpose and meaning. If it doesn't someone will love it regardless.

**Comment by meteos77** [comment]
Since there are personal computers, there have always been crazy fan clubs (I remember Atari/Amiga).

Brands have a vested interest in making their users captive. So the more ingrained the habits, the harder it is to change.
