### ISSUE TITLE
Can't document grey literature

### ISSUE THREAD

**Issue by AndrewM-** [textbrowser/biblioteq#3]
Grey literature is a term for technical reports such as Environmental Impact Assessments, which have not been published via normal publishers and which may be present in public libraries in small numbers.  The grey literature monkier hints at the fact these (key) documents have low visibility to  normal bibliographic services.   Can you please add a screen for documenting grey literature.  The key fields are authors (person & corporation), client, type of document, location (local government area/county), document title, and unstructured notes.

**Comment by textbrowser** [comment]
Sure. This will require a new category. I will attempt to start on it this upcoming week.

At least one database enumeration may be required to cover document types. The other fields that you mentioned appear to be free-form.

**Comment by AndrewM-** [comment]
There is usually a job number and document code as well.  I have looked long and hard for desktop document managers and they almost don't exist anymore.  I wonder what people in remote areas with low bandwidth are supposed to do.  There is no standardisation for document code or job number.  Thanks for putting the feature on the list.

**Comment by textbrowser** [comment]
Please review the below table definition. Some fields are required while others are not. Please correct if necessary.

CREATE TABLE grey_literature
(
	author		TEXT NOT NULL,
	client		TEXT,
	document_code	TEXT NOT NULL,
	document_title	TEXT NOT NULL,
	document_type	TEXT NOT NULL,
	job_number	TEXT,
	location	TEXT,
	myoid		BIGSERIAL UNIQUE,
	notes		TEXT,
	type		VARCHAR(16) NOT NULL DEFAULT 'Grey Literature',
);

**Comment by textbrowser** [comment]
Which field(s) should be used for unique constraints?
Thanks.

**Comment by AndrewM-** [comment]
That looks pretty good.  I have attached a couple of screen shots from my corporate document register.  The only thing that is missing from the field list above seems to be some kind of version status.  For example draft reports are released for public comment.  Add a document status field as a text field.  Leave out the not null constraint.  Location is ambigious, it could be the document location or the geographic location that the report relates to.  There may also be two document codes, the consultants document code and the clients library code.  

Cheers,

Andrew

![2015-12-31_documentregister](https://cloud.githubusercontent.com/assets/5060805/12061864/b7d046fe-afdc-11e5-94be-543d82e45255.png)
![2015-12-31_planregister](https://cloud.githubusercontent.com/assets/5060805/12061869/c3660a08-afdc-11e5-930e-3b01003e31df.png)

**Comment by AndrewM-** [comment]
The plan register is not flat, it is a parent-child relationship.  Just a note, I have found another product that satisfies my needs, it is a digital asset manager rather than a library manager so I will be putting my future efforts into that.  I will however help you finish this feature as it is important for your project.  There is a lot of overlap between the different categories of software and of the many applications I tested, yours came second in my list, even though it was off-center for my needs case.  Keep up the good work!

**Comment by textbrowser** [comment]
Very good. Below is the most recent table definition. As for the Plan Register, this appears to be specific to the application that you posted. A future release of BQ will cover per-item files. For example, one will be able to assign PDF files to book items. I could define a plan_register table. The table would have a one-to-many relationship with the grey_literature table (grey_literature being the parent). Let me know.

CREATE TABLE grey_literature
(
	author		TEXT NOT NULL,
	client		TEXT,
	document_code_a	TEXT NOT NULL,
	document_code_b TEXT NOT NULL,
	document_date	TEXT NOT NULL,
	document_id	TEXT NOT NULL PRIMARY KEY,
	document_status TEXT,
	document_title	TEXT NOT NULL,
	document_type	TEXT NOT NULL,
	job_number	TEXT NOT NULL,
	location	TEXT,
	myoid		BIGSERIAL UNIQUE,
	notes		TEXT,
	type		VARCHAR(16) NOT NULL DEFAULT 'Grey Literature'
);

**Comment by textbrowser** [comment]
Do you know if there is an ISO definition for grey literature?

**Comment by AndrewM-** [comment]
Sorry, I do not but Wikipedia suggests that some defacto standards may be in the process of being developed.  https://en.wikipedia.org/wiki/Grey_literature.  Regarding the plan register, I would ask a librarian how they handle this situation.  Plan registers are critical for consultants as several rather different designs can be produced as different releases under the same plan number.  I am not sure how libraries deal with these.

**Comment by textbrowser** [comment]
New type completed and should be ready in 2018.05.05.
