### ISSUE TITLE
Possible Bug?  "Unable to retrieve the data required for populating the main views."

### ISSUE THREAD

**Issue by mlamias** [textbrowser/biblioteq#302]
Hello,

I had been using a previous version of Biblioteq for years to manage my large, personal, statistics library.  I wanted to upgrade to the latest version of the software today so I downloaded [Version 2023.03.15 of Source code (zip).](https://github.com/textbrowser/biblioteq/archive/refs/tags/2023.03.15.zip), made a backup copy of my SQLlight database, and followed the instructions detailed in the attached Windows Installation document provided in the QT (being sure to install the recommended version of QT:  
[Windows Installation.pdf](https://github.com/textbrowser/biblioteq/files/11482563/Windows.Installation.pdf).

After successfully completing the install, I launched the program and I receive a message indicating that the database must be updated and it instructs me to use the "Upgrade SQLite Database" Utility under the Tools menu.  When I run the Upgrade utility, I see the following success messages:

```
Executing 2 statement(s).

1. CREATE TABLE book_conditions (condition TEXT NOT NULL PRIMARY KEY)

Statement concluded correctly!

2. CREATE TABLE book_originality (originality TEXT NOT NULL PRIMARY KEY)

Statement concluded correctly!
```
But then, when I try to run a query, I receive the following error message:

`Unable to retrieve the data required for populating the main views.`

The error logs display the following message:

`2023/05/15 19:05:17,Database Error,Unable to retrieve the data required for populating the main views.,no such table: photograph_collection Unable to execute statement,Source\biblioteq_b.cc,3449`

I'm attempting to move from version 6.58 of BiblioteQ to the latest version 2023.03.15.

Any idea how to resolve this?  

Thank you!

**Comment by textbrowser** [comment]
You're serious?

**Comment by textbrowser** [comment]
6.58 was released 11 years ago.

**Comment by textbrowser** [comment]
The repository version includes a new method of upgrading an SQLite database by executing all known upgrade statements. Two versions: All, Recent.

**Comment by textbrowser** [comment]
You can build it again or wait until the next release in June.

**Comment by textbrowser** [comment]
And your request has been asked before. It's very irritating. :P

**Comment by mlamias** [comment]
> 6.58 was released 11 years ago.

Yes.  Sadly, it's worked well for me since and I haven't upgraded.

**Comment by mlamias** [comment]
> And your request has been asked before. It's very irritating. :P

My apologies for the duplication.  Can you point me to the the question and answer?  Otherwise, I was thinking of simply exporting the data as a CSV and importing it.

**Comment by mlamias** [comment]
> The repository version includes a new method of upgrading an SQLite database by executing all known upgrade statements. Two versions: All, Recent.

Got it.  Thanks for your help.  I'll try and run the repo updates since 6.58.  I'll so try to be better about keeping up with updates.

Thanks again!

**Comment by textbrowser** [comment]
1. Create a new SQLite database.
2. Merge the legacy database via Tools -> Merge...

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/discussions/191

**Comment by mlamias** [comment]
> #191

Many thanks.  This is very helpful.  I appreciate the support and love this software!  I'll be better about upgrading in the future! ;-)
