### ISSUE TITLE
Default flags for enumerable values.

### ISSUE THREAD

**Issue by coldacid** [textbrowser/biblioteq#308]
It would be very helpful if one value out of each enumeration set could be flagged as the default value when opening (or resetting) the add item forms.

**Comment by textbrowser** [comment]
Splendid idea. :)

**Comment by coldacid** [comment]
If you don't mind the default values being client-side, I can probably whip up something reasonable this weekend storing defaults in the per-user BiblioteQ.ini file, although I'm not sure how far I'd get on the UI side of things.

**Comment by textbrowser** [comment]
![bq](https://github.com/textbrowser/biblioteq/assets/10701156/3462c6d6-71e1-4153-9f89-81f532001549)

**Comment by textbrowser** [comment]
The defaults are considered for **create** and **search** functions.

**Comment by textbrowser** [comment]
Completed and available in the next release!
