### ISSUE TITLE
Custom Template for Photo Collection

### ISSUE THREAD

**Issue by Strunge29** [textbrowser/biblioteq#309]
Hello, I work at a small library and wish to import our air photo collection to biblioteq. The current template does not aptly describe the fields and columns in our photo database. Is it possible to create a custom template to accommodate the fields in our library's air photo collection database?

for clarification, our collection database has the following columns:

 Roll_Number | Photo_Number | X_No | Y_No | Center_line | Height | Width |

I want to create a customized template that includes the above fields to store my photos. Can you show me how?

**Comment by textbrowser** [comment]
Which import are you referring to?

You can attach (import) images by first creating a collection and then importing the relevant images.

**Comment by Strunge29** [comment]
Thank you so much for getting back to me. I think my problem is more about creating the collection. Could you please tell me how I can create a customize collection? I assume this involves specifying the fields or columns for storing the metadata info of the images. Are there any resources/trainings/tutorials/ you could point me to learn how to create a customized collection?. The image/photo collection we have currently is not digital. They are print images. We check them out to patrons physically. I just will like to create a catalog for them in BiblioteQ to document them. And I want to use customize fields like I posted earlier to describe them. Please, I do hope I make sense.

**Comment by textbrowser** [comment]
Create a photograph collection and inspect the numerous fields. You should be able to map your fields to the existing ones.

**Comment by textbrowser** [comment]
Photograph collections are more appropriate for digital images. As you don't have digital data, consider grey literature. That's the umbrella category.

The sample SQLite file includes a grey literature entry.

**Comment by textbrowser** [comment]
Roll Number -> Code A
Photo Number -> Code B

The remaining under notes.

Only one copy is allowed per grey literature item and only that one item may be reserved by patrons. For instance, you would have one vehicle title. Or, a box of tax information. Or, a collection of physical photographs. You can get creative by creating multiple grey literature entries which are related physically and artificially in BQ. For instance, identifiers could be '2023-taxes:form-a' followed by '2023-taxes:form-b', etc.

**Comment by Strunge29** [comment]
Thank you so much for the clarification and also for taking the time to provide me some recommendations. I have taken a look at the Grey Literature template, and it just might suit my current needs - up to a point. 

If I may ask, given your recommendation to use the Grey Literature template instead, I take it that currently BQ does not offer any feature that allows users to import customized/ or create their own template they wish to use for special collections, especially in instances like mine where the default templates aren't adequate or suitable? If so, will you consider adding such a feature? I sincerely believe this could help small libraries like mine that rely heavily on your program. 

In the meantime, I will see if I can get creative and use the Grey Literature template to create the catalog for our air photo collection. I will report back later. Thanks

**Comment by textbrowser** [comment]
It's very difficult to create a blank category where clients may fuse into BQ. Why?

A. SQL revisions and the numerous custom and standard queries.
B. Integration of the category into BQ.
C. New interface class and source.
D. New search types.
E. Custom queries.
F. Print support.
G. Etc.

Creating a means of custom categories is not impossible, but is it practical? It would have to be limitless while not violating BQ. Where would the templates be stored?

Each category has much work into it because of uniqueness.

I would list the new category and / or the new fields of an existing category.

**Comment by meteos77** [comment]
Hello,
here's an idea: play with the translation of an unused language.

you take an unused language
translate the fields as you wish.
Use the language with a photo collection or grey literature.

Code A -> Roll Number
Code B -> Photo Number
See if the fields and their types are OK for your needs.
Also depend on whether you use BQ for other resources.

**Comment by meteos77** [comment]
![modification_langue](https://github.com/textbrowser/biblioteq/assets/56431039/d2332fb2-5a88-4c2b-93f6-de0f44306f8f)
In this case, it's easy to create another input/search mask using this method.

with custom SQL queries using the AS command, you can have the column names OK, but you have to juggle with the original field name and the actual data.

I think we can even rework the UI/biblioteq_greyliteratureinfo.ui file to redo the presentation (keeping all the boxes). On the other hand, the original appearance will be lost.
Another solution is to make 2 biblioteQ with the UI modification and one with the original one.


Thanks to texbrowser for BQ, which is quite flexible ; it's a lot of fun. :-)

**Comment by textbrowser** [comment]
What's happening with this?

**Comment by textbrowser** [comment]
Closing. Silent person.
