### ISSUE TITLE
Change installation directory.

### ISSUE THREAD

**Issue by avalanchemarramrat** [textbrowser/biblioteq#310]
`BiblioteQ-2023.06.06_powerpc.deb` installs files under `/usr/local`, which is against Debian tradition.

Also, creating a directory named `biblioteq` under `/usr/local` [violates the Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html).

> No other directories, except those listed below, may be in /usr/local after first installing a FHS-compliant system.

You must change the installation directory to `/opt/biblioteq`.

**Comment by textbrowser** [comment]
Let's first consider the fact that BQ is available in PowerPC. For sure, right?

'Locally installed software must be placed within /usr/local rather than /usr unless it is being installed to replace or upgrade software in /usr.'

**Comment by textbrowser** [comment]
You is welcome!
