### ISSUE TITLE
Sort "Read Status" column

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#321]
Question: 
I've just used the "Read Status" column for the first time.

Is it easy to program the sort on the "Read Status" column?
(Check / uncheck)
if 5 minutes I make the request if > 5 minutes I don't need it

sort "Read Status" column
![11](https://github.com/textbrowser/biblioteq/assets/56431039/51acc2ff-6267-436b-9a8b-51d4ca3ef9e2)

**Comment by textbrowser** [comment]
Completed.
