### ISSUE TITLE
SRU isbndb API

### ISSUE THREAD

**Issue by t-h2o** [textbrowser/biblioteq#324]
Hello !

Is it possible to add this **NOT FREE** [API](https://isbndb.com/apidocs/v2) from [isbndb.com](https://isbndb.com/) ?

**Comment by textbrowser** [comment]
How does I verify the resolution if the interface is not free?

**Comment by textbrowser** [comment]
Yah, will not be implementing this because it's at least $8 per month and that's limited. I would have to register and convince them this is non-profit but I don't want to pay.

**Comment by textbrowser** [comment]
Someone may implement it so we should remain it be open.

**Comment by textbrowser** [comment]
Thanks for the query.

**Comment by textbrowser** [comment]
Someone has to be paid for their work and that's the problem with software and data. Society needs access to truth but people must be paid for their work, the electricity to house the binary data, and it becomes complicated from there to list it all.
