### ISSUE TITLE
Barcode Scanner USE

### ISSUE THREAD

**Issue by Lib2GELKalyv** [textbrowser/biblioteq#33]
I would like to ask if I can connect a barcode reader on the BiblioteQ, if yes how

**Comment by textbrowser** [comment]
BQ doesn't contain a direct interface to such a device. The question has been asked several times. Perhaps a future Android integration would suffice.
Sorry!

**Comment by textbrowser** [comment]
Request added to Documentation/TO-DO.

**Comment by Lib2GELKalyv** [comment]
What do you mean?

**Comment by textbrowser** [comment]
There are some Android scanner applications. I prefer to integrate a common interface for scanning codes.
