### ISSUE TITLE
Reset fields in BA/Borrowing.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#330]
Small problem in BA/Borrow :

The "Discovered name" is deleted if we don't borrow any books.

on the other hand 

The "Name discovered" is not erased when the button is reset if we have borrowed a book.
(after the confirmation request window).

Thanks for the correction.

**Comment by textbrowser** [comment]
?

**Comment by textbrowser** [comment]
Done. :P

**Comment by meteos77** [comment]
![reinit-BA](https://github.com/textbrowser/biblioteq/assets/56431039/3dc6209b-ac66-4bfa-8e6a-75cc101f9ed8)

**Comment by textbrowser** [comment]
"Discovered Name is not cleared after Reset is pressed."

**Comment by meteos77** [comment]
Open ticket is immediately closed. Thanks again for everything
