### ISSUE TITLE
Search & Download Files Libgen

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/biblioteq#337]
https://wiki.mhut.org/software:libgen_desktop
https://github.com/libgenapps/LibgenDesktop
https://www.libgen.is/

**Comment by textbrowser** [comment]
BQ is a search engine and it can already manage files. Plenty of other download managers.

1. Download.
2. Create grey.
3. Attach.
4. Done.

**Comment by textbrowser** [comment]
And! One may create a beautiful Arduino program which downloads files and places them in a separate location accessible by another simple program which then creates BQ grey literature entries. As long as the proper format is followed, an automated machine is created. The insanity of endless requests is solved. The do-it-yourself paradigm replaces the do-it-why paradigm.

**Comment by textbrowser** [comment]
Or! There is software right now. Right now. In the present and near past, certainly in the near future which allow you to download files from the space, from nearly anywhere. Vessels and submarines and even on the backs of turtles. You just click and download and done. Then you have like a NAS or a script or another program populate PQ or SQLite and done again. Many, many, many solutions already exist. Nothing new required. Just a willing mind. Just a will. A will. A motion to move. An ambition. A desire to do.
