### ISSUE TITLE
Outdated Version # in biblioteq-debian/DEBIAN/control

### ISSUE THREAD

**Issue by yasbean** [textbrowser/biblioteq#338]
To anyone who wants to build the Debian .deb package, the Version # in the DEBIAN/control file is still 2023.06.06.

**Comment by textbrowser** [comment]
I don't maintain versions unless I produce release files. Needless work is needless. :)

**Comment by textbrowser** [comment]
When be a release, there be a new version. When there be no release, there be the last version of the last release which includes a release file.

**Comment by textbrowser** [comment]
And for those who wish to prepare their own release, they can locally revise their version accordingly. It's all sense.
