### ISSUE TITLE
Z3950 Unimarc Analyser: Fields Publisher / Place of Publication and Date (210 and 214)

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#343]
Status of Z3950 Unimarc analyzer **before 2019**
**test Z3950 BnF (France)**
_isbn13 : 978-2355-0442-98_

publisher and place of publication fields are filled in correctly
210$a -> Place of publication
210$c -> Publisher

date does not work because "DL" in front of it
210$d -> Publication date

Situation for Z3950 Unimarc scanner **after 2019**
**test Z3950 BnF (France)**
_isbn13 :978-2749-9349-83  ; isbn13 :979-1036-6069-77_

the fields Publisher and Place of publication and Date are not filled in.
214$a -> Place of publication
214$c -> Publisher
214$d -> Publication date

The standard has therefore evolved. Could you please add fields 214 to the analysis made by BiblioteQ for the addition of books by Z3950?
Thank you in advance.

**Comment by meteos77** [comment]
[u_b_210_update2019_online_final.pdf](https://github.com/textbrowser/biblioteq/files/13648307/u_b_210_update2019_online_final.pdf)

**Comment by textbrowser** [comment]
BQ downloads the data and you can copy and paste it into the fields. BQ can't adapt to infinite text possibilities as it doesn't have a programmable parser. One could be added and then the expectation becomes that BQ provides the parser too. The standard will always evolve and BQ cannot continue adapting to it. So, copy and paste is your best solution. I'll add a simple tool to other options. Simple and that's that. Beyond that, I won't be forever tweaking parsers. :)

**Comment by textbrowser** [comment]
I see the DL. Redesign! The $d field may include a c and that's proper. What's DL? Nonsense.

**Comment by textbrowser** [comment]
The issue with standards is that they are not standard. The date may be "2 0 0 2" and BQ will not comprehend it. See? It appears like it's valid. All of these variations require a strong regular expression.

**Comment by meteos77** [comment]
I understand that you can't foresee every crazy case.

What's surprising to me is that the Z3950 server specified is the service of the "French National Library", so it should follow the "standard norm" on its server.

**Comment by textbrowser** [comment]
Dates are now extracted super smartly without a regular expression. Discover the first 4 numbers after $d. Those must compose the date. Now, as BQ is super smart anyway and flexible (and I know most people do not know of this feature), you can modify the downloaded data and command BQ to parse it again. In a way, teach it to work with correct data instead of dictating the software to comprehend endless possibilities. So that's completed; the date.

**Comment by textbrowser** [comment]
![parse-me](https://github.com/textbrowser/biblioteq/assets/10701156/fe2e2200-dc90-4546-b76f-a347ac518198)

**Comment by textbrowser** [comment]
214 is totally new to BQ and requires new logic.

**Comment by meteos77** [comment]
I've just learned how to modify them directly in the Marc tag field :-)
it may indeed help, but why hide features (I didn't see anything in the doc)?

**Comment by textbrowser** [comment]
It's not hidden if you scroll. And I don't document everything because there are too many things.

**Comment by meteos77** [comment]
for 214, no need to modify, with the "new functionality" (writing in the marc tag area)
214 -> 210 Analysis button is therefore discovered Editor, and Place + Date

**Comment by textbrowser** [comment]
Almost done with 214.

**Comment by textbrowser** [comment]
Committed.

**Comment by textbrowser** [comment]
2014 works for books.

**Comment by meteos77** [comment]
Super, thanks for the modification : 210 and 214 work fine.

I know you don't like to touch the parser because it's repetitive programming, 
But as an end user, a program that with just the isbn + a click allows you to have all the information pre-filled is really GREAT!
With the favorite feature of enumerations for language and currency unit. 2 fields are automatically filled in.

**Comment by meteos77** [comment]
I hope they don't change the numbers of the fields  (constaments and that 210 -> 214 is an exception).

Your example is certainly usable for a simple user, as opposed to modifying the .cpp file.

The work involved in creating your language description seems enormous compared with the modifications you make to the .cpp file?

**Comment by textbrowser** [comment]
Yes, it will be more work now. But we must live in the present and in the future. Plan for the unknown.

**Comment by textbrowser** [comment]
Configurable software is a form of programmable software. Software which allows you to execute another language so that it can be configured is initially expensive but allows you to customize it according to the richness of the language.
