### ISSUE TITLE
 Z3950 Unimarc Analyser: Fields "Dewey Class Number" (676)

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#344]
BiblioteQ provides a field for deweynumber. The Z3950 Unimarc analyzer does not automatically fill the field.

can you please add the field 676$a in the analysis made by BiblioteQ for the addition of books by Z3950?
thank you in advance.

**test Z3950 BnF (France)**
978-2330-1032-31
979-1026-4030-81

**Comment by meteos77** [comment]
equivalent Unimarc - Marc21

![Unimarc-676_marc21-082](https://github.com/textbrowser/biblioteq/assets/56431039/f650d1e5-cee5-4a4b-95c8-c6b94d269630)

**Comment by textbrowser** [comment]
Yuck.

**Comment by textbrowser** [comment]
BQ needs supplements for future fields. So in other options I'm going to add a Z39.50 parser. Example: 676$a -> id.field. It's an easy mapping. I won't have to provide source changes in the future.

**Comment by textbrowser** [comment]
Will look after Dooble request.

**Comment by textbrowser** [comment]
Happy NY!

**Comment by meteos77** [comment]
Happy 2024 too. I hope your year is off to a good start

**Comment by textbrowser** [comment]
It's been an unhappy year so far. How about you?

**Comment by meteos77** [comment]
I wish you great personal improvement then.
a few years ago, i had a hard time starting a new year, and i found some help by coming across a book
"The power of emotions" by michelle larivey 9782761917025

I don't know if it's translated into English, but it helped me clear my head.

Good luck to you!

**Comment by meteos77** [comment]
On a positive note: We're very happy to be using BiblioteQ in our library. The volunteers are starting to master the basic functions, 
**Thanks to your determination to make BiblioteQ simple and highly effective! A BIG BRAVO!**

**Comment by meteos77** [comment]
I'm back from vacation ... I'm slowly getting back into computers
I saw that you had put a lot of points in the release note for 30/04/2024.
I'll have a look at BiblioteQ tomorrow or the day after. Thank you very much

**Comment by meteos77** [comment]
Magnificent, a new field filled in automatically!
It works well with my tests.

Thank you very much for this development.
