### ISSUE TITLE
External Tools :  enhancement with a personal toolbar via --special-executable.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#347]
I hope February will be better !

Currently, I'm running BiblioteQ with the automatic opening of the database and a number of external programs.

For ease of use, can we have an option that would add a --special-executable icon to a "personal toolbar"?

```
./BiblioteQ --open-sqlite-database $BIBLIOTEQ_CURRENT_SQLITE_FILE \
--special-executable $HOME/$BIB/09_lanceurplus \
--special-executable $HOME/$BIB/10_transfertPapyrusBiblioteQ \
--special-executable $HOME/$BIB/31_statistiques \

```
the icon path would be given via the --special-executale option (.png)

```
./BiblioteQ --open-sqlite-database $BIBLIOTEQ_CURRENT_SQLITE_FILE \
--special-executable $HOME/$BIB/09_lanceurplus,$HOME/$BIB/09_lanceurplus.png \
--special-executable $HOME/$BIB/10_transfertPapyrusBiblioteQ,$HOME/$BIB/10_transfertPapyrusBiblioteQ.png \
--special-executable $HOME/$BIB/31_statistiques,$HOME/$BIB/31_statistiques.png \
```

I don't know how much work it takes for you to do that?

Another solution I considered:
- I tried to do it directly in BiblioteQ :

- After declaring the icons in the icons.qrc file
- Modify the UI/biblioteq_mainwindow.ui file and add the actions.

I'm stuck here because I don't know what to do next
- declare the action
- link the button with the action

Thanks in advance

**Comment by textbrowser** [comment]
./biblioteq.sh --special-executable /usr/local/dooble/dooble.sh --special-executable-icon /usr/local/dooble/dooble.png

**Comment by textbrowser** [comment]
Completed.

**Comment by meteos77** [comment]
Super thanks for the modification.

I'll see how to rework my icons
