### ISSUE TITLE
Create a duplicate feature: Book Reservation. Exists with PostgreSQL.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#350]
Summary of the situation:
- Every month, we have a list of books to return to our central library.
- These books may be on loan from members.
- When they are returned, we would like BiblioteQ to display a message such as: "Attention, this book (Access number, Title, ISBN13) has been returned to the central library".

This is also the case if a book is requested by a member who has already borrowed it from another member.
In this case, we wait for the member to return the book and then put it aside until the next visit.
- When the requested book is returned, we would like BiblioteQ to display a message such as: "Attention, this book is reserved by member XXXX, put it aside".

Summary of request:
To be able to give a list to BiblioteQ and if a scan of a reserved book is made : BiblioteQ displays a warning message to the user.

**Comment by textbrowser** [comment]
"Has been returned." should be "Will be returned." That's because if some person has the book in their closet or shoes or stacked away in a sandwich, the book cannot have been returned to the central library. Right?

**Comment by textbrowser** [comment]
This is a splendid request for a many reasons. Let's think. Well, you think. Let's consider. What's more proper, consideration or thinking? I think we should think and consider. Sometimes ponder or dwell. Dwelling on a dwelling moment. OK, the rambling will stop. Perhaps for the next release. Since this is per copy, the copy editor should have a status of something indicating that the book is summoned by the centrality of central repositories.

**Comment by textbrowser** [comment]
We should also define a set of new potential status texts for items in the enumerations thingy. So much work. Beyond lost and deleted and available. Anything like summoned or eaten or sold or auctioned or gifted or lottery winner. Something positive or melancholy. Rivered or oceaned.

**Comment by meteos77** [comment]
Thanks for looking into this new feature.

It's true that if the book is stuck in a sandwich it "will be returned" later :-)

I'm not too familiar with the copy function as we only use one copy per book. So I'm discovering this one

I can see that you've been thinking about this for a long time, because with the interfacing you can change the status to "reserve" or "request".
it places the book in the right state and when it's returned, if the copy has the right keyword, a message is displayed.

I hope that the mechanism of the relationship between "status in copy explorer" and "return action" won't be too complex to develop.

**Comment by textbrowser** [comment]
Have not been thinking about it for a long time unless a few minutes is a long time which is for small entities free of time.

**Comment by textbrowser** [comment]
In PostgreSQL, notify() exists and with QSqlDriver, one may notify a client of any desired event. In your situation, another faraway BQ could be and would be modified if for example the status of a copy was modified. That's some interesting near-real-time bell.

**Comment by textbrowser** [comment]
This is already cleverly solved.
![bq](https://github.com/textbrowser/biblioteq/assets/10701156/f1bba498-3add-40ef-9b3b-43a9ec28c365)

**Comment by textbrowser** [comment]
A. Create custom query and label it descriptively.
B. Execute favorite whenever desired.
C. If results exist, action.

**Comment by textbrowser** [comment]
Background queries, separate tasks, are bothersome for many reasons. And popups are confusing and forgettable unless they're not modal. I suppose the Favorites system could include non-modal popups with special text, also configurable per query, if they return results.

**Comment by meteos77** [comment]
I started looking at the request to use the copy status:
`SELECT book_copy_info.status, title, author,callnumber, book_copy_info.item_oid AS CopyOidBook, book.myoid AS OidBook FROM book_copy_info INNER JOIN book ON book_copy_info.item_oid = book.myoid WHERE book_copy_info.status LIKE ('Rappelé')`

**Comment by textbrowser** [comment]
In the PostgreSQL universe, a book with a single copy can be requested by several people. As a librarian, the first request will receive the item. When the item is returned, the next patron receives the item. The librarian reads the All Requested category.

**Comment by textbrowser** [comment]
Popups after every action are annoying and require more options. The methods are present and are available as a process and not as a demand by the software.

**Comment by textbrowser** [comment]
And a popup after an item is returned is a popup even if the other patron isn't there to reserve the returned item so no one knows the significance of the popup. A reminder that is discarded.

**Comment by textbrowser** [comment]
And when the patron comes in a week after or a month or 6 months, the popup is gone and someone has to determine if they requested the item anyway. Should BQ popup everyday with a reminder? Nope.

**Comment by textbrowser** [comment]
This is a process thing not an infinite popup notification reminder until someone takes the copy thing.

**Comment by textbrowser** [comment]
The world is addicted to notifications.

**Comment by textbrowser** [comment]
Then you get a 100 books returned and have to set them aside because they may just be checked out. Nah, return them to the shelves and if the patron comes by, reserve them. Again, process. Keep around or not for a few days. How many? Where? All smells and tastes like process and not software.

**Comment by textbrowser** [comment]
Dysfunction is when you have a thousand sticky notes and nothing is getting completed. Yah, billions of notifications are lost and the software is now a noise generator. Do this and do that don't forget this and put this there and check this and go there and read that.

**Comment by meteos77** [comment]
For me, I saw this function as an exception rather than a noise generator.
Few books are marked as having to emit an alert and be set aside.

It's more like finding the needle in the haystack when it miraculously appears :-)

**Comment by textbrowser** [comment]
1. Book returned. A process in a big or little library will have a set-aside-in-case-reserved.
2. Librarian queries the item to determine if it's desired by anyone else.
3. Return to 1 or go home.
4. Home. Done.

**Comment by textbrowser** [comment]
Quiet software is nice.

**Comment by meteos77** [comment]
We'll do without this software feature, but for me, software can also help attract attention.

**Comment by textbrowser** [comment]
Attraction to it or warn you? BQ warns. But I consider this request a bit more. Even small laptop can house two BiblioteQ instances half-and-half. One for infrequent queries like All Requested. Item returned, let me All Requested refresh. Oh, best set this item aside. But OK, could be lots of requested and noisy. Is a valid request but also invalid because a process is still required. Set it aside? No, I'm an angry cheese, I return it to the shelf. Next person will have to find it. Process broken and BQ sad. Happy BQ instead rests.

**Comment by meteos77** [comment]
As well as being a programmer, do you write poetry?

**Comment by textbrowser** [comment]
No, I find most books boring and dull. Poems usually exist as written things so I don't like. I enjoy the complexity and brevity of video games. No, reading harms the brain. I did accept conclude maybe that education is salvation but it isn't. Some is if you're compassed for skill like being a plumber or nurse or teacher but then those are professions and should be prioritized. But other things are society needs for proper etiquette and normality. Although knowledge is nice to know. Best to know or be ignorant and the question doesn't need knowledge but thought and is approachable without education. Education is good for keeping people with something to consider but not through reading. Writing better. Writing about anything because that's what thinking does. Poetry is skimming and conciseness horizontally but not necessarily vertically and without rhyme it doesn't do so well. Is a poem required to have a resonance. Music without rhythm is fine too without many conditions. So onto poems, not. They are too brief and emotional. They're instructional for those who fancy cerebral nonsense.

**Comment by textbrowser** [comment]
Maybe by the end of May for LTS releases. :)

**Comment by meteos77** [comment]
This is a "bonus" feature request, so enjoy the development and we'll be happy when it's ready.

**Comment by textbrowser** [comment]
This is really easy to complete for PostgreSQL. For SQLite, this is a lot of work.

**Comment by textbrowser** [comment]
I think you should migrate to a local PQ database. PQ can be local and or remote. It would be complete, this request. I can help or we can work together on a migration from SQ to PQ.

**Comment by meteos77** [comment]
Thank you for your offer to help us switch from SQ -> PQ.

For the moment, we are not ready to switch to PQ. The .sqlite file offers simplicity of management (backup, transfer to other machines, my developments with python).

We've known from the start that we don't have all the possibilities of BiblioteQ with Sqlite.
Our knowledge of computers and our available time are constraints.

If the function is too energy-intensive to develop for .sqlite to close the tocket, we'll continue with paper/pencil to do the job :-)

Translated with DeepL.com (free version)

**Comment by textbrowser** [comment]
It would be duplicating a function and database tables. Like is already done because it was logical but now it would be done for an engine which is meant for personal databases not institutions.

**Comment by textbrowser** [comment]
Like imagine Google database was SQLite.

**Comment by textbrowser** [comment]
And you want to add functions to network it or make it appear that it serves a concept of multi-person (as in this example). You wouldn't do that. You'd switch to a multi-person database. Like imagine you are a single-person account on a multi-person computer and you circumvent that by allowing multiple people on your account and then request Linux Mint people to have multiple people on your single account. They would say what? Problem already solved. Is you the problem.

**Comment by textbrowser** [comment]
So yes this is a request which is illogical people small libraries should use local PostgreSQL because it provides a different paradigm than a personal library. A friend borrowing your item would not have you remember digitally that another friend is borrowing same item and if that was possible you would initially conclude that your configuration is incorrect so you would return to the selection process and ponder. Yes, I best select PQ even though I'm an an individual but perhaps I lend to many people because I have many books; maybe I'm a hoarder or discovered a hidden library or a huge donation so now you're a little librarian and SQLite is not logical.

**Comment by meteos77** [comment]
I'm well aware that we're taking an original approach.
If we followed the logic of the world, our library wouldn't exist.

The municipality would have to create a job for a librarian, have a contract for adapted computer support and buy the necessary equipment. Volunteers wouldn't just be there to help the library staff.
Unfortunately, our settlement area is not dense or wealthy enough to have this kind of structure. So 9 people are trying to keep a "volunteer" library going with their time and skills.

**Comment by textbrowser** [comment]
By that logic, I should rewrite BQ in Python because only Python is available on a system. That's something else.

**Comment by textbrowser** [comment]
If one asks something and that something exists in a form - a concluded process - but desires it in another form - a form not suitable for that something - than one must re-consider their original desire. I would like pink platform shoes but all platform shoes are black. I would like you to restructure your factory for this one request. Everything, do it again.

**Comment by textbrowser** [comment]
The request is really, really completed. Ask SQLite to become a network database. Really, that's the request. Is done. But is not done with how I do it. But is done, done. Well, not done for me. But for you, I need to create a new pencil. You have all these pencils and only one pencil for you. Why not change your imagination - enhance it - to work for these pencils?

**Comment by textbrowser** [comment]
There proper title of request. Now I can read it many times pondering my life decisions.

**Comment by textbrowser** [comment]
:)

**Comment by meteos77** [comment]
No worries, I understood you correctly, I told you to close the ticket.
If we want the functionality, we need to switch to the PostgreSQL version.

**Comment by textbrowser** [comment]
So SQLite is a non-patron database because anyone can access it. You, a friend, me, GitHub. How would an item request work? Like who puts in the request? How do you see requests of a patron because you don't log in so you'd see all of them. How do you cancel? There are some files which could be modified for this, plus maybe another table, but the concept may not work.

**Comment by meteos77** [comment]
I have the impression that my initial request has not been properly understood. Perhaps my explanations were poor or the translation impressive?

If I had to program my request, I would have done something like this:

- when opening BA/Return, BQ establishes the list of documents positioned as searched in the copy browser or in a separate list (simple text file).

At each scan with the handheld BQ makes the comparison between the barcode entered/scanned and the list of documents searched -> if found then BQ emits a message to the user.

As I don't have your technical analysis and programming talent, I can't make a concrete proposal in C++ :-)

**Comment by meteos77** [comment]
I have the impression that you want the registration to the new borrower to be completed as soon as the document is returned?

**Comment by textbrowser** [comment]
In PQ world. A patron requests an item and a librarian fulfills the request whenever the item is available. The patron may also cancel a request if it hasn't been fulfilled. There may be other requests for that item and the librarian should fulfill the newest request.

1. Patron requests.
2. Librarian fulfills.
3. Patron visits library and fetches item.

1. Patron requests A.
2. Patron requests A.
3. Librarian fulfills #1.
4. #1 returns and librarian sets aside A for #2.

Is very simple process.

**Comment by textbrowser** [comment]
The process you just described is very complex because it now requires a file somewhere.

**Comment by meteos77** [comment]
Forget it, if it's too complicated, our current method works quite well.
- I make an image with the desired covers.
-
![RETARDS_PERDUS](https://github.com/textbrowser/biblioteq/assets/56431039/8306dc64-4c20-4e43-b7df-f6363eda335d)


During the returns, the volunteers' memory helps to find documents.
And we search the shelves from time to time to see if we've missed any.

**Comment by meteos77** [comment]
Tomorrow, we have a large delivery of 750 documents ... a bit of work for BiblioteQ :-)

**Comment by meteos77** [comment]
One last idea ...
when returning documents, the display is positioned in the “All borrowed” category.

In this display format, overdue books are highlighted in red in the “Deadline” column.

Could we have a “to be defined” color on the title or on the barcode to indicate that the book is wanted?

**Comment by textbrowser** [comment]
I do not understand the request because in SQLite a desired item cannot be labeled as such. SQLite does not offer requests. Something is available or has been loaned.

**Comment by meteos77** [comment]
In the copy explorer, we can change the status of the copy.
When I specify status recalled (Rappelé en français), it means that this loan is recalled for another person or entity (central library).

![Explorateur_de_copies_Statut](https://github.com/textbrowser/biblioteq/assets/56431039/11872aa6-2d07-48a8-9329-21fd6622c294)

**Comment by meteos77** [comment]
With this SQL query, I can see which books are marked as “Recalled”.

`SELECT book_copy_info.status, title, author,callnumber,accession_number, book_copy_info.item_oid AS CopyOidBook, book.myoid AS OidBook FROM book_copy_info INNER JOIN book ON book_copy_info.item_oid = book.myoid WHERE book_copy_info.status LIKE ('Rappelé')`

![Liste-des-rappelés](https://github.com/textbrowser/biblioteq/assets/56431039/d5ef4bb3-1242-4482-931a-39f70d0f60f9)

**Comment by textbrowser** [comment]
> One last idea ... when returning documents, the display is positioned in the “All borrowed” category.
> 
> In this display format, overdue books are highlighted in red in the “Due Date” column.
> 
> Could we have a “to be defined” color on the title or on the barcode to indicate that the book is wanted?

https://github.com/textbrowser/biblioteq/issues/369

**Comment by textbrowser** [comment]
This works on the main table only. For a column title and a cell text, the color is applied to that cell (or multiple cells). Custom queries are not complete. Once they are, you could include a count or a status and specify in this configuration the name of your column title (like 'status') and the cell text and the cell(s) would be highlighted.

**Comment by textbrowser** [comment]
The text you provide must be identical to the cell text and column title.

**Comment by meteos77** [comment]
Great job, thanks for this nice customizable feature.
I'm going to test this new feature to see what it can do for our searches!

Can we have the "status" column in the query that allows books to be returned from BA/Return?

**Comment by textbrowser** [comment]
> Great job, thanks for this nice customizable feature. I'm going to test this new feature to see what it can do for our searches!
> 
> Can we have the "status" column in the query that allows books to be returned from BA/Return?

I don't know until I see the amount of complexities.

**Comment by textbrowser** [comment]
Reviewed and declined.

https://github.com/textbrowser/biblioteq/issues/370

Explanation there.

**Comment by meteos77** [comment]
After a few holidays, I'm glad to see you again.

I haven't managed to get the alert to work yet?

**Comment by textbrowser** [comment]
Done done.

**Comment by meteos77** [comment]
Thank you very much for this new feature for users of BiblioteQ sqlite version.

I tested it:
It works well with ISBN-10.
With ISBN-13, the message doesn't arrive (problem with all new books in 979-xxxx-xxxxx-x because they don't have an ISBN10).

Can you also search for ISBN13?

Thank you in advance

**Comment by textbrowser** [comment]
Does the return work? Not the question, the return. Does it work?

**Comment by textbrowser** [comment]
Yup, it does.

**Comment by textbrowser** [comment]
Done done ^ 3.

**Comment by textbrowser** [comment]
I need to see your string and your numbers which are reserved. If you have a string in 10 and a reserved in 13 of 979 it cannot be converted from 10 to 13 979. Details matter. Don't know what you're doing. And cannot convert.

**Comment by textbrowser** [comment]
If you have a 979 it cannot be a 10-digit and if you have 10-digit in your string it will not work because it cannot be converted. Mixing everything will not work. Have a 979, put a 979 in your string.

**Comment by textbrowser** [comment]
It's messy again. I dislike all of these reminders. Adopt PostgreSQL!

**Comment by meteos77** [comment]
Thank you for looking into my problem

In the example provided, I have 3 books on loan
the 2 books in 978.... work

the book Humus which is in 979 does not work
of course I filled the field with 979.... for this book

**Comment by textbrowser** [comment]
See commit and notes.

**Comment by textbrowser** [comment]
Does not work because 13 to 10 results in empty because 979 is new and illogical in the world of 10. Notes describe revision.

**Comment by textbrowser** [comment]
Now try.

**Comment by meteos77** [comment]
As far as I'm concerned, this doesn't change the result.

**Comment by textbrowser** [comment]
Because it's broken. I solved this like 20 years ago. In PQ, an item is not forced into its identifier. So the identifier can be corrected or modified without requiring the entire relationship to be modified. How? Object identifiers in the database. A beautiful relationship is mandated because of them. Now because you require SQLite, which I solved 20 years ago, a 979 does not exist in 10; and ISBNs exist for humans and not databases. So when an item is returned, the database cannot process a 10 which does not exist from a 979 so it does the logical thing; object identifiers. Always defined, always proper, always relatable. Again, solved 20 years ago. Cannot put an object identifier in Other Options because humans do not comprehend numbers. However, when an item is returned now in SQLite, I have to locate it magically through a machine of values which do not exist. None of this is logical nor meaningful. It adds nonsense. Anyway, maybe it will require modifying the entire program so that one person can have a reminder while some things will break. Jesus.

**Comment by textbrowser** [comment]
I need the stop sign to be black because red is bloody. But sir, millions will die! I am prepared for millions to die because red is bloody.

**Comment by textbrowser** [comment]
I don't understand!

**Comment by textbrowser** [comment]
And I have to verify this reminder in 3 places. One in Batch Activities. One in the respective item. One in the main table. I be about to quite BQ and become an inspect farmer.

**Comment by textbrowser** [comment]
I already spent 6.5 hours on this plus before. What the heck am I doing?

**Comment by textbrowser** [comment]
Out!

**Comment by meteos77** [comment]
Thanks for the technical explanation.

As I understand it, this was the original mistake made by the creators of ISBN10 ... they hadn't planned for a sufficient number for all future publications.

they did it again with ip v4 and ip v6

You had nothing to do with it, and thanks for BiblioteQ.


Insect breeders ... maybe our future steack :-)

**Comment by meteos77** [comment]
Forget it, we'll settle for 978

**Comment by textbrowser** [comment]
The project is 99% completed. Well, it's your fault you listened to me. I was kidding. :P

**Comment by textbrowser** [comment]
Doesn't work for any book without optional ISBN. Ha!

**Comment by textbrowser** [comment]
But it does work with PQ because PQ isn't forced into exceptions for a single person in the known universe.

**Comment by textbrowser** [comment]
Accession numbers are optional.

**Comment by textbrowser** [comment]
Will only work with OID field but that is never shown and I'm not about to show it for this request. Many optional fields which is really nice and because PQ solves this with actual relationship, I didn't have to do any of it in SQLite. SQLite is made for small data. The concept of the concept of requesting items in a personal database is meaningless. It's like adding a virtual card catalog to your house for patrons which don't exist. If you want that, invest in the world of PQ. If you want Windows, invest in Windows. I want Windows so I'm going to harass Linux to make it Windows.

**Comment by textbrowser** [comment]
My little brain sploded right now because I spent days in this but it has exceptions like missing ISBNs and 979 and 980 and 1,000,000. All this avoided with a proper database but you don't want to invest in it and I have to spend my time now which is spent and never recovered and the problem is only 99% solved and have to add reminders to remind people of the reminders that there are exceptions. Jesus.

**Comment by textbrowser** [comment]
Reminder of reminder added.

**Comment by textbrowser** [comment]
979 proper from here now.

**Comment by meteos77** [comment]
First of all, thanks to the little users of BiblioteQ SQ for the better features!
We manage our library (50-60 members and 4800 books) with BiblioteQ thanks to you and to all your developments for the sqlite version since 2 years.
-> We're only 99% satisfied :-)

My decision: I won't bother you anymore with BiblioteQ SQ until I've tried to make BiblioteQ PQ version work.

**Comment by textbrowser** [comment]
There is often a crazy idea that open source is democratic. It's not. It should not be. It cannot be. If one individual consistently insists that their requirements to revolutionize some software, any software, into their liking through consistent requests is actually a form of dictatorship. Open source isn't my-way-or-the-highway. Open source is more like an ecosystem. And sometimes, in such places, there are losers. One distinction, a very important one, between open source and proprietary is choice. Don't like BQ? Use something else. Don't like Windows? Well, you're screwed if you have to use it.

**Comment by textbrowser** [comment]
We is not bothered. And continue SQLite. Tickets which replicate a solution are not good because they don't build new ideas and they don't solve new things. They create headaches and repetition.

**Comment by textbrowser** [comment]
Imagine I ask you to write the same exercise on 3x+1 problem in French and the in English using good translations without introducing new approaches or ideas or criticisms. Maybe first time you excited and then I ask you to write same paper in Ukrainian. OK, you less excited. So I go with Finnish and then Laotian and then whatever. Pretty soon you go bonkers and tell me to buzz of. You not learning, you repeating like a school boy. And Jack and Bart writing nonsense on the infinite chalk.

**Comment by textbrowser** [comment]
I know wealthy people who eat pasta for last 50 years and not because they have to eat pasta. They rich and greedy and think the money will go to their death. I think they're insane. So, I don't eat pasta everyday. Life requires diverse else we automatons and I know I not an automaton.

**Comment by meteos77** [comment]
You offer 2 database systems for BQ (SQ and PQ).
As a user, I chose “BQ SQ” for its ease of use and configuration.

So I can ask for duplicate features, because if they're only implemented in BQ PQ, I don't know about them.

Then, as usual ... mountain or coline, time spent, interest for you are always the criteria for developing requests.


As mentioned above, BQ SQ more than meets our current needs. Requests for new features are therefore already listed in TO-DO. or in our past exchanges.


I'm not yet familiar with the BQ PQ version.
For info:  configuring PQ is not straightforward, despite the Administrator-Guide.pdf document.
I'd be delighted if some kind soul could add some clarification to this documentation.

PostGreSQL doc version 16 = 3182 pages :-)

**Comment by textbrowser** [comment]
Repetition is for practice.
