### ISSUE TITLE
Z39.50 greyed out.

### ISSUE THREAD

**Issue by yasbean** [textbrowser/biblioteq#356]
When adding a new book title, the Z39.50 search button is greyed out.

Linux: Debian Bookworm, amd64.
![image](https://github.com/textbrowser/biblioteq/assets/13955470/2c53d1bf-f9b5-49f9-b72e-5ec9fd08114b)

**Comment by textbrowser** [comment]
#ifndef BIBLIOTEQ_LINKED_WITH_YAZ
  id.z3950QueryButton->setEnabled(false);
  id.z3950QueryButton->setToolTip(tr("The YAZ library is not available."));
#endif

**Comment by textbrowser** [comment]
SRU is better than Z39.50.

**Comment by textbrowser** [comment]
Did you compile it yourself? If so, that's a problem. If not, I did not compute correctly.

**Comment by yasbean** [comment]
I did compile myself. This is today's release. I will continue to investigate and report back.

**Comment by textbrowser** [comment]
sudo apt install libyaz-dev

**Comment by textbrowser** [comment]
It is nice right? The software includes information and depicts functions which are not available. Some software or most has options which are not available and you don't know the cause so you have to wonder many days and sometimes weeks or don't wonder at all because.

**Comment by textbrowser** [comment]
Take care.
