### ISSUE TITLE
Date format configuration interface and Translation.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#357]
We don't touch the date configuration often so it's not a problem just feedback.

I have the impression that the translation has an influence on the configuration in the date format display (in fact the position in the menu).

To change the presentation of the books, I have to edit the music CDs.

If I modify the books via the UI, the photographic collection is modified.

![Interface_Config_Date](https://github.com/textbrowser/biblioteq/assets/56431039/7395e8c2-3785-4ced-a734-6d0a68ceca78)

**Comment by textbrowser** [comment]
Pls. add you INI here. The data format literals are not translated (not surrounded by tr()).

**Comment by meteos77** [comment]
[BiblioteQ.ini.txt](https://github.com/textbrowser/biblioteq/files/15013377/BiblioteQ.ini.txt)

**Comment by textbrowser** [comment]
Availability colors table is incorrect too. Maybe.

**Comment by textbrowser** [comment]
Translating software is impossibly difficult.

**Comment by meteos77** [comment]
We don't touch the date configuration often so it's not a problem just feedback !
I understand the difficulty.

Colors ... not yet discovered because we only have books.

**Comment by textbrowser** [comment]
Try again.

**Comment by textbrowser** [comment]
Qt::UserRole is a neat method of storing hidden data. I ignored my cleverness and recorded the values as they exist; neglecting that they may be sorted.

**Comment by textbrowser** [comment]
This was not a problem because a previous release introduced sorted columns.

**Comment by textbrowser** [comment]
June 6, 2023.

<li>Enable sorting for table widgets in Other Options.</li>

**Comment by textbrowser** [comment]
The detailed release notes are very important for historic concepts because GH and git require that you elaborate your commits and if you do not you must review the revisions which can be quite impossible without vast time and memory.

**Comment by textbrowser** [comment]
I did remember that I enabled sorting and the Qt::UserRole was for that very purpose but I didn't percolate the sorted idea into the save instructions. Now you see it because no one else cares about it. So I publish release notes for people to review but they won't because carelessness and such.

**Comment by meteos77** [comment]
It's working well now.  I have no doubt that you are very organized in your developments ... 

I read the release notes but I don't really understand them all :-)

**Comment by meteos77** [comment]
I'm always impressed by how quickly you correct things.
SUPER BRAVO !

**Comment by textbrowser** [comment]
Availability colors also corrected: Other Options -> Main Window. It's a sort thing.

**Comment by meteos77** [comment]
According to my tests,  Color availability not corrected.
strange behavior: if the Show Table / View Images option is checked, the colors are not the same.

right BiblioteQ.ini file
![color-dispo](https://github.com/textbrowser/biblioteq/assets/56431039/6f076021-580a-4416-96ff-1895de72b0d7)

**Comment by meteos77** [comment]
If I save with the English interface, everything returns to normal.
![color-dispo_EN](https://github.com/textbrowser/biblioteq/assets/56431039/81eea8aa-902e-4dc8-9ed7-56b10fb14033)

**Comment by meteos77** [comment]
https://github.com/textbrowser/biblioteq/assets/56431039/9c8c432a-08dc-4bca-b01f-60bfaee5cc79

**Comment by meteos77** [comment]
I hope this helps. For me, there's nothing very urgent about this problem.

**Comment by textbrowser** [comment]
> According to my tests, Color availability not corrected. strange behavior: if the Show Table / View Images option is checked, the colors are not the same.
> 
> right BiblioteQ.ini file ![color-dispo](https://private-user-images.githubusercontent.com/56431039/323663828-6f076021-580a-4416-96ff-1895de72b0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjcyMTcsIm5iZiI6MTcxMzQ2NjkxNywicGF0aCI6Ii81NjQzMTAzOS8zMjM2NjM4MjgtNmYwNzYwMjEtNTgwYS00NDE2LTk2ZmYtMTg5NWRlNzJiMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE5MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTVkMjM4MGU1ZDdmNmM0MGZhM2JjMjhlNDU2YzZhNmY2ZDdhNDg4MTIwZDk3MmI5ZmI4MzUyZDI0NjBiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-qtIJ0b26xxKt6S_5W1C1CB4lZb6zJPjCtxII_xriw)

Did you pull the newest commit? I cannot replicate this problem in English and in French. Other Options is fine. Main window is fine.

**Comment by textbrowser** [comment]
> According to my tests, Color availability not corrected. strange behavior: if the Show Table / View Images option is checked, the colors are not the same.
> 
> right BiblioteQ.ini file ![color-dispo](https://private-user-images.githubusercontent.com/56431039/323663828-6f076021-580a-4416-96ff-1895de72b0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzM0MTgsIm5iZiI6MTcxMzQ3MzExOCwicGF0aCI6Ii81NjQzMTAzOS8zMjM2NjM4MjgtNmYwNzYwMjEtNTgwYS00NDE2LTk2ZmYtMTg5NWRlNzJiMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIwNDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5N2M0ZGZjMWE0YjNjMTRjNTVkMjc3YzNhY2VkNWViNmU4YzI4YjJmMzQ4ZTg5ZDg1ODBhNTE3MDQwOTE4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dm9sXDN4KIq3vVy7UOUc2rPmR48NMWlUZ_mUvz_nu78)

I removed Latin-1 conversions. I would see a color as "=QByteArray()" in my INI.

**Comment by textbrowser** [comment]
You have "=#...".

**Comment by meteos77** [comment]
Everything works perfectly, Thank you very much for BiblioteQ!

**Comment by textbrowser** [comment]
Please create tickets for incomplete items which you've mentioned and require.
