### ISSUE TITLE
Color configuration interface for availability and translation.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#358]
with the French interface, color is not put in the right category.
![color-dispo](https://github.com/textbrowser/biblioteq/assets/56431039/e2d0dc95-893a-4094-9f20-611a4e0484ad)

If I save with the English interface, everything returns to normal.

![color-dispo_EN](https://github.com/textbrowser/biblioteq/assets/56431039/bfb6f003-da3b-42cf-84a2-587bebfe6f69)

**Comment by textbrowser** [comment]
This is what I see.
![bq](https://github.com/textbrowser/biblioteq/assets/10701156/a181d3f0-4014-4848-b6b9-156b4b8eb683)

**Comment by meteos77** [comment]
The problem was solved yesterday, you asked me to open tickets for regularization :-)

**Comment by textbrowser** [comment]
Oh. I was requesting new-new tickets. Never mind then.
