### ISSUE TITLE
Using biblioteq on multiple computers with synchronicity 

### ISSUE THREAD

**Issue by ajibs2x** [textbrowser/biblioteq#36]
Hello, 

Can someone please help me by giving me a step by step instructions on how to get biblioteq synced on the same database for two computers? I have about 5,000 books and that will drive me crazy if I don't get help. A friend is willing to help me but I don't know how to synchronize the computers. I have been able to install it on each computer and they are working fine individually. 

Please someone should just help me come up with a solution or the best way to make it work.

**Comment by textbrowser** [comment]
https://sourceforge.net/p/biblioteq/feature-requests/49/
