### ISSUE TITLE
Database Enumeration / Location and Translation

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#360]
Version of 2024-03-25 locations had translation in place  and book search OK

![2024-03-25_enumeration_OK](https://github.com/textbrowser/biblioteq/assets/56431039/954cb204-b8eb-40e5-b203-c1ef60a72af6)

-----------------------
With today's version: "Book" has replaced "Livre" for enumerations already created
![2024-04-20_enumeration_KO](https://github.com/textbrowser/biblioteq/assets/56431039/88c4934b-c3e3-434b-a9f0-d55d1c7c90f4)

-----------------------
But if we add a location then "Livre" appears in the enumeration 
![2024-04-20_enumeration_TEST](https://github.com/textbrowser/biblioteq/assets/56431039/94ae4323-59d0-4a45-8357-accc683d4ee9)

-----------------------
One consequence is that it doesn't appear in the book search enumeration.

-----------------------
Can you take a look at this feature
Thank you in advance !

**Comment by textbrowser** [comment]
Did you translate Source/biblioteq_dbenumerations.h?

**Comment by textbrowser** [comment]
My successful test:
1. Add a new location for book.
2. Open a new book search.
3. I see the new book location.

My successful test if I ignore the reminder:
1. I open a book search.
2. I add a new book location in DEB.
3. I do not see the new book location in my existing book search. Normal.

**Comment by textbrowser** [comment]
I could propagate changes in one panel with other panels. However, it would create more confusion if values disappear in existing windows because something was changed in other windows. You have to decide the priority of states. One thing has been created and it has this state. Another thing was created afterwards and that is the newest state. Should older items now include the new state?

**Comment by textbrowser** [comment]
The Locations thing in DEB includes item delegates, replacing the older combination boxes. There's an item in the release notes describing the revision. Essentially, it corrects a strange Qt warning and item delegates are friendlier on resources. You'll need to translate new tr() instances.

**Comment by meteos77** [comment]
I'm well aware that the search panel must not be open to take the changes into account.

in Source/biblioteq_dbenumerations.h the book values are in English.

Version 2024-03-25 works fine, the value "book" was translated into "livre".

Now: when I click on the plus icon (+), the value translated as "book" appears, whereas older items have the value "book".

**Comment by meteos77** [comment]
French version
https://github.com/textbrowser/biblioteq/assets/56431039/189a7384-5086-4c0f-96f2-3a277f80354a

**Comment by meteos77** [comment]
English version

https://github.com/textbrowser/biblioteq/assets/56431039/e01e4e09-6d6f-4888-a662-56f6495de0b5

**Comment by textbrowser** [comment]
> I'm well aware that the search panel must not be open to take the changes into account.
> 
> in Source/biblioteq_dbenumerations.h the book values are in English.
> 
> Version 2024-03-25 works fine, the value "book" was translated into "livre".
> 
> Now: when I click on the plus icon (+), the value translated as "book" appears, whereas older items have the value "book".

The file Source/biblioteq_dbenumerations.h includes new tr() instances which are not included in the TS file.

**Comment by textbrowser** [comment]
Committed a translation run.

**Comment by textbrowser** [comment]
```
<context>
    <name>biblioteq_dbenumerations_item_delegate</name>
    <message>
        <location filename="../Source/biblioteq_dbenumerations.h" line="109"/>
        <location filename="../Source/biblioteq_dbenumerations.h" line="127"/>
        <location filename="../Source/biblioteq_dbenumerations.h" line="128"/>
        <source>Book</source>
        <translation type="unfinished">Livre</translation>
    </message>
```

**Comment by textbrowser** [comment]
If you translate book as livre, Qt does not translate every new occurrence. You need to execute lupdate and lrelease and possibly run the Qt Linguist.

**Comment by meteos77** [comment]
For me the translation is good (done as usual). everything is in green?

![linguist_OK](https://github.com/textbrowser/biblioteq/assets/56431039/5a8d7fca-8c2f-4096-a3ae-86ea4c186242)

**Comment by meteos77** [comment]
TEST in EN language
TEST2 in FR language
![enumeration_SQL](https://github.com/textbrowser/biblioteq/assets/56431039/853c3be8-7b37-44b4-abbf-03e90327a7bf)

**Comment by textbrowser** [comment]
Moving from language to language will not translate database values.

**Comment by textbrowser** [comment]
You'll need a current French translation and remain in the French language. If you mix things, you'll see mixed results.

**Comment by meteos77** [comment]
Ok so I'll start from scratch and let you enjoy a great weekend.

We'll take stock once I've checked everything again.

Thanks for your time.

**Comment by textbrowser** [comment]
Delete your weird Locations first. Then pull the latest source. I updated the translation files via lupdate and lrelease. Then add new locations in your French locale.

**Comment by meteos77** [comment]
BiblioteQ updated and recompiled.

By default the plus sign (+) but the French value "Livre" is not working in the search.

With the popup I place the untranslated value "Book" and it's OK for the search.

If in linguist I translate "biblioteq_dbenumerations_item_delegate" "Book" by "Livre" ... it doesn't let me put Book anymore.

Should the pop-up display be in French, but the database entry in English?

**Comment by textbrowser** [comment]
I do not experience these problems while I'm in French mode.

**Comment by textbrowser** [comment]
> BiblioteQ updated and recompiled.
> 
> By default the plus sign (+) but the French value "Livre" is not working in the search.
> 
> With the popup I place the untranslated value "Book" and it's OK for the search.
> 
> If in linguist I translate "biblioteq_dbenumerations_item_delegate" "Book" by "Livre" ... it doesn't let me put Book anymore.
> 
> Should the pop-up display be in French, but the database entry in English?

The combination box values are translated. See tr(). If you save them in English and move towards French, things will not work. If you save them in French and move towards English, things will not work. The combination box performs a findText() via the database value.

**Comment by textbrowser** [comment]
Let's think a bit.

**Comment by textbrowser** [comment]
You're right. We should not translate the Type field. Give me a bit.

**Comment by textbrowser** [comment]
There is also a problem with Minimum Days.

**Comment by textbrowser** [comment]
Committed.

**Comment by meteos77** [comment]
Super, it works well
Thanks for the modification.

**Comment by textbrowser** [comment]
These are lovely problems.

**Comment by meteos77** [comment]
Ubuntu 24.04... Kubuntu 24.04 ... LinuxMint !

**Comment by textbrowser** [comment]
Now with immediate synchronization. DBE -> everyone -> Hi.

**Comment by meteos77** [comment]
We've lost the translation but gained the automatic update!

I checked which version the problem started with: 
version 2024-03-25 mixes up the types between the + button when saving.

Release Notes : 
“Sort item types in Database Enumerations combination boxes.

So it must have something to do with types and sorting as with dates and colors in the options settings.

**For me it works perfectly now, thank you very much.**

**Comment by textbrowser** [comment]
The translations are lost because the types represent literal reserved words. Like a BigInteger in Java. Of course I could introduce a mapping from BQ and the world, however, if the actual translations are incorrect, new problems.
