### ISSUE TITLE
How to build from the source code?

### ISSUE THREAD

**Issue by aasami** [textbrowser/biblioteq#364]
Sorry for the noob question, but where are instructions on how to build the source on Linux?

**Comment by textbrowser** [comment]
```
Qt 4 is not supported.
Qt 5.5.1 LTS is supported for PowerPC only.
Qt 5.15 LTS is supported until it is not.
Qt 6.5 LTS is supported.

For Android, MacOS, and Windows, the newest Qt LTS is required.

> qmake -o Makefile biblioteq.platform.pro
> gmake or make or mingw32-make
> make install or mingw32-make install

MacOS

A. Install the newest Qt LTS via Qt's online installer.
B. https://formulae.brew.sh/formula/libpq
C. > qmake -o Makefile biblioteq.macos.pro
D. > make -j 5
E. > make install
F. > make dmg
```

**Comment by textbrowser** [comment]
Is from Documentation/COMPILING.

**Comment by textbrowser** [comment]
What you system about?

**Comment by aasami** [comment]
Arch Linux

**Comment by textbrowser** [comment]
Is you Windows OpenBSD FreeBSD OS/2 Solaris Windows 2000 Debian Haiku?

**Comment by textbrowser** [comment]
Then you need not install because you see those instructions are for not you. Says so there in the computer screen.

**Comment by aasami** [comment]
So, what are my options?

**Comment by textbrowser** [comment]
Is Aaaaaarch Android -> no. Not MacOS. Not Windows.

**Comment by textbrowser** [comment]
So now you launch the program or set it aside in /opt. The biblioteq.sh script is full of hints as are many of the files in Distributions. All there for reading and thinking and not asking for the help of everything to be said.

**Comment by textbrowser** [comment]
Prefer /opt/biblioteq? OK. Just a few files and you can add a Desktop icon or a task bar or terminal like /opt/bq/bq.sh or whatever. Then happy and close ticket. See you.

**Comment by aasami** [comment]
> The software is available for many operating systems and should be compatible with any system that supports a modern Qt.

From the frontpage.

**Comment by textbrowser** [comment]
Yah and is. On BSDs and Raspberry Pis and PowerPCs but nothing written about how you install it everywhere or how to run it. Linux people are considered a bit wiser and independent and crafty-oriented or so - so hand-holding is limited. Preferred, yes.

**Comment by aasami** [comment]
Thank you. Your advice is helpful enough. I'll play with it and see if I can manage.

**Comment by textbrowser** [comment]
You is welcome and just peruse the files and if you cannot I maybe make a video but then I spend more time and later more questions and confusions and unhappy people wanting it to pop of the proverbial box and just work. But just-work mentality requires teals to make it work on ACHOO-64 or I don't know say AntiX or weird Puppy Linux or outdated Alpha processors. So, it is you who must spend to learn or not but it worthwhile as very simple.

**Comment by textbrowser** [comment]
And thanks for considering the BQ it happy for you and glad. Closing now. Luck and serendipity.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/discussions/365
