### ISSUE TITLE
 Create a new feature : move entry to another category.

### ISSUE THREAD

**Issue by SanAntonio37** [textbrowser/biblioteq#367]
Hi,

Can you plan to develop a feature that moves an entry to another category (eg. book -> paper) ?

Best regards

**Comment by textbrowser** [comment]
The categories are unique. Some share some features because that's natural. Even a digital item like a grey literature (PDF) to a book would be best done by a create and a delete. There are many things to consider.

**Comment by textbrowser** [comment]
Attach files to your physical book.
