### ISSUE TITLE
Just upgraded and can't read DB

### ISSUE THREAD

**Issue by dsuguy2007** [textbrowser/biblioteq#37]
I just downloaded and upgraded to version 2018.07.04 and when I ran it and connected to the DB then ran the upgrade db schema it gave an error. Not it won't read the db at all. The error was about duplicate field names.

**Comment by textbrowser** [comment]
An SQLite database? Open the database, then access the Upgrade SQLite Schema menu item from the Tools menu.

**Comment by textbrowser** [comment]
Please re-open if you're continuing to experience problems.
