### ISSUE TITLE
member history empty using a SQLite database

### ISSUE THREAD

**Issue by Arnok88** [textbrowser/biblioteq#373]
Context :
SQLite Database containing :
- A list of dvd
- A list of members (users)

I made a reservation for a dvd for a member.
Through, the member browser, I can visualize the brorow item.
But when I click on the "Member's reservation history" the windows remains empty.

Thanks to SQL query , I can see that the item_borrower table is correctly populated, but unfortunately the member_history table remains empty.

**Comment by textbrowser** [comment]
![bq](https://github.com/user-attachments/assets/cc3db059-c44d-4371-93cf-f86c99aa9601)

**Comment by textbrowser** [comment]
All things require exploration. Like in video games, we cannot directly contact the artists and the programmers and the sound engineers. So we have to explore and sometimes that's where it ends. Although we kind of enjoy answering questions, we most prefer that tickets are tickets for troublesome troubles.

**Comment by Arnok88** [comment]
I don't understand your comment .. sorry
The member reservation history remains empty even if we click on the reloaded button.
Using a query, we can see that the table member_history is empty, that is why the windows is empty .
I create a ticket because it is a trouble, not a question

**Comment by textbrowser** [comment]
No, is a question because when we do it it works correctly so it cannot be a problem unless you have like the release from 2009.

**Comment by textbrowser** [comment]
At the top of that image is an important check box. It says that BQ should not record a member's history if it is checked. You need to uncheck it. It is turned on by default so it requires exploration for it to be discovered. Perhaps we'll move it to Other Options. But then people who have explored will be annoyed.

**Comment by textbrowser** [comment]
GitHub has tickets and some people love to have everything handed to them instead of exploring. Cats are peculiar animals. Sometimes they are grumpy and sometimes playful. We are not paid to answer questions. If you enjoy free software, is your responsibility to explore and finally scream "hey, this busted, please help."

**Comment by Arnok88** [comment]
I used the version 2023.12.30 and it doesn't work.
I don't scream for help before searching that's why I created a ticket

**Comment by Arnok88** [comment]
![image](https://github.com/user-attachments/assets/683a3fd5-f1e3-4574-a39d-1b0e804de262)

**Comment by textbrowser** [comment]
We create video. Stay tuned. We know it works and video proves.

**Comment by Arnok88** [comment]
![image](https://github.com/user-attachments/assets/08476230-b88b-4b60-9b5a-afef7e20c5fb)

**Comment by Arnok88** [comment]
You are the proof ... with SQLite it doesn't work ...

**Comment by textbrowser** [comment]
https://github.com/user-attachments/assets/5ee33587-e4ad-4de1-9436-295e3876949a

**Comment by textbrowser** [comment]
Done!

**Comment by textbrowser** [comment]
If you borrowed an item before the check box was turned off, well, the expectation that all items borrowed before that event should now be inserted in the history table is silly.

**Comment by textbrowser** [comment]
Is for privacy. History off by default. We think about adding it elsewhere. Is much work because it requires synchronization. And 0% probability people will ignore it and would ask again.

**Comment by textbrowser** [comment]
Happy? Working? Another happy person on the Internet! Hooray for the cats!

**Comment by textbrowser** [comment]
https://textbrowser.github.io/biblioteq/

June 6, 2023.

Optional member reservation history for SQLite databases.

**Comment by Arnok88** [comment]
https://github.com/user-attachments/assets/6cbbffdc-5fb3-4e15-b6f3-ea2030865a89

**Comment by Arnok88** [comment]
https://github.com/user-attachments/assets/85615c6f-cd16-4631-810c-36d81bb7fe9b

**Comment by textbrowser** [comment]
If you reserve an item BEFORE the history is disabled, a history entry will not appear. If you reserve an item AFTER the history is enabled, the item will be present in the history table.

**Comment by textbrowser** [comment]
Your video does not depict the process of reserving an item. Instead, it simply displays a list of some reserved items and an empty history table.

The video I posted details the reservation process for both history-enabled and history-disabled processes. And both results are correct.

**Comment by textbrowser** [comment]
I be reviewing the entire reservation process now.

**Comment by textbrowser** [comment]
BA is incomplete.

**Comment by Arnok88** [comment]
> BA is incomplete. Next time, detail your problem.

ok for me.
Next time, don't treat the person directly as an idiot.

**Comment by Arnok88** [comment]
The video shows that the member history is not fulfilled when you make a multi reservation thanks to the "Batch activities Browser". 
I should have been be more precise in my description.

**Comment by textbrowser** [comment]
No one treated you as an idiot or as a savant.

**Comment by textbrowser** [comment]
The proper reservation process was documented via a video and an image.

**Comment by textbrowser** [comment]
Humor is complex and sometimes contagious. Not this time. :P

**Comment by textbrowser** [comment]
I didn't snipe your operating system, BQ version, your process. I mean your initial problem description didn't persuade or help me. BQ is made from the perception that it wants to benefit you. So there are many ways of doing things. Because of that, there is an implied expectation that the person reporting or requesting takes as much care as BQ does. Details matter sometimes. And the aggression, well, that be on you. Remember, you're getting something for free. Free. That's not a high horse or low horse or tarnished warrior or belligerent queen; free!

**Comment by textbrowser** [comment]
I don't know how to be rude or mean. I suppose I could ignore requests. Close tickets without interacting with people. Close ticket systems which I've had to do because of persistent abuse. And with all of that, you're getting a pleasant response, immediate corrections, and free.

**Comment by textbrowser** [comment]
And then there is the additional item for free, the enabling of history from another perspective. So there is the additional feature of benefit future people. Evolving software.

**Comment by Arnok88** [comment]
> I didn't snipe your operating system, BQ version, your process. I mean your initial problem description didn't persuade or help me. BQ is made from the perception that it wants to benefit you. So there are many ways of doing things. Because of that, there is an implied expectation that the person reporting or requesting takes as much care as BQ does. Details matter sometimes. And the aggression, well, that be on you. Remember, you're getting something for free. Free. That's not a high horse or low horse or tarnished warrior or belligerent queen; free!

If I wasn't clear, you should have asked me for clarification and not been sarcastic.
I have a sense of humour, but I don't understand all the subtleties used because I'm not an English speaker.

**Comment by textbrowser** [comment]
Sarcasm requires wit something we do not have here. We speak many languages too. English is the common interface.

**Comment by textbrowser** [comment]
Completed.

**Comment by Arnok88** [comment]
Great !!
