### ISSUE TITLE
Unable to pull covers from Amazon.

### ISSUE THREAD

**Issue by JasonQuasar** [textbrowser/biblioteq#375]
Despite taking the ISBN from amazon to do some test for a database I'm not able to pull covers from the site.
I noticed the recent URL is shorter than the one in the .conf

I have tried both the ISBN-10 and the 13. It does not work
Windows 10

![Immagine 2024-09-17 181227](https://github.com/user-attachments/assets/8dcb7a3d-47b7-4a47-bd15-1cec7c862815)

**Comment by textbrowser** [comment]
Thanks for the report and I don't know about it. Maybe we try later. Try the other query for images because Amazon is evil and it was once the only place for pictures, however, now there are others and we should abandon it because it's cruel.

**Comment by textbrowser** [comment]
OpenL does not contain as many images so another is preferred but I don't know of any other one for free with many images.

**Comment by JasonQuasar** [comment]
978-8829-9297-26 Book about physics. 

https://www.amazon.it/Fisica-Meccanica-termodinamica-U-Gasparini/dp/8829929727

**Comment by textbrowser** [comment]
![bq](https://github.com/user-attachments/assets/53196243-4e56-4e85-ab20-1649318c1a33)

**Comment by textbrowser** [comment]
Another person has SRU problem on Windows with TLS so maybe this is similar. Billy Gates doesn't like privacy and that's his way of telling you that his adverts are reaching you.

**Comment by JasonQuasar** [comment]
should I install something to avoid this? Maybe firewall exception?

**Comment by JasonQuasar** [comment]
Covers are way more important than anything else for this library lol

**Comment by textbrowser** [comment]
I'm clueless right now with Windows until I enter the darkness sometime later for releasing another program so I'll test then. Maybe Amazon doesn't want you to query through BQ but it works here so it would be querying through BQ on Windows in Italy. Maybe defenestration is the problem.

**Comment by textbrowser** [comment]
Try querying through a proxy on your system. Like a free proxy just for this test but I doubt it would solve the problem and that's not a good resolution anyway. I would wait until I see or someone responds with insight or install PostgreSQL and put the images in a proper operating system and then you don't have this problem because anyone can read it remotely and locally. All good then.

**Comment by textbrowser** [comment]
You can also attach the images and then takes lots longer or through save and then drag-and-drop. So there are slower ways to get the images. I remember someone writing a script with wget and then inserting the base-64 images into their database. So a list of ISBNs and downloads through wget and then sqlite. All easy but I don't have the time now.

**Comment by textbrowser** [comment]
Aha it would be nice with the trillion dollar image manipulation ai machines: fetch me all images for these isbns and then insert them into my database in this format. But right now ai is garbage and used for nefarious propaganda.

**Comment by textbrowser** [comment]
So you have to wait for slow ticket people to do the work but they'll do it properly and you'll be happy then but not now. See you. Maybe this week or next. But someone will look.

**Comment by JasonQuasar** [comment]
> Try querying through a proxy on your system. Like a free proxy just for this test but I doubt it would solve the problem and that's not a good resolution anyway. I would wait until I see or someone responds with insight or install PostgreSQL and put the images in a proper operating system and then you don't have this problem because anyone can read it remotely and locally. All good then.

I tried with tunnelbear and it did not work.
thanks anyway

**Comment by textbrowser** [comment]
Found the problem and now for the correction.

**Comment by textbrowser** [comment]
Download tls directory from https://github.com/textbrowser/qt-products/tree/main/6.5_LTS/Windows/plugins and place in the plugins folder. The tls directory should be plugins/tls. Or download attachment and place unzipped in plugins.

[tls.zip](https://github.com/user-attachments/files/17063758/tls.zip)
