### ISSUE TITLE
Keyboard accelerators for modify book entry window

### ISSUE THREAD

**Issue by wohali** [textbrowser/biblioteq#38]
I'd love it if I could hit Ctrl+S and Ctrl+W to save and close a "Modify Book Entry" (or similar) window. Other keys would be fine too, especially the as-of-yet unused F keys.

Because there are multiple buttons with S or C as the accelerator, hitting Alt+S or Alt+C only highlights that button, and does not activate it. It also requires multiple keypresses to "scroll" through all of the choices before the right button is selected.

**Comment by textbrowser** [comment]
I'll add the two control shortcuts. Please let me know if you need other shortcuts.

**Comment by textbrowser** [comment]
All windows now support closing via Control + W. Dialog objects are not included. Some windows also support Control + S. Will now work on item windows.

**Comment by textbrowser** [comment]
Except the main window.

**Comment by textbrowser** [comment]
Control + S added to item windows. Shortcuts will save() or search(). Changes will be included in the next release.
