### ISSUE TITLE
Tabbed item windows and pasting of images into Back and Front cover image containers.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#386]
Allow pasting of images into Back and Front cover image containers. GitHub ticket #284. 

This feature doesn't seem to work when tabbed windows are enabled.

If it's quick to correct, otherwise it's enough to know. I haven't yet decided between the 2 modes (with or without tabs).

What motivated you to do the tabs?

**Comment by textbrowser** [comment]
You enjoy the tabbing? I do. Is very cozy, like a home or library or a place of warmth. I look for your images.

**Comment by textbrowser** [comment]
It's the shortcut.

**Comment by textbrowser** [comment]
You're Ctrl +V - ing. So, another place is more important. I eliminate the shortcut and maybe introduce a button. You have Select and you have drag & drop. Closing!

**Comment by textbrowser** [comment]
I see 10 application icons and I become disturbed. It requires review of each window and that is a lot of review. I may also add icons to the pages and their respective menu actions. Some items have descriptive icons and those icons may identity the specific pages. Cannot be done with windows unless those windows adapt the icons of the items, however, then the relationship of the minimized window is lost, that is, we do not know that it belongs to BiblioteQ.

**Comment by textbrowser** [comment]
> Allow pasting of images into Back and Front cover image containers. GitHub ticket #284.
> 
> This feature doesn't seem to work when tabbed windows are enabled.
> 
> If it's quick to correct, otherwise it's enough to know. I haven't yet decided between the 2 modes (with or without tabs).
> 
> What motivated you to do the tabs?

"I'll add Paste buttons."

**Comment by meteos77** [comment]
I like the tabs with a small screen, because you can no longer manage the placement of the windows, which is great.

Are you going to place the “Member browsers and Custom queries” as tabs?

**Comment by meteos77** [comment]
I'm not sure if I've understood everything, but you can't create icons like “BiblioteQ and Books”. 
![book](https://github.com/user-attachments/assets/93413f19-eb80-482d-8262-798a09c1e871)

**Comment by textbrowser** [comment]
No, the other windows do not bother me. I don't know. Maybe. Not easy.

**Comment by meteos77** [comment]
Help: Does the ctrl + v shortcut no longer work in “window” mode?
It's my preferred method because it requires fewer clicks :-)

Could you have a look at this, in advance?

**Comment by textbrowser** [comment]
Official shortcuts are in Other Options. This old shortcut was clearly invalid.

**Comment by textbrowser** [comment]
![bq](https://github.com/user-attachments/assets/82af7772-3609-4b5e-b238-c0fc51328e94)

**Comment by textbrowser** [comment]
Menu or paste. Single click or click-to-menu and select something else. Works everywhere without shortcuts. Shortcuts are stupid anyway because Android doesn't have a real keyboard.

**Comment by textbrowser** [comment]
And shortcuts are enable preferences. Nothing in English says that pasting in Ctrl+V. The shortcut is manufactured from key placement on a keyboard. And if you have custom layouts, it means nothing to you. I don't like function shortcuts because many keyboards don't have explicit function keys so you're spending more time pressing keys just to activate a shortcut. Buttons are clear and visible. And with future speech, the system would be able to click a button for you. Say: click the Paste button. And with brain, you can instruct the system to select something. Can't be done with a keyboard or on a tablet when you can't shortcut in a virtual world.

**Comment by meteos77** [comment]
Thanks for the evolution, it looks good (I'm going to test it with the new arrival of books tomorrow).
