### ISSUE TITLE
Support for ISBN starting with 979

### ISSUE THREAD

**Issue by Safranil** [textbrowser/biblioteq#39]
Today some ISBN start with 979 (instead of 978), but biblioteq convert ISBN 13 to ISBN 10 and recalculate the value on save. So it's impossible to handle ISBN starting by 979 and this lead to collision in the database.

Can you add support to ISBN starting with 979 ?

**Comment by Safranil** [comment]
Note: With ISBN starting with 979, It's impossible to use it to found it on Amazon, so I use the ASIN (e.g. B074BNFY7F) to download the cover.

**Comment by textbrowser** [comment]
Sure, support for 979 ISBNs will be added.

https://www.isbn.org/about_isbn_standard

**Comment by textbrowser** [comment]
Done and will be available in the next release.

Also added a brief note about ASINs in the official document.

Thanks!

**Comment by Safranil** [comment]
That was fast! Thanks.

**Comment by textbrowser** [comment]
That's how we roll. :o)
