### ISSUE TITLE
broken link for online version

### ISSUE THREAD

**Issue by dP14EOOgMDg** [textbrowser/biblioteq#4]
On the page http://biblioteq.sourceforge.net/download.html, there is a link to http://code.google.com/p/biblioteqonline, which yields a 404.

Online Version

    Please visit http://code.google.com/p/biblioteqonline for the online version of BiblioteQ. 

404. That's an error.

The project biblioteqonline was not found.

**Comment by textbrowser** [comment]
Are you sure? I'm transferred to a functional page.

I will modify the http to https, however.

**Comment by textbrowser** [comment]
Alright! Sometimes it works, sometimes it doesn't. Which browser are you using?

**Comment by textbrowser** [comment]
I'm replacing the link with https://github.com/search?utf8=%E2%9C%93&q=biblioteqonline.
Thanks!

**Comment by dP14EOOgMDg** [comment]
I was (and still am) using iceweasel, which is a firefox derivative (on debian).

derek


On Tue, Feb 23, 2016 at 03:06:26PM -0800, Guess Who wrote:
>    Alright! Sometimes it works, sometimes it doesn't. Which browser are you
>    using?
> 
>    -
>    Reply to this email directly or view it on GitHub.
> 
>    Link:
>    https://github.com/textbrowser/biblioteq/issues/4#issuecomment-187956453

-- 
Ventis secundis, tene cursum.

dt at hawkmoon dot mn dot org
slash slash lastditch dot dyndns dot org

**Comment by textbrowser** [comment]
On Dooble, I see the error. On Firefox, I do not.

**Comment by textbrowser** [comment]
Dooble without WebKit also produces the error. Perhaps Google is targeting user agent strings.

**Comment by textbrowser** [comment]
Let's close.

**Comment by textbrowser** [comment]
And thank you for the discovery.

**Comment by dP14EOOgMDg** [comment]
On Wed, Feb 24, 2016 at 07:13:19AM -0800, Guess Who wrote:
>    And thank you for the discovery.

You're welcome!  Do I need to do anything to help close?  Like confirm or anything?

derek

-- 
Ventis secundis, tene cursum.

dt at hawkmoon dot mn dot org
slash slash lastditch dot dyndns dot org

**Comment by textbrowser** [comment]
Nope. You or I can close the ticket. I've seen it done.

And I'm not the creator of the online version. It could be abandoned.
