### ISSUE TITLE
O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil

### ISSUE THREAD

**Issue by Eraldo-Junior** [textbrowser/biblioteq#40]
Adorei o programa, mas creio que, muitas pessoas que utilizam este programa aqui no brasil, gostaria que estivesse uma versão em português/br. Vocês tem em mente em algum dia criar uma versão em português? - I loved the program, but I believe that many people who use this program here in Brazil would like it to be a Portuguese version. Do you have in mind someday to create a Portuguese version?

**Comment by textbrowser** [comment]
Several people have offered to provide a Portuguese translation. Have not received one yet. It's pretty easy with Qt's Linguist.

**Comment by leemour** [comment]
@Eraldo-Junior You can find a freelance translater to do it for you. I just paid $10 for full translation in Russian and you might want to do the same and get that Portugese version for all the world to use:)

**Comment by AndreSantosMG** [comment]
> Several people have offered to provide a Portuguese translation. Have not received one yet. It's pretty easy with Qt's Linguist.

I can do it for you. How can I help?
I've did some translations for Android Softwares on CrowdIn. Have you any tool like this? Could you send me the strings to translate?

**Comment by textbrowser** [comment]
Please see https://doc.qt.io/qt-5/qtlinguist-index.html. Download Qt from https://www.qt.io/download.

You will find a new biblioteq_pt_PT.ts file in BQ's source repository.

Qt's Linguist is the application that you'll be using.

Thank you!

**Comment by nafergo** [comment]
Is this still open? Or someone already took this task?

**Comment by textbrowser** [comment]
Still open. :)

**Comment by AndreSantosMG** [comment]
> biblioteq_pt_PT.ts

At, first, I've just received Github email about your reply yesterday. Weird...

I can't find a free download from QT site. If you help me, I'm ready to work!

**Comment by textbrowser** [comment]
Try https://www.qt.io/download.

**Comment by textbrowser** [comment]
Online installer: https://www.qt.io/download-qt-installer.

**Comment by textbrowser** [comment]
Anyone alive?

**Comment by nafergo** [comment]
Yap. I was under the impression that this was already ongoing. Will start asap.
It's just one file and it's Translations/biblioteq_pt_PT.ts  right?

**Comment by textbrowser** [comment]
Yup, that's the file for Portuguese. Thank you.

**Comment by nafergo** [comment]
next weekend I'll try finish it and do pull request or directly send you (as you prefer)

**Comment by textbrowser** [comment]
Thank you. You can upload it here as a ZIP file or issue a pull request.

**Comment by AlbertoBN** [comment]
Hi, 
Excellent work! I am planning to use BiblioteQ to replace an aging VB6 library program at my kids school. Can I just use the PT file contents with hebrew translation (and of course use the correct local name on the file) or should you issue a new one for hebrew?
Thanks in advance

**Comment by textbrowser** [comment]
Just updated the translation files. I think your approach may work. Will modify the source to include Hebrew. Thank you.

**Comment by textbrowser** [comment]
For the locale, is he_IL correct?

**Comment by textbrowser** [comment]
OK, added biblioteq_he_IL.qm and biblioteq_he_IL.ts to Translations. Can be renamed if the locale is incorrect.

**Comment by AlbertoBN** [comment]
Sorry for the delay in answering. Yes he_IL is perfect! Thanks!

**Comment by alcovinho** [comment]
Olá pessoal alguem me pode arranjar o ficheiro para colocar o biblioteq em PT ? E as instruções de onde colocar o ficheiro ? Agradeço desde ja a todos. Abraços.

**Comment by FriedrichFroebel** [comment]
@alcovinho As I do not speak Portuguese, I used a translator to understand your query and will be answering in English.

The corresponding translation source file is available [here](https://github.com/textbrowser/biblioteq/blob/master/Translations/biblioteq_pt_PT.ts), but at the moment it seems like none of the strings there has already been translated into Portuguese. Once it has been translated, a new build should provide a real Portuguese GUI as well.

**Comment by a12554** [comment]
I'm portuguese and I can translate the source. My question is where I translate in the code? Is in the place where it says "unfinished"? thx in advance, I'll do the job fast.

**Comment by textbrowser** [comment]
See https://github.com/textbrowser/biblioteq/blob/master/Documentation/TRANSLATIONS.

Thanks.

**Comment by a12554** [comment]
The portuguese translation is really extensive but I will finishit this week, maybe friday.

All the best.

Fernando Oliveira.

________________________________
De: textbrowser <notifications@github.com>
Enviado: 4 de janeiro de 2021 03:27
Para: textbrowser/biblioteq <biblioteq@noreply.github.com>
Cc: Fernando Jorge Lopes de Oliveira <a12554@alunos.ipca.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [textbrowser/biblioteq] O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil (#40)


See https://github.com/textbrowser/biblioteq/blob/master/Documentation/TRANSLATIONS.

Thanks.

**Comment by textbrowser** [comment]
Cool. Thanks.

**Comment by a12554** [comment]
Still working on portuguese translation, I need more 4 or 5 days.

________________________________
De: Fernando Jorge Lopes de Oliveira <a12554@alunos.ipca.pt>
Enviado: 4 de janeiro de 2021 16:59
Para: textbrowser/biblioteq <reply@reply.github.com>
Assunto: RE: [textbrowser/biblioteq] O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil (#40)

The portuguese translation is really extensive but I will finishit this week, maybe friday.

All the best.

Fernando Oliveira.

________________________________
De: textbrowser <notifications@github.com>
Enviado: 4 de janeiro de 2021 03:27
Para: textbrowser/biblioteq <biblioteq@noreply.github.com>
Cc: Fernando Jorge Lopes de Oliveira <a12554@alunos.ipca.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [textbrowser/biblioteq] O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil (#40)


See https://github.com/textbrowser/biblioteq/blob/master/Documentation/TRANSLATIONS.

Thanks.

**Comment by alcovinho** [comment]
Cool 👍😉

A domingo, 10/01/2021, 19:02, Terrapine <notifications@github.com> escreveu:

**Comment by a12554** [comment]
I finish the translation.

**Comment by textbrowser** [comment]
Excellent. You can attach the file here or create a pull request.

**Comment by a12554** [comment]
How I can make a pull request?
![pullRequest](https://user-images.githubusercontent.com/22908543/109163659-76054a00-7771-11eb-924e-31636ce03d1e.png)

**Comment by a12554** [comment]
Ok I attached in a zip file.
[biblioteq_pt_PT.zip](https://github.com/textbrowser/biblioteq/files/6043445/biblioteq_pt_PT.zip)

**Comment by a12554** [comment]
Ok, I attached in a zip file
[biblioteq_pt_PT.zip](https://github.com/textbrowser/biblioteq/files/6043453/biblioteq_pt_PT.zip)

**Comment by a12554** [comment]
I created in QTLinguistic and export the file as .qm format. Please, give me feedback if it's ok. Thx.

**Comment by textbrowser** [comment]
OK, committed the qm file. Please also attach the ts file. Will integrate the new translation later and let you know what it looks like.

**Comment by textbrowser** [comment]
Pull requests require that the repository first be forked, unless you have proper permissions.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by a12554** [comment]
ok both files ziped
[biblioteq_pt_PT.zip](https://github.com/textbrowser/biblioteq/files/6043659/biblioteq_pt_PT.zip)

**Comment by textbrowser** [comment]
Committed.

**Comment by textbrowser** [comment]
![Screenshot_20210225_094147](https://user-images.githubusercontent.com/10701156/109169557-e8643300-774d-11eb-8b65-b9007509ac1f.png)

**Comment by textbrowser** [comment]
Closing after almost 3 years. Thank you very much. Looks great. :)

**Comment by a12554** [comment]
How I install the version for windows? With Visual Studio? You don't have an installer?
Thx.

________________________________
De: textbrowser <notifications@github.com>
Enviado: 25 de fevereiro de 2021 14:45
Para: textbrowser/biblioteq <biblioteq@noreply.github.com>
Cc: Fernando Jorge Lopes de Oliveira <a12554@alunos.ipca.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [textbrowser/biblioteq] O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil (#40)


Closed #40<https://github.com/textbrowser/biblioteq/issues/40>.

**Comment by textbrowser** [comment]
BQ is Windows portable. Installer not needed.

**Comment by a12554** [comment]
Sorry my ignorance, but where is the exe file to run the software? How I run BliblioteQ?


________________________________
De: textbrowser <notifications@github.com>
Enviado: 25 de fevereiro de 2021 22:42
Para: textbrowser/biblioteq <biblioteq@noreply.github.com>
Cc: Fernando Jorge Lopes de Oliveira <a12554@alunos.ipca.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [textbrowser/biblioteq] O programa não possui a língua Português/Brasil - The program does not have the language Portuguese / Brazil (#40)


BQ is Windows portable. Installer not needed.

**Comment by textbrowser** [comment]
Always in releases.

https://github.com/textbrowser/biblioteq/releases

I do not provide nightly or daily builds.

**Comment by a12554** [comment]
Ok I find it, thx! Last question, I try to choose pt language but doen't appear in menu, what should I do? The files are in the folder Translations.
![BiblioteQ](https://user-images.githubusercontent.com/22908543/109231822-28afc980-77bf-11eb-8cbc-e794c049c730.png)

**Comment by textbrowser** [comment]
You can build the latest source and the new language will be present. BQ does not auto-detect languages.

**Comment by alcovinho** [comment]
Thanks my friend 🙂

A domingo, 9/02/2020, 10:31, FriedrichFroebel <notifications@github.com>
escreveu:
