### ISSUE TITLE
SRU Query gives "network error (Protocol unknown..)"

### ISSUE THREAD

**Issue by sit42** [textbrowser/biblioteq#42]
We are using
BiblioteQ Version 2018.10.01
Architecture amd64.
Compiled on Oct 2 2018, 07:19:00.
Copyright (c) 2005 - present, Mushroom.
Poppler version 0.62.0.
Qt version 5.9.5 (runtime 5.11.2).
YAZ version 5.19.2.

Downloaded as a deb archive for ubuntu. 18.04. Using sqlite db currently.
After using the program without the .conf file a first book could be entered using the SRU Query.
But because of another issue, we are using now a .conf file.
Now the SRU query does not work anymore.
It always gives a popup with:
"A network error (Das Protokoll "" ist unbekannt) occurred."

The conf file looks like this:
```
[SRU-2]
name = Library of Congress
url_isbn = "https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =

# Format (http://www.indexdata.com/yaz/doc/zoom.records.html).

[SRU-3]
name = Library of Congress Online Catalog
url_isbn = "https://lx2.loc.gov:210/lcdb?version=1.1&operation=searchRetrieve&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://lx2.loc.gov:210/lcdb?version=1.1&operation=searchRetrieve&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_type = None
```

Both do not work.
We checked the SRU data as you can see in SRU-3, but this also does not work.

I could not find any help in the documentation about a used "protocol" unfortunately.

Are there any suggestions?

**Comment by textbrowser** [comment]
What's the ISBN?

**Comment by textbrowser** [comment]
That's a good one! :P

How about the ISBN which you're using for the query?

**Comment by sit42** [comment]
Yes, I was a bit irritated you are asking for that :) :) But close to the evening I thought, Ok ....

I used different ones, taken from Amazon for test purposes.
E.g. 9780596154486
for "Linux in a Nutshell"

**Comment by textbrowser** [comment]
OK, thanks a bunch.

**Comment by sit42** [comment]
I just tried it again from another computer logged into the system by ssh.
This time the search seems to work. For ISBNs, which are not in the LibOfCongress it responds correctly with a message and ones known, ir downloads now.

So it looks like some strange problem with the reading of configs etc. Firewalls are not a problem here, I am pretty sure.
Very strange. I will try it again tomorrow morning directly on this computer. Lets see what the result then is.

If you have any idea, what I could try to figure out the reason, just let me know.

PS: By the way, is there a SRU search using amazon books? Because a lot of books are not in the library of congress lists.... And that would make it a hazzle to fill the database...

**Comment by textbrowser** [comment]
Shortly after BQ launches, it will display an error if it cannot access biblioteq.conf. Did you notice such an error? You can try the SRU queries using a browser. For example: ```https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=9780596154486%20or%20bath.isbn=9780596154486&recordSchema=marcxml&startRecord=1&maximumRecords=1```.

No, I don't know if Amazon supports SRU. There are other SRU servers beyond LoC.

**Comment by textbrowser** [comment]
So, I tried the SRU query using the ISBN and it completed normally.

**Comment by sit42** [comment]
I tried it here again and again I get the error.

I did:
Use the attached config.
Connected to the attached sqlite db.
Selected "Add Book" Menu
Inserted the following ISBN10 "3540234055", and pushed button "From ISBN-10".
Then selected SRU Library of Congress.
Then pushed button SRU Query.
Then I get the attached screenshot message.

The error log is empty.

What I did once (maybe this has influence):
I selected SRU-1 and started it. Then interrupted it while displaying "Downloading" because it took very long. Idon't know, but maybe this caused something, which forces the other error...

Config file:
`# Values may be case-sensitive.

# Proxy types: HTTP, None, Socks5, System.

[Amazon Front Cover Images]
host = images.amazon.com
path = "/images/P/%.01._SCMZZZZZZZ_.jpg"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =

# Proxy types: HTTP, None, Socks5, System.

[Amazon Back Cover Images]
host = images.amazon.com
path = "/images/P/%.01._SCMZZZZZZZ_.jpg"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =

[Branch-1]
database_name = local_db
database_type = sqlite

[Branch-2]

# connection_options = "connect_timeout=10;sslmode=verify-full"

connection_options =
database_name = xbook_db
database_type = postgresql
hostname = localhost
port = 5432
ssl_enabled = true

# Proxy types: HTTP, None, Socks5, System.
# BiblioteQ shall replace %1 and %2 accordingly. Please follow the examples
# below when defining SRU sites.

[SRU-1]
name = CUNY Union Catalog
url_isbn = "http://libadmin.cuny.edu:5661/U-CUN01?version=1.1&operation=searchRetrieve&query=bath.isbn=%1 or bath.isbn=%2&startRecord=1&maximumRecords=1"
url_issn = "http://libadmin.cuny.edu:5661/U-CUN01?version=1.1&operation=searchRetrieve&query=bath.issn=%1&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =

[SRU-2]
name = Library of Congress
url_isbn = "https://z3950.loc.gov:7090/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =

# Format (http://www.indexdata.com/yaz/doc/zoom.records.html).

[SRU-3]
name = Library of Congress Online Catalog
url_isbn = "https://lx2.loc.gov:210/lcdb?version=1.1&operation=searchRetrieve&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://lx2.loc.gov:210/lcdb?version=1.1&operation=searchRetrieve&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_type = None



[Z39.50-1]
name = Columbia University
hostname = z3950.library.columbia.edu
port = 7090
database_name = VOYAGER
format = "marc8,utf-8"
record_syntax = "MARC21"
username =
password =
proxy_host =
proxy_port =

[Z39.50-2]
name = Library of Congress
hostname = lx2.loc.gov
port = 210
database_name = LCDB
format = "marc8,utf-8"
record_syntax = "MARC21"
username =
password =
proxy_host =
proxy_port =

[Z39.50-3]
name =  National Library of Morocco
hostname = opac.bnrm.ma
port = 1111
database_name = DEFAULT
format = "UNIMARC"
record_syntax = "UNIMARC"
username =
password = bnrm2015
proxy_host =
proxy_port =

[Z39.50-4]
name = National Technical University of Athens
hostname = 147.102.210.209
port = 21210
database_name = advance
format = "advancegreek"
record_syntax = "UNIMARC"
username =
password =
proxy_host =
proxy_port =
`
Screenshot of error:
![grafik](https://user-images.githubusercontent.com/44637017/48048343-7c83e800-e19b-11e8-8a53-1f9873d9977c.png)

SqlLite File:
[biblioteq_sql.sqlite.zip](https://github.com/textbrowser/biblioteq/files/2551956/biblioteq_sql.sqlite.zip)

**Comment by textbrowser** [comment]
Did you try the SRU query with a Web browser? See above comment.

**Comment by textbrowser** [comment]
Your 3rd SRU entry is incorrect for ISBN queries as it does not support HTTPS.

**Comment by textbrowser** [comment]
Right, so I tested the 3rd SRU server too. Network error. After changing the HTTPS to HTTP, the query of 9780596154486 completed successfully. So, if you're ever experiencing problems with SRU, try a query with a Web browser.

**Comment by textbrowser** [comment]
[SRU-3] is not in the official biblioteq.conf file. So, I can't change it.

As for the error, what's your preferred (Options -> Preferred...) SRU site?

**Comment by sit42** [comment]
But [SRU-2] is and is also wrong.

The preferred is always [SRU-1] because changing it to SRU-2 and saving the settings does not work. So we always select the LibOfCon manually.

**Comment by textbrowser** [comment]
Where are you saving the setting?

**Comment by sit42** [comment]
In the home directory of the user. Thats where we currently start the program.
As I understood the conf file is taken from the directory the tool is started from and needs to be called biblioteq.conf.

**Comment by textbrowser** [comment]
So: Options -> Preferred... -> Select. Then, Options -> Save Settings. Also, Options -> Automatically Save Settings...

**Comment by textbrowser** [comment]
biblioteq.conf does not include user settings. It includes application settings.

I use [SRU-2] and other people use [SRU-2] successfully.

Notice the little pull-down on the SRU Query button? You may be querying CUNY instead of LoC.

**Comment by textbrowser** [comment]
Interesting. Does your list of preferred SRU sites include translated text? You'll notice the ampersand before Library of Congress. I don't have this character.

**Comment by textbrowser** [comment]
Also "mainwindow_canvas_background_color=#&ffffff". Remove the ampersands from your BiblioteQ.INI file.

**Comment by textbrowser** [comment]
Yes, CUNY is dead. I'll remove it.

**Comment by sit42** [comment]
I thought the ampersand is used by you somehow...
But
It gets even more strange.
If I remove the ampersand from the ini file, start it, the setting in the options menu is correct as LibOfCon, but when I then load the db and add a book, the SRU site is back to SRU-1 in the little menu...
If I store the settings again, its back to SRU-1 in the ini file.... Although I did not change anything, before saving the settings again.

**Comment by sit42** [comment]
I can remove all ampersands, but next time settings are saved, the ampersand is there again...

**Comment by textbrowser** [comment]
You're using a German language? Can you select English, restart, and save your settings? Then see if the selection is correct.

**Comment by sit42** [comment]
I changed to english language, but still get the ampersands in both SRU and z3950 sites...

**Comment by textbrowser** [comment]
Super strange.

Meanwhile, remove the CUNY and your 3rd SRU entries from biblioteq.conf. Then attempt the query and let me know the results.

I'll look at the ampersands.

**Comment by textbrowser** [comment]
You have this?

```
name = Library of Congress
url_isbn = "https://z3950.loc.gov:7090/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =
```

**Comment by textbrowser** [comment]
https://raw.githubusercontent.com/textbrowser/biblioteq/master/biblioteq.conf

**Comment by sit42** [comment]
Yes exactly this!
Only change: The "https" is replaced with "http" for ISBN, because it only works with http.

**Comment by textbrowser** [comment]
In your post above, you have:

```
[SRU-2]
name = Library of Congress
url_isbn = "https://z3950.loc.gov:7090/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=%1 or bath.isbn=%2&recordSchema=marcxml&startRecord=1&maximumRecords=1"
url_issn = "https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =
```

That's a mixture of SRU and Z39.50. That's an epic failure.

**Comment by sit42** [comment]
Took the one you referenced here a few minutes ago, deleting my old one.
Restarted, but still the same error.

**Comment by textbrowser** [comment]
Attach the biblioteq.conf you're using.

**Comment by sit42** [comment]
Here the conf file:
[biblioteq.conf.zip](https://github.com/textbrowser/biblioteq/files/2558631/biblioteq.conf.zip)

**Comment by textbrowser** [comment]
Using the official biblioteq.conf and the ISBN 3540234055, my SRU query results in an error stating that the ISBN may not exist.

**Comment by textbrowser** [comment]
I don't have a network error.

**Comment by textbrowser** [comment]
```
netstat -anp | grep BiblioteQ
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 192.168.178.15:60094    104.16.54.16:443        ESTABLISHED 18703/./BiblioteQ 
```

**Comment by textbrowser** [comment]
```ping www.loc.gov
PING www.loc.gov.cdn.cloudflare.net (104.16.55.16) 56(84) bytes of data.
```

**Comment by textbrowser** [comment]
https://catalog.loc.gov/vwebv/search?searchCode=STNO&searchArg=3540234055&searchType=1&limitTo=none&fromYear=&toYear=&limitTo=LOCA%3Dall&limitTo=PLAC%3Dall&limitTo=TYPE%3Dall&limitTo=LANG%3Dall&recCount=25

Zero results.

**Comment by sit42** [comment]
The ping also works here.

netstat -anp | grep BiblioteQ
(Es konnten nicht alle Prozesse identifiziert werden; Informationen über
nicht-eigene Processe werden nicht angezeigt; Root kann sie anzeigen.)
unix  3      [ ]         STREAM     VERBUNDEN     4138135  1720/BiblioteQ
unix  3      [ ]         STREAM     VERBUNDEN     4140085  1720/BiblioteQ
unix  3      [ ]         STREAM     VERBUNDEN     4136452  1720/BiblioteQ
unix  3      [ ]         STREAM     VERBUNDEN     4145634  1720/BiblioteQ
unix  3      [ ]         STREAM     VERBUNDEN     4135567  1720/BiblioteQ

**Comment by textbrowser** [comment]
http://www.dnb.de/EN/Service/DigitaleDienste/SRU/sru_node.html

**Comment by sit42** [comment]
I still got the error. 

BUT I have now done the following:
- I created a new SQL database (sqlite)
- Then I used this one and did searching and now it works.

So it seems that the database has caused the problems!!
Because this was only a test database with oine entry, its no problem.

How did I create the database:
- New db
- Added one entry using searching
- Called "Upgrade SQLite Schema"
- Then searched for more books

-> Maybe the database gets corrupted by the "Upgrade Schema" stuff and causes these problems...

Hope this helps to find this problem.

**Comment by textbrowser** [comment]
Let me try that.

**Comment by sit42** [comment]
Here the database, which seems to cause the probklems. Maybe you can check if you have also problems with it on your PC.
[biblioteq_sql.sqlite.zip](https://github.com/textbrowser/biblioteq/files/2558691/biblioteq_sql.sqlite.zip)

**Comment by textbrowser** [comment]
First the test:
1. New SQLite database.
2. Added a book entry. Queried LoC. Saved.
3. Upgraded the database via the tool.
4. Initiated a LoC query on the existing entry. Success.

Your database:
1. Initiated a query. Success.
2. Upgraded the database via the upgrade tool.
3. Initiated a query. Success.

So, I cannot reproduce this problem.

**Comment by textbrowser** [comment]
What's bothering me is that you're using Qt 5.11.x runtime libraries and the software was built with Qt 5.9.x.

**Comment by sit42** [comment]
Not good.
I did some more playing around and now I have the error again.
I could not really find a pattern which triggers the error.

MAybe one more thought, which just happened:
- New DB
- One entry entered by hand manually
- Then searching, worked.
- Searching once with Z39.50 gives the error
![z3950queryerror](https://user-images.githubusercontent.com/44637017/48152901-58242a80-e2c5-11e8-93f3-064fe13f88e8.png)
- After that, I get the protocol error with the SRU query now...

I am not sure, but maybe that could be something.

**Comment by textbrowser** [comment]
You need to build BQ from source.

**Comment by sit42** [comment]
KDE Neon 5.14 based on Ubuntu 18.04

**Comment by textbrowser** [comment]
Can you build from source? I can assist.

**Comment by sit42** [comment]
Sorry for late response, have been too busy unfortunately.

I compiled it and created a deb package and tried to install it.
Everything worked until I install then I get:
---
 biblioteq hängt ab von libyaz4 (>= 4.0); aber:
  Paket libyaz4 ist nicht installiert.
---
and it seems that there is no libyaz4 package for ubuntu 18.04.1 unfortunately.

I can run the program anyway (?), but it again shows the error described above, sorry.

Remark: Ubuntu comes with 
libyaz5 - YAZ Z39.50 toolkit (runtime files)
libyaz5-dev - YAZ Z39.50 toolkit (development files)

**Comment by textbrowser** [comment]
You don't need to create a Debian package.

In Ubuntu 18.10 (also 18.04):
qtchooser -qt=5 -run-tool=qmake -o Makefile biblioteq.pro 
make

If you want to create a Debian package in newer Ubuntus, use LUBUNTU/control.

**Comment by sit42** [comment]
Without Debian package and using your commands from above, it compiled also ok.
Then I started the executable produced, and it worked once using SRU, but then with a second ISBN, I got the error again.

**Comment by textbrowser** [comment]
Are you using the latest source from GITHUB?

**Comment by textbrowser** [comment]
```
BiblioteQ Version 2018.12.12
Architecture __amd64__.
Compiled on Nov 8 2018, 22:12:33.
Copyright (c) 2005 - present, Mushroom.
Poppler version 0.68.0.
Qt version 5.11.1 (runtime 5.11.1).
YAZ version 5.19.2.
```

That's my version information.

**Comment by textbrowser** [comment]
What are the two ISBNs that you're testing with?

**Comment by sit42** [comment]
I used:
BiblioteQ Version 2018.10.01
Architecture __amd64__.
Compiled on Nov 14 2018, 17:28:32.
Copyright (c) 2005 - present, Mushroom.
Qt version 5.11.2 (runtime 5.11.2).
YAZ version 5.19.2.

I will download the newest github and do it again.

The two ISBNs used are:
9780672329463
and
9783446443436

But I tired many others.

PS: I just tried it again with the version I just mentioned.
And compared to this afternoon, it works much more stable. Now I only got once the error, while about 20 times it worked....

For me this looks like a kind of timing problem or network problem. So maybe if the timeouts are longer or you make the query at the "wrong" time, it gives this error. Just a guess, but because its also difficult now to reproduce the error, it seems that it is not a purely "logical" error,it has some timing in it probably...

**Comment by textbrowser** [comment]
I don't have timeout values for either query type.

Other factors: you're querying from Germany and this could introduce delays, LoC could have protections against repeated queries from non-US clients, network problems (wireless?).

If you're satisfied with the results, please close the ticket.

**Comment by textbrowser** [comment]
Have you tried a German SRU server?

http://www.dnb.de/EN/Service/DigitaleDienste/SRU/sru_node.html

**Comment by sit42** [comment]
Newly compiled on newest sources from github:
BiblioteQ Version 2018.12.12
Architecture __amd64__.
Compiled on Nov 14 2018, 19:56:29.
Copyright (c) 2005 - present, Mushroom.
Poppler version 0.62.0.
Qt version 5.11.2 (runtime 5.11.2).
YAZ version 5.19.2.

Seems that the new versions from source are somehow more stable or its just the time of day which helps.
I will try tomorrow again, just to be sure.
But currently it is much more stable!
The Z39.50 is still not working (always "Connection lost"), but as long as SRU is working its fine.

I will also try the german SRU tomorrow as a comparison to the US one.

**Comment by sit42** [comment]
So now I could test a bit more.

I have compiled it with the parameters from the last message from me.
I have started with a new sqlite file, empty database.
I have applied for the german national library, which took some time for the allowance and the access. But now we have access to it and queries from the browser work.

The following entry has been added to the config file:
`[SRU-2]
name = German National Library catalogues 
url_isbn = "http://services.dnb.de/sru/dnb?version=1.1&operation=searchRetrieve&query=isbn=%1 or isbn=%2&recordSchema=MARC21-xml"
###url_issn = "http://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.issn=%1&recordSchema=marcxml&startRecord=1&maximumRecords=100"
proxy_host =
proxy_port =
proxy_type = None
proxy_username =
proxy_password =`

When using this new SRU-2 alone it seems to work.
I tried 3 times with restarting the program and opening the "add" dialog many times.

BUT the following problems are still there:
1) When switching to SRU-1, it still gives often the reported error. If this is - as you already concluded - an access problem with the US SRU server, it would be nice to have a better error information, like "SRU server not accessible right now", etc.
-> If I switch from German SRU to US SRU it mostly does give the error. After one such error, the german SRU also does not work anymore. BUT After closing the "Add" Dialog, the german SRU works again.

2) The german SRU supports only the "MARC-21 XML" Format, which seems to be different from the "marcxml" of the SRU in the US.
Can you give me a hint on how to tell biblioteq to interpret the data send by the Marc-21 XML format and put them correctly into the fields in the dialog?

**Comment by textbrowser** [comment]
Good, good.

1. Error is provided by the server. See https://github.com/textbrowser/biblioteq/blob/master/Source/biblioteq_book.cc, starting with line 3457.
2. I'll research it.

**Comment by textbrowser** [comment]
Please post the XML of 9780672329463 using the DNB site. Use a browser.

**Comment by sit42** [comment]
http://services.dnb.de/sru/dnb?version=1.1&operation=searchRetrieve&query=isbn=9780672329463%20or%20isbn=0672329463%20&recordSchema=MARC21-xml

gives

`
<searchRetrieveResponse><version>1.1</version><numberOfRecords>0</numberOfRecords><records/><nextRecordPosition>1</nextRecordPosition><echoedSearchRetrieveRequest><version>1.1</version><query>isbn=9780672329463 or isbn=0672329463 </query><xQuery xsi:nil="true"/><recordSchema>MARC21-xml</recordSchema></echoedSearchRetrieveRequest><extraResponseData><accountOf>XXXXr</accountOf></extraResponseData></searchRetrieveResponse>
`

AND

http://services.dnb.de/sru/dnb?version=1.1&operation=searchRetrieve&query=isbn=9783446443436%20or%20isbn=3446443436%20&recordSchema=MARC21-xml

gives

`
<searchRetrieveResponse><version>1.1</version><numberOfRecords>1</numberOfRecords><records><record><recordSchema>MARC21-xml</recordSchema><recordPacking>xml</recordPacking><recordData><record type="Bibliographic"><leader>00000pam a2200000 c 4500</leader><controlfield tag="001">1070705543</controlfield><controlfield tag="003">DE-101</controlfield><controlfield tag="005">20161214223021.0</controlfield><controlfield tag="007">tu</controlfield><controlfield tag="008">150508s2017    gw ||||| |||| 00||||ger  </controlfield><datafield tag="015" ind1=" " ind2=" "><subfield code="a">16,A51</subfield><subfield code="z">15,N20</subfield><subfield code="2">dnb</subfield></datafield><datafield tag="016" ind1="7" ind2=" "><subfield code="2">DE-101</subfield><subfield code="a">1070705543</subfield></datafield><datafield tag="020" ind1=" " ind2=" "><subfield code="a">9783446443433</subfield><subfield code="c">Broschur : ca. EUR 34.99 (DE), ca. EUR 36.00 (AT), ca. sfr 46.90 (freier Pr.)</subfield><subfield code="9">978-3-446-44343-3</subfield></datafield><datafield tag="020" ind1=" " ind2=" "><subfield code="a">3446443436</subfield><subfield code="9">3-446-44343-6</subfield></datafield><datafield tag="024" ind1="3" ind2=" "><subfield code="a">9783446443433</subfield></datafield><datafield tag="028" ind1="5" ind2="2"><subfield code="a">Best.-Nr.: 553/44343</subfield></datafield><datafield tag="035" ind1=" " ind2=" "><subfield code="a">(DE-599)DNB1070705543</subfield></datafield><datafield tag="035" ind1=" " ind2=" "><subfield code="a">(OCoLC)909063715</subfield></datafield><datafield tag="040" ind1=" " ind2=" "><subfield code="a">1245</subfield><subfield code="b">ger</subfield><subfield code="c">DE-101</subfield><subfield code="d">9999</subfield><subfield code="e">rda</subfield></datafield><datafield tag="041" ind1=" " ind2=" "><subfield code="a">ger</subfield></datafield><datafield tag="044" ind1=" " ind2=" "><subfield code="c">XA-DE-BY</subfield></datafield><datafield tag="082" ind1="0" ind2="4"><subfield code="8">1\u</subfield><subfield code="a">658.5</subfield><subfield code="q">DE-101</subfield><subfield code="2">22/ger</subfield></datafield><datafield tag="083" ind1="7" ind2=" "><subfield code="a">650</subfield><subfield code="q">DE-101</subfield><subfield code="2">23sdnb</subfield></datafield><datafield tag="085" ind1=" " ind2=" "><subfield code="8">1\u</subfield><subfield code="b">658.5</subfield></datafield><datafield tag="090" ind1=" " ind2=" "><subfield code="a">b</subfield></datafield><datafield tag="100" ind1="1" ind2=" "><subfield code="0">(DE-588)1022425331</subfield><subfield code="0">http://d-nb.info/gnd/1022425331</subfield><subfield code="0">(DE-101)1022425331</subfield><subfield code="a">Leopold, Klaus</subfield><subfield code="d">1977-</subfield><subfield code="e">Verfasser</subfield><subfield code="4">aut</subfield></datafield><datafield tag="245" ind1="0" ind2="0"><subfield code="a">Kanban in der Praxis</subfield><subfield code="b">vom Teamfokus zur Wertschöpfung</subfield><subfield code="c">Klaus Leopold</subfield></datafield><datafield tag="264" ind1=" " ind2="1"><subfield code="a">München</subfield><subfield code="b">Hanser</subfield><subfield code="c">[2017]</subfield></datafield><datafield tag="300" ind1=" " ind2=" "><subfield code="a">XII, 225 Seiten</subfield><subfield code="b">Illustrationen</subfield><subfield code="c">25 cm</subfield></datafield><datafield tag="336" ind1=" " ind2=" "><subfield code="a">Text</subfield><subfield code="b">txt</subfield><subfield code="2">rdacontent</subfield></datafield><datafield tag="337" ind1=" " ind2=" "><subfield code="a">ohne Hilfsmittel zu benutzen</subfield><subfield code="b">n</subfield><subfield code="2">rdamedia</subfield></datafield><datafield tag="338" ind1=" " ind2=" "><subfield code="a">Band</subfield><subfield code="b">nc</subfield><subfield code="2">rdacarrier</subfield></datafield><datafield tag="650" ind1=" " ind2="7"><subfield code="0">(DE-588)4202406-7</subfield><subfield code="0">http://d-nb.info/gnd/4202406-7</subfield><subfield code="0">(DE-101)042024064</subfield><subfield code="a">Kanban-System</subfield><subfield code="2">gnd</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(Produktform)Hardback</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">Agile Softwareentwicklung</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">Agilität</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">Change Management</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">Kanban</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">Lean IT</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(VLB-WN)1632: Hardcover, Softcover / Informatik, EDV/Informatik</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(BISAC Subject Heading)COM032000</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">FBITMETH: Scrum, Kanban & Co.</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">INF2016</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(Artikeltyp)00100</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(Artikelmerkmal)41</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(Verlagssektor)55300</subfield></datafield><datafield tag="653" ind1=" " ind2=" "><subfield code="a">(Produktgruppe)65530</subfield></datafield><datafield tag="689" ind1="0" ind2="0"><subfield code="0">(DE-588)4202406-7</subfield><subfield code="0">http://d-nb.info/gnd/4202406-7</subfield><subfield code="0">(DE-101)042024064</subfield><subfield code="D">s</subfield><subfield code="a">Kanban-System</subfield></datafield><datafield tag="689" ind1="0" ind2=" "><subfield code="5">DE-101</subfield><subfield code="5">DE-101</subfield></datafield><datafield tag="776" ind1="0" ind2="8"><subfield code="i">Erscheint auch als</subfield><subfield code="n">Online-Ausgabe</subfield><subfield code="z">9783446446540</subfield></datafield><datafield tag="776" ind1="0" ind2="8"><subfield code="i">Erscheint auch als</subfield><subfield code="n">Online-Ausgabe</subfield><subfield code="a">Leopold, Klaus</subfield><subfield code="t">Kanban in der Praxis</subfield><subfield code="d">München : Carl Hanser Verlag GmbH & Co. KG, 2016</subfield><subfield code="h">Online-Ressource</subfield><subfield code="w">(DE-101)1118915062</subfield></datafield><datafield tag="850" ind1=" " ind2=" "><subfield code="a">DE-101a</subfield><subfield code="a">DE-101b</subfield></datafield><datafield tag="856" ind1="4" ind2="2"><subfield code="m">X:MVB</subfield><subfield code="q">text/html</subfield><subfield code="u">http://deposit.dnb.de/cgi-bin/dokserv?id=5242961&prov=M&dok_var=1&dok_ext=htm</subfield><subfield code="3">Inhaltstext</subfield></datafield><datafield tag="856" ind1="4" ind2="2"><subfield code="m">B:DE-101</subfield><subfield code="q">application/pdf</subfield><subfield code="u">http://d-nb.info/1070705543/04</subfield><subfield code="3">Inhaltsverzeichnis</subfield></datafield><datafield tag="925" ind1="r" ind2=" "><subfield code="a">ra</subfield></datafield><datafield tag="926" ind1="1" ind2=" "><subfield code="a">UY</subfield><subfield code="o">93</subfield><subfield code="q">WGSneuMapping</subfield><subfield code="v">1.0</subfield><subfield code="x">Informatik</subfield></datafield></record></recordData><recordPosition>1</recordPosition></record></records><nextRecordPosition>2</nextRecordPosition><echoedSearchRetrieveRequest><version>1.1</version><query>isbn=9783446443436 or isbn=3446443436 </query><xQuery xsi:nil="true"/><recordSchema>MARC21-xml</recordSchema></echoedSearchRetrieveRequest><extraResponseData><accountOf>XXXXX</accountOf></extraResponseData></searchRetrieveResponse>
`

**Comment by textbrowser** [comment]
For the first ISBN (0672329463), you'll notice that the number-of-records is 0. I'll review the second.

**Comment by textbrowser** [comment]
Super great fantastic absolutely good nice awesome.
