### ISSUE TITLE
Why member management in biblioteq did not work with sqlite?

### ISSUE THREAD

**Issue by bibliotheq** [textbrowser/biblioteq#44]
Hey,

i will use biblioteq with administrator roles using sqlite as database and not postpresql.

Is that possible?

Thanks for your help!

Regards

**Comment by textbrowser** [comment]
Hey, what's going on? Patron management works with both database types. Administrator roles are for PQ only because SQLite is not a networked database. If you have an SQLite file, you own the file. So, you're an administrator.

**Comment by textbrowser** [comment]
So, yes, it's all possible. If it's not possible, make it possible!

**Comment by bibliotheq** [comment]
ok, thanks.

**Comment by textbrowser** [comment]
Super welcome.
