### ISSUE TITLE
Help importing into Biblioteq

### ISSUE THREAD

**Issue by daveslab** [textbrowser/biblioteq#45]
Hi folks,

I would like to import a database of 5000 books into Biblioteq. I realize that you haven't integrated this functionality yet and that it's difficult to do so. However, I've already given it a try by importing directly into the SQLite tables and it didn't quite work (added the records to the book table, but then saw that I needed some in book_copy_info). 

Is there anywhere I can find documented how to do this? I only have three columns: author, title, dewey number.

Thank you for any guidance!

**Comment by textbrowser** [comment]
Hello. Importing is not possible through BQ. There are several tickets and a TO-DO item covering this request. There are many tables in the BQ schema and each table has peculiarities. However, it is quite possible to write a script as long as your insert statements adhere to the constraints of the tables. Read Source/biblioteq_sqlite_create_schema.h.

**Comment by textbrowser** [comment]
It has begun.

https://github.com/textbrowser/biblioteq/commit/ad89842f9182f5e0e4f2b71b768d7bed29c2bef6

**Comment by textbrowser** [comment]
The importing of books has been completed. One mapping template is included. Additional templates require software changes. The import mechanism allows an operator to define the mappings.
