### ISSUE TITLE
Help with translations is needed, please.

### ISSUE THREAD

**Issue by ChekPuk** [textbrowser/biblioteq#46]
Hello. Recently found your project, looks very interesting. Wanted to add some translations, but stuck with strange issue. Can you help me with it?

First problem is that I can't edit existing translations. I took german translation as a base, wanted to edit it, but it doesn't let me to do it. Copied ts file, renamed it to the language I want, but still it is blocked. And so is with every translation. There are some untranslated lines in some files, I can edit these lines, but not anything else. Tried with both - Qt4 Linguist and with Qt5 Linguist.

Second problem is - when I try to generate language file with 'lupdate' command it generates empty file. I add my language to biblioteq-source.pro file and run lupdate. It says
```
$ lupdate -verbose biblioteq-source.pro
Info: creating stash file /Data1/kostia/Bin/git/biblioteq/.qmake.stash
Updating 'Translations/biblioteq_ar_JO.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_cs_CZ.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_de_DE.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_el_GR.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_fr_FR.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_hu_HU.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_it_IT.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_nl_BE.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_nl_NL.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_zh_CN.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
Updating 'Translations/biblioteq_ru_RU.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
```

Can you help me with this? I've looked thru internet and didn't found a solution except that my Qt might be to new. I am running Manjaro with Qt 5.12.0 and Qt 4.8.7. Program compiles well with Qt5, existing translations are present in running app.

**Comment by textbrowser** [comment]
The paths in biblioteq-source.pro were specialized for Windows. Update your repository and try again.

**Comment by ChekPuk** [comment]
Thank you, file has generated. Working on the translation. But I see a lot of administration/priveleged menus and items in translation file. In my Biblioteq with SQLite all administrative buttons are greyed out. Does it mean that it only works in PostgreSQL? Is there manual for using PostgreSQL?

**Comment by textbrowser** [comment]
Yes and yes. There are many PQ manuals (https://www.postgresql.org/docs/). Many printed documents too. BQ supports PQ and SQ.

**Comment by ChekPuk** [comment]
No, I mean how to make Biblioteq to use PostgreSQL? What user should I create and how to pass it to Biblioteq? I tried to start Biblioteq --help, but there was nothing and in database selection only SQLite is listed. Ofcourse, I better should create another topic about that.

**Comment by textbrowser** [comment]
Yes. See the Documentation directory. There is information pertaining to preparing a PQ schema.

**Comment by ChekPuk** [comment]
Thank you. I'll return when finish translation

**Comment by textbrowser** [comment]
A Russian translation file has been provided. Please see https://github.com/textbrowser/biblioteq/issues/47. Closing this ticket. Please contribute additions to the other ticket. Thanks. Bye-bye now. See you. Later.

**Comment by ChekPuk** [comment]
Sory, had absoltely no time to finish by my self. Thank you for your work.

**Comment by textbrowser** [comment]
It's fine. Mr. L. provided the translation. You can refer to the other ticket. Thanks and good luck!
