### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by leemour** [textbrowser/biblioteq#48]
I followed the following instructions:

> a) Download the W32 online installer from http://download.qt.io/official_releases/online_installers/
> b) Capture the BQ source (GitHub has a W32 interface somewhere)
> c) I use the W32 terminal (one is prepared by the Qt installer), or much luck with Qt's Creator
> d) qmake -o Makefile biblioteq.win.pro (terminal)
> e) make

I installed Qt 5.13, QtCreator.
For step c) I launched `Qt 5.13.0 (MinGW 7.3.0 32bit)` terminal
When I run `qmake -o Makefile biblioteq.win.pro` inside the root of the source code I downloaded from github, I get:
```
Info: creating stash file C:\biblioteq-master\.qmake.stash
Info: creating cache file C:\biblioteq-master\.qmake.cache
```
Then when I try to run `make` I get 
```
'make' is not recognized as an internal or external command,operable program or batch file
```
 What should I do?

**Comment by textbrowser** [comment]
From https://github.com/textbrowser/biblioteq/blob/master/Documentation/COMPILING: 
> qmake -o Makefile biblioteq.win.pro
> make or mingw32-make

**Comment by leemour** [comment]
`mingw32-make` started compiling and then I got this error:
```
C:/Qt/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lyaz5
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [Makefile.Release:223: release/BiblioteQ.exe] Error 1
mingw32-make[1]: Leaving directory 'C:/biblioteq-master'
mingw32-make: *** [Makefile:38: release] Error 2
```
How can I install -lyaz5? I tried `mingw-get` but it doesn't exist.

I also remember you mentioned something about the version change. What do I need to do about it?

**Comment by textbrowser** [comment]
The version change of BQ. As you're compiling from the latest source, you're fine.

That's a linking error. I don't understand it as I've never encountered it before on W32. You do have the non-empty Libraries.win32/yaz.d directory, yes?

**Comment by leemour** [comment]
Yep, it's not empty. Where are the links stored? Maybe I can check the path/change it?

Would it be possible for you to compile a windows version for me with my translations so I can start using it while I'm trying to compile it myself?

**Comment by textbrowser** [comment]
I will have to schedule a release. Will see.

**Comment by leemour** [comment]
Ok, thanks!

**Comment by textbrowser** [comment]
Compiled and link with Qt 5.9.7.
![screenshot](https://user-images.githubusercontent.com/10701156/54446037-6f17d500-471c-11e9-84ee-15d158bf3e07.png)

**Comment by textbrowser** [comment]
Done, released. Please experiment.

**Comment by leemour** [comment]
It works, thanks a lot! Btw I see you use an old version of Qt (5.9 vs me using 5.13) and MinGW(5.3 vs me using 7.3) so did you install it some time ago? Probably that's why you don't have errors compiling it?

**Comment by textbrowser** [comment]
Qt 5.x is LTS. See https://en.wikipedia.org/wiki/Qt_version_history. I'll introduce 5.12 in the future.

**Comment by textbrowser** [comment]
Qt 5.9.x.

**Comment by leemour** [comment]
Alright! I'll try to use 5.9 and see how it works. Suprisingly, installing Qt was taking several hours so I had to do it overnight.
