### ISSUE TITLE
Editting information in BiblioteQ

### ISSUE THREAD

**Issue by hfjabre** [textbrowser/biblioteq#49]
Good evening. I would like to enter information for language, monetary units, location, originality, condition, and book binding type. However, these are in grey and do not allow for editing. They seem to be locked as a default. Any idea why or any suggestions on how to change them? Thanks

**Comment by textbrowser** [comment]
Please post an image.

**Comment by textbrowser** [comment]
If you're in View mode, you won't be able to edit items. If you need to define new languages, see the Database Enumerations Browser.

**Comment by hfjabre** [comment]
[cid:b934d3f5-13ea-4868-89e0-236375f8337c]
All of pull downs that say "unknown". These don't give or allow for any other option.
________________________________

**Comment by textbrowser** [comment]
See the Database Enumerations Browser. It will allow you to define new values.

**Comment by textbrowser** [comment]
All set? Please also read the included documentation!
