### ISSUE TITLE
Enumerations not saved

### ISSUE THREAD

**Issue by paolofrancioso** [textbrowser/biblioteq#5]
Hello,
if you create locations in enumerations, save, quit the application and go to enumerations database again all the previous enumerations are lost. I think they are not fetched from DB when the page is loaded, but if you press save again when the form is in this status you lose all your data because empty enumerations are saved.

**Comment by paolofrancioso** [comment]
Fixed with populate enumaration database at display. I suggest to flag this by default or you risk to lose data.

**Comment by textbrowser** [comment]
Yes, you have to save the changes. A reminder of stale data is probably helpful. I'll see what I can do.

**Comment by textbrowser** [comment]
OK, so a reminder will be much work. Modifying the default option will require a change to another option that controls the saving of the options. The defaults, I think, are fine. So let's proceed with a reminder.

**Comment by textbrowser** [comment]
Reminder completed.

https://github.com/textbrowser/biblioteq/commit/367de6662b65bf8830479de2d47fe2fb3f11fb87

Closing.
