### ISSUE TITLE
Read and save settings to user directory

### ISSUE THREAD

**Issue by coldacid** [textbrowser/biblioteq#51]
For situations where the install directory cannot be written to, retain support for writing to a dot-directory in the user's home directory instead, and always read settings from same directory.

**Comment by textbrowser** [comment]
Are you referring to the biblioteq.conf file?

**Comment by coldacid** [comment]
No, actually the `.biblioteq/biblioteq.ini` file that gets saved by Options -> Save Settings in the menu.

**Comment by textbrowser** [comment]
The INI file is stored in the user's home directory. The home path is determined as:

```
#ifdef Q_OS_WIN32
  return QDir::currentPath() + QDir::separator() + ".biblioteq";
#else
  return QDir::homePath() + QDir::separator() + ".biblioteq";
#endif
```

Are you experiencing problems?

**Comment by coldacid** [comment]
Yes, and that would be the problem. In situations where BiblioteQ is installed to a normally read-only directory (such as when using software management automation like Chocolatey) user settings changes can't be saved.

Based on the code above, I launched BiblioteQ from a temporary directory, but then the app complained that it couldn't find the conf file. However it did save the INI to `.biblioteq/BiblioteQ/BiblioteQ.ini` inside that temp directory. (I guess the extra "BiblioteQ" in the path is because `QSettings::setPath()` expects a common settings directory and creates its own subdirectory for the app within it.) Because of this behaviour, setting up shortcuts with the "Start in" propery set to "%USERPROFILE%" won't work (right now) because then the app can't find its common settings.

It looks like there's a couple issues here, but at least the one for finding biblioteq.conf when run from a directory other than the install directory appears to be simple to fix. Changing line 3306 in biblioteq_a.cc to `QSettings settings(QCoreApplication::applicationDirPath() + QDir::separator() + "biblioteq.conf", QSettings::IniFormat);` will ensure that on Windows the conf file will always be located in the install directory. With that, using the shortcut "Start in" property can be set to "%USERPROFILE%" and configuration should work for both portable and managed installs.

**Comment by textbrowser** [comment]
Have you confirmed the changed path? I will also test it when I'm on a Windows machine.

Thanks.

**Comment by coldacid** [comment]
Unfortunately I can't get BiblioteQ to build at all on Windows but based on the Qt docs this should work just fine.

During build, the headers for SQLite and YAZ can't be found by g++ despite being in Include.win32/sqlite3.d and Include.win32/yaz.d. However this is a different issue.

**Comment by textbrowser** [comment]
I have access to Windows 7 only. How do you build on Windows? Qt's Creator or a terminal? I use a terminal.

**Comment by coldacid** [comment]
I'm working from msys2 in the terminal on Windows 10. I ran the script for grabbing the prerequisites, then followed the instructions in the COMPILING file.

**Comment by textbrowser** [comment]
Try the Qt DOS terminal.

**Comment by coldacid** [comment]
There's a Qt shell? I've installed Qt into an existing msys2 setup to avoid a separate msys2 just for Qt.

**Comment by textbrowser** [comment]
Yes. It's somewhere in the Qt menu.

**Comment by coldacid** [comment]
I can't find any such thing even after setting up a new Qt install on my system.

**Comment by textbrowser** [comment]
Which version of Qt?

**Comment by coldacid** [comment]
5.12.3

**Comment by textbrowser** [comment]
https://stackoverflow.com/questions/24219732/where-can-i-found-qt-5-3-0-command-prompt

**Comment by textbrowser** [comment]
https://www.seppemagiels.com/sites/default/files/images/qt-terminal.png

**Comment by coldacid** [comment]
Yeah so I guess the only way to get it is to have a duplicate msys install :(

**Comment by textbrowser** [comment]
What's msys? Cygwin?

**Comment by textbrowser** [comment]
For Qt on W32, I use the Qt online installer.

**Comment by coldacid** [comment]
MSYS is an improved Mingw environment that supports both 32- and 64-bit toolchains.

**Comment by coldacid** [comment]
Okay so after installing a new Qt kit for mingw32 through the Qt installer, I still get the build failure on `#include`.

```
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'C:/Users/chris/source/Repos/biblioteq'
g++ -c -fno-keep-inline-dllexport -O2 -Wall -Wcast-align -Wcast-qual -Wextra -Wformat=2 -Woverloaded-virtual -Wpointer-arith -Wstrict-overflow=5 -fwrapv -mtune=generic -pie -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DBIBLIOTEQ_LINKED_WITH_POPPLER -DBIBLIOTEQ_POPPLER_VERSION_DEFINED -DQT_NEEDS_QMAIN -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -ISource -IInclude.win32 -IInclude.win32\poppler.d\cpp -IInclude.win32\poppler.d\qt5 -Itemp -IC:\Qt\5.12.3\mingw73_32\include -IC:\Qt\5.12.3\mingw73_32\include\QtPrintSupport -IC:\Qt\5.12.3\mingw73_32\include\QtWidgets -IC:\Qt\5.12.3\mingw73_32\include\QtGui -IC:\Qt\5.12.3\mingw73_32\include\QtANGLE -IC:\Qt\5.12.3\mingw73_32\include\QtNetwork -IC:\Qt\5.12.3\mingw73_32\include\QtSql -IC:\Qt\5.12.3\mingw73_32\include\QtCore -Irelease -Itemp -IC:\Qt\5.12.3\mingw73_32\mkspecs\win32-g++  -o release\biblioteq_a.o Source\biblioteq_a.cc
Source\biblioteq_a.cc:69:10: fatal error: sqlite3/sqlite3.h: No such file or directory
 #include <sqlite3/sqlite3.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [Makefile.Release:6908: release/biblioteq_a.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/chris/source/Repos/biblioteq'
mingw32-make: *** [Makefile:38: release] Error 2
```

**Comment by textbrowser** [comment]
Let me see. I renamed some directories recently.

**Comment by textbrowser** [comment]
OK, changed. Please try again.

**Comment by coldacid** [comment]
Still failing, now due to paths within the Yaz include files themselves. Looks like they expect to be in an include subdirectory called `yaz` rather than `yaz.d`.

```
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'C:/Users/chris/source/Repos/biblioteq'
g++ -c -fno-keep-inline-dllexport -O2 -Wall -Wcast-align -Wcast-qual -Wextra -Wformat=2 -Woverloaded-virtual -Wpointer-arith -Wstrict-overflow=5 -fwrapv -mtune=generic -pie -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DBIBLIOTEQ_LINKED_WITH_POPPLER -DBIBLIOTEQ_POPPLER_VERSION_DEFINED -DQT_NEEDS_QMAIN -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -ISource -IInclude.win32 -IInclude.win32\poppler.d\cpp -IInclude.win32\poppler.d\qt5 -Itemp -IC:\Qt\5.12.3\mingw73_32\include -IC:\Qt\5.12.3\mingw73_32\include\QtPrintSupport -IC:\Qt\5.12.3\mingw73_32\include\QtWidgets -IC:\Qt\5.12.3\mingw73_32\include\QtGui -IC:\Qt\5.12.3\mingw73_32\include\QtANGLE -IC:\Qt\5.12.3\mingw73_32\include\QtNetwork -IC:\Qt\5.12.3\mingw73_32\include\QtSql -IC:\Qt\5.12.3\mingw73_32\include\QtCore -Irelease -Itemp -IC:\Qt\5.12.3\mingw73_32\mkspecs\win32-g++  -o release\biblioteq_a.o Source\biblioteq_a.cc
In file included from Source\biblioteq_a.cc:74:0:
Include.win32/yaz.d/yaz-version.h:33:10: fatal error: yaz/yconfig.h: No such file or directory
 #include <yaz/yconfig.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [Makefile.Release:6916: release/biblioteq_a.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/chris/source/Repos/biblioteq'
mingw32-make: *** [Makefile:38: release] Error 2
```

**Comment by textbrowser** [comment]
I did change that path too.

**Comment by textbrowser** [comment]
```
extern "C"
{
#include <math.h>
#ifdef Q_OS_WIN32
#include <sqlite3.d/sqlite3.h>
#else
#include <sqlite3.h>
#endif
#ifdef Q_OS_WIN32
#include <yaz.d/yaz-version.h>
#else
#include <yaz/yaz-version.h>
#endif
}
```

**Comment by coldacid** [comment]
Yeah but yaz.d/yaz-version.h is itself trying to `#include <yaz/yconfig.h>` and failing since none of the include directories have a yaz/ directory in them.

**Comment by textbrowser** [comment]
Ah, I see. OK. Let me rename the directories to their original names.

**Comment by textbrowser** [comment]
OK, renamed.

**Comment by coldacid** [comment]
Alright, now compilation is failing in biblioteq_a.cc in two places where `#elif def(Q_OS_WIN32)` is used instead of `#elif defined(Q_OS_WIN32)`. Making those changes produced a successful build, but it looks like it's still trying to find biblioteq.conf in the app working directory rather than the app install directory. At least now perhaps I can get into debugging and figure out why.

**Comment by textbrowser** [comment]
Sorry about the numerous errors. Also corrected.

**Comment by textbrowser** [comment]
I think I know why.

**Comment by coldacid** [comment]
If stumbling across bugs and errors means I get a better program in the end, then it's all good!

**Comment by textbrowser** [comment]
OK, committed.

**Comment by coldacid** [comment]
Ah, I missed a spot! Looks like it works now, thanks.

Did find a couple more bugs that I'll file, to do with the user-specific config.
