### ISSUE TITLE
Add Open Library API covers support

### ISSUE THREAD

**Issue by coldacid** [textbrowser/biblioteq#53]
It'd be quite nice to have Open Library as an alternate to Amazon for book covers. API docs are at https://openlibrary.org/dev/docs/api/covers

**Comment by textbrowser** [comment]
Yes, that's a good idea and the implementation is as simple as the one for Amazon.

**Comment by textbrowser** [comment]
Completed for book covers. Also added a TO-DO item for journals/magazines.
