### ISSUE TITLE
Dropdown menus showing "UNKNOWN"

### ISSUE THREAD

**Issue by FriedrichFroebel** [textbrowser/biblioteq#59]
I just wanted to give BiblioteQ a try using an SQLite3 database on Ubuntu 18.04 using the current master. Although I have a German system, I changed the interface to English and restarted the application as the German translation seems to be incomplete at the moment.

After creating the database, I wanted to create a new book entry, but for some reason some of the dropdown menus in this dialog only have an entry "UNKNOWN". This seems to affect the book binding type, the language, the monetary units and the location. What should I do to be able to select the book language for example?

**Comment by textbrowser** [comment]
That's normal behavior. See Database Enumerations. BQ has a document which answers this question. Most of the translations are incomplete because translators vanish.

[BiblioteQ.pdf](https://github.com/textbrowser/biblioteq/files/3407661/BiblioteQ.pdf)

**Comment by FriedrichFroebel** [comment]
Thanks for the hint - I must have missed that while having a look at the manual or have it mistaken for another feature not related to my problem.

If I have familiarized myself further with the application itself and find some time for it, I will probably have a look at the German translation to make it more complete.

**Comment by textbrowser** [comment]
That would be nice of you. Thanks. :o)
