### ISSUE TITLE
Impossible to search for multiple words

### ISSUE THREAD

**Issue by paolofrancioso** [textbrowser/biblioteq#6]
Hello,

I tried to search multiple keywords, complex DB search using \* or + but it's not possibile to search more than one word at once. Is this an issue or a new feature to implement?

Thank you

**Comment by textbrowser** [comment]
You're right. This is not available. Many of the item field widgets display the data as hyper links. I could add this feature in the general search panel.

**Comment by textbrowser** [comment]
This is another challenging solution. The query text must be separated into tokens and then dynamic conjunctive queries must be created.

**Comment by textbrowser** [comment]
Using the wizard, you can create custom queries.

**Comment by textbrowser** [comment]
The General Search panel now offers new options for constructing queries from multiple words. Fields: Abstract, Categories, Keywords.

The other search panels will not include these changes.
