### ISSUE TITLE
Can BQ integrate with Zotero?

### ISSUE THREAD

**Issue by nafergo** [textbrowser/biblioteq#61]
Can we export-import between these two softwares?
Zotero would be useful for online sharing and BW for inhouse.

 Zotero can import among others the following bibliographic file formats:

    Zotero RDF
    CSL JSON
    MODS (Metadata Object Description Schema)
    BibTeX
    RIS
    Refer/BibIX
    Unqualified Dublin Core RDF
    Bibliontology RDF
    Endnote XML
    XML ContextObject
    Web of Science Tagged
    MEDLINE/nbib

Zotero can export among others the following  file formats:
    Zotero RDF
   CSL JSON
    MODS (Metadata Object Description Schema)
    BibTeX
    RIS
    Refer/BibIX
    Unqualified Dublin Core RDF
    Bibliontology RDF
    Endnote XML
    CSV
    COinS

**Comment by textbrowser** [comment]
Need more information. Currently working on an import of books. It'll feature format templates. BQ has an export feature: comma-separated values. Outside of BQ, PostgreSQL offers its own export/import tools.

**Comment by textbrowser** [comment]
The import is complete. :)

**Comment by enricllagostera** [comment]
Hi, that is great news, thank you! Do you have an estimate on when you'll release a public build with that feature? This is what has been holding us back from using the software. 😄 Thank you.

**Comment by textbrowser** [comment]
It's scheduled for 2020.01.01. The import includes a single template based on BQ. Additional templates require software changes. One can also define the import based on the contents of a CSV file. Importing of images is not supported.

The test case: exported a bunch of books from a PQ database. Imported the CSV file into an SQLite database. Exported the SQLite books to a separate CSV file. Compared the two CSV files.

![Screenshot_20191225_114235](https://user-images.githubusercontent.com/10701156/71448573-b00d3300-270b-11ea-8f09-5abee224d2a5.png)

**Comment by textbrowser** [comment]
If other types (journals, etc.), BQ will require changes.
