### ISSUE TITLE
Help by translation in Persian

### ISSUE THREAD

**Issue by metemaddar** [textbrowser/biblioteq#62]
Thank you dear developers for great work.
I would like to help ourselves by committing translation in Persian language.
I understand English and I can create PO file from English version.
It would be appreciated to help me about getting the English PO file.

Express Thanks.

**Comment by textbrowser** [comment]
From the documentation:

``Translations are incomplete. Translating BiblioteQ is quite simple. Please download and install Qt from https://download.qt.io, download BiblioteQ’s source, and familiarize yourself with Qt’s Linguist.
Linguist documentation is available at https://doc.qt.io/qt-5/qtlinguist-index.html.``

Please let me know if you need additional help.

**Comment by textbrowser** [comment]
Were you able to start the translation process?

**Comment by textbrowser** [comment]
Super silent operator. Added as a reminder. Closing.
