### ISSUE TITLE
Problem installing 2020.01.01 Ubuntu 18.04

### ISSUE THREAD

**Issue by nafergo** [textbrowser/biblioteq#63]
problem is that Ubuntu 18.04 is still on libqt5core5a  5.9
and Blilioteq requires libqt5core5a  >=5.11.0

I was under the impression that previous available release installed well on my ubuntu 18.04 machine...

**Comment by textbrowser** [comment]
I can modify the control file but I don't know if a new package will help you. What's the minor version of Qt on 18.04?

**Comment by textbrowser** [comment]
Please see https://github.com/textbrowser/biblioteq/commit/9a87337921a6634d3c12bbc1fbf5e30b8f1d975e#diff-e526ec5288b4342c6cb9f2fbc38523a2.

**Comment by nafergo** [comment]
Ubuntu 18.04 is  on 5.9.5

**Comment by textbrowser** [comment]
Qt 5.5.1 (https://github.com/textbrowser/biblioteq/commit/4c3371e3e6bd64e978dc98912897120ddf8d2c96). The non-Qt 5 dependencies remain unchanged. Will create a new bundle and include it here. Let me know if it works.

**Comment by textbrowser** [comment]
[BiblioteQ-2020.01.01_amd64.deb.gz](https://github.com/textbrowser/biblioteq/files/4030556/BiblioteQ-2020.01.01_amd64.deb.gz)
Here you go.

**Comment by nafergo** [comment]
Error dependency is not satisfiable libyaz5 (>=5.25)

**Comment by textbrowser** [comment]
Ugh. Which version do you have?

**Comment by textbrowser** [comment]
[BiblioteQ-2020.01.01_amd64.deb.gz](https://github.com/textbrowser/biblioteq/files/4032565/BiblioteQ-2020.01.01_amd64.deb.gz)
Try this one. :)

**Comment by nafergo** [comment]
not working... 
when I run /usr/local/biblioteq$ ./biblioteq.qt5.sh 
returns 
./BiblioteQ: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./BiblioteQ)

**Comment by textbrowser** [comment]
What does ldd /usr/local/biblioteq/BiblioteQ return?

**Comment by textbrowser** [comment]
You can also build BQ from source. Much easier.

**Comment by textbrowser** [comment]
Closing this. I do not have a machine to prepare BQ for U2018. I can help with a build from source if interested.
