### ISSUE TITLE
No ISBN when exporting to .csv?

### ISSUE THREAD

**Issue by neuralpositive** [textbrowser/biblioteq#64]
When exporting to .csv, and then trying to open in Excel, it opens with Title, Quantity, Location, Availability and Total Reserved. But no ISBN? Is there a way of configuring what tags are exported to the .csv file?

**Comment by textbrowser** [comment]
The exported columns include the viewable columns.

**Comment by textbrowser** [comment]
Will add this information to the documentation.

**Comment by neuralpositive** [comment]
Thank you very much.

**Comment by textbrowser** [comment]
Are you able to export ISBNs now?

**Comment by neuralpositive** [comment]
Yes it worked this time thank you.
