### ISSUE TITLE
SRU-Formats other than marcxml

### ISSUE THREAD

**Issue by eineerdnuss** [textbrowser/biblioteq#65]
Is there a way to process SRU querys witch don't support marcxml, but instead mark21-xml or similliar formats?

**Comment by textbrowser** [comment]
This http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd?

**Comment by textbrowser** [comment]
Hellooooooooooooooooooooooooooooooooo? Is you present?

**Comment by textbrowser** [comment]
Absent operator. Lack of interest? Silence? Closing!

**Comment by textbrowser** [comment]
Please re-open with detailed details.

**Comment by textbrowser** [comment]
The record-schema value which is supported is marcxml. Which other schemas are you interested in?

https://www.loc.gov/z39voy?operation=searchRetrieve&version=1.1&query=bath.isbn=0786851112&recordSchema=dc&startRecord=1&maximumRecords=1
