### ISSUE TITLE
No support Documentation

### ISSUE THREAD

**Issue by bakertaylor28** [textbrowser/biblioteq#66]
This package needs support documentation on how to setup, deploy, and use the software.

**Comment by textbrowser** [comment]
You be trolling!

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/tree/master/Documentation

Documentation overflow!

**Comment by textbrowser** [comment]
[x] Administration Information
[x] Compilation Instructions
[x] Contributed Documentation
[x] General Documentation

**Comment by textbrowser** [comment]
Documentation has been spread. Hopefully, it's not a cheeky resolution. If concerned, please do not hesitate to butt in the conversation. Thanks.
Closing!
