### ISSUE TITLE
Publication Date Format option

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#68]
Good evening,
I have a problem with above mentioned option: i.e. when I try to set it in "BiblioteQ: Other Options" (Item Type: Books) as "yyyy", after a book is added, I see the date in the main table "Publication Date" as e.g. 1981-01-01, 2007-01-01 etc.
Any idea? Thank you in advance.

**Comment by textbrowser** [comment]
The option only applies to item details.

**Comment by textbrowser** [comment]
https://textbrowser.github.io/biblioteq/

January 4, 2013.
    Display formats of dates have been changed to ISO 8601.

**Comment by jerzyPL** [comment]
OK, understood.

**Comment by textbrowser** [comment]
ISO 8601 is suitable for natural sorting. Would you like the option to be applied to categories too? Some of the formats will prevent correct sorting.

**Comment by textbrowser** [comment]
Added information to Other Options regarding date formats.

Thank you for the ticket! :)

**Comment by jerzyPL** [comment]
Just because, I think, a catalogue description usually looks like this: "Publisher: New York : Oxford University Press, 2009, ©**2007**" ( https://www.worldcat.org/title/new-english-translation-of-the-septuagint-and-the-other-greek-translations-traditionally-included-under-that-title/oclc/782046916&referer=brief_results ), and not: "A new English translation of the Septuagint : and the other Greek translations traditionally included under that title | Oxford University Press | **2007-01-01**".
______
BTW: I translated BQ into Polish, but...
As I am not familiar with Qt and all these "lupdate" sophisticated mysteries etc., I begun my translation using the Greek "biblioteq_el_GR" qm file. Then, I realize, that Greek version has not all entries translated, so I turned to the German qm file and finally almost finished my translation, but...
After all I still have the English word "Search" in the Main Window at the scrolling menu: Category / ID / Keyword / Title. I found every instance of "Suche" and "Αναζήτηση" to make it Polish "Szukaj", but this "Search" still remains...
So I am asking you, if it's possible, to send me a file (*ts, *po or anything else) with complete current set of English source text commands in BQ, which I can open and edit/translate using my Qt Linguist version 5.12.2. Thank you.

**Comment by textbrowser** [comment]
Translations are provided by volunteers. Most of the translation files have aged poorly.

Just added biblioteq_pl_PL.ts.

**Comment by textbrowser** [comment]
As for publication dates, a good solution is a lot of work. For instance, consider the All category. Displayed will be items of varying types. One solution would be to adhere to the specific item types while another solution is to have a format specific to All. Then there is the problem with sorting items by dates.

**Comment by jerzyPL** [comment]
First: Thank you for biblioteq_pl_PL.ts file.
It was a problem while opening it, but I solved it by copying the content first into Notepad and finally opening in Qt Linguist (pure barbarian way ;-)
Second: You are absolutely right. My point of view is, let me call it "bookcentric", and I actually don't pay so much attention to the other categories...
See you soon, and thank you.

**Comment by textbrowser** [comment]
Qt Linguist manual for translators.

https://doc.qt.io/qt-5/linguist-translators.html

**Comment by textbrowser** [comment]
I opened the "PL".ts file via Linguist and Linguist complained about missing source files. You will need BQ's source files during the translation process.

**Comment by jerzyPL** [comment]
Yes, Qt Linguist says: "**Unexpected tag at** _[-my path-]_ **biblioteq_pl_PL.ts:7:16**", and you say that I will need source files.
It means that I have to look up into all these ( https://github.com/textbrowser/biblioteq/tree/master/Source ) files, or some specific?

**Comment by textbrowser** [comment]
Yes, download the source.

On Debian.

cd biblioteq.d
linguist Translations/biblioteq_pl_PL.ts 

Something similar for your environment.

**Comment by textbrowser** [comment]
git clone https://github.com/textbrowser/biblioteq biblioteq.d

Or download the ZIP bundle from GH.

**Comment by textbrowser** [comment]
Completed! Dates will be displayed according to category formats, except for non-specific categories. For example, dates within the All category will be displayed in the ISO-8601 format.

**Comment by textbrowser** [comment]
Available in the next release. Closing.
