### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#69]
Good afternoon,
I have made files (*.ts & *.qm) with Polish translation. Hope all is OK.
The problem is: how can I upload them?
(I got the message: We don't support that file type).

**Comment by textbrowser** [comment]
Very good.

Create a pull request in your fork or ZIP the file and upload it here.

**Comment by jerzyPL** [comment]
It works?
[biblioteq_pl_PL.zip](https://github.com/textbrowser/biblioteq/files/4772613/biblioteq_pl_PL.zip)

**Comment by textbrowser** [comment]
Yup. Uploaded.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/fe8fd99bf261d0b49257cd037206a768b6ba15a3

**Comment by textbrowser** [comment]
Yes, it's working well.

**Comment by jerzyPL** [comment]
Fine. Thank you.
May I submit an another question?
Why there are still untranslated fields appearing in the Main Table window?
![screen_shot](https://user-images.githubusercontent.com/66644295/84537585-57991480-acf0-11ea-9277-a004a235a8cb.jpg)

**Comment by textbrowser** [comment]
That's a tool tip? Let me look.

**Comment by textbrowser** [comment]
I think I know the problem. Correcting.

**Comment by jerzyPL** [comment]
Yes, tool tip. It shows untranslated fields and values, e.g. UNKNOWN, which I have translated into Polish as "Nieznane", in field "Originality" you can see "Original" but I named it "Oryginalność" and "Oryginał", next field is "Condition" with value "As New" => Polish: "Stan" "Jak nowy"... etc.

**Comment by textbrowser** [comment]
Corrected.

If you created the entries before applying the translations, the entries would be in English. BQ does not translate database values.

**Comment by jerzyPL** [comment]
I have the version 2020.01.01, because I don't have enough skills to compile a fresh source code.
After installing the above version, I added the file with Polish translation, created a new database and entered an entry from Z39.50.
The tool tip fields are still in English, but the entries are already in Polish (except for the field 'Type' which still says "Book" instead of "Książka").
![Bez tytułu2](https://user-images.githubusercontent.com/66644295/84551234-414d8180-ad0d-11ea-822f-f565c11a9c04.jpg)

**Comment by textbrowser** [comment]
Well, yes, the tool tips would be in English because you're using a software version which doesn't have the software corrections.

The tool tip field names are not stored in the database. The tool tip values are stored in the database. Some database values, Originality for example, have a fixed set of values. Those values are translatable and stored in the database in their translated form during a database write.

**Comment by jerzyPL** [comment]
OK, so just one last question before I go to sleep: When should we expect a new release?

**Comment by textbrowser** [comment]
Future version information is published: https://textbrowser.github.io/biblioteq/. So, early July. :)

Some documentation needs to be updated to describe some of the confusion that you've encountered with translations.

**Comment by jerzyPL** [comment]
Thank you, so I look forward to it.
Topic to close (but other ideas come to my mind...).

**Comment by textbrowser** [comment]
Ideas are encouraged.

**Comment by textbrowser** [comment]
Closing!

**Comment by textbrowser** [comment]
New information added to the documentation.

**Comment by jerzyPL** [comment]
Good evening,
thank you for information, downloaded.
And, as I said, here is the most annoying guy in the world ;-)
I have some questions, again, and even a suggestion.
May I put it here, or should I create new topic?

**Comment by textbrowser** [comment]
If the topic is not related to this ticket, please create a new ticket.

**Comment by jerzyPL** [comment]
Updated Polish translation for the 02.02.2021 version attached. Happy NY!

**Comment by jerzyPL** [comment]
;-)

**Comment by textbrowser** [comment]
Can you attach the file please?

**Comment by textbrowser** [comment]
Thanks a bunch.
