### ISSUE TITLE
Being forced to fill in ISBN-10

### ISSUE THREAD

**Issue by robindegen** [textbrowser/biblioteq#71]
I have some magazines with only an ISBN-13 number. There is no ISBN-10 and I can't generate one. If i click the "FROM ISBN13" button nothing happens. I've tried some online converters and they do come up with a number but i'm doubious about it being correct since if I google around for that number nothing comes up.

This means I can't fill in the ISBN at all since it requires me to fill in both. Is there a way to fix this? Why do you have to fill in both and not just 1 if you supposedly can convert between them anyway?

**Comment by textbrowser** [comment]
Please paste one of the ISBN-13 numbers.

**Comment by robindegen** [comment]
Sure 4910115880601. I also can not enter it under magazines since it's an ISBN, not an ISSN and the regex doesn't work.

**Comment by textbrowser** [comment]
OK, so a 13-digit ISBN must begin with 978. Yes?

**Comment by textbrowser** [comment]
That requirement (if it's true) will be relaxed. Let me see.

**Comment by textbrowser** [comment]
The new conversions results in 0115880607.

**Comment by textbrowser** [comment]
https://www.isbn.org/ISBN_converter produces 0-11-588060-7.
Done!

**Comment by textbrowser** [comment]
https://www.loc.gov/publish/pcn/isbncnvt_pcn.html prevents the conversion because the 13-digit ISBN does not begin with 978.

**Comment by robindegen** [comment]
Yes I saw that too, but i'm dubious about that being correct. If you convert it back, it comes up with a completely different number (978-0-11-588060-5).

**Comment by robindegen** [comment]
Also note that isbn.org mentions ```This ISBN Converter Tool only supports ISBNs allocated inside the USA and Australia```. This is a japanese asigned ISBN number. Maybe this is where the problem lies?

**Comment by textbrowser** [comment]
Yup, it's a wonky ISBN. So, one requirement is that 13-digit ISBNs must begin with 978 (and possibly 979) otherwise conversions are incorrect.

Check out https://en.wikipedia.org/wiki/International_Standard_Book_Number#Overview.

**Comment by textbrowser** [comment]
I don't have an issue if operators provide invalid ISBNs. So the conversion will now proceed without inspecting the prefix.

**Comment by robindegen** [comment]
I think there is a problem anyway, since if you look here:
https://www.isbn-international.org/content/changes-united-states-isbn-prefixes

It says that 
```
a 13-digit ISBN starting 979 is not backwards compatible and does not have an equivalent 10-digit ISBN. Trying to convert a 979 ISBN into a 10 digit ISBN will bring serious errors including duplicated ISBNs and incorrect supply of orders.
```

This means that there are ISBN-13 numbers out there that don't have a ISBN-10 equivalent. I think this japanese one is one of them.

**Comment by textbrowser** [comment]
Yup. Sounds problematic. However, the ISBN fields must be unique at the database level. So, if the conversions create duplicate values, the database will raise an exception during insert / update.

**Comment by textbrowser** [comment]
I have not looked at ISSN. ISSN must be exactly 8 digits, right?

**Comment by robindegen** [comment]
Well currently in the application it says ISSN has to be ```[0-9]{4}-[0-9]{3}[0-9X]```. Which is again very different. This whole system seems to fall appart with non-western books and magazines. and the isbn website isn't very helpful on this either.

**Comment by textbrowser** [comment]
The numbers are not very international, are they?

If you can find another conversion algorithm for ISBNs which works for specialized ISBNs, I'll implement it. The software could then convert from 978 (or 979) 13-digit ISBNs as well as non-internationalized ISBNs.

As for ISSNs, they're defined according to the standard: 8 digits. Please include some documentation for other standards and then we can determine how to proceed.

**Comment by robindegen** [comment]
Here is an interresting resource:
https://en.wikipedia.org/wiki/List_of_ISBN_identifier_groups . It lists japan as prefix 419. 

But this may answer the strangeness that we're dealing with:
https://www.gs1jp.org/2014/barcodes_identification/1_4.html
It says it's a numbering structure for periodical publications (magazines). It also says "GS1 Japan works together with Japan ISBN Agency in registration and management of the number."

**Comment by textbrowser** [comment]
OK, according to gs1jp.org, the current implementation for books is correct (978 is a required prefix).

You're experiencing a problem with a periodical.

**Comment by textbrowser** [comment]
So, we can expand the ISSN structure to be more relaxed.

**Comment by robindegen** [comment]
That might work yes. It just goes to show how confusing it is if even Amazon is listing them as isbn's.

**Comment by textbrowser** [comment]
I'll also add a reminder that the 978 prefix is required. Will also allow for 979.

**Comment by textbrowser** [comment]
Thank you very much.

**Comment by robindegen** [comment]
Thank you too!

**Comment by textbrowser** [comment]
OK, so. Relaxed the ISSN. Can include any character, maximum length of 32 characters.

**Comment by textbrowser** [comment]
Available with the July release. Closing!
