### ISSUE TITLE
Changed column order between (earlier) create schema and Upgrade SQLite Schema results empty member table

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#74]
It caused me a lot of headache... I use BiblioteQ since 2019-01 when the SQLite database was newly created with the actual version at that time and with column order:
`city,comments,dob,email,expiration_date,first_name,general_registration_number,last_name,memberclass,memberid,membersince,middle_init,overdue_fees,sex,state_abbr,street,telephone_num,zip`

Member table in current Upgrade SQLite Schema:
```
CREATE TABLE member_temporary (memberid VARCHAR(16) NOT NULL PRIMARY KEY DEFAULT 1,membersince VARCHAR(32) NOT NULL,dob VARCHAR(32) NOT NULL,sex VARCHAR(32) NOT NULL DEFAULT 'Female',first_name VARCHAR(128) NOT NULL,middle_init VARCHAR(1),last_name VARCHAR(128) NOT NULL,telephone_num VARCHAR(32),street VARCHAR(256) NOT NULL,city VARCHAR(256) NOT NULL,state_abbr VARCHAR(16) NOT NULL DEFAULT 'N/A',zip VARCHAR(16) NOT NULL DEFAULT 'N/A',email VARCHAR(128),expiration_date VARCHAR(32) NOT NULL,overdue_fees NUMERIC(10, 2) NOT NULL DEFAULT 0.00,comments TEXT,general_registration_number TEXT,memberclass TEXT)

INSERT INTO member_temporary SELECT * FROM member

DROP TABLE IF EXISTS member
```
so it should be:

`INSERT INTO member_temporary SELECT memberid,membersince,dob,sex,first_name,middle_init,last_name,telephone_num,street,city,state_abbr,zip,email,expiration_date,overdue_fees,comments,general_registration_number,memberclass FROM member`

It's unfortunately a mess now for anyone who using SQLite and want to update if schema update is necessary.

**Comment by textbrowser** [comment]
Did you create a backup of the database before upgrading?

**Comment by tamascz** [comment]
Of course.

**Comment by textbrowser** [comment]
Good. So what is the exact problem?

**Comment by textbrowser** [comment]
I think I understand, the SELECT has to be specific.

**Comment by textbrowser** [comment]
I'll see if there is a mechanism for creating a table using the definition of another table: create table (select * from table).

**Comment by textbrowser** [comment]
OK, try the following:

a.) create table member_temporary as select * from member where 0;
b.) drop table member;
c.) alter table member_temporary rename to member;

You'll need SQLite.

**Comment by textbrowser** [comment]
Ugh, that is that a carbon copy. Wait please.

**Comment by textbrowser** [comment]
OK, order corrected. Now reviewing other temporary tables.

**Comment by textbrowser** [comment]
Column orders corrected. I apologize for the problems.

**Comment by tamascz** [comment]
OK. Thanks! (Note to others: cause of the 1st error `Error 20: unique constraint failed: member_temporary.memberid unable to fetch row.` and the resulting empty member table in my previous issue, if Upgrade SQLite Schema run on an SQLite db created with an earlier BiblioteQ version.)

**Comment by textbrowser** [comment]
![Screenshot from 2020-07-17 17-26-03](https://user-images.githubusercontent.com/10701156/87831882-a9ced780-c852-11ea-9c98-f90d935504f2.png)

**Comment by textbrowser** [comment]
Preparing packages. Closing!
