### ISSUE TITLE
Question (silly)

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#75]
Where in Win10 are stored front/back cover images downloaded from Amazon/Open Library?

**Comment by textbrowser** [comment]
In the database. If not saved, in the application's memory space.

**Comment by jerzyPL** [comment]
OK. Thank you.

**Comment by textbrowser** [comment]
:)

**Comment by textbrowser** [comment]
Inserted a new page: Database Content.

**Comment by jerzyPL** [comment]
Perfectly.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/a9540962c592b81cb88036ff9af618e4b0f4afd7
