### ISSUE TITLE
ZACK Z39.50 Gateway

### ISSUE THREAD

**Issue by yeancek** [textbrowser/biblioteq#76]
Hello. I am new to BiblioteQ. I am starting to build a private library. However, there are a lot of books which I cannot find from the intergrated z39.50 sites, but I can find them through another z39.50 site, i.e. https://z3950.de/zack/.
This site is linked to many germand databases, and very often brings back good result for my books.

IS IT POSSIBILE FOR YOU TO ADD THIS SITE INTO THE Z39.50 QUERY?

Or can I do it myself? if Yes, how do I do it?

Here are more infor about this z39.50 site:

https://z3950.de/zack/faq.html#targetprofile

appreciate your help.

Thanks in advance.

Yean

**Comment by textbrowser** [comment]
This is a duplicate ticket.

**Comment by textbrowser** [comment]
Please read the documentation before submitting a ticket. If the documentation does not answer your question, or if there is a software glitch, please submit a ticket!

**Comment by textbrowser** [comment]
Next release will allow users to parse MARC tags.

**Comment by textbrowser** [comment]
![Screenshot_20200812_081019](https://user-images.githubusercontent.com/10701156/90013460-4ed2a980-dc73-11ea-967a-d184058846aa.png)
Please see image.

**Comment by textbrowser** [comment]
For books, journals, and magazines.
