### ISSUE TITLE
Inconsistency between copy browser and reservation status after copy deleted

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#77]
Imagine a school library situation: a textbook with reserved copies that will be returned, and copies that never will be returned (from members of run out classes). If these copies are not deleted  (after "return") the quantity and total reserved values are not real and unusable.

Copies and reservation status before deleting 2nd copy:
![c](https://user-images.githubusercontent.com/50261477/89407888-dd00da00-d71f-11ea-895d-3516f4b9a825.png)
![rs](https://user-images.githubusercontent.com/50261477/89407890-de320700-d71f-11ea-94fc-304b8c0ef83c.png)

Copies and reservation status after deleting 2nd copy:
![c2](https://user-images.githubusercontent.com/50261477/89408009-0588d400-d720-11ea-96d3-2471cb7113a3.png)
![rs2](https://user-images.githubusercontent.com/50261477/89408011-06216a80-d720-11ea-8082-dbed50e5c98b.png)

**Comment by textbrowser** [comment]
I see the problem. Thanks.

**Comment by textbrowser** [comment]
The Delete button should not be available as the number of copies is configured via the Copies widget. Corrected and will be available in the next release.

The logic which prevents the removal of reserved copies already exists in the parent panel.
