### ISSUE TITLE
Downloading Data (Plugins)

### ISSUE THREAD

**Issue by andrkac** [textbrowser/biblioteq#78]
This is my first touch with bibliteq. I've tried to add a book (ISBN 9788375068351, this is polish edition of A Clash of Kings) and - I can retrieve a cover from Amazon, but no other data from any source. Is it possible to use Amazon for other data? Or define other sources?

**Comment by textbrowser** [comment]
Does Amazon offer an implemented format?

**Comment by andrkac** [comment]
I don't know to be honest. I just know, that some time ago, when I've tried to use data crow, it was possible to get data for most books I've checked. Amazon was one of sources iirc.
Also there are another ISBN databases. Of course it is impossible for you to handle all bases around the world :) but maybe some idea to let users define their own sources?
For example, in Poland there is http://data.bn.org.pl/bibs (in theory it should be the most complete, BN - National Library - officialy handles polish ISBN base), with few formats available: json, xml, marcxml, marc. I guess there are many bases like this and users may help you to use them (I hope :) )

**Comment by textbrowser** [comment]
The one thing that would be awesome would be a programmable interface, or plugins. These would allow users to develop their own format parsers.

**Comment by jerzyPL** [comment]
@andrkac 
After you add the following rows:

**[Z39.50-7]

database_name = 48OMNIS_NLOP
format = "UNIMARC"
hostname = eu.alma.exlibrisgroup.com
name = Biblioteka Narodowa
password =
port = 1921
proxy_host =
proxy_port =
record_syntax = "UNIMARC"
username =**

in the "biblioteq.conf" file, you will have something like this:
![screen](https://user-images.githubusercontent.com/66644295/90681020-06168400-e263-11ea-8878-c71326b296f2.jpg)

Hope it helped you - Mam nadzieję, że pomogłem ;-)

**Comment by textbrowser** [comment]
What's the problem?

**Comment by jerzyPL** [comment]
Not on my side of the pitch...
My advise for andrkac was, that he can use the Z39.50 protocol instead of Amazon and/or http://data.bn.org.pl/bibs.
Unless, he cares about the multiplicity of formats...

**Comment by textbrowser** [comment]
Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh. I be thinking that there was a problem with the software. Clearly, I be not thinking.

**Comment by textbrowser** [comment]
Yes, Amazon is a cautionary tale. Prefer adoption of friendlier services such as World Catalog, Open Library.

**Comment by jerzyPL** [comment]
;-)

**Comment by andrkac** [comment]
I will use this advice, just when I localize biblioteq.conf in my linux mint system :)
Dzięki, jerzyPL :)

**Comment by andrkac** [comment]
I forgot to add: found, added and it works. Thank you!
