### ISSUE TITLE
Record reservation history

### ISSUE THREAD

**Issue by nikoscrete** [textbrowser/biblioteq#8]
it is "check" the button "Do not record reservation history" in the members list. How can I change it? 

![default](https://cloud.githubusercontent.com/assets/20591427/17047564/08535a3e-4fe8-11e6-8e12-ed7401f8bea1.JPG)

**Comment by textbrowser** [comment]
SQLite database?

**Comment by textbrowser** [comment]
Will add a tool tip!

**Comment by textbrowser** [comment]
OK. Added a tool tip. In short, this option is only available for patrons and PostgreSQL databases.

**Comment by nikoscrete** [comment]
i have this version:
![default](https://cloud.githubusercontent.com/assets/20591427/17132622/382259b8-532b-11e6-9a5c-a53626397e4f.JPG)
what tool tip can i add and where?
thank you for the supporting!!!

**Comment by textbrowser** [comment]
Already added. You'll have to wait for the next release or build BQ yourself from source.
