### ISSUE TITLE
Version 2020.09.09 for Win 10

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#80]
Finally, but where is the Windows 10 version? It was present in previous releases.
Compiling the code is beyond my abilities...

**Comment by textbrowser** [comment]
It's still September 9! Have to be patient. BQ is not an organization. Have life and chores and responsibilities. Patience is important.

Also, the process is quite simple but not timely. Also involves uploading. Large bundle.

Anyway, tickets are for problems and not for "stop doing whatever you're doing and send me the file".

**Comment by jerzyPL** [comment]
Thank you very much for your comprehensive answer.

**Comment by textbrowser** [comment]
Uploaded the new Windows release. :) On September 9, 2020. Release: 2020.09.09. On time. Not late. Not early. On time!

**Comment by jerzyPL** [comment]
Thank you.
I changed the title because I have the following problem in "Database Enumerations":
- after opening "Database Enumerations Browser" (when connected to the existing Database) all fields are blank.
There are no prior values.
However, in the "Modify Book Entry" window, the old values ​​are shown, as well as in the "Create Book Entry" window.
Will I have in each new release to retype values ​​in the "Database Enumerations Browser"?

**Comment by textbrowser** [comment]
:)

**Comment by textbrowser** [comment]
Is there a problem with the Database Enumerations Browser?

**Comment by jerzyPL** [comment]
Yes, it was, before I discovered the amazing properties of the "Refresh" button... ;-)

**Comment by textbrowser** [comment]
Options -> Populate ... On Display

**Comment by textbrowser** [comment]
Explore the application and its documentation before contacting support. Not only for BQ, but for everything.

**Comment by jerzyPL** [comment]
![yes](https://user-images.githubusercontent.com/66644295/92664451-52099580-f304-11ea-8a46-bdace90ebf0f.jpg)
