### ISSUE TITLE
Feature request: Read status

### ISSUE THREAD

**Issue by ksl1989** [textbrowser/biblioteq#84]
Thank you for your work. I've been looking for some time and I've not seen any comparable application in terms of features/ease of use.

However, one of the main features I need is missing: I'd like to be able to set a book as read/unread. One of the reasons I'm looking to organize my books is that I keep forgetting books I haven't read, so I'd be able to list/filter unready books.

I understand it's possible to achieve a possible result by adding myself as a member and checking out books to me, but that feels uncessarily complicated when I'm using this application to organize my personal collection. I'd just like to be able to set a book as read or unread when I add it and be able to update it to read in the book entry dialogue.

**Comment by textbrowser** [comment]
Unfortunately BQ isn't designed for reminders. A read/unread feature is not relevant to libraries. Item notes could be used for that, although you'd have to query the database to determine which items you've read.

An elegant solution will have to include new categories (All Read, etc.), read status, notes (maybe for specifying personal details), and some other things.

Will think.

https://github.com/textbrowser/biblioteq/discussions

**Comment by textbrowser** [comment]
Moved to https://github.com/textbrowser/biblioteq/discussions/85.
