### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#9]
"Additions:
1) Series fields (MARC21: 490) $a - Series statement and $v - Volume/sequential designation
2) Dewey Edition (22, 23, 13a etc)
3) Futher Title info:MARC21 245: $b - Remainder of title
4) Parallel titile: MARC21 246: 31$a

Changes:
1) Give the option to show "Publication Date" as year only (or at least, month/year)
2) Rename "Abstract" field to "Physical Description"
3) Rename "Categories" field to "Subjects"

Also, it would be nice to add a field called Accession Number or Input Number or something like that: it's a number given to each item (like the ID number of Biblioteq) not by a computer program but from an Accession book (much much long ago before pc existed...)"

**Comment by textbrowser** [comment]
@gushjones Can you provide some more information for the Additions? Are these new fields? Thanks.

**Comment by gushjones** [comment]
Hello.
Yes, all the suggested additions (plus the "Accession Number field", 5 additions in total) are new fields. I gave the MARC21 data to help.
From the 3 proposed changes only the first is of actual importance.
Thanks

**Comment by textbrowser** [comment]
New Options dialog in the works. Unfortunately, I cannot rename the other fields. More later.

**Comment by textbrowser** [comment]
Options window is complete. Canvas background color. Per-item-type publication date display formats.

**Comment by textbrowser** [comment]
For Additions, which of the items require new fields? I could append 3, 4 to the existing title.

**Comment by gushjones** [comment]
Thanks again for you efforts. Renaming is not that important.

Actually all of the Additions are new fields (in MARC). How would the appendix work? I'm only interested in "getting" the correct field from a library's record to my record, and, vice versa, when i export a record, not to lose all this data. I don't really care for aesthetics.

If you mean which item types need these fields, i think all of them need the additions.

By the way, i'm trying to export a record in MARC type. I export to .csv, then i go to MARCEdit, but it can't read Greek characters (yes, i'm Greek!). Any ideas?

Thank you. 
________________________________________
���: Guess Who [notifications@github.com]
��������: ������, 24 ��������� 2016 11:40 ��
����: textbrowser/biblioteq
����.: gushjones; Mention
����: Re: [textbrowser/biblioteq] Suggestions (#9)

For Additions, which of the items require new fields? I could append 3, 4 to the existing title.

�

**Comment by gushjones** [comment]
Never mind my question about greek characters, i think i found the solution.
________________________________________
���: Guess Who [notifications@github.com]
��������: ������, 24 ��������� 2016 11:34 ��
����: textbrowser/biblioteq
����.: gushjones; Mention
����: Re: [textbrowser/biblioteq] Suggestions (#9)

Options window is complete. Canvas background color. Per-item-type publication date display formats.

�

**Comment by textbrowser** [comment]
The MARC data are present under MARC Tags for books, journals, magazines. It's as complete as possible.

Let's consider item #4. Do you want the Title widget to contain that additional information?
"A Title" || MARC21-246?

I'll add Accession Number fields to all supported item types. Their values will be optional.
Will use https://en.wikipedia.org/wiki/Accession_number_(library_science) as guidance.

**Comment by gushjones** [comment]
MARC data are generated omly when i insert a record through queries, not when i fill in the fields myself. So, when i catalogue a new book, where should i insert the Additional info?

Item #4? You mean magazines? You never know when parallel titles are gonna show up, but, indeed, they mostly appear in translated books, movies, but not music CDs...

You are on the right direction regarding the Accession number.

**Comment by textbrowser** [comment]
You can override the title. I was asking if you would like BiblioteQ to append additional information to the title widget after a Z30.50 query. You can also modify the MARC data. Unfortunately, it does not parse MARC data that exists in MARC Tags. It could, if you'd like.

**Comment by gushjones** [comment]
Sorry for the delay, too many things going on...

Yes, it would be nice to append the additional info after the query. Yes, it would be nice the MARC data. Lots of bother...

If i modify the MARC data it saves the changes?


On 29/11/2016 11:25 μμ, Guess Who wrote:

You can override the title. I was asking if you would like BiblioteQ to append additional information to the title widget after a Z30.50 query. You can also modify the MARC data. Unfortunately, it does not parse MARC data that exists in MARC Tags. It could, if you'd like.

**Comment by textbrowser** [comment]
Yes, you can modify the MARC data and it will save it.

**Comment by textbrowser** [comment]
Accession Number is now available in all item types in version 2016.12.16.

**Comment by textbrowser** [comment]
Items completed. Please open a new ticket if you disagree.
