### ISSUE TITLE
Bug in populateAfterOpenLibrary

### ISSUE THREAD

**Issue by jferby** [textbrowser/biblioteq#93]
There is a serious bug in populateAfterOpenLibrary method. All UTF8 values are not correctly converted to Unicode string.

Part of code is:

QString value("");

for(int i = m_openLibraryResults.indexOf('"', index) + 1;
		i < m_openLibraryResults.length();
		i++)
	if(m_openLibraryResults.at(i) == '"')
		break;
	else
		value.append(m_openLibraryResults.at(i));

if(!value.isEmpty())
	{
		if(key == "\"publish_date\":")
			publicationDate = value;
		else if(key == "\"subtitle\":")
			subtitle = value;
		else if(key == "\"title\":")
			title = value;
	}_

m_openLibraryResults UTF8 bytes are just appended to Qstring what is completely wrong.

Quick and dirty correction of the code is:

QByteArray value("");

for(int i = m_openLibraryResults.indexOf('"', index) + 1;
		i < m_openLibraryResults.length();
		i++)
	if(m_openLibraryResults.at(i) == '"')
		break;
	else
		value.append(m_openLibraryResults.at(i));

QString valueS(QString::fromUtf8 (value));

if(!valueS.isEmpty())
	{
		if(key == "\"publish_date\":")
			publicationDate = valueS;
		else if(key == "\"subtitle\":")
			subtitle = valueS;
		else if(key == "\"title\":")
			title = valueS;
	}

**Comment by textbrowser** [comment]
Can you include a test ISBN?

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/f23d6fbc2257384f1140447a1210b488e467fc76

**Comment by textbrowser** [comment]
Corrected. Let me know if you the problem persists. Thanks.

**Comment by jferby** [comment]
Can you please explain why this bug was closed?

**Comment by textbrowser** [comment]
I closed it because the problem was resolved. :P

**Comment by textbrowser** [comment]
That's how we roll at BiblioteQ Industries. On time all of the time.

**Comment by textbrowser** [comment]
Released!
