### ISSUE TITLE
Feature request : hyperlinks 

### ISSUE THREAD

**Issue by g1ra** [textbrowser/biblioteq#94]
Please add a possibility for adding a hyperlink . 
Use case , For example  author wikipedia , or youtube  

![biblioScreenshot from 2021-02-21 00-59-59](https://user-images.githubusercontent.com/1227764/108611588-3ab8f300-73e0-11eb-88ad-186d17a3c0c0.png)

note , I couldn't find out why "Image is not available" 

Would be nice to have a little bigger book cover images . 

:+1:  Very great library software . I made a comparison to others , and this was my choice for my home library ! 
Please keep up good work ! Many thanks !

**Comment by textbrowser** [comment]
See Grey Literature.

https://www.lib.sfu.ca/help/research-assistance/format-type/grey-literature

Do you need a hyperlink in the book item? The back and front book images are stored in their original formats and resized in the summary section.

**Comment by g1ra** [comment]
I don't see how would be a Grey Literature . This is published book . 

I need hyperlink somewhere in the book item for a specific book .

**Comment by textbrowser** [comment]
In addition to the tabular view, there is the icon view. Larger cover views without the item information.

**Comment by g1ra** [comment]
Thanks for the info . Is it possible removing Image from the title column ? Problem is the row height is expanded with the image height .

**Comment by textbrowser** [comment]
No. Another request. :P Will be added to Other options.

**Comment by textbrowser** [comment]
URL field completed. Available in the next release.

**Comment by textbrowser** [comment]
Table images now optional. Next release. Closing!
