### ISSUE TITLE
Cannot search by author or view author name in grid view

### ISSUE THREAD

**Issue by RyanMcCoskrie** [textbrowser/biblioteq#96]
I'm looking deploy Biblioteq in a small lending library* and searching by author (and viewing the author's name in grid view) would be quite helpful.

*Too small for anything that runs on a server

**Comment by textbrowser** [comment]
Authors are displayed for Books category.

![Screenshot_20210320_204651](https://user-images.githubusercontent.com/10701156/111890178-73d38b80-89bd-11eb-9459-072cb20b9ec2.png)

**Comment by textbrowser** [comment]
See Book Search. You can search by several fields.

![Screenshot_20210320_204816](https://user-images.githubusercontent.com/10701156/111890208-b1381900-89bd-11eb-9ce1-c7d785166516.png)

**Comment by textbrowser** [comment]
Hello? Do you need Authors in the main page (Search [Authors | ...])? If yes, it'll require some delicate changes. Closing. Paste a response soon.
