### ISSUE TITLE
manjaro

### ISSUE THREAD

**Issue by urgentus** [textbrowser/biblioteq#97]
Hi. Please, Help install the program on Manjaro x64. Thanks.

**Comment by textbrowser** [comment]
Please provide information as BQ can be easily compiled from source.

**Comment by textbrowser** [comment]
It's based on Arch. Yah, install Qt, poppler, yaz.

> qmake -o Makefile biblioteq.pro
> make

Then read Documentation/README.DEBIAN for installation guidance.

Good luck. Closing!
