### ISSUE TITLE
Problem with the sort by accession number

### ISSUE THREAD

**Issue by ChrysaChm** [textbrowser/biblioteq#98]
I am using the program biblioteq for a school library but i have the following problem. When i try to sort by the column "accession number" the numbers appears like 
1,10,11,12,13,....,18,19, 2,20,21,22,...28,29, 3 , 30,31,32,...…...etc. I think that the sort by should be like 1,2,3,4,5,6,7,8,9,10,11,........20,21,.....,30,31...  etc.....
How can i fix-solve this problem?

**Comment by textbrowser** [comment]
Aha, the data are interpreted as strings instead of numbers. Apologies.

**Comment by textbrowser** [comment]
OK. Please read included document.
[Accession Form Samples.pdf](https://github.com/textbrowser/biblioteq/files/6260724/Accession.Form.Samples.pdf)
Accession Numbers may include non-numeric characters.

**Comment by textbrowser** [comment]
The implementation is correct. :)

**Comment by ChrysaChm** [comment]
I have the same problem for every columns i try to put numbers (like LC, Dewey,etc). I do not how can i solve this. In which column i should put number in order to show me the right sort by?

**Comment by textbrowser** [comment]
If the values represent text, the columns are sorted via alphanumeric algorithms. Pure numeric data are sorted correctly.

**Comment by ChrysaChm** [comment]
I have only numbers ....and it can not shorted ........remaining 1,10,11,.....2,20,21....,3,30......
![Screenshot_1](https://user-images.githubusercontent.com/81994278/113674540-f4370380-96c2-11eb-8291-a731265284a2.jpg)

**Comment by textbrowser** [comment]
Yes, I understand that. The Accession Number may include non-numeric characters. The software cannot detect that your particular values are all numbers. The sort must work for the one case where a single A.N. field contains a non-numeric character.

**Comment by textbrowser** [comment]
There are other fields in BQ where only numbers are allowed and these fields are sorted properly. The Accession Number is not a numeric-only field. Some databases may contain only numbers while others contain a mixture. BQ supports the superset.

**Comment by ChrysaChm** [comment]
Do you know which fields are allowed only numbers in order to sort by properly? Because i try the LC control number and Dewey class number, and call number....and i have the same problem.............

**Comment by textbrowser** [comment]
Yes, fields which contains down / up arrows (or + / -) indicate numeric values. You can also review the included SQL files as they describe the data types.

I have a solution that would help you. It needs to be implemented, however. For example, accession numbers should be treated as numbers or strings. The settings would exist in Other Options. Of course, it would produce weird results if a sort is numeric and a particular entry contains a non-numeric character. Since you know your data and you trust your data, the results would otherwise be correct.

**Comment by textbrowser** [comment]
Introduced new widget in Other Options.

**Comment by textbrowser** [comment]
Sorting preference for book accession numbers completed. Will be available in the next release. Are there other fields which you'd like custom sorting? Will be closing the ticket if not.

https://github.com/textbrowser/biblioteq/commit/5cc89719d5bb6921a5899da3b9b3958e1d33f545

**Comment by ChrysaChm** [comment]
No thank you , sort by accession number it enough. Thank you

**Comment by textbrowser** [comment]
OK. Closing. :)
